// HVAC 235 — Scenario lab.
// Scenario labs run on the numeric engine: each row is a decision point; the student
// enters the number of the correct option, a step number, or a computed value.

module.exports = [
  {
    id: "furnace-draft-diagnosis",
    title: "Furnace Pressure-Switch & Draft Fault Diagnosis",
    introHtml: "<p><strong>Job ticket #2291 — No heat, third visit.</strong> Equipment: 5-year-old 96% AFUE two-pipe condensing furnace, 80,000 Btu/h input. The board shows a pressure-switch lockout code. Two previous visits (another company) replaced the pressure switch, then the igniter; the fault returned both times. The pressure switch now fitted is the manufacturer's specified part, <strong>rated 0.60 in. w.c.</strong> The customer is cold, frustrated, and will suggest at least once that you 'just bypass that switch.' You have a manometer, a multimeter, your personal CO monitor, and the furnace's installation manual.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=MWn55b8DXO0\" target=\"_blank\" rel=\"noopener\">How to Test Pressure Switch on a Furnace</a> — the manometer-in-series method this lab is built on: tee in, run the inducer, and compare the measured draft against the rating printed on the switch.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> (1) Your personal CO monitor goes on before you open the furnace and stays on for the whole call; take an ambient CO reading of the mechanical room first — if it is elevated, the call becomes Module 10's response protocol (people out, responders called from outside) and diagnosis waits. (2) Treat the pressure switch as what it is: the proof that combustion gases are being vented before gas flows. <strong>Never jumper, tape, or otherwise defeat a pressure switch to 'test' a furnace into running — and never leave a furnace running with a safety defeated, not for one night, not with the customer's permission.</strong> A switch that will not close is evidence about the vent system, and the correct responses are diagnosis, repair, or a red-tag shutdown with safe temporary heat — those are the only three doors. (3) Electrical discipline: inducer and board circuits are live during draft testing; keep leads, hoses, and hands clear of the inducer wheel and blower. (4) If you smell gas at any point, stop — no switch-flipping, out of the house, utility/911 from outside.</p><p><strong>Your job:</strong> work the call in order. Enter the number each row asks for — an option number, a step number in the test procedure, or a computed value. Method (Module 4): read the rating on the switch, tee the manometer into the switch's hose, run a call for heat, and compare measured draft to the rating. Draft below the rating means the switch is telling the truth and the fault lives in the hose/ports, trap/drain, vent/intake, exchanger, or inducer.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY FIRST. Before touching the furnace, the customer says: 'The last guy almost jumpered that switch so we'd have heat. If it comes to that, just do it — I'll sign anything.' Your call? 1) Agree — a signed waiver makes it acceptable for one night 2) Decline, and explain: a pressure switch proves exhaust is venting; defeating it can let the furnace fire into a blocked vent and fill the home with CO, so you'll diagnose the draft fault or, if it can't be made safe, shut the furnace down and arrange safe temporary heat 3) Jumper it only while you stand there watching 4) Jumper it but open a basement window for safety", cells: [""], inputs: [
        { col: 1, key: "safety_no_jumper", expected: 2, hint: "Correct: option 2. No waiver, window, or time limit makes a defeated safety acceptable — the switch is the only proof that flue gas leaves the house. Options 1, 3, and 4 are the same prohibited gamble in different costumes; 'watching it' does not stop CO, which harms without warning (Module 10)." } ] },
      { label: "SAFETY CHECK. Your ambient CO survey of the mechanical room (furnace off, before you start) reads normal — no elevation. The correct interpretation and next step? 1) CO is ruled out for the whole call; skip the monitor from here 2) Proceed with diagnosis, monitor still on: conditions change when the furnace and other appliances run, and the survey gets repeated with equipment operating before you leave 3) The normal reading proves the vent system is fine 4) Cancel the call — no CO means no fault", cells: [""], inputs: [
        { col: 1, key: "safety_ambient", expected: 2, hint: "Correct: option 2. A pre-work ambient check is a snapshot, not a clearance — spillage and CO production appear under operating conditions (Module 10's ambient survey is done with appliances running). Option 1 discards protection exactly when it matters; option 3 over-reads the test (draft faults exist with zero ambient CO as long as the switch refuses to let the furnace fire); option 4 ignores the lockout fault you were sent to fix." } ] },
      { label: "STEP ORDER. The professional pressure-switch test has five steps: A) Read the rating printed on the switch, B) Inspect the hose and pressure port for water, cracks, and blockage, C) Tee the manometer into the switch's hose, D) Run a call for heat and read the draft with the inducer at full speed, E) Compare measured draft to the rating and decide. Enter the step number (1–5) of: 'Read the rating printed on the switch.'", cells: [""], inputs: [
        { col: 1, key: "step_rating", expected: 1, hint: "Step 1. Every later judgment is 'measured vs. rating,' so the rating is captured first — here, 0.60 in. w.c. from the switch label. Inspecting the hose (B) is step 2, teeing in (C) step 3, running and reading (D) step 4, comparing and deciding (E) step 5." } ] },
      { label: "STEP ORDER. Enter the step number (1–5) of: 'Inspect the hose and pressure port for water, cracks, and blockage.' (Sequence: A) read the rating, B) inspect hose and port, C) tee in the manometer, D) run and read draft, E) compare and decide.)", cells: [""], inputs: [
        { col: 1, key: "step_inspect", expected: 2, hint: "Step 2. A water-logged or cracked hose, or a crusted-shut pressure port, makes every later reading a lie (Module 4). Two minutes of inspection before instruments protects the whole diagnosis — on this call, keep what you find in mind: the hose will matter shortly." } ] },
      { label: "STEP ORDER. Enter the step number (1–5) of: 'Compare the measured draft to the rating and render the verdict — switch or system.' (Sequence: A) read rating, B) inspect hose/port, C) tee in manometer, D) run and read, E) compare and decide.)", cells: [""], inputs: [
        { col: 1, key: "step_compare", expected: 5, hint: "Step 5 — the decision the whole procedure exists to produce. Draft at or above the rating with the switch open = failed switch. Draft below the rating = healthy switch reporting a draft-system fault. Everything before this step is evidence-gathering for it." } ] },
      { label: "COMPUTED VALUE. The switch is rated 0.60 in. w.c. With the inducer at full speed, your manometer teed into the switch hose reads 0.40 in. w.c. By how many HUNDREDTHS of an inch of water column does the measured draft fall short of the rating? (Enter a whole number: a shortfall of 0.20 in. w.c. is entered as 20.)", cells: [""], inputs: [
        { col: 1, key: "shortfall", expected: 20, hint: "0.60 − 0.40 = 0.20 in. w.c. = 20 hundredths. The draft reaching the switch is only two-thirds of what it needs to close — this is not a marginal, could-go-either-way reading; the vent path is genuinely restricted or the inducer is genuinely weak." } ] },
      { label: "VERDICT. Measured draft 0.40 in. w.c. against a 0.60 in. w.c. rating, and the switch is open. The correct verdict? 1) The switch is faulty — replace it (again) 2) The switch is telling the truth: draft is insufficient, so the fault is in the hose/ports, trap/drain, vent/intake, secondary exchanger, or inducer — diagnose those 3) The inducer is proven bad — replace it without further tests 4) The board is misreading the switch — replace the board", cells: [""], inputs: [
        { col: 1, key: "verdict_low_draft", expected: 2, hint: "Correct: option 2. A healthy switch offered 0.40 against a 0.60 rating MUST stay open — two predecessors replaced this messenger already. Option 1 repeats their error. Options 3 and 4 name parts the evidence hasn't reached: the manometer convicts 'the draft path' as a system, and segment-by-segment testing (next rows) finds which part of it." } ] },
      { label: "FIRST SUSPECTS. Following your step-2 discipline, you pull the pressure hose: it holds a slug of water, and the trap below it is visibly full to the top. Your interpretation? 1) Normal — hoses are supposed to carry water 2) The hose must transmit air pressure only; water in it corrupts the signal — and a brim-full trap points to the real story: condensate drainage is backed up, which also strangles the inducer's air path 3) The water proves the pressure switch is internally flooded and must be replaced 4) Ignore it and proceed to vent measurements", cells: [""], inputs: [
        { col: 1, key: "hose_water", expected: 2, hint: "Correct: option 2. Water in the sensing hose offsets and blocks pressure transmission (Module 4), and the full trap is the upstream cause to chase: a plugged or frozen drain path backs condensate into the collector until the inducer moves water instead of air — draft collapses and the faithful switch locks the furnace out. Option 1 is false (the hose is a pressure line, not a drain). Option 3 invents an internal flood the evidence doesn't show. Option 4 would measure a vent system while the appliance drowns in its own condensate." } ] },
      { label: "COMPUTED VALUE. You clear the trap and drain (a plug of debris and slime) and re-test: the manometer now reads 0.90 in. w.c. against the 0.60 in. w.c. rating. By what PERCENT does the restored draft exceed the switch's rating? (Enter a whole number.)", cells: [""], inputs: [
        { col: 1, key: "margin_pct", expected: 50, hint: "(0.90 − 0.60) ÷ 0.60 = 0.30 ÷ 0.60 = 0.50 = 50% above the rating. A healthy margin like this matters: the switch should close crisply and stay closed through the whole cycle, not hover at its threshold waiting for a gust or a gurgle to drop it out." } ] },
      { label: "SEGMENT CHECK. Before declaring victory you isolate the vent: with the vent pipe disconnected at the furnace (a brief diagnostic state, burner not left running), the draft reads the same healthy value as connected. What has this test established? 1) Nothing — the vent was never suspect 2) The vent run and termination are moving air freely; combined with the before/after trap evidence, the condensate backup was the restriction, and the vent is cleared of suspicion 3) The vent is plugged and must be replaced 4) The inducer is oversized for the vent", cells: [""], inputs: [
        { col: 1, key: "segment_vent", expected: 2, hint: "Correct: option 2. Segment isolation splits the world in half (Module 4): if draft had stayed low with the vent off, the fault would be inside the appliance; if it had jumped only when disconnected, the vent/termination would be convicted. Equal-and-healthy readings both ways, plus a trap that was demonstrably plugged and a draft that recovered when it was cleared, close the vent question with evidence instead of assumption." } ] },
      { label: "OUTDOOR CHECK. Your termination inspection finds the sidewall exhaust/intake pair clean, correctly separated, and above the snow line — but you note the intake screen is an aftermarket add-on, not the manufacturer's fitting, and it is half-frosted even on this mild day. The right call? 1) Leave it — some screen is better than none 2) Remove/replace it with the manufacturer's listed termination fitting: unlisted screens frost shut in cold weather and become the restriction that locks the furnace out on the worst nights 3) Drill the screen's holes larger 4) Move the intake to the attic", cells: [""], inputs: [
        { col: 1, key: "termination_screen", expected: 2, hint: "Correct: option 2. Module 3's termination catalog: add-on screens are frost traps; half-frosted on a mild day means fully closed on a design night — the exact intermittent pattern that generates 2 a.m. lockouts. Option 1 leaves a designed-in failure. Option 3 keeps an unlisted fitting and its frost behavior. Option 4 relocates combustion air indoors to an unapproved source — a new problem wearing a fix's clothes." } ] },
      { label: "COMPUTED VALUE. While the furnace runs its verification cycle you check temperature rise: the unit is delivering 64,800 Btu/h and moving 1,000 CFM. Compute the temperature rise in °F using ΔT = Output ÷ (1.08 × CFM) and enter it.", cells: [""], inputs: [
        { col: 1, key: "temp_rise", expected: 60, hint: "ΔT = 64,800 ÷ (1.08 × 1,000) = 64,800 ÷ 1,080 = 60°F. Logged against the rating plate's range during verification, this confirms the air side is healthy while you close out a vent-side call — and gives the next tech a benchmark pair on the ticket (Module 12)." } ] },
      { label: "THE SECOND FURNACE (same afternoon, next call). Switch rated 0.60 in. w.c.; hose and port verified clean and dry; trap draining freely; manometer reads a steady 0.88 in. w.c. — yet the switch's contacts never close and the sequence stops. The verdict this time? 1) Same as the first call — the vent must be restricted 2) This switch has genuinely failed: it is offered draft well above its rating and still won't close — replace it with the manufacturer's specified switch (matching rating), then verify 3) The manometer must be wrong 4) Add a second pressure switch in parallel", cells: [""], inputs: [
        { col: 1, key: "verdict_bad_switch", expected: 2, hint: "Correct: option 2 — and the contrast is the whole lesson. Same code, same model, opposite verdicts, because the manometer numbers differ: 0.40 vs. 0.60 rating = system fault; 0.88 vs. 0.60 with clean sensing lines = the switch itself. Option 1 pattern-matches yesterday's answer instead of today's evidence. Option 3 discards the instrument that just proved itself on the previous call. Option 4 parallels a safety to make the fault invisible — defeated-safety logic again, and prohibited." } ] },
      { label: "CLOSE-OUT. Both furnaces are repaired. Which close-out makes the work professional? 1) Leave as soon as heat is felt at a register 2) Run full verification cycles, repeat the ambient CO survey with the equipment operating, record benchmark pairs on the ticket (rating vs. measured draft before/after; rise vs. plate range), state the safety conversation that happened, and tell the customer what was actually wrong with the two previous repairs 3) Reset the board and leave without paperwork to save the customer money 4) Recommend replacing both furnaces because they have history", cells: [""], inputs: [
        { col: 1, key: "closeout", expected: 2, hint: "Correct: option 2. Verification under operating conditions, the repeated CO survey, and documented before/after numbers are what separate a diagnosis from a lucky guess (Modules 4, 10, 12) — and an honest, non-triumphant explanation of the earlier misdiagnosis (parts replaced without a manometer comparison) is what the customer is owed. Option 1 verifies nothing. Option 3 erases the evidence trail. Option 4 sells iron to punish a drainage problem." } ] }
    ],
    passing: 70
  }
];
