// HVAC 127 — Scenario labs (Control & Thermostat Wiring Diagnosis; Sequence-of-Operations Diagnosis — DDC Rooftop Unit).
// Each row is checked on a single numeric input in column 1: an option number, a procedure step number, or a computed reading.

module.exports = [
  {
    id: "thermostat-wiring-diagnosis",
    title: "Control & Thermostat Wiring Diagnosis",
    introHtml: "<p><strong>Job ticket #2214 — New thermostat, three complaints.</strong> Customer: a heat pump system (energizes its reversing valve in cooling, per the unit's wiring diagram) got a replacement smart thermostat yesterday from a handyman. Since then: (1) the system <strong>heats when set to cool</strong>, (2) the thermostat screen <strong>goes dark and reboots</strong> whenever the system starts, and (3) on last night's cold snap the <strong>auxiliary heat never came on</strong>. Wires at the wall: R, W, Y, G, O — five conductors, colors match their terminals except as you will discover. No C conductor is connected at either end. Your task: diagnose all three complaints by measurement and configuration, in the correct order, without replacing good parts.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=4ERgdc_RRBE\" target=\"_blank\" rel=\"noopener\">Thermostat Terminals Fully Explained</a> — a terminal-by-terminal walk-through of what each thermostat connection does, before you make your calls below.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Thermostat wiring is low voltage (24 VAC), but the equipment it controls is not: the air handler and outdoor unit contain line-voltage circuits and a fan that can start without warning. Before opening any equipment panel or pulling the thermostat off its subbase, switch the equipment off at its disconnect/breaker and verify it is off; treat every conductor as live until your meter proves otherwise. Wear safety glasses when working inside panels, keep tools and loose screws out of the blower compartment, and never jumper a safety device and walk away. If any part of the call requires opening a line-voltage compartment, lockout/tagout applies exactly as it does on any electrical work.</p><p><strong>The correct diagnostic sequence (for the order questions):</strong> Step 1 — Safety: power controlled, PPE on, existing wiring photographed and labeled before anything moves. Step 2 — Verify control power at the equipment (R to C at the air handler). Step 3 — Verify the thermostat's configuration (system type and O/B energize direction) against the unit's documentation. Step 4 — Test each call with a meter at the equipment terminals (W, Y, G, O). Step 5 — Correct the wiring and configuration faults found. Step 6 — Run and observe complete cooling, heating, auxiliary-heat, and fan cycles and record the results.</p><p><strong>Readings available:</strong> control transformer is rated 40 VA; measured control loads are contactor coil 8 VA, fan relay 6 VA, control board 10 VA. The unit's diagram states the reversing valve is energized in cooling. For each row, enter the option number, the step number, or the computed value asked for.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY CALL — Before pulling the thermostat off its subbase or opening the air handler panel, what governs your first move? 1) Work fast while power is on so you can watch it misbehave 2) Control the power at the disconnect/breaker, verify it is off, PPE on — the stat is 24 V but the equipment holds line voltage and a fan that can start unannounced 3) Jumper R to Y at the wall to test the compressor first 4) Have the customer hold the disconnect closed while you work", cells: [""], inputs: [
        { col: 1, key: "tw_safety", expected: 2, hint: "Step 0 governs: low-voltage wiring lives inside line-voltage equipment. Power controlled and verified before panels open; no jumpers as a first move (3), no live-panel shortcuts (1), and never another person's hand as your lockout (4)." } ] },
      { label: "ORDER — 'Photograph and label the existing wiring before moving any conductor.' Which step of the diagnostic sequence is this?", cells: [""], inputs: [
        { col: 1, key: "tw_ord_photo", expected: 1, hint: "Step 1 includes recording the as-found wiring along with safety and PPE. You cannot prove what was wrong later — or restore it — if the evidence was never captured." } ] },
      { label: "ORDER — 'Test each call with a meter at the equipment terminals.' Which step of the diagnostic sequence is this?", cells: [""], inputs: [
        { col: 1, key: "tw_ord_test", expected: 4, hint: "Sequence: 1 safety/record, 2 verify control power, 3 verify configuration, 4 meter-test the calls, 5 correct faults, 6 run full cycles. Testing calls before power and configuration are verified produces misleading results." } ] },
      { label: "COMPUTED — What voltage do you expect to measure between R and C at the air handler with control power healthy? (Enter volts.)", cells: [""], inputs: [
        { col: 1, key: "tw_rc_volts", expected: 24, hint: "R to C is the control transformer's secondary: nominal 24 VAC. No voltage here means the call path doesn't matter yet — power comes first in the sequence (Step 2)." } ] },
      { label: "DECISION — Complaint 1: the system heats on cooling calls, starting right after the stat replacement. Configuration, wiring, and signal have not yet been checked. Your first suspect is: 1) The reversing valve is mechanically stuck 2) The thermostat's O/B setting does not match this unit (it energizes the valve in cooling, but the stat may be set to energize in heating) 3) The compressor is failing 4) The refrigerant charge is wrong", cells: [""], inputs: [
        { col: 1, key: "tw_ob_first", expected: 2, hint: "A mode reversal appearing exactly at a stat change is a configuration fault until proven otherwise (Module 4). A stuck valve (1) is possible but is a parts diagnosis made after settings and signal. Charge (4) affects capacity, not mode; compressors (3) cannot swap heating and cooling." } ] },
      { label: "COMPUTED — This unit energizes its reversing valve in cooling. During a cooling call, what voltage should be present between the O terminal and C at the air handler? (Enter volts.)", cells: [""], inputs: [
        { col: 1, key: "tw_o_volts", expected: 24, hint: "An active call = 24 VAC on the function terminal measured to common. If O shows 24 V in cooling as designed, the stat and wire are doing their job and suspicion moves to the valve solenoid/mechanism; if it shows 0 V, the stat's configuration or the O conductor is the break." } ] },
      { label: "DECISION — Complaint 2: the stat reboots whenever the system starts, and there is no C conductor connected at either end. The cause and cure are: 1) A defective thermostat; replace it with the same wiring 2) The stat is starved of a complete power circuit without common — run a C conductor (or use an approved common-maker kit) 3) The transformer is too large 4) Wi-Fi interference from the outdoor unit", cells: [""], inputs: [
        { col: 1, key: "tw_cwire", expected: 2, hint: "Power-stealing stats brown out when calls energize and control voltage shifts; the missing C is the textbook cause (Module 4). Replacing the stat onto the same wiring (1) reproduces the fault. Transformer size (3) works the other direction, and radios (4) don't reboot in sync with compressor starts." } ] },
      { label: "COMPUTED — Total measured control load: contactor coil 8 VA + fan relay 6 VA + control board 10 VA. What is the combined load on the 40 VA transformer, in VA?", cells: [""], inputs: [
        { col: 1, key: "tw_va_total", expected: 24, hint: "8 + 6 + 10 = 24 VA — comfortably under the 40 VA rating, so the transformer is NOT the cause of the reboot complaint. Doing this arithmetic is how you exonerate a suspect instead of replacing it." } ] },
      { label: "DECISION — Complaint 3: auxiliary heat never energized on the cold snap. At the wall you find the aux conductor landed on the stat's W terminal of a stat configured as 'heat pump with aux on W2/AUX,' and nothing on W2/AUX. The correct action is: 1) Replace the heat strips 2) Move the aux conductor to the terminal the configuration expects (W2/AUX) and verify a call reaches the strips 3) Raise the heating setpoint 4) Set the stat to emergency heat permanently", cells: [""], inputs: [
        { col: 1, key: "tw_aux_wire", expected: 2, hint: "Function follows the terminal: the stat was driving its aux output on W2/AUX into an empty terminal while the aux wire sat on a terminal this configuration doesn't use for aux. Strips (1) are unproven and downstream of a call that never arrives; setpoint (3) doesn't reroute terminals; emergency heat (4) is a manual failure mode, not a repair." } ] },
      { label: "DECISION — At the equipment, the green conductor is landed on the Y terminal and the yellow conductor on G (colors swapped by the previous installer). Cooling calls start the blower only. Your practice: 1) Trust the colors and replace the contactor 2) Trust terminals and function — the stat's Y output is driving the fan circuit and its G output the contactor path; re-land conductors by terminal letter and re-test 3) Swap the wires at the thermostat only and leave the equipment end 4) Re-label the diagram to match the colors", cells: [""], inputs: [
        { col: 1, key: "tw_color_swap", expected: 2, hint: "Equipment responds to where conductors land, not their insulation color (Module 4). Correct both ends to the standard terminal mapping and verify by meter. Replacing parts (1) punishes a healthy contactor; a one-end swap (3) creates a new mismatch; paperwork (4) doesn't move electrons." } ] },
      { label: "DECISION — After corrections, you test the cooling call: Y shows 24 V at the outdoor unit but the contactor does not pull in, and the contactor coil measures open (infinite resistance) with power off. The fault is: 1) The thermostat 2) The contactor coil — the call arrives and the coil is electrically dead 3) The O/B configuration 4) The float switch", cells: [""], inputs: [
        { col: 1, key: "tw_contactor", expected: 2, hint: "Call proven present + coil proven open = the coil is the break in the chain (Module 5's two-half rule). The stat (1) demonstrably delivered its call; O/B (3) steers mode, not contactor pull-in; an open coil explains everything without invoking a float switch (4) that would have removed the 24 V you measured." } ] },
      { label: "COMPUTED — A condensate float switch wired in series with the cooling call is open (pan full). With a call present, what voltage appears across the open float switch? (Enter volts.)", cells: [""], inputs: [
        { col: 1, key: "tw_float_volts", expected: 24, hint: "In a series chain the full control voltage drops across the single open device (Module 5). ~0 V across it would mean closed and conducting. This is the meter signature that finds the open link in any safety string." } ] },
      { label: "DECISION — All three complaints are corrected. What closes the call? 1) Leave as soon as cooling starts once 2) Run and observe complete cycles — cooling, heating, auxiliary heat staging, and fan-only — confirm the stat stays powered throughout, and record the as-left wiring and configuration 3) Tell the customer the handyman's work is always bad 4) Skip the heating test because it is summer", cells: [""], inputs: [
        { col: 1, key: "tw_closeout", expected: 2, hint: "Step 6 of the sequence: prove every affected function through a full cycle, including heating and aux behavior you cannot 'feel' in summer, and document the as-left state. A single start (1) doesn't exercise staging or heat; skipping heat (4) leaves complaint 3 unverified." } ] },
      { label: "DECISION — The customer asks you to 'just make the old stat work' by removing the smart stat's C-wire need: leave it power-stealing since 'it mostly works.' Your response: 1) Agree — intermittent reboots are acceptable 2) Decline and explain: the reboot fault will return under load; the correct repair is a real common connection or an approved kit, verified by a full-load run 3) Remove the thermostat entirely 4) Tape over the screen so the reboots aren't visible", cells: [""], inputs: [
        { col: 1, key: "tw_decline", expected: 2, hint: "Professional standard: a known power fault left in place is a callback scheduled. Options 1 and 4 hide a symptom; option 3 removes the control. The fix is small, defined, and testable — do that one." } ] }
    ],
    passing: 70
  },
  {
    id: "sequence-of-operations",
    title: "Sequence-of-Operations Diagnosis — DDC Rooftop Unit",
    introHtml: "<p><strong>Job ticket #2301 — RTU-3, classroom wing, four complaints.</strong> Equipment: a two-stage packaged rooftop unit under DDC control (BACnet MS/TP to the building front end), VAV boxes downstream, integrated economizer, duct static-pressure control. Complaints from the school: (1) classrooms are <strong>cold at 7:30 a.m.</strong> though the schedule says occupied at 7:00, (2) the <strong>economizer 'never works'</strong> — compressors run on mild days, (3) <strong>stage 2 cooling has never been seen running</strong>, and (4) intermittent <strong>'fan fail' alarms</strong> clear themselves. The written sequence of operation and points list are in the job folder. Points of interest: supply fan DO with current-switch DI status; duct static transmitter 0–4 in. w.c., 4–20 mA; damper AO 0–10 V; cooling valve-equivalent staging by DOs; zone sensors are 10K NTC thermistors. Your task: work the complaints in method order and let the sequence — not guesses — convict the faults.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=9d6plsLOZhA\" target=\"_blank\" rel=\"noopener\">Building Automation Systems Basics Lesson 4 - BAS 101 system training simulator</a> — a BAS/DDC training session on a simulator with real field devices and networks, showing how points, commands, and status are exercised before you make your calls below.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> A rooftop unit mixes line voltage, a supply fan, and a roof: before any panel opens, follow lockout/tagout on the unit disconnect (29 CFR 1910.147 basics — lock, tag, verify zero energy), remember that a DDC command from the front end can restart equipment you believe is off — place the unit in a safe local state and communicate with the operator before and after work — and treat the roof itself as a work area (fall awareness at edges, weather, housekeeping). Low-voltage signal work is still electrical work: no meter probes across line terminals, and no safety input (freezestat, pressure cutouts) is ever jumpered and left. PPE: safety glasses and gloves for panel work.</p><p><strong>The correct diagnostic sequence (for the order questions):</strong> Step 1 — Safety and operator communication (unit state controlled). Step 2 — Read the sequence, points list, trends, and alarm history; check mode, schedules, and overrides. Step 3 — Verify the key sensors against reference instruments. Step 4 — Force modes and stages and observe the sequence execute. Step 5 — Test the safeties and failure responses. Step 6 — Restore everything to automatic, clear test overrides, document findings.</p><p><strong>Readings available:</strong> duct static transmitter ranged 0–4 in. w.c. on a 4–20 mA loop currently reads 12 mA. Damper AO currently reads 7.0 V. Cooling loop: proportional band 4°F, setpoint (discharge) per sequence; measured error right now is 3°F. Economizer changeover limit per sequence: outdoor air suitable below 60°F; today's outdoor air is 52°F and verified accurate. For each row, enter the option number, the step number, or the computed value asked for.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY CALL — You are about to open RTU-3's control panel. The front-end operator is in another building and the unit is in automatic. What governs your first move? 1) Open the panel quickly; the fan is probably off 2) Lockout/tagout at the disconnect, verify zero energy, place the unit in a safe state, and coordinate with the operator — a remote command can restart equipment at any time 3) Ask the operator to watch the screen and shout if the fan starts 4) Wedge the panel door and work fast", cells: [""], inputs: [
        { col: 1, key: "so_safety", expected: 2, hint: "Step 0: DDC equipment has two masters — your hands and the network. LOTO plus operator coordination removes both start paths. Options 1, 3, and 4 all bet your safety on equipment politely staying off." } ] },
      { label: "ORDER — 'Read the sequence, trends, and alarm history; check mode, schedules, and overrides.' Which step of the diagnostic sequence is this?", cells: [""], inputs: [
        { col: 1, key: "so_ord_read", expected: 2, hint: "Step 2 comes right after safety (Step 1) and before instruments touch sensors (Step 3). Most DDC 'failures' are found in this paperwork step — modes, overrides, and histories — at zero risk and zero parts cost." } ] },
      { label: "ORDER — 'Force modes and stages and observe the sequence execute.' Which step of the diagnostic sequence is this?", cells: [""], inputs: [
        { col: 1, key: "so_ord_force", expected: 4, hint: "Forcing happens at Step 4 — after intent is read (2) and sensors are verified (3), because forcing a sequence on top of lying sensors produces evidence about nothing." } ] },
      { label: "COMPUTED — The duct static transmitter (0–4 in. w.c., 4–20 mA) reads 12 mA in the loop. What duct pressure is it reporting? (Enter in. w.c.)", cells: [""], inputs: [
        { col: 1, key: "so_static", expected: 2, hint: "Fraction = (12 − 4) ÷ 16 = 0.50. Pressure = 0.50 × 4 = 2 in. w.c. Subtract the live zero first — the single most-skipped step in signal math (Module 3)." } ] },
      { label: "COMPUTED — The economizer damper's analog output reads 7.0 V on its 0–10 V command. What percent open is the damper being commanded? (Enter percent.)", cells: [""], inputs: [
        { col: 1, key: "so_damper_pct", expected: 70, hint: "0–10 V scales linearly: 7.0 ÷ 10 = 70%. If the damper blade is not near 70%, the fault moved from signal to actuator/linkage — command vs. physical response is a checkout pair (Module 12)." } ] },
      { label: "COMPUTED — The cooling loop (proportional band 4°F) currently has a 3°F error. What output percentage should the loop be producing? (Enter percent.)", cells: [""], inputs: [
        { col: 1, key: "so_loop_out", expected: 75, hint: "Output = (error ÷ band) × 100 = (3 ÷ 4) × 100 = 75%. Compare this expectation with the actual AO/staging state — a mismatch between what the loop math demands and what the outputs show is a finding with an address." } ] },
      { label: "DECISION — Complaint 4: 'fan fail' alarms appear and self-clear. Trend shows fan DO on continuously; the status DI flickers off for a few seconds several times a day while duct pressure stays steady. Most likely: 1) The fan stops and restarts several times a day 2) The status device or its wiring is intermittent (e.g., a marginal current-switch setting or loose connection) — the fan's own physics (steady duct pressure) contradicts a real stop 3) The sequence is wrong 4) The front end invents alarms", cells: [""], inputs: [
        { col: 1, key: "so_fan_flicker", expected: 2, hint: "Cross-examine the witnesses: if the fan truly stopped, duct static would sag in the same seconds — it doesn't. A flickering proof with steady process = the proving device/wiring (Module 8: status is a sensor, and sensors lie in their own ways). The sequence (3) is reporting its inputs faithfully." } ] },
      { label: "DECISION — Complaint 2: outdoor air is a verified 52°F, changeover limit is 60°F, zones call for cooling, yet dampers sit at minimum and compressors carry the load. Per the sequence, the economizer should be the first cooling source. Your fault family is: 1) Refrigerant-side 2) Economizer enable path — damper actuator/linkage, economizer configuration (e.g., disabled or changeover mis-set in software), or the call never reaching the damper AO 3) The zone sensors 4) The utility meter", cells: [""], inputs: [
        { col: 1, key: "so_econ", expected: 2, hint: "Conditions provably satisfy the sequence's economizer clause (52 < 60, cooling demand exists), so work the economizer's own chain: is the AO actually commanding (compare with the damper reading you computed), is the actuator stroking, is economizer mode enabled in configuration? Refrigerant (1) can't explain dampers parked at minimum." } ] },
      { label: "DECISION — Complaint 3: stage 2 has never run. Stage 1 satisfies the building on all but the hottest afternoons, when zones drift 3°F high for hours with stage 2 still off. The sequence enables stage 2 at setpoint +2°F OR after 15 continuous minutes of stage 1. Your first checks are: 1) Replace the stage 2 compressor 2) The stage-up logic path — whether the +2°F threshold and 15-minute timer exist as configured (found: staging was left disabled in configuration), plus the stage 2 output wiring 3) The economizer dampers 4) The duct static setpoint", cells: [""], inputs: [
        { col: 1, key: "so_stage2", expected: 2, hint: "Both sequence triggers demonstrably occurred (3°F drift > 2°F threshold; hours > 15 minutes) with no stage 2 — the logic never issued the command. Configuration first (it was disabled), then the DO path. A compressor (1) can't refuse a command it never received; dampers (3) and static (4) belong to other loops." } ] },
      { label: "DECISION — Complaint 1: rooms are cold at 7:30 a.m. Schedule: occupied 7:00. The sequence specifies optimal start enabled, but the front end shows optimal start OFF and the plant starting at 6:45 fixed — 15 minutes cannot recover a Monday-cold building. Root cause family: 1) The boiler plant is undersized 2) A strategy disabled in configuration — the building is being started like a fixed-schedule system, and Monday's deep weekend drift exposes it 3) The zone thermostats are inaccurate 4) The roof insulation failed over the weekend", cells: [""], inputs: [
        { col: 1, key: "so_optstart", expected: 2, hint: "Module 11: optimal start exists precisely because fixed starts fail exactly this way — worst after long cold weekends. The strategy being OFF in configuration is the finding. Plant size (1) is unproven until the plant is actually started early enough to test; sensors (3) were verified in Step 3 of your method." } ] },
      { label: "DECISION — During Step 5 you simulate a freezestat trip. Per the sequence the expected response set is: 1) Nothing — freezestats only log 2) Supply fan stops, outdoor dampers drive closed, heating valve opens, and a priority alarm posts at the front end 3) Stage 2 cooling starts 4) The unit switches to unoccupied mode only", cells: [""], inputs: [
        { col: 1, key: "so_freezestat", expected: 2, hint: "The standard protective trio plus annunciation (Module 10). A log-only freezestat (1) abandons the coil it protects; cooling (3) is the hazard direction; mode change (4) understates a safety event. If the live test produces anything less, it is a punch-list item, not a pass." } ] },
      { label: "DECISION — In Step 2 you found the discharge-air setpoint point in a manual override from a service visit five months ago. Correct disposition: 1) Leave it — someone wanted it there 2) Determine why it was overridden, confirm the reason is resolved, return it to automatic, and note it in the report — an override this old is an energy and control fault in itself 3) Delete the point 4) Raise the override value", cells: [""], inputs: [
        { col: 1, key: "so_override", expected: 2, hint: "Overrides are clinical tools, not settings (Modules 8/11/12). Five months of overridden discharge control silently defeated reset and staging logic — plausibly connected to the other complaints. Deleting points (3) destroys evidence and function; leaving it (1) is how the next five months happen." } ] },
      { label: "COMPUTED — A CO₂ sensor on this unit is ranged 0–2000 ppm on a 4–20 mA loop and currently outputs 8 mA. What concentration is it reporting? (Enter ppm.)", cells: [""], inputs: [
        { col: 1, key: "so_co2", expected: 500, hint: "Fraction = (8 − 4) ÷ 16 = 0.25. Concentration = 0.25 × 2000 = 500 ppm. Ventilation decisions are made from this number — compute it before you believe the graphic." } ] },
      { label: "DECISION — Zone sensors for the wing were verified in Step 3: two read within a degree of your reference at room temperature but drift 5°F apart when you warm them with your hand. Interpretation: 1) They are fine — hand-warming isn't a test 2) A curve/type mismatch on those inputs (error that changes across the range) — correct the configured sensor type and re-verify at two points 3) Replace both sensors immediately 4) Apply a 5°F offset", cells: [""], inputs: [
        { col: 1, key: "so_curve", expected: 2, hint: "Module 3/12 signature: agreement at one point, divergence at another = curve/scaling, not offset and not (yet) a dead element. Configuration fix first, then two-point re-verification. An offset (4) would force agreement at one end and worsen the other; replacement (3) installs the same mismatch on new hardware." } ] },
      { label: "DECISION — All faults are corrected and verified. What closes this call per Step 6? 1) Remove your test overrides only if you remember them 2) Restore every point to automatic, run the unit through its modes (occupied start, economizer, staging, safety trip), trend the repaired loops, and document findings and as-left configuration 3) Leave the unit in hand mode so it 'stays working' 4) Email the school that it is fixed without testing the heating-side functions", cells: [""], inputs: [
        { col: 1, key: "so_closeout", expected: 2, hint: "Step 6 is a full restoration and proof: automatic everything, modes exercised, loops trended, paperwork honest. 'If you remember them' (1) is how five-month overrides are born; hand mode (3) is an override with extra steps; untested functions (4) are unverified claims." } ] }
    ],
    passing: 70
  }
];
