// HVAC 208 - Module 4: Chiller Applications Overview
module.exports = {
  number: 4,
  slug: "chiller-applications-overview",
  title: "Chiller Applications Overview",
  estTime: "3–4 hours",
  objectives: [
    "Explain what a chiller produces and how chilled water decouples cooling production from air delivery.",
    "Compare air-cooled and water-cooled chillers on heat rejection, equipment needs, and typical applications.",
    "Distinguish scroll, screw, and centrifugal chiller compressors at the application level.",
    "Describe the three loops of a water-cooled chiller plant: refrigerant, chilled water, and condenser water.",
    "Use the water heat formula to compute chiller load from flow and temperature difference.",
    "Identify application factors — capacity, footprint, water availability, part-load profile — that drive chiller selection."
  ],
  sections: [
    {
      heading: "What a Chiller Is: Cooling as a Utility",
      html: `<p>A <strong>chiller</strong> is a refrigeration machine whose product is cold water. Instead of blowing air over its own evaporator coil in the occupied space, a chiller cools a circulating water loop — <strong>chilled water</strong> — and pumps send that water to air handlers and fan-coil units throughout a building, where it absorbs heat through their coils. The warm water returns to the chiller to be cooled again. Production of cold is centralized; delivery of cold is distributed.</p><p>This separation is the chiller's application power. One plant can serve a whole campus of coils through piping, zones can be added by adding terminal units, and the refrigeration equipment lives in one mechanical space (or on the roof) instead of in dozens of ceilings. The price of that power is complexity: pumps, piping, water treatment, and controls become part of the technician's world — the subjects of this module and Module 6.</p><div class="callout"><strong>Key idea:</strong> In a chiller plant there are up to three separate loops to keep straight: the <em>refrigerant</em> loop inside the machine, the <em>chilled-water</em> loop to the building, and (on water-cooled machines) the <em>condenser-water</em> loop to the cooling tower. Most beginner confusion in a plant room is really loop confusion.</div><p>Chillers still run the familiar four processes; their evaporator is a heat exchanger where refrigerant absorbs heat from the returning chilled water, and their condenser rejects heat to air or to condenser water.</p>`
    },
    {
      heading: "Air-Cooled vs. Water-Cooled",
      html: `<p>An <strong>air-cooled chiller</strong> rejects heat directly to outdoor air through finned condenser coils and fans, much like a very large condensing unit. It needs no cooling tower, no condenser-water loop, and no tower water treatment. It sits outdoors, and its efficiency suffers on the hottest days because its condensing temperature must float above the outdoor air temperature — exactly when the building needs it most.</p><p>A <strong>water-cooled chiller</strong> rejects heat into a condenser-water loop that carries the heat to a <strong>cooling tower</strong> (Module 6), where evaporation does the final rejection to the atmosphere. Because evaporation can cool water toward the outdoor <em>wet-bulb</em> temperature — lower than the dry-bulb on most days — a water-cooled plant can condense refrigerant at lower temperatures and generally runs more efficiently at large capacities. The trade is the tower itself: water consumption, treatment, freeze protection, and more equipment to maintain.</p><ul><li><strong>Air-cooled fits:</strong> smaller plants, scarce water, simple installations, places where tower maintenance is impractical.</li><li><strong>Water-cooled fits:</strong> large, steady loads where efficiency at scale pays back the tower and its upkeep.</li></ul><div class="callout"><strong>Key idea:</strong> The choice is an application decision, not a quality ranking. A small clinic may be best served air-cooled; a hospital campus almost always justifies water-cooled. Always ask about water availability, maintenance staffing, and load size before recommending either.</div>`
    },
    {
      heading: "Compressor Families Inside Chillers",
      html: `<p>At the application level, three compressor types dominate chillers. <strong>Scroll compressors</strong> appear in smaller air-cooled and modular chillers, often several in parallel so capacity can stage by turning compressors on and off. <strong>Screw compressors</strong> — twin intermeshing rotors — cover the broad middle range in both air- and water-cooled machines and typically control capacity with a slide valve that changes their effective pumping length. <strong>Centrifugal compressors</strong> use a high-speed impeller to fling refrigerant outward, converting velocity to pressure; they serve the largest water-cooled plants, move large volumes at modest pressure ratios, and control capacity with inlet guide vanes and speed.</p><p>Each type carries an application personality the technician should recognize. Scrolls: simple, staged in multiples. Screws: smooth continuous capacity control, comfortable at part load. Centrifugals: superb at design load in big plants, but with an operating boundary called <strong>surge</strong> — unstable flow at low load against high head — that their controls exist to avoid.</p><div class="callout"><strong>Key idea:</strong> Module 7 develops compressor mechanics and capacity control in full. Here, hold the map: scroll = small/modular, screw = mid-range workhorse, centrifugal = large-plant specialist. When a plant problem mentions surging, staging, or a slide valve, the compressor family tells you which conversation you are in.</div><p>Many modern machines in all three families use variable-speed drives to widen their efficient operating range — again, Module 7's territory.</p>`
    },
    {
      heading: "Reading the Plant: The Three Loops in Operation",
      html: `<p>Walk a water-cooled plant in the direction heat travels. The building's heat arrives at the air handlers, moves into the <strong>chilled-water loop</strong>, and returns warm to the chiller's evaporator. The <strong>refrigerant loop</strong> absorbs that heat (the compressor adding its work on the way) and rejects the total into the <strong>condenser-water loop</strong>. The condenser water carries it to the tower, where a portion evaporates and the atmosphere receives the heat. Pumps move the water loops; the compressor moves the refrigerant loop; controls coordinate them all.</p><p>The workhorse measurement of plant operation is the water-side temperature difference, because water heat transfer computes directly:</p><div class="formula">Btu/h = 500 × GPM × ΔT &nbsp;(water, standard approximation) &nbsp;·&nbsp; Tons = Btu/h ÷ 12,000</div><p><strong>Worked example.</strong> A chiller's chilled-water loop flows 240 GPM with water returning at 54°F and leaving at 44°F, a ΔT of 10°F. Load = 500 × 240 × 10 = 1,200,000 Btu/h = 100 tons. If the same flow shows only a 5°F ΔT, the plant is moving half the load — a clue (often oversized flow or bypassing coils) worth more than any single gauge reading.</p><p>Technicians earn trust in plant rooms by measuring ΔT and flow before touching setpoints: those two numbers state what the plant is actually doing, as opposed to what its displays assume.</p>`
    },
    {
      heading: "Selecting a Chiller for the Application",
      html: `<p>Application selection balances five factors. <strong>Capacity and load profile:</strong> a plant that lives at part load needs machines and staging that stay efficient there, not merely a big full-load rating. <strong>Heat rejection:</strong> air vs. water, decided by water supply, space, and maintenance capability. <strong>Footprint and access:</strong> a centrifugal machine needs rigging paths and tube-pull clearance; an air-cooled unit needs unobstructed condenser airflow. <strong>Redundancy:</strong> critical facilities often split load across multiple chillers so one can fail or be serviced without losing the building. <strong>Controls integration:</strong> the plant must sequence machines, pumps, and tower fans together, usually through the building automation system introduced in the controls courses.</p><div class="callout"><strong>Key idea:</strong> A chiller is never selected alone — it is selected as a plant: machine + pumps + tower (if water-cooled) + controls. Evaluating any one piece without the others repeats, at plant scale, the matched-components lesson of Module 1.</div><p><strong>Worked check — redundancy math.</strong> A building peaks at 200 tons. Two 100-ton chillers give full capacity but zero backup; three 100-ton machines (or two larger machines sized so one carries the critical load) trade first cost for resilience. There is no universally correct answer — there is only the owner's tolerance for a hot building during a failure, priced honestly.</p><p>For the rest of this course, hold the chiller picture steady: it is the refrigeration cycle wearing a water coat, chosen by application, and measured by flow and ΔT.</p>`
    }
  ],
  keyTerms: [
    { term: "Chiller", def: "Refrigeration machine that produces chilled water for distribution to air handlers and terminal coils." },
    { term: "Chilled-water loop", def: "Piping circuit carrying cooled water from the chiller to building coils and back." },
    { term: "Condenser-water loop", def: "Piping circuit carrying heat from a water-cooled chiller's condenser to the cooling tower." },
    { term: "Air-cooled chiller", def: "Chiller that rejects heat directly to outdoor air through finned coils and fans." },
    { term: "Water-cooled chiller", def: "Chiller that rejects heat into a condenser-water loop served by a cooling tower." },
    { term: "Scroll chiller compressor", def: "Orbiting-scroll compressor used in smaller and modular chillers, often staged in multiples." },
    { term: "Screw compressor", def: "Twin-rotor positive-displacement compressor common in mid-range chillers, often with slide-valve capacity control." },
    { term: "Centrifugal compressor", def: "Impeller machine that converts refrigerant velocity to pressure; used in large water-cooled chillers." },
    { term: "Surge", def: "Unstable flow condition in a centrifugal compressor at low flow against high pressure difference." },
    { term: "Slide valve", def: "Screw-compressor device that varies effective rotor length to control capacity." },
    { term: "Inlet guide vanes", def: "Adjustable vanes at a centrifugal compressor inlet that control capacity by pre-swirling refrigerant flow." },
    { term: "ΔT (delta-T)", def: "Temperature difference between entering and leaving water across a coil or chiller; used with flow to compute load." },
    { term: "GPM", def: "Gallons per minute, the standard unit of water flow in chiller plants." },
    { term: "Terminal unit", def: "Air handler or fan-coil unit where chilled water absorbs heat from building air." },
    { term: "Part-load operation", def: "Running below full capacity, where most plants spend most hours; staging and control quality matter most here." },
    { term: "Plant", def: "The coordinated system of chiller(s), pumps, tower, and controls serving a building's cooling." }
  ],
  video: {
    title: "How a Chiller System Works | Chiller to AHU Explained | MEP SOLUTIONS",
    embedUrl: "https://www.youtube.com/embed/P1HK410I_NU",
    note: "A short walk-through of a chiller system from the machine to the air handling unit, showing chilled water leaving the chiller, serving the AHU coil, and returning warm — with the cooling tower rejecting the heat. It mirrors the three-loop picture in Section 4 of this module.",
    more: []
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A chilled-water loop flows 120 GPM with a 10°F ΔT across the chiller. Compute the load in Btu/h and tons.</p>", solution: "<p><strong>Answer: 600,000 Btu/h = 50 tons.</strong> Step 1: Btu/h = 500 × GPM × ΔT = 500 × 120 × 10 = 600,000. Step 2: Tons = 600,000 ÷ 12,000 = 50. Step 3: This is the load actually being carried at those measured conditions.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A remote site has unreliable water supply and a 40-ton load. Air-cooled or water-cooled chiller, and why?</p>", solution: "<p><strong>Answer: air-cooled.</strong> Step 1: Water-cooled plants consume tower water and need treatment and upkeep. Step 2: With unreliable water, the tower is a liability. Step 3: An air-cooled chiller rejects heat to air with no water loop, accepting lower peak efficiency for reliability.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Name the three loops of a water-cooled chiller plant and what each carries.</p>", solution: "<p><strong>Answer:</strong> Step 1: Refrigerant loop — inside the machine, moves heat from evaporator to condenser, driven by the compressor. Step 2: Chilled-water loop — carries building heat to the chiller, driven by pumps. Step 3: Condenser-water loop — carries heat from the condenser to the cooling tower, driven by pumps.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A large plant's centrifugal chiller becomes unstable and noisy when the building load falls very low. Name the condition and one control feature used to avoid it.</p>", solution: "<p><strong>Answer: surge.</strong> Step 1: Centrifugal compressors surge at low flow against high head — flow breaks down and oscillates. Step 2: Controls avoid the surge region using inlet guide vanes and/or variable speed. Step 3: Plant sequencing (running a smaller machine at low load) is the application-level fix.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A chiller shows design flow but only half its design ΔT on the chilled-water side. State two likely application-level causes.</p>", solution: "<p><strong>Answer: any two of —</strong> Step 1: Coils bypassing or three-way valves sending water around coils so it returns unheated. Step 2: Excess flow for the actual load (over-pumped), which spreads the same load over more water and shrinks ΔT. Step 3: Terminal coils fouled or air-starved so they cannot transfer heat into the water. All three are distribution problems, not chiller failures.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Why do critical facilities often use multiple chillers instead of one large machine?</p>", solution: "<p><strong>Answer: redundancy and part-load staging.</strong> Step 1: With several machines, one can fail or be serviced while others carry critical load. Step 2: Staging machines lets the plant match output to part-load hours efficiently. Step 3: The trade is higher first cost and more controls complexity — an owner's risk decision.</p>" }
  ],
  quiz: [
    { q: "A chiller's direct product is:", choices: ["Cold air at a register", "Chilled water for distribution to coils", "Ice for storage only", "Condenser water"], answer: 1, explanation: "Correct: (b). Chillers cool water; terminal coils turn that into cool air. (a) Registers deliver air from air handlers, downstream of the chiller. (c) Ice storage is one optional application, not the definition. (d) Condenser water is the heat-rejection loop, which leaves warm, not chilled." },
    { q: "A water-cooled chiller can usually condense at lower temperatures than an air-cooled unit because:", choices: ["Its compressor is larger", "The tower uses evaporation, cooling water toward the wet-bulb temperature", "It uses a different refrigerant family", "Its water loops are shorter"], answer: 1, explanation: "Correct: (b). Evaporative cooling approaches wet bulb, typically below dry bulb, allowing lower condensing temperatures. (a) Compressor size does not set the heat-sink temperature. (c) Both types use common refrigerants. (d) Pipe length does not change the sink temperature." },
    { q: "Twin intermeshing rotors with a slide valve describe a:", choices: ["Scroll compressor", "Centrifugal compressor", "Screw compressor", "Reciprocating compressor"], answer: 2, explanation: "Correct: (c). Screw machines compress between helical rotors and often unload with a slide valve. (a) Scrolls use orbiting spiral plates. (b) Centrifugals use an impeller and guide vanes. (d) Reciprocating machines use pistons and valves." },
    { q: "With 180 GPM and an 8°F ΔT, the chilled-water load is:", choices: ["720,000 Btu/h", "500,000 Btu/h", "1,440,000 Btu/h", "90,000 Btu/h"], answer: 0, explanation: "Correct: (a). 500 × 180 × 8 = 720,000 Btu/h (60 tons). (b) 500,000 omits correct multiplication of flow and ΔT. (c) 1,440,000 doubles the true product. (d) 90,000 is 500 × 180 with no ΔT applied." },
    { q: "Surge is a concern specific mainly to which compressor type?", choices: ["Scroll", "Centrifugal", "Reciprocating", "Rotary vane"], answer: 1, explanation: "Correct: (b). Surge is unstable flow in a dynamic (centrifugal) compressor at low flow and high head. (a), (c), and (d) are positive-displacement machines; they have other limits but do not surge in this sense." },
    { q: "The condenser-water loop connects the:", choices: ["Chiller evaporator to the air handlers", "Chiller condenser to the cooling tower", "Tower basin to the boiler", "Compressor to the metering device"], answer: 1, explanation: "Correct: (b). Condenser water carries rejected heat from the chiller's condenser to the tower. (a) That path is the chilled-water loop, tied to the evaporator side. (c) Boilers are heating equipment, not part of this loop. (d) Compressor-to-metering flow is inside the refrigerant loop." },
    { q: "An air-cooled chiller is the better application choice when:", choices: ["The load is thousands of tons", "Water is scarce and maintenance staffing is minimal", "A tower already exists on site", "Peak efficiency is the only criterion"], answer: 1, explanation: "Correct: (b). No tower means no water use or treatment — decisive where water and staffing are limited. (a) Very large loads favor water-cooled plants. (c) An existing tower argues for water-cooled. (d) On efficiency alone, water-cooled usually wins at scale." },
    { q: "'Low ΔT' at design flow in a chilled-water plant most often indicates:", choices: ["A failed compressor", "A distribution problem — bypassing coils or excess flow for the load", "Correct operation at all times", "Low refrigerant charge"], answer: 1, explanation: "Correct: (b). Design flow with small ΔT means water returns without picking up its share of heat: bypasses, over-pumping, or fouled/starved coils. (a) Compressor failure shows as no cooling, not a specific flow/ΔT pattern. (c) Design ΔT is the target, not half of it. (d) Charge faults are refrigerant-side; ΔT here is measured on water." }
  ],
  studyGuide: `
<h3>Module 4 — Chiller Applications Overview: Quick Reference</h3>
<p><strong>Chiller = chilled-water factory.</strong> Three loops: refrigerant (inside machine), chilled water (to building coils), condenser water (to tower, water-cooled only).</p>
<p><strong>Air-cooled:</strong> rejects to air; simple, no water/treatment; efficiency falls on hot days. <strong>Water-cooled:</strong> rejects via tower toward wet bulb; efficient at scale; needs water, treatment, maintenance.</p>
<p><strong>Compressors:</strong> scroll = small/modular, staged in multiples · screw = mid-range, slide-valve control · centrifugal = large plants, guide vanes/speed, watch for surge at low load/high head.</p>
<div class="formula">Water load: Btu/h = 500 × GPM × ΔT · Tons = Btu/h ÷ 12,000</div>
<p><strong>Low ΔT at full flow</strong> = distribution fault (bypass, over-pumping, fouled coils), not a chiller fault.</p>
<p><strong>Selection:</strong> load profile and part-load behavior, heat-rejection resources, footprint/access, redundancy, controls — the plant as a matched system.</p>
<p><strong>Plant-round habit:</strong> log entering/leaving water temperatures and flows for both loops on every visit; trends in ΔT and approach (Module 6) predict most plant trouble weeks early.</p>
`
};
