// HVAC 245 - Module 5: Manual S: Equipment Selection
module.exports = {
  number: 5,
  slug: "manual-s-equipment-selection",
  title: "Manual S: Equipment Selection",
  estTime: "3–4 hours",
  objectives: ["State the selection rule: equipment capacity at design conditions must meet the load without gross oversizing.", "Read a nameplate and manufacturer-style rating in nominal tons and convert between tons and Btu/h.", "Use given capacity data at design conditions (not nominal) to accept or reject a candidate unit.", "Explain the penalties of oversizing: short cycling, poor dehumidification, noise, wear, and cost.", "Check sensible and latent capacity separately against the load's split."],
  sections: [
    { heading: "Selection Follows the Load", html: `<p>Equipment selection — the territory of ACCA Manual S in real practice — is a matching exercise. The load calculation hands you two numbers (heating and cooling, each split sensible/latent for cooling). The manufacturer's published performance data hands you capacities <em>at specific conditions</em>: outdoor temperature, indoor conditions, and airflow. The selection is correct when the equipment's capacity <strong>at the design conditions</strong> meets the load with a modest margin, following the sizing rules of the current procedure and code. Real selections use the manufacturer's full expanded performance tables and the current Manual S; here we practice with stated teaching data.</p><p>The traps are symmetrical. <strong>Undersizing</strong> fails openly: the space drifts from setpoint on design afternoons. <strong>Oversizing</strong> fails quietly and is far more common: the unit satisfies the thermostat quickly, shuts off, and never runs long enough to do its latent work or distribute air evenly. This module's job is to make you allergic to both — and fluent in the only antidote: compare capacity at design conditions to load at design conditions, in writing.</p><div class="callout"><strong>Key idea:</strong> A tonnage number on a brochure is a nickname, not a capacity. Capacity lives in performance data at stated conditions.</div><p>Keep the rejected candidates in the file with their rejection reasons. When a client asks why the 'bigger, safer' unit was not chosen, the worksheet — capacities at design conditions against the three load figures — answers better than any argument.</p>` },
    { heading: "Nominal Tons and Nameplates", html: `<p>One ton of cooling equals 12,000 Btu/h. Equipment is marketed in nominal sizes — 2-ton, 3-ton, 5-ton — but <strong>nominal</strong> means 'named,' not 'delivered.' A unit nicknamed 3 tons is rated under one standard set of test conditions; at your hotter design afternoon, with your longer duct system and your indoor humidity target, its delivered total and sensible capacities will differ, usually downward for cooling capacity as outdoor temperature climbs.</p><p><strong>Worked example.</strong> A candidate unit is listed as nominal 3 tons: 3 × 12,000 = 36,000 Btu/h nominal. The problem then gives its capacity at the project's design conditions as 33,500 Btu/h total, 24,500 sensible. The design load (given) is 31,000 total, 23,000 sensible. Check both: total 33,500 ≥ 31,000 ✓ (about 8% margin); sensible 24,500 ≥ 23,000 ✓. Latent available = 33,500 − 24,500 = 9,000 vs latent load 31,000 − 23,000 = 8,000 ✓. This unit passes on all three checks using <em>design-condition</em> data. Had you compared the load to the 36,000 nickname, you'd have believed the margin was 16% and never learned the unit's sensible split at all.</p><p>Nameplates still matter: they carry model and serial numbers, electrical requirements, and refrigerant — the identity card you record on every survey (and the data an installer needs for safe electrical and venting decisions).</p><p>Electrical and physical data ride along with the capacity decision: the selected unit's voltage, breaker, and clearance requirements must fit the building as surveyed. A capacity-perfect unit that cannot be legally wired or safely serviced is not, in fact, selectable.</p>` },
    { heading: "The Oversizing Penalties", html: `<p>Oversizing is not 'extra safety.' It is a different, worse system. <strong>Short cycling:</strong> a too-large unit reaches setpoint in minutes and shuts off; starts are the hardest wear a compressor and blower endure, and efficiency suffers because systems spend their first minutes reaching steady operation. <strong>Humidity failure:</strong> dehumidification needs long, steady coil time; short cycles leave the air cool and clammy — temperature satisfied, comfort not. <strong>Distribution failure:</strong> brief blasts of air cannot even out room temperatures, and the larger blower's air through ducts sized for less flow (or the noise when ducts are upsized) turns capacity into a noise complaint. <strong>Cost:</strong> bigger equipment costs more to buy, more to wire, and often more to run.</p><p><strong>Worked example.</strong> Load (given): 24,000 Btu/h total cooling. Candidate A capacity at design (given): 25,500 Btu/h — about 6% over. Candidate B: 36,000 Btu/h — 50% over. B will cycle roughly in proportion to its excess: on a mild day needing half the design load (12,000), B runs about 12,000 ÷ 36,000 = 33% of each hour in bursts, while A runs about 47% in longer, steadier stretches — and at design, A still covers the load. Select A. 'Bigger' bought nothing but shorter cycles.</p><div class="callout"><strong>Key idea:</strong> Runtime is a feature. A right-sized unit running long and steady dehumidifies, mixes, and lasts; an oversized unit sprinting and resting does none of those well.</div>` },
    { heading: "Heating Selection and Balance Point Thinking", html: `<p>Heating selection mirrors cooling: compare the equipment's output at design conditions to the heat loss. Furnaces are rated by input and output — the difference is efficiency — and heat pumps add a twist: their capacity <em>falls</em> as outdoor temperature drops, exactly when the load rises. The temperature where a heat pump's capacity line crosses the house's load line is its <strong>balance point</strong>; below it, supplemental heat must make up the difference.</p><p><strong>Worked example (all values given).</strong> House heat loss: 1,000 Btu/h per degree below 70°F (so at 30°F outdoors, loss = 40 × 1,000 = 40,000 Btu/h). A heat pump's given capacities: 36,000 Btu/h at 40°F outdoors, 28,000 at 30°F, 21,000 at 20°F. At 40°F the house loses 30 × 1,000 = 30,000 — the pump (36,000) carries it. At 30°F the house loses 40,000 but the pump gives 28,000 — supplemental heat must supply 12,000 Btu/h. The balance point lies between 40°F and 30°F, where the falling capacity line crosses the rising load line. No table was memorized; lines and given points did the work — and Module 7 of the heat-pump applications course builds operations on this same picture.</p><p>For furnaces, the parallel check is output vs loss with the modest margin the current procedure allows, plus the blower's ability to move the design CFM against the duct system's resistance — the bridge to Module 6.</p><p>Balance-point thinking also disciplines expectations in cold snaps: below the balance point the supplemental heat is not a failure or a backup in the emergency sense — it is a designed partner carrying a calculated share, sized by exactly the subtraction practiced here.</p>` },
    { heading: "The Selection Worksheet Discipline", html: `<p>Professional selection is a written comparison, not a verbal one. The worksheet lists: the loads (heating; cooling total/sensible/latent), the design conditions, each candidate's capacities <em>at those conditions</em> from manufacturer data, the resulting margins, and the airflow the candidate will move. Any candidate failing any line is rejected with the failing line noted. That paper trail is what separates design from salesmanship, and it is what you would want attached to your own home's installation.</p><p><strong>Worked example — a rejection.</strong> Load (given): total 28,000, sensible 22,400, latent 5,600 Btu/h. Candidate's design-condition data (given): total 29,500, sensible 21,000. Total passes (29,500 ≥ 28,000) but sensible fails: 21,000 &lt; 22,400. Latent available = 29,500 − 21,000 = 8,500 ≥ 5,600 passes, but one failure is enough — this unit would let indoor temperature drift on the design afternoon while over-drying the air. Reject, and note 'sensible short at design' as the reason. A different model (or the same model at higher airflow, if its data allows) is the fix, not a bigger nickname: the next nominal size might fix sensible while wrecking the latent split and the cycling behavior.</p><div class="callout"><strong>Key idea:</strong> Three checks — total, sensible, latent — at design conditions, in writing. Nominal tonnage is allowed on the worksheet only as a label.</div>` },
  ],
  keyTerms: [{ term: "Equipment selection", def: "Matching a specific unit's capacities at design conditions to the calculated loads (Manual S territory in real practice)." }, { term: "Nominal capacity", def: "The marketed size (e.g., 3 tons = 36,000 Btu/h nominal), a label rather than a delivered capacity." }, { term: "Expanded performance data", def: "Manufacturer tables giving capacity at combinations of outdoor temperature, indoor conditions, and airflow." }, { term: "Design-condition capacity", def: "What a unit actually delivers at the project's design temperatures and airflow; the only capacity a selection may use." }, { term: "Short cycling", def: "Frequent start-stop operation caused by oversizing; wastes energy, wears equipment, and ruins dehumidification." }, { term: "Sensible capacity", def: "The temperature-changing portion of a unit's cooling capacity at stated conditions." }, { term: "Latent capacity", def: "The moisture-removing portion: total capacity minus sensible capacity at stated conditions." }, { term: "Balance point", def: "Outdoor temperature where a heat pump's capacity exactly equals the building's heat loss." }, { term: "Supplemental heat", def: "Auxiliary heat (often electric resistance or a furnace) that covers the load below a heat pump's balance point." }, { term: "Furnace output", def: "Heat delivered to the airstream; input × efficiency, and the figure compared against heat loss." }, { term: "Oversizing", def: "Installing capacity far above the load; penalized by cycling, humidity, noise, and cost." }, { term: "Undersizing", def: "Installing capacity below the load; the space cannot hold setpoint at design conditions." }, { term: "Nameplate", def: "The equipment data label: model, serial, electrical, and refrigerant information." }, { term: "Runtime", def: "The fraction of time equipment runs; longer, steadier runtime aids dehumidification and mixing." }, { term: "Steady-state efficiency", def: "Efficiency once a system has run long enough to stabilize; short cycles rarely reach it." }, { term: "Selection margin", def: "The percentage by which design-condition capacity exceeds the load; kept modest by procedure." }, { term: "Rated combination", def: "The specific indoor/outdoor pairing for which performance data is published." }, { term: "Load line", def: "The building's heat loss plotted against outdoor temperature; rises as temperature falls." }],
  video: { title: "Mastering Manual J and COMcheck – Austin Energy Green Building Webinar", embedUrl: "https://www.youtube.com/embed/5IqGqjj49YA", note: "An Austin Energy Green Building webinar in which instructors walk through a Manual J load calculation for residential sizing and discuss code compliance. Use it to see the order of a real load calculation — survey, envelope, gains — before this module's simplified teaching examples. This course teaches the method only; real designs use the current ACCA manual and approved software.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A unit is nicknamed 4 tons. What is its nominal capacity in Btu/h, and why may the selection not stop there?</p>", solution: "<p><strong>Answer: 48,000 Btu/h nominal.</strong> Step 1: 4 × 12,000 = 48,000. Step 2: Nominal is a label at standard test conditions; selection must use the unit's capacity at the project's design conditions, which will differ.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Load (given): total 30,000, sensible 21,000, latent 9,000. Candidate at design (given): total 31,500, sensible 23,500. Accept or reject?</p>", solution: "<p><strong>Answer: reject — the latent check fails.</strong> Step 1: Total 31,500 ≥ 30,000 ✓ (5% margin). Step 2: Sensible 23,500 ≥ 21,000 ✓. Step 3: Latent available = 31,500 − 23,500 = 8,000, which is less than the 9,000 latent load ✗. Step 4: Passing two of three checks is still a rejection — this unit would hold temperature but let humidity climb.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Correct Problem 2 by finding the latent capacity of a second candidate (given): total 32,000, sensible 22,500. Does it pass all three checks?</p>", solution: "<p><strong>Answer: yes.</strong> Step 1: Total 32,000 ≥ 30,000 ✓. Step 2: Sensible 22,500 ≥ 21,000 ✓. Step 3: Latent = 32,000 − 22,500 = 9,500 ≥ 9,000 ✓. All three pass with modest margins.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A house loses 800 Btu/h per degree below 70°F. A heat pump's given capacity at 20°F outdoors is 18,000 Btu/h. How much supplemental heat is needed at 20°F?</p>", solution: "<p><strong>Answer: 22,000 Btu/h.</strong> Step 1: ΔT = 70 − 20 = 50. Step 2: Loss = 50 × 800 = 40,000 Btu/h. Step 3: Shortfall = 40,000 − 18,000 = 22,000 Btu/h of supplemental heat.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A furnace is rated (given) 80,000 Btu/h input at 80% efficiency. Find its output and judge it against a heat loss of 62,000 Btu/h.</p>", solution: "<p><strong>Answer: output 64,000 Btu/h — acceptable modest margin.</strong> Step 1: Output = 80,000 × 0.80 = 64,000. Step 2: Margin = 2,000 ÷ 62,000 ≈ 3% over the loss — it covers design without the gross oversize that causes short cycling.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A contractor proposes a 5-ton unit for a 30,000 Btu/h total load 'so it cools faster.' Give three specific penalties, referencing numbers where possible.</p>", solution: "<p><strong>Answer:</strong> Step 1: Capacity 60,000 vs load 30,000 = 100% oversize; on a half-load day (15,000) it runs ~25% of the hour in short bursts. Step 2: Short runtime starves dehumidification — the coil barely gets cold and wet before shutdown, so humidity stays high while temperature is met. Step 3: More starts = more compressor/blower wear, larger electrical demands, higher purchase cost — paying more for worse comfort.</p>" },
  ],
  quiz: [
    { q: "Selection must compare the load against the unit's capacity:", choices: ["At standard rating conditions only", "At the project's design conditions", "At the mildest day of the year", "From its nominal tonnage nickname"], answer: 1, explanation: "Correct: (b). Only design-condition data describes what the unit will do on the design day. (a) Standard conditions are a comparison convention, not your building's conditions. (c) Mild-day capacity is irrelevant to peak performance. (d) Nominal tonnage is a label, not a capacity at any condition." },
    { q: "A nominal 3-ton unit has a nominal capacity of:", choices: ["30,000 Btu/h", "36,000 Btu/h", "3,000 Btu/h", "42,000 Btu/h"], answer: 1, explanation: "Correct: (b). 3 × 12,000 = 36,000 Btu/h. (a) is 2.5 tons. (c) confuses tons with thousands. (d) is 3.5 tons." },
    { q: "A unit passes total and latent checks but its sensible capacity is below the sensible load. The selection is:", choices: ["Acceptable — two of three is enough", "Rejected — every check must pass", "Acceptable if the price is low", "Fixed by adding a humidifier"], answer: 1, explanation: "Correct: (b). Sensible shortfall means the space drifts above setpoint on the design afternoon; partial passes do not select equipment. (a) invents a majority rule that does not exist. (c) Price never cures a physics failure. (d) A humidifier adds moisture — the opposite direction and irrelevant to sensible capacity." },
    { q: "Oversizing most directly damages humidity control because:", choices: ["Big coils freeze", "Short runtimes give the coil too little time to condense moisture", "Big units use more refrigerant", "Humidity control needs small ducts"], answer: 1, explanation: "Correct: (b). Dehumidification is a runtime game: brief cycles satisfy the thermostat before sustained condensation occurs. (a) Freezing is an airflow/charge issue, not the oversizing mechanism. (c) Refrigerant quantity does not set humidity removal. (d) Duct size affects distribution and noise, not the coil's moisture time." },
    { q: "A heat pump's balance point is where:", choices: ["The thermostat is set", "Heat pump capacity equals the building heat loss", "Supplemental heat turns off in summer", "The ducts balance"], answer: 1, explanation: "Correct: (b). Below that outdoor temperature the falling capacity line drops under the rising load line and supplemental heat must help. (a) Setpoint is an indoor preference, not the crossing. (c) Supplemental heat is a heating-season device. (d) 'Balance' in duct work means airflow proportioning — a different term." },
    { q: "House loss rate (given): 900 Btu/h per °F below 70°F. Heat pump capacity at 30°F (given): 27,000 Btu/h. Supplemental heat needed at 30°F is:", choices: ["9,000 Btu/h", "36,000 Btu/h", "0 Btu/h", "63,000 Btu/h"], answer: 0, explanation: "Correct: (a). Loss at 30°F = 40 × 900 = 36,000; shortfall = 36,000 − 27,000 = 9,000 Btu/h. (b) is the loss itself, ignoring the pump's contribution. (c) would require capacity ≥ loss. (d) adds loss and capacity instead of subtracting." },
    { q: "Latent capacity of a unit is found by:", choices: ["Reading it from the nominal tonnage", "Total capacity minus sensible capacity at the same conditions", "Doubling sensible capacity", "The furnace efficiency"], answer: 1, explanation: "Correct: (b). Total = sensible + latent, so latent is the difference — always at the same stated conditions. (a) Tonnage carries no split information. (c) The split is not a fixed doubling. (d) Furnace efficiency concerns heating output." },
    { q: "Which candidate is best for a given 24,000 Btu/h design load?", choices: ["Capacity at design 60,000 — 'plenty of reserve'", "Capacity at design 25,200 — about 5% over", "Capacity at design 20,000 — 'it will catch up at night'", "Whichever is cheapest per ton"], answer: 1, explanation: "Correct: (b). A modest margin at design conditions covers the load without oversizing penalties. (a) is 150% oversize — cycling and humidity failure. (c) is undersized and cannot hold setpoint at design. (d) Price per ton ignores the capacity split and conditions entirely." },
  ],
  studyGuide: `
<h3>Module 5 — Manual S: Equipment Selection: Quick Reference</h3>
<p><strong>Rule:</strong> capacity at design conditions (from manufacturer data) must meet the load — checked three ways: total, sensible, latent. Real selections follow the current Manual S and the manufacturer's expanded tables.</p>
<div class="formula">1 ton = 12,000 Btu/h (nominal) · Latent capacity = total − sensible · Furnace output = input × efficiency</div>
<p><strong>Oversizing penalties:</strong> short cycling, poor dehumidification (runtime starvation), temperature unevenness, noise, wear, cost. <strong>Undersizing:</strong> cannot hold setpoint at design.</p>
<p><strong>Heat pumps:</strong> capacity falls as outdoor temperature falls; balance point = where capacity line crosses load line; below it, supplemental heat covers the difference (loss − capacity).</p>
<p><strong>Worksheet discipline:</strong> loads, design conditions, each candidate's design-condition capacities, margins, and a written accept/reject reason per candidate.</p>
<p><strong>Watch out:</strong> selecting on the tonnage nickname; passing a unit on two of three capacity checks.</p>
<p><strong>One-line summary:</strong> a selection is three inequalities at design conditions — total, sensible, latent — and a unit that fails any one is not 'close enough,' it is the wrong unit for this building.</p>
`
};
