// HVAC 245 - Module 7: Air Distribution
module.exports = {
  number: 7,
  slug: "air-distribution",
  title: "Air Distribution",
  estTime: "3–4 hours",
  objectives: ["Distinguish registers, grilles, and diffusers and the job each does in supply and return paths.", "Explain throw, spread, and drop in plain language and use given throw data to place an outlet.", "Compute face velocity from CFM and given free area, and relate velocity to noise and draft complaints.", "Describe the balancing procedure: measure, compare to design CFM, adjust dampers, re-measure.", "Explain why every room with a supply and a closable door needs a return path."],
  sections: [
    { heading: "Three Devices, Three Jobs", html: `<p>The duct system ends at the room, and the ending hardware decides whether good air becomes good comfort. A <strong>register</strong> is a supply outlet fitted with adjustable dampers or vanes — it delivers air and lets you aim it. A <strong>grille</strong> is a covering with no damper — most return inlets are grilles, since return air needs no aiming, only an easy, quiet entry. A <strong>diffuser</strong> is a supply device engineered to mix supply air with room air rapidly, commonly ceiling-mounted in commercial work with a patterned discharge. The vocabulary matters because each device is selected from different manufacturer data: registers and diffusers by throw and airflow at an acceptable sound level, return grilles by face velocity and free area.</p><p>Selection follows the room schedule from Module 6: each room's design CFM is assigned to one or more outlets, and each outlet is chosen from its catalog data to deliver that CFM within the room's noise target and with a throw that fits the room's geometry. Catalog data — throws, pressure drops, sound ratings at given flows — comes from the grille/register manufacturer on real jobs; in this course any such data is given in the problem.</p><div class="callout"><strong>Key idea:</strong> The register is not a decoration screwed on at the end. It is a selected component with flow, throw, pressure, and sound numbers, like every other part of the design.</div>` },
    { heading: "Throw, Spread, and Drop", html: `<p>Supply air leaves an outlet as a jet. <strong>Throw</strong> is how far that jet travels before its speed decays to a stated terminal velocity (catalog data states the convention it uses). <strong>Spread</strong> is how wide the jet fans out. <strong>Drop</strong> is how far a cool jet falls as it slows — cold air is denser and sinks, so a cooling jet arcs downward while a warm jet rises. Good placement uses all three: the jet should wash the load (typically the exterior wall and its windows, where the load is), mix with room air before reaching occupants, and arrive at breathing level gently.</p><p><strong>Worked example (catalog values given).</strong> A register's given throw at 200 CFM is 12 ft to the catalog's terminal velocity. The room is 14 ft from the register wall to the far seating area. Verdict: at design flow the jet effectively reaches 12 of the 14 ft — marginal. Options a designer weighs: select the next outlet style with a longer rated throw at the same CFM, split the 200 CFM between two registers on the same wall (each at 100 CFM with its own given throw), or relocate the outlet. What the designer does not do is open the register damper 'harder' — damper position does not change the catalog throw relationship, it only unbalances the branch.</p><p>Ceiling diffusers play the same game in plan view: throw is measured along the ceiling, and the jet clings (the Coandă effect along a surface) before dropping at the room's edges — which is why diffuser placement near walls is a catalog-guided decision, not a guess.</p>` },
    { heading: "Velocity, Free Area, and Noise", html: `<p>Air squeezed through a small opening speeds up, and speed at a grille means noise, drafts, and pressure drop. The governing arithmetic is simple:</p><div class="formula">Velocity (fpm) = CFM ÷ free area (sq ft)</div><p><strong>Worked example.</strong> A return grille with a given free area of 1.5 sq ft must pass 600 CFM: velocity = 600 ÷ 1.5 = 400 fpm. A smaller grille with 0.75 sq ft free area passing the same 600 CFM runs at 800 fpm — twice the speed, audibly louder, and with a higher pressure drop that spends ASP (Module 6's budget) at the worst place. Gross area (the hole in the wall) is not free area: bars and louvers block part of it, and manufacturer data gives the free-area ratio. Using gross area in this equation understates velocity and is a classic return-sizing error — the same undersized-return failure the course lab flags as a safety-and-performance issue.</p><p>Supply registers follow the same physics with an added comfort term: the jet's speed at occupants is what throw data describes. The design targets differ by location — a bedroom wants the quietest hardware in the house; a commercial space tolerates more — and the applicable targets come from the current design references and manufacturer ratings on real jobs.</p><div class="callout"><strong>Key idea:</strong> When a grille whistles, the fix is area, not patience. Double the free area and the same CFM moves at half the velocity.</div>` },
    { heading: "Balancing: Making the Paper True", html: `<p>A duct design is a prediction. <strong>Balancing</strong> is the field procedure that makes the installed system match it: measure each outlet's actual airflow, compare it with the design CFM, adjust branch dampers, and re-measure until each room is within a reasonable tolerance of its scheduled flow. Measurement uses instruments Module 11 covers — flow hoods that capture an outlet's air, or traverse/anemometer methods in ducts. The adjustment logic is proportional: the branch furthest over its target gets dampered first, and because branches share a trunk, each change shifts the others, so balancing proceeds in rounds.</p><p><strong>Worked example.</strong> Design CFM: living 300, kitchen 250, bed 1 200, bed 2 150 (the lab house). First measurement: living 330 (+10%), kitchen 240 (−4%), bed 1 210 (+5%), bed 2 120 (−20%). Total measured = 900 — the blower is delivering design total, so this is a distribution problem, not an airflow problem. Action: trim the living branch damper (and slightly bed 1), pushing share toward bed 2; re-measure; expect bed 2 to rise toward 150 as the over-fed branches come down. If the total had been 720 instead of 900, no damper work could fix it — the fault would be upstream (blower setting, static pressure, duct restriction), and balancing dampers cannot create air the system does not move.</p><div class="callout"><strong>Key idea:</strong> Dampers redistribute; they do not generate. Verify total airflow first, then proportion the branches.</div>` },
    { heading: "Return Paths and Pressure Balance Between Rooms", html: `<p>Supply air delivered to a bedroom with the door closed must get back to the return, or the room pressurizes and the supply flow chokes off. The return path may be a ducted return in the room, a transfer grille, a jumper duct over the door, or a generous door undercut — but it must be a designed path with enough area, not a hope. <strong>Worked example.</strong> A bedroom is supplied 200 CFM. Its only return path is a door undercut with a given free area of 0.2 sq ft: velocity = 200 ÷ 0.2 = 1,000 fpm through the gap — the door whistles, the room pressurizes, and the delivered flow falls as the blower works against the restriction. Enlarging the path to a transfer grille of 1.0 sq ft free area drops the velocity to 200 fpm and restores both quiet and flow.</p><p>Pressure balance also matters for safety-adjacent reasons designers must respect: a strongly depressurized room containing fuel-burning appliances can interfere with venting draft — one more reason return design got a Step 0 safety callout in this course's lab, and why 'just close the vents in unused rooms' is bad advice: it unbalances pressures and raises duct static for the rooms still open. Air distribution is the visible end of the whole design chain — when it is right, the system disappears: even temperatures, low sound, no drafts, no whistling doors.</p><p>Real-estate corollary worth telling clients: the 'bonus room is always hot' complaint is very often this section's problem — a supplied room with no real return path — rather than an equipment failure. The fix is carpentry and a grille, not a bigger air conditioner.</p>` },
  ],
  keyTerms: [{ term: "Register", def: "A supply outlet with adjustable dampers/vanes for delivering and aiming air." }, { term: "Grille", def: "A non-adjustable covering, typically used at return inlets." }, { term: "Diffuser", def: "A supply device engineered to mix supply air with room air, usually ceiling-mounted." }, { term: "Throw", def: "Distance a supply jet travels before decaying to a stated terminal velocity, per catalog data." }, { term: "Spread", def: "The width over which a supply jet fans out." }, { term: "Drop", def: "The downward arc of a cooling jet as it slows and its denser air sinks." }, { term: "Face velocity", def: "Air speed at a grille or register face: CFM ÷ free area." }, { term: "Free area", def: "The unobstructed portion of an outlet's area available for airflow, per manufacturer data." }, { term: "Gross area", def: "The overall dimensions of an outlet opening, including bars and frame; always larger than free area." }, { term: "Flow hood", def: "An instrument that captures air from an outlet to measure its CFM directly." }, { term: "Balancing", def: "Measuring actual outlet flows and adjusting dampers so each matches its design CFM." }, { term: "Branch damper", def: "The adjustable plate in a branch duct used during balancing to trim that branch's share." }, { term: "Transfer grille", def: "A grille providing a return-air path between a room and the return system, often through a wall or door." }, { term: "Jumper duct", def: "A short duct above a ceiling connecting a room to a hallway as its return path." }, { term: "Door undercut", def: "The gap under a door serving as a (often inadequate) return path." }, { term: "Room pressurization", def: "Pressure rise in a supplied room lacking a return path, which chokes its own supply flow." }, { term: "Terminal velocity", def: "The jet speed at which throw is rated in catalog data." }, { term: "Coandă effect", def: "A jet's tendency to cling to a nearby surface such as a ceiling." }],
  video: { title: "Duct Design for Great Results w/ Ed Janowiak (ACCA)", embedUrl: "https://www.youtube.com/embed/-KqmAQgUXY4", note: "An ACCA presentation on fan and duct design, system testing, and Manual D — including grille selection, throw, and terminal velocity, which are this module's air-distribution topics. Watch the grille and register portions closely.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A return grille has a given free area of 2.0 sq ft and must pass 700 CFM. Find face velocity.</p>", solution: "<p><strong>Answer: 350 fpm.</strong> Step 1: Velocity = CFM ÷ free area. Step 2: 700 ÷ 2.0 = 350 fpm.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> The grille in Problem 1 is replaced by one with 1.0 sq ft free area at the same 700 CFM. Find the new velocity and state two consequences.</p>", solution: "<p><strong>Answer: 700 fpm.</strong> Step 1: 700 ÷ 1.0 = 700 fpm — doubled. Step 2: Consequences: higher noise at the grille, and higher pressure drop spending the system's ASP, which can reduce delivered CFM everywhere.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Design flows are A 300, B 200, C 100 (total 600). Measured: A 360, B 180, C 60 (total 600). Which branches get dampered, which opened, and why is no blower change needed?</p>", solution: "<p><strong>Answer:</strong> Step 1: Total matches design (600), so the blower and ducts deliver enough air — distribution only. Step 2: A is +20% (damper down), B is −10% and C is −40% (open their paths / trim A further). Step 3: Re-measure after each round; expect B and C to rise as A's excess is redirected.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A register's given throw at 150 CFM is 10 ft. The room needs effective reach of 13 ft. List three legitimate design responses.</p>", solution: "<p><strong>Answer:</strong> Step 1: Choose a different outlet whose catalog throw at 150 CFM reaches 13 ft. Step 2: Split the flow between two outlets (75 CFM each) positioned to cover the room, using their given throws at that flow. Step 3: Relocate the outlet (e.g., ceiling diffuser placement) so geometry shortens the needed reach. Cranking a damper is not on the list — it does not change catalog throw and unbalances the branch.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A bedroom supplied 180 CFM has a return path of 0.3 sq ft free area. Find the path velocity and the free area needed to bring it to 300 fpm.</p>", solution: "<p><strong>Answer: 600 fpm now; 0.6 sq ft needed.</strong> Step 1: 180 ÷ 0.3 = 600 fpm. Step 2: Area = CFM ÷ velocity = 180 ÷ 300 = 0.6 sq ft — e.g., a properly sized transfer grille. Step 3: Doubling area halves velocity, ending the whistle and the room pressurization.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Measured total airflow is 750 CFM against a design total of 1,000 CFM, though branch proportions match the design schedule almost exactly. Can balancing fix this? What is the correct next step?</p>", solution: "<p><strong>Answer: no.</strong> Step 1: Dampers redistribute an existing total; proportions are already right, so there is nothing to redistribute. Step 2: The fault is upstream: check blower speed/setting, filter condition, and total external static pressure against the design budget (Module 11's verification work). Step 3: Fix the cause, restore the total, then re-check proportions.</p>" },
  ],
  quiz: [
    { q: "A grille differs from a register in that a grille:", choices: ["Delivers supply air with dampers", "Has no damper and is typically used at returns", "Is always ceiling-mounted", "Moves more air"], answer: 1, explanation: "Correct: (b). Grilles are plain coverings, standard for return inlets. (a) describes a register. (c) Grilles appear on walls, floors, and ceilings. (d) Flow depends on size and pressure, not the label." },
    { q: "Throw is defined as the distance a jet travels before:", choices: ["It stops completely", "Its velocity decays to the catalog's stated terminal velocity", "It reaches the return", "It warms to room temperature"], answer: 1, explanation: "Correct: (b). Catalog throw is measured to a specified terminal velocity — air still moves beyond it, just more gently. (a) A jet decays gradually; 'stops' is not a rating basis. (c) Return location is a layout choice, not the throw definition. (d) Temperature equalization is mixing, not the throw criterion." },
    { q: "A grille passing 800 CFM with 2.0 sq ft free area has a face velocity of:", choices: ["1,600 fpm", "400 fpm", "266 fpm", "800 fpm"], answer: 1, explanation: "Correct: (b). 800 ÷ 2.0 = 400 fpm. (a) multiplies instead of dividing. (c) divides by 3. (d) repeats the CFM as if area were 1.0." },
    { q: "Using gross area instead of free area in the velocity equation:", choices: ["Overstates velocity", "Understates velocity and hides a noise/drop problem", "Has no effect", "Only matters for supplies"], answer: 1, explanation: "Correct: (b). Gross area is larger, so the computed velocity is lower than reality — the grille is louder and more restrictive than the paper says. (a) is backwards. (c) The difference is exactly the bars and louvers — significant. (d) Returns are where this error is most common." },
    { q: "During balancing, the correct first comparison is:", choices: ["Each room's temperature", "Measured total airflow vs design total", "Damper positions vs the blueprint color", "Register prices"], answer: 1, explanation: "Correct: (b). If the total is wrong, the fault is upstream and dampers cannot help; if the total is right, proportioning is meaningful. (a) Temperatures lag and mislead during adjustment. (c) and (d) are not measurements of airflow." },
    { q: "A closed-door bedroom that whistles at the undercut and receives weak supply most likely lacks:", choices: ["A larger supply register", "An adequate return path", "A colder coil", "A second thermostat"], answer: 1, explanation: "Correct: (b). Supplied air cannot leave, the room pressurizes, and flow chokes — the undercut velocity example (1,000 fpm) is the tell. (a) A bigger supply worsens pressurization. (c) Coil temperature does not fix a pressure path. (d) Controls cannot move air through a wall." },
    { q: "Dampers in a duct system can:", choices: ["Create additional total airflow", "Redistribute airflow among branches", "Lower the blower's static capability", "Replace the friction-rate design"], answer: 1, explanation: "Correct: (b). Dampers trim over-fed branches so under-fed ones gain share. (a) Only the blower and system resistance set the total. (c) Dampers spend pressure; they do not change the blower. (d) Design sets the sizes balancing then fine-tunes." },
    { q: "A cool supply jet tends to drop as it slows because:", choices: ["Cold air is denser and sinks as jet momentum fades", "The register aims it down", "Returns pull it down", "Humidity makes it heavy enough to matter"], answer: 0, explanation: "Correct: (a). Density and momentum explain drop (and why warm jets rise). (b) Some registers do aim, but drop occurs with level throws too. (c) Returns are too far and too gentle to steer the jet. (d) Moisture's density effect is minor beside temperature's." },
  ],
  studyGuide: `
<h3>Module 7 — Air Distribution: Quick Reference</h3>
<p><strong>Devices:</strong> register = supply with dampers · grille = plain covering, mostly returns · diffuser = engineered mixing supply, usually ceiling.</p><div class="formula">Face velocity (fpm) = CFM ÷ free area (sq ft) — never gross area</div>
<p><strong>Jet behavior:</strong> throw = distance to catalog terminal velocity · spread = width · drop = cool jet's downward arc. Place outlets to wash the load and mix before reaching occupants; use given catalog data.</p>
<p><strong>Balancing:</strong> measure total first (fix upstream faults if wrong), then compare each outlet to its design CFM, trim over-fed dampers, re-measure in rounds.</p>
<p><strong>Return paths:</strong> every supplied room needs one — ducted return, transfer grille, jumper duct, or adequate undercut. Pressurized rooms whistle, starve, and can disturb appliance venting.</p>
<p><strong>Watch out:</strong> selecting outlets by appearance; believing dampers create airflow; closing registers in 'unused' rooms.</p>
<p><strong>Exam-style drill:</strong> velocity problems are always CFM ÷ area — check that the area is free area and in square feet before dividing. Pressure problems are always about paths: air supplied must have a way back, or the room itself becomes the restriction.</p>
`
};
