// HVAC 245 - Module 11: Insulation, Sound & Measurement Techniques
module.exports = {
  number: 11,
  slug: "insulation-sound-measurement",
  title: "Insulation, Sound & Measurement Techniques",
  estTime: "3–4 hours",
  objectives: ["Explain where duct insulation belongs, what it prevents (loss, gain, condensation), and how its value is specified on real jobs.", "Describe noise criteria thinking: sources, paths, and why velocity is the designer's main sound lever.", "Measure and interpret total external static pressure against the design budget.", "Verify delivered airflow by three methods — flow hood, duct traverse/anemometer, and temperature-split/rise — and cross-check them.", "Run a design-verification checklist that closes the loop from Module 3's worksheet to the installed system."],
  sections: [
    { heading: "Duct Insulation: Protecting Air You Already Paid to Condition", html: `<p>Air inside a duct is finished product: it has been heated or cooled at fuel expense. A duct running through an unconditioned attic, crawlspace, or garage leaks that value through its walls by the same Q = U × A × ΔT physics as Module 3 — with duct surface area as the A. In summer the reverse also bites: a cold supply duct in a humid attic both gains heat and can sweat if its outer surface falls below the attic air's dew point, dripping onto ceilings. Insulation with a proper vapor-retardant jacket answers all three problems — loss, gain, condensation — and its required level for a real job comes from the applicable energy code; the design skill here is accounting for ducts honestly in the load (ducts outside the envelope add load or deserve a location change) and specifying insulation where ducts must live outside.</p><p><strong>Worked example (values given).</strong> A supply trunk presents 60 sq ft of surface in a vented attic. Bare-metal effective U is given as 0.60; insulated effective U is given as 0.08 (teaching values for this example). Summer condition: attic 130°F at peak hour in this example, supply air 55°F (ΔT 75). Bare: 0.60 × 60 × 75 = 2,700 Btu/h gained — nearly a quarter-ton of cooling spent on the attic. Insulated: 0.08 × 60 × 75 = 360 Btu/h. The insulation 'saved' 2,340 Btu/h of delivered capacity — often the cheapest 'capacity' in the whole design, and invisible in any selection that ignored duct location.</p><div class="callout"><strong>Key idea:</strong> The best duct location is inside the thermal envelope. The second best is insulated like it matters — because arithmetically, it does.</div>` },
    { heading: "Sound: The Comfort You Hear", html: `<p>Occupants judge systems by ear as much as by skin. HVAC noise has three families: <strong>equipment sound</strong> (blower, compressor, burner), <strong>air sound</strong> (velocity noise at ducts, dampers, and grilles — rising steeply with speed), and <strong>structure-borne sound</strong> (vibration traveling through framing and duct metal). Design attacks each at its lever: equipment located and isolated sensibly; velocities kept in the quiet range by the Module 6 friction-rate discipline and Module 7's free-area choices; flexible connectors and lined or properly supported runs breaking the vibration path. Noise criteria in professional practice are expressed with rating systems from the current references and manufacturer sound data; the designer's working rule in this course is the causal chain — sound follows velocity and turbulence, so a quiet system is designed quiet on paper, through FR, sizes, and outlet selection, not muffled afterward.</p><p><strong>Worked comparison.</strong> A branch must deliver 200 CFM. Option A (given velocity through its register free area): 200 CFM ÷ 0.25 sq ft = 800 fpm. Option B: 200 ÷ 0.50 sq ft = 400 fpm. Same air, same room — but B's outlet runs at half the face velocity, with the corresponding drop in air noise and pressure drop, at the cost of a larger register. Multiplied across a bedroom wing, that single ×2 in free area is the difference between 'the system hums all night' and silence. Turbulence deserves its line: a crushed flex run or a damper nearly closed can out-shout any register — installation quality is a sound specification too.</p>` },
    { heading: "Verifying Static Pressure: The Budget Meets the Manometer", html: `<p>Module 6 designed against a pressure budget; commissioning measures the real one. <strong>Total external static pressure</strong> is measured with a manometer (or digital pressure gauge) between the blower's inlet and outlet sides — return-side pressure at the filter/blower inlet, supply-side pressure at the blower outlet/plenum — with the probes and locations per instrument and manufacturer guidance. The total is compared with the blower's rating table at the measured CFM: if TESP exceeds the design value, the blower rides a worse point on its curve and delivered CFM falls (with constant-torque motors) or energy use climbs (with constant-airflow ECMs compensating).</p><p><strong>Worked example (values given).</strong> Design: TESP 0.50 in. w.c. at 900 CFM. Measured: supply side +0.32, return side −0.38 (magnitudes sum: 0.32 + 0.38 = 0.70 in. w.c.). The system runs 0.20 over budget. Diagnostic split: the return side alone exceeds its design share — pointing at the return path (undersized return, restrictive grille, or a dirty/premium filter, Module 6's swap story) rather than the supply ducts. Remediation follows the measurement: enlarge the return path or correct the filter selection, then re-measure. Guessing would have upsized supplies and missed the fault entirely.</p><div class="callout"><strong>Key idea:</strong> Measure both sides separately. The total tells you there is a problem; the split tells you where.</div>` },
    { heading: "Verifying Airflow Three Ways", html: `<p>Delivered CFM is the design's promise; three field methods verify it, and professionals cross-check because each has a weakness. <strong>Flow hood:</strong> captures air at each register/grille and reads CFM directly — fast and room-specific (Module 7's balancing instrument), but hoods add a little back-pressure and struggle with odd outlet shapes. <strong>Duct traverse / anemometer:</strong> velocity measured at points across a duct, averaged, times duct area (CFM = average fpm × sq ft) — accurate in straight runs, poor near fittings. <strong>Temperature method:</strong> in heating, airflow follows from the sensible equation using measured temperature rise and delivered Btu/h; in cooling, the split is a rough indicator only.</p><p><strong>Worked examples.</strong> Traverse: average velocity (given) 750 fpm in a duct of 1.2 sq ft free area → CFM = 750 × 1.2 = 900 CFM. Temperature rise: a furnace delivering a given 43,200 Btu/h output with measured rise of 50°F → CFM = 43,200 ÷ (1.08 × 50) = 800 CFM. If the hood total says 900, the traverse says 900, and (in cooling, where the temp method is weaker) the math is consistent for heating at 800 against a different operating point — agreement within reason between independent methods is what 'verified' means; a lone number from one tool is a claim, not a verification.</p><p>Safety note for field work: verification happens around live equipment — lockout/tagout for opened panels, care with rotating blowers, and no measurements that require defeating safeties. Module 11 measures; it never bypasses.</p>` },
    { heading: "The Design-Verification Checklist", html: `<p>Close the loop in writing, comparing installed reality against each design document: (1) <strong>Loads:</strong> as-built envelope matches the survey assumptions (insulation installed, windows as specified). (2) <strong>Selection:</strong> installed model numbers are the selected rated combination. (3) <strong>Airflow:</strong> total CFM within tolerance of design; room CFMs balanced per Module 7. (4) <strong>Static:</strong> TESP at or under the budgeted value, split by side. (5) <strong>Ducts:</strong> insulation intact where specified, flex pulled tight, dampers marked at balanced positions. (6) <strong>Ventilation:</strong> measured rate matches design; recovery unit running, drained, and hoods clear. (7) <strong>Humidity:</strong> indoor RH observed in range across a run cycle, not just temperature. (8) <strong>Sound:</strong> subjective pass in the quietest room at design speed, plus any grille whistle hunted to its area problem.</p><p>Each unchecked box is a specific, findable defect — that is the point of designing on paper first. A system with no design documents can only be judged by 'seems fine,' and 'seems fine' is how 0.70-static systems and clammy houses get signed off. The checklist is also the homeowner's evidence and the next technician's map: leave it with the job paperwork, beside the load worksheet where this course began.</p><div class="callout"><strong>Key idea:</strong> Verification is not distrust — it is the final design step, the one that happens with instruments instead of pencils.</div>` },
  ],
  keyTerms: [{ term: "Duct insulation", def: "Material (with vapor-retardant jacket where required) limiting heat loss/gain and condensation on ducts outside conditioned space." }, { term: "Vapor retardant jacket", def: "The outer facing on duct insulation that slows moisture migration toward cold duct surfaces." }, { term: "Noise criteria", def: "Rating frameworks used to set acceptable sound levels for spaces; applied via current references and manufacturer data." }, { term: "Air (velocity) noise", def: "Sound generated by air turbulence at ducts, dampers, and outlets; rises steeply with velocity." }, { term: "Structure-borne sound", def: "Vibration transmitted through building structure and duct metal from equipment." }, { term: "Manometer", def: "An instrument measuring pressure difference in inches of water column (or digital equivalent)." }, { term: "Total external static pressure (measured)", def: "Supply-side plus return-side static magnitudes at the blower in the installed system." }, { term: "Blower curve/table", def: "Manufacturer data relating CFM to static pressure for a blower and speed/setting." }, { term: "Flow hood", def: "A capture instrument reading CFM directly at an outlet or inlet." }, { term: "Duct traverse", def: "A pattern of velocity measurements across a duct cross-section, averaged to compute CFM." }, { term: "Anemometer", def: "An instrument measuring air velocity (fpm) at a point or outlet." }, { term: "Temperature rise", def: "Supply minus return air temperature in heating; with output, yields CFM via the sensible equation." }, { term: "Temperature split", def: "Return minus supply air temperature in cooling; a rough performance indicator, not an airflow meter." }, { term: "Commissioning", def: "The systematic verification that an installed system performs as designed." }, { term: "As-built", def: "The installed condition as actually constructed, compared against design documents during verification." }, { term: "Tolerance", def: "The accepted deviation between design and measured values for a verified quantity." }, { term: "Balanced position marks", def: "Permanent marks recording final damper settings after balancing." }, { term: "Lockout/tagout", def: "The safety procedure isolating equipment energy before service — required around opened panels during verification." }],
  video: { title: "Measuring Static Pressure on an Air Handler for Airflow CFM!", embedUrl: "https://www.youtube.com/embed/eFmDmk1Siqc", note: "A field demonstration of measuring static pressure on an air handler and using it to judge airflow. This module is about verifying a design after installation, and this video shows the first verification measurement you will actually make.", more: [{ title: "Airflow CFM Measure with a Hot Wire Anemometer", url: "https://www.youtube.com/watch?v=0wWYsAn6eGo" }] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Duct surface 80 sq ft, ΔT 70 (given). Compare heat loss for effective U values (given) of 0.50 (bare) and 0.07 (insulated).</p>", solution: "<p><strong>Answer: 2,800 vs 392 Btu/h.</strong> Step 1: Bare: 0.50 × 80 × 70 = 2,800. Step 2: Insulated: 0.07 × 80 × 70 = 392. Step 3: Insulation avoids 2,408 Btu/h of loss — capacity the plant no longer owes.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Measured statics: supply +0.28, return −0.47. Design TESP is 0.50. Find measured TESP, the excess, and the likely side at fault.</p>", solution: "<p><strong>Answer: TESP 0.75; excess 0.25; return side.</strong> Step 1: 0.28 + 0.47 = 0.75. Step 2: 0.75 − 0.50 = 0.25 over budget. Step 3: The return magnitude (0.47) is the outsized share — investigate return sizing, grille free area, and filter drop first.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A traverse gives average velocity (given) 600 fpm in a duct of 1.5 sq ft. Find CFM. A flow-hood total reads 880 CFM. Are the methods consistent?</p>", solution: "<p><strong>Answer: 900 CFM; yes.</strong> Step 1: 600 × 1.5 = 900. Step 2: 900 vs 880 differ by about 2% — well within cross-method agreement; the airflow is verified, not just claimed.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A furnace delivers a given 54,000 Btu/h output; measured rise is 60°F. Find airflow, then judge it against a design of 1,000 CFM.</p>", solution: "<p><strong>Answer: ≈ 833 CFM — short of design.</strong> Step 1: CFM = 54,000 ÷ (1.08 × 60) = 54,000 ÷ 64.8 ≈ 833. Step 2: Shortfall ≈ 167 CFM (about 17%). Step 3: Next steps: check TESP and its split, filter, and blower setting before touching anything else.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Two register options for 250 CFM have given free areas of 0.4 and 0.8 sq ft. Compute face velocities and choose for a bedroom, with reasoning.</p>", solution: "<p><strong>Answer: 625 vs ≈ 313 fpm — choose 0.8 sq ft.</strong> Step 1: 250 ÷ 0.4 = 625 fpm. Step 2: 250 ÷ 0.8 ≈ 313 fpm. Step 3: Halved velocity cuts air noise and pressure drop — decisive in the quietest room class in the house.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> An installed system cools to setpoint but the bedroom wing is noisy and the measured TESP is 0.85 against a 0.50 design. Write the three most probable design/install causes in investigation order.</p>", solution: "<p><strong>Answer:</strong> Step 1: Return path restriction (undersized return/grille/filter) — check the static split first; it is the most common single cause. Step 2: Duct installation defects: crushed or slack flex, kinked elbows spending unbudgeted equivalent length. Step 3: Outlet/damper issues: undersized registers or a balancing damper left nearly closed creating local velocity noise. Each is confirmed by measurement (split, inspection, hood), not by ear alone.</p>" },
  ],
  quiz: [
    { q: "Duct insulation in a humid attic prevents condensation because it:", choices: ["Heats the duct", "Keeps the insulation's outer surface above the attic air's dew point", "Removes attic humidity", "Raises supply temperature"], answer: 1, explanation: "Correct: (b). With a vapor-retardant jacket, the cold duct metal is isolated so the exposed surface stays warm enough not to condense attic moisture. (a) Insulation does not add heat. (c) Attic humidity is unchanged. (d) Supply air temperature is essentially unchanged — heat gain is reduced, which is a different statement." },
    { q: "Measured supply static is +0.30 and return is −0.30. TESP is:", choices: ["0.00 in. w.c.", "0.30 in. w.c.", "0.60 in. w.c.", "−0.60 in. w.c."], answer: 2, explanation: "Correct: (c). TESP sums the magnitudes across the blower: 0.30 + 0.30 = 0.60. (a) treats it as a signed cancellation. (b) counts one side only. (d) keeps a meaningless sign on a magnitude total." },
    { q: "A traverse averages 800 fpm in a 1.0 sq ft duct. Airflow is:", choices: ["800 CFM", "1,600 CFM", "400 CFM", "8,000 CFM"], answer: 0, explanation: "Correct: (a). CFM = fpm × area = 800 × 1.0 = 800. (b) doubles without basis. (c) halves without basis. (d) multiplies by 10." },
    { q: "The fastest way to cut grille noise at fixed CFM is to:", choices: ["Close the damper halfway", "Increase the grille's free area", "Raise blower speed", "Paint the grille"], answer: 1, explanation: "Correct: (b). Velocity = CFM ÷ free area; more area is proportionally less speed and noise. (a) adds turbulence and noise. (c) raises flow and pressure — louder. (d) is cosmetic." },
    { q: "A heating temperature-rise airflow check needs:", choices: ["Enthalpy readings", "Delivered Btu/h and measured rise in the sensible equation", "A psychrometric chart only", "Refrigerant pressures"], answer: 1, explanation: "Correct: (b). CFM = output ÷ (1.08 × rise). (a) belongs to total-cooling checks. (c) charts states, not flows. (d) Refrigerant-side data does not measure airside CFM." },
    { q: "If TESP measures well above design, the diagnostic value of splitting supply vs return readings is that it:", choices: ["Doubles the measurement", "Shows which side of the system holds the excess restriction", "Changes the blower curve", "Eliminates the need for airflow measurement"], answer: 1, explanation: "Correct: (b). The oversized side localizes the hunt (return path vs supply ducts). (a) Two readings are still one TESP total. (c) Readings do not alter equipment data. (d) Static and airflow are companion checks, not substitutes." },
    { q: "Cross-checking airflow by two independent methods matters because:", choices: ["Each method alone can mislead; agreement is what makes a value verified", "It uses more tools", "One method is always wrong", "Regulations require exactly two"], answer: 0, explanation: "Correct: (a). Hoods, traverses, and temperature methods each carry distinct error modes; convergence is the evidence. (b) Tool count is not the point. (c) Each can be right — that is why agreement is meaningful. (d) No such universal rule was stated." },
    { q: "A verification checklist item that belongs on every job is:", choices: ["Homeowner's opinion of the installer", "Installed model numbers vs the selected rated combination", "Paint color of the outdoor unit", "The sales quote"], answer: 1, explanation: "Correct: (b). A substituted or mismatched combination invalidates the selection's capacity data — it must be caught on paper-versus-plate comparison. (a) and (c) are not performance items. (d) The quote is commercial, not verification." },
  ],
  studyGuide: `
<h3>Module 11 — Insulation, Sound &amp; Measurement Techniques: Quick Reference</h3>
<p><strong>Duct insulation:</strong> same Q = U × A × ΔT; ducts outside the envelope add real load and sweat risk — insulate with jacket intact, or better, locate ducts inside the envelope. Required levels come from the applicable energy code.</p>
<p><strong>Sound:</strong> follows velocity and turbulence. Levers: friction-rate discipline (Module 6), free area (Module 7), gentle fittings, isolation. Design quiet on paper.</p>
<div class="formula">TESP = |supply static| + |return static| · CFM = avg fpm × duct area · CFM = output ÷ (1.08 × rise)</div>
<p><strong>Verification set:</strong> TESP vs budget (split by side) · total CFM by two methods · room CFM balanced · ventilation rate · RH across a cycle · model numbers vs selection · insulation/dampers as designed.</p>
<p><strong>Safety:</strong> lockout/tagout for opened equipment; never defeat a safety to take a measurement.</p>
<p><strong>Watch out:</strong> judging by 'seems fine'; trusting a single airflow reading; hunting noise by ear before checking the static split.</p>
<p><strong>One-line summary:</strong> design numbers are promises; commissioning is where they are kept — measure static, measure flow two ways, and leave the checklist with the job.</p>
`
};
