// HVAC 101 — Scenario labs (Manifold Gauge Hookup & Reading; Refrigerant Recovery Procedure — EPA Order).
// Each row is checked on a single numeric input in column 1: an option number, a procedure step number, or a computed reading.

module.exports = [
  {
    id: "manifold-gauge-hookup",
    title: "Manifold Gauge Hookup & Reading",
    introHtml: "<p><strong>Job ticket #1042 — Weak cooling complaint.</strong> Customer: split-system air conditioner cools poorly on warm afternoons. Equipment: residential TXV system, nameplate refrigerant <strong>R-410A</strong>, nameplate subcooling target <strong>10°F</strong>. Readings so far: none — you are the first technician on site. Indoor filter is clean, blower runs, outdoor fan runs, and the system has been running steadily for 20 minutes. Your task: connect a manifold gauge set correctly, in the correct order, and turn the readings into superheat and subcooling verdicts.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=cF-4bW8y5Zs\" target=\"_blank\" rel=\"noopener\">HVACR: How To Use AC/Refrigeration Gauges (Manifold Gauge Set) Everything You Need To Know!</a> — a full walk-through of gauge faces, hose connections, and valve use before you make your calls below.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Wear safety glasses and gloves for every refrigerant connection; escaping liquid refrigerant boils on contact and can frost skin and eyes. Confirm the refrigerant from the equipment nameplate before connecting anything, use gauges and hoses rated for that refrigerant's pressures, keep refrigerant away from flames and hot surfaces, and treat the outdoor fan as able to start at any moment. Never vent refrigerant to make a connection faster.</p><p><strong>The correct hookup sequence (for the order questions):</strong> Step 1 — PPE on, nameplate refrigerant confirmed, service ports located. Step 2 — Inspect hoses and gauges, confirm the gauge set is clean and the correct refrigerant is selected on digital tools. Step 3 — Connect the blue hose to the suction service port. Step 4 — Connect the red hose to the high-side (liquid) service port. Step 5 — Keep the yellow center hose capped or connected to a closed, isolated source while reading pressures. Step 6 — Read the stabilized pressures and line temperatures and compute superheat and subcooling.</p><p><strong>Readings once connected and stabilized:</strong> Suction pressure 118 psig; suction line temperature 52°F; head (liquid) pressure 317 psig; liquid line temperature 90°F. Use the course P/T anchors: R-410A 40°F ≈ 118 psig and 100°F ≈ 317 psig. For each row, enter the option number, the step number, or the computed value asked for.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY CALL — Before any hose moves, what do you do first? 1) Connect the red hose to the suction port to check pressure quickly 2) Put on safety glasses and gloves, and confirm from the nameplate that the system is R-410A and your gear is rated for it 3) Open both manifold valves to relieve the system 4) Loosen a fitting to smell which refrigerant it is", cells: [""], inputs: [
        { col: 1, key: "mg_safety", expected: 2, hint: "Step 0 governs: eye and hand protection first, and identity plus pressure rating confirmed before a connection is made. Options 1, 3, and 4 each connect, open, or release refrigerant before identity and protection are settled." } ] },
      { label: "ORDER — 'Connect the blue hose to the suction service port.' Which step of the hookup sequence is this?", cells: [""], inputs: [
        { col: 1, key: "mg_ord_blue", expected: 3, hint: "Per the sequence in the task: Step 1 safety/nameplate, Step 2 inspect the set, Step 3 blue to suction, Step 4 red to high side, Step 5 yellow isolated, Step 6 read and compute." } ] },
      { label: "ORDER — 'Connect the red hose to the high-side (liquid) service port.' Which step of the hookup sequence is this?", cells: [""], inputs: [
        { col: 1, key: "mg_ord_red", expected: 4, hint: "Red follows blue in the sequence: it is Step 4, after the blue hose is on the suction port (Step 3)." } ] },
      { label: "ORDER — 'Inspect hoses and gauges and confirm the correct refrigerant is selected on your digital gauge.' Which step of the hookup sequence is this?", cells: [""], inputs: [
        { col: 1, key: "mg_ord_inspect", expected: 2, hint: "Inspection comes after safety and identity (Step 1) and before any hose touches a port: Step 2. A dirty set or a wrong refrigerant setting manufactures false data." } ] },
      { label: "ORDER — 'PPE on, nameplate refrigerant confirmed, service ports located.' Which step of the hookup sequence is this?", cells: [""], inputs: [
        { col: 1, key: "mg_ord_ppe", expected: 1, hint: "This is Step 1 — safety and identity precede inspection, connection, and reading." } ] },
      { label: "COMPUTED — What saturation temperature does the suction pressure of 118 psig give you for R-410A? (Enter the temperature in °F.)", cells: [""], inputs: [
        { col: 1, key: "mg_suction_sat", expected: 40, hint: "Course anchor: R-410A at 118 psig is a 40°F saturation temperature. This is the coil's boiling temperature." } ] },
      { label: "COMPUTED — Superheat: suction line temperature 52°F minus the saturation temperature from the suction pressure. (Enter °F of superheat.)", cells: [""], inputs: [
        { col: 1, key: "mg_superheat", expected: 12, hint: "Superheat = 52 − 40 = 12°F. Positive superheat proves only vapor is leaving the evaporator toward the compressor." } ] },
      { label: "COMPUTED — What saturation temperature does the head pressure of 317 psig give you for R-410A? (Enter the temperature in °F.)", cells: [""], inputs: [
        { col: 1, key: "mg_cond_sat", expected: 100, hint: "Course anchor: R-410A at 317 psig is a 100°F condensing saturation temperature." } ] },
      { label: "COMPUTED — Subcooling: condensing saturation temperature minus the liquid line temperature of 90°F. (Enter °F of subcooling.)", cells: [""], inputs: [
        { col: 1, key: "mg_subcooling", expected: 10, hint: "Subcooling = 100 − 90 = 10°F, which exactly matches this system's nameplate target." } ] },
      { label: "DECISION — Subcooling is exactly on the 10°F target and superheat is a healthy 12°F on this TXV system. What is the charge verdict? 1) Add refrigerant — superheat should be lower 2) Recover refrigerant — subcooling is too high 3) Charge is correct; do not adjust it, and look elsewhere (airflow, load, controls) for the weak-cooling complaint 4) Convert the system to superheat charging", cells: [""], inputs: [
        { col: 1, key: "mg_verdict", expected: 3, hint: "On a TXV system, subcooling reports charge and it is on target; superheat in range says the valve is working. Adjusting a correct charge in either direction (1 or 2) creates a fault, and the method (4) is set by the device, not by preference." } ] },
      { label: "DECISION — Your digital gauge displays a saturation temperature far from 40°F for the 118 psig suction reading. First suspicion? 1) The system has the wrong refrigerant in it 2) The gauge is set to the wrong refrigerant — verify its setting against the nameplate before trusting any derived value 3) The compressor is failing 4) The P/T relationship does not apply to this system", cells: [""], inputs: [
        { col: 1, key: "mg_wrong_setting", expected: 2, hint: "118 psig must convert to 40°F for R-410A. A tool converting with another refrigerant's table manufactures the error (2). Condemning the charge (1) or compressor (3) comes only after the instrument is verified, and saturation always applies where liquid and vapor coexist (4 is false)." } ] },
      { label: "COMPUTED — Later the suction line temperature rises to 57°F while suction pressure stays at 118 psig. What is the new superheat? (Enter °F.)", cells: [""], inputs: [
        { col: 1, key: "mg_superheat2", expected: 17, hint: "Saturation is still 40°F at 118 psig, so superheat = 57 − 40 = 17°F. The rise means boiling is finishing earlier in the coil — feed or load changed, and on this TXV system you would check the valve's sensing and liquid supply as well as conditions." } ] },
      { label: "DECISION — Which gauge and hose reported the suction pressure in this lab? 1) Red gauge, red hose 2) Blue compound gauge, blue hose 3) Yellow hose alone 4) Whichever gauge was closest", cells: [""], inputs: [
        { col: 1, key: "mg_which_gauge", expected: 2, hint: "Blue is the low side: compound gauge and hose to the suction port. Red (1) reads the high side and would be the liquid pressure of 317 psig here; yellow (3) is the center working hose, not a reading side." } ] },
      { label: "DECISION — Readings are recorded. The correct way to finish is: 1) Crack a hose fitting and let the trapped refrigerant hiss out 2) Close the manifold valves, disconnect using low-loss fittings to minimize release, cap the service ports, and record your readings 3) Leave the gauge set connected until the next visit 4) Open both valves so the hoses store system pressure", cells: [""], inputs: [
        { col: 1, key: "mg_finish", expected: 2, hint: "Finish clean: valves closed, low-loss disconnect, ports capped, readings documented (2). Venting hose contents on purpose (1) violates the venting ban, leaving gear connected (3) invites damage and leaks, and storing hoses pressurized (4) is unsafe and contaminates the next job." } ] }
    ],
    passing: 70
  },
  {
    id: "refrigerant-recovery-procedure",
    title: "Refrigerant Recovery Procedure — EPA Order",
    introHtml: "<p><strong>Job ticket #1077 — Compressor replacement, system to be opened.</strong> Equipment: a residential air conditioner holding <strong>R-22</strong>, nameplate charge <strong>6 lb</strong>, with a failed compressor. Before the system may be opened, its refrigerant must be recovered into an approved recovery cylinder using a recovery machine — none of it may be vented. A recovery cylinder, refrigerant scale, manifold set, and recovery machine are on the truck. Readings so far: system equalized and off; cylinder identity verified as an approved recovery cylinder for this job.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=os9gKLf7LJg\" target=\"_blank\" rel=\"noopener\">Refrigerant RECOVERY Procedure Step by Step! Fully Recovered!</a> — a complete field recovery run showing machine and cylinder hookup and valve order before you sequence the job below.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Safety glasses and gloves on before any hose moves; refrigerant liquid causes frostbite and vapor displaces oxygen in low spaces, so ventilate the work area. Refrigerant is <strong>never vented</strong> — knowingly releasing it during service or disposal is prohibited under EPA Section 608, and only certified technicians perform this work. Confirm the refrigerant from the nameplate, use an approved recovery cylinder (never a disposable cylinder), set it on a scale, and never fill past the cylinder's rated fill limit or heat a cylinder. Treat fans and compressors as able to start until power is controlled.</p><p><strong>The correct recovery sequence (for the order questions):</strong> Step 1 — PPE, identify the refrigerant, and confirm certification and equipment. Step 2 — Place the approved recovery cylinder on the scale and label/record its starting weight and refrigerant identity. Step 3 — Connect manifold, recovery machine, system ports, and cylinder with clean hoses. Step 4 — Open the cylinder valve and the recovery path valves. Step 5 — Start the recovery machine. Step 6 — Monitor pressures and scale weight while recovering to the required level for the appliance category. Step 7 — Close valves, stop the machine in the maker's order, cap all ports, and document the recovered amount.</p><p>For each row, enter the option number, the step number, or the computed value asked for.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY CALL — The system still holds its full R-22 charge and must be opened for a compressor swap. What governs your first move? 1) Open the system quickly so less refrigerant escapes 2) Recover the refrigerant first with a machine into an approved cylinder — venting is prohibited, and PPE goes on before connections 3) Top the system off so the new compressor starts full 4) Release the charge outdoors where it can disperse", cells: [""], inputs: [
        { col: 1, key: "rr_safety", expected: 2, hint: "Step 0: recovery before opening, always, with eye and hand protection and a ventilated area. Options 1 and 4 are venting by two different speeds; option 3 adds charge to a system about to be emptied." } ] },
      { label: "ORDER — 'Start the recovery machine.' Which step of the recovery sequence is this?", cells: [""], inputs: [
        { col: 1, key: "rr_ord_start", expected: 5, hint: "Sequence: 1 safety/identify, 2 cylinder on scale and labeled, 3 hoses connected, 4 valves opened, 5 machine started, 6 monitor to the required level, 7 close up and document." } ] },
      { label: "ORDER — 'Connect manifold, recovery machine, system ports, and cylinder with clean hoses.' Which step of the recovery sequence is this?", cells: [""], inputs: [
        { col: 1, key: "rr_ord_connect", expected: 3, hint: "Connections are Step 3 — after safety/identification (1) and cylinder-on-scale setup (2), and before valves are opened (4) or the machine runs (5)." } ] },
      { label: "ORDER — 'Place the approved recovery cylinder on the scale and record its starting weight and the refrigerant identity.' Which step of the recovery sequence is this?", cells: [""], inputs: [
        { col: 1, key: "rr_ord_scale", expected: 2, hint: "The cylinder is weighed and labeled at Step 2, before connections, so the recovered amount can be proven by weight at the end." } ] },
      { label: "ORDER — 'Close valves, stop the machine in the maker's order, cap all ports, and document the recovered amount.' Which step of the recovery sequence is this?", cells: [""], inputs: [
        { col: 1, key: "rr_ord_close", expected: 7, hint: "Closing up and documenting is Step 7, the final step, after recovery has been monitored to the required level (Step 6)." } ] },
      { label: "ORDER — 'Open the cylinder valve and the recovery path valves.' Which step of the recovery sequence is this?", cells: [""], inputs: [
        { col: 1, key: "rr_ord_valves", expected: 4, hint: "Valves open at Step 4 — everything connected (3) first, machine start (5) only after a complete open path exists." } ] },
      { label: "ORDER — 'Monitor pressures and scale weight while recovering to the required level for the appliance category.' Which step of the recovery sequence is this?", cells: [""], inputs: [
        { col: 1, key: "rr_ord_monitor", expected: 6, hint: "Monitoring the active recovery is Step 6. The scale watches the cylinder fill limit; the gauges watch the system's remaining pressure fall toward the required recovery level." } ] },
      { label: "COMPUTED — The scale read 31 lb with the empty recovery setup at the start and reads 37 lb after recovery. How many pounds of refrigerant were recovered? (Enter the number of pounds.)", cells: [""], inputs: [
        { col: 1, key: "rr_recovered_lb", expected: 6, hint: "Recovered amount = 37 − 31 = 6 lb — matching the nameplate charge, a good cross-check that the system gave up its full charge. Weight, not pressure, is the cylinder's truth." } ] },
      { label: "DECISION — The recovering cylinder is approaching its rated fill limit shown on the cylinder, and the system still holds some refrigerant. Correct call? 1) Keep going — a little over the limit is fine 2) Stop, close the cylinder, and continue into another approved cylinder with capacity 3) Vent the cylinder down to make room 4) Warm the cylinder so it holds more", cells: [""], inputs: [
        { col: 1, key: "rr_fill_limit", expected: 2, hint: "A cylinder is never filled past its rated limit and never heated (options 1 and 4), and refrigerant is never vented to make room (3). Swapping to a cylinder with capacity (2) is the only lawful, safe continuation." } ] },
      { label: "DECISION — A helper suggests cracking a fitting at the end to 'let the last bit hiss out' instead of finishing recovery. Your answer? 1) Agree — small amounts do not count 2) Refuse — knowingly venting refrigerant is prohibited; finish recovery to the required level 3) Agree, but only outdoors 4) Agree, if the customer is not watching", cells: [""], inputs: [
        { col: 1, key: "rr_no_vent", expected: 2, hint: "The venting ban has no small-amount, outdoor, or unobserved exceptions for knowing releases during service. Recovery runs to its required level (2)." } ] },
      { label: "DECISION — Mid-job you find a second cylinder on the truck with no label and unknown contents. Correct handling? 1) Use it — a cylinder is a cylinder 2) Add its contents to your recovery cylinder to save space 3) Do not use it; tag it as unknown and route it through the company's reclamation process 4) Judge it by its paint color and proceed", cells: [""], inputs: [
        { col: 1, key: "rr_unknown_cyl", expected: 3, hint: "Unknown contents are never used or mixed (1 and 2 would contaminate good refrigerant and possibly a system), and color is not identification (4). Tagging and routing (3) is the Module 3 rule." } ] },
      { label: "DECISION — The manifold still shows meaningful pressure in the system while the recovery machine runs. What does that tell you? 1) Recovery is finished 2) Refrigerant remains — keep recovering and monitoring until the required level is reached 3) The cylinder must be empty 4) The gauges are certainly broken", cells: [""], inputs: [
        { col: 1, key: "rr_pressure_remains", expected: 2, hint: "Pressure in the system is refrigerant still present. Recovery continues, with the scale and gauges monitored, until the required level for the category is reached (2) — the opposite conclusion from option 1." } ] },
      { label: "DECISION — The recovered R-22 is documented and the repair is done. What are the refrigerant's lawful destinations from here? 1) The atmosphere, slowly 2) Back into the same owner's system after repair, or into recycling/reclamation channels per the rules 3) Any unlabeled cylinder in the shop 4) A disposable cylinder for storage", cells: [""], inputs: [
        { col: 1, key: "rr_destination", expected: 2, hint: "Recovered refrigerant is reused properly or sent for recycling or reclamation (2). Venting (1) is prohibited, unidentified storage (3) breaks the labeling discipline, and disposable cylinders (4) are never refilled or used for recovery storage." } ] },
      { label: "DECISION — The job is finished. Which documentation closes it correctly? 1) None — recovery leaves no paperwork 2) Record the refrigerant, the amount recovered by weight, the cylinder used, and the date, per your employer's recordkeeping practice 3) A note that 'some gas' was removed 4) Only the customer's signature on an invoice marked 'miscellaneous'", cells: [""], inputs: [
        { col: 1, key: "rr_document", expected: 2, hint: "Refrigerant work is recorded work: identity, quantity by weight, cylinder, and date (2). Vague or absent records (1, 3, 4) cannot prove the charge was recovered rather than released." } ] }
    ],
    passing: 70
  }
];
