// HVAC 111 — Scenario labs (numeric engine).
// Each row is a checked decision: choose-the-option-number, a computed reading, or a procedure-order step.

module.exports = [
  {
    id: "multimeter-troubleshooting",
    title: "Multimeter Electrical Troubleshooting",
    introHtml: "<p><strong>Job ticket #4471 — No cooling.</strong> Residential split system, 240 V condensing unit, 24 V controls. Homeowner reports the indoor blower runs but the outdoor unit is completely silent — no fan, no compressor, no hum. You have a CAT-rated multimeter with a clamp, a spare contactor on the truck, and the unit's ladder diagram (control rung: R → thermostat Y → high-pressure switch → low-pressure switch → contactor coil → C). Work the call in order: every decision below is graded, and the safety decision comes first, as it must on the real job.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=m2wHS4uJUfU\" target=\"_blank\" rel=\"noopener\">HVAC: How To Check a DUAL CAPACITOR With A Multimeter (HVAC Training - Dual Run Capacitor)</a> — the capacitance test you will call for in this lab, demonstrated terminal by terminal.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Before any cover comes off: safety glasses on, meter and leads inspected (CAT rating matched to the equipment, no cracked insulation), and a lockout/tagout plan for every power-off test — open the disconnect, apply your lock and tag, release stored energy (discharge capacitors through a resistor), and prove dead with the live-dead-live method before resistance or capacitance work. Voltage tests are live tests: deliberate, minimal probe time, one hand away from grounded metal where practical. No row in this lab outranks this step.</p><p>For each decision point, enter the number requested: an option number, or the computed/measured value the scenario asks for. Your meter work follows the course rule — volts live, ohms dead, amps running, µF discharged and isolated.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "You arrive at the silent condensing unit. What is your FIRST action? 1) Pull the disconnect and immediately start resistance tests 2) Put on PPE, inspect your meter and leads, notify the homeowner of the shutdown plan, and set up lockout/tagout for the power-off tests to come 3) Replace the contactor — it is the most common failure 4) Jumper the thermostat Y terminal to force a start", cells: [""], inputs: [
        { col: 1, key: "mt_safety_first", expected: 2, hint: "Safety and setup precede diagnosis: PPE, verified meter, notification, LOTO plan. Resistance tests without proving dead (1) skip verification; parts-swapping (3) is guessing; jumpers (4) bypass the control logic you are supposed to be testing." } ] },
      { label: "Before trusting any 'dead' reading at this unit, you verify your meter. Which sequence is correct? 1) Dead test only — a modern meter is reliable 2) Test a known live source, test the target circuit, test the known live source again (live-dead-live) 3) Test the target circuit twice in a row 4) Check the meter's battery icon and proceed", cells: [""], inputs: [
        { col: 1, key: "mt_ldl", expected: 2, hint: "Live-dead-live brackets the dead test with proof the meter works. A lone zero (1, 3) can be a broken lead lying to you, and a battery icon (4) does not prove the leads or the measurement path." } ] },
      { label: "With the disconnect closed and a call for cooling active, you measure the line side of the disconnect to confirm supply. Enter the voltage you expect to read L1 to L2 on this 240 V unit.", cells: [""], inputs: [
        { col: 1, key: "mt_supply_v", expected: 240, hint: "The unit is a 240 V machine; L1–L2 at the line side should read nominal 240 V. Anything near zero sends you upstream (breaker, disconnect, service) before any component diagnosis." } ] },
      { label: "The transformer secondary reads 27 V with the control circuit idle. Your call? 1) Condemn the transformer — it must read exactly 24.0 V 2) Accept it — a nominal 24 V secondary characteristically reads a few volts high unloaded 3) Replace it with a 120 V transformer 4) Add a resistor to drop it to 24.0 V", cells: [""], inputs: [
        { col: 1, key: "mt_xfmr_reading", expected: 2, hint: "27 V unloaded is normal for a nominal 24 V secondary; it settles toward rating under load. Exactness (1) misunderstands 'nominal.' (3) and (4) create problems that do not exist." } ] },
      { label: "During the cooling call you measure 24 V at the contactor coil terminals, but the contactor never clicks and the load side is dead. What is the correct next test? 1) Measure coil resistance with the power locked out and one coil lead lifted 2) Measure coil resistance live, in circuit 3) Clamp the coil wire for amps while it is energized 4) Replace the dual capacitor", cells: [""], inputs: [
        { col: 1, key: "mt_next_test", expected: 1, hint: "Voltage present + no pull-in points at the coil itself; resistance is a power-OFF, isolated test. Live in-circuit ohms (2) corrupts the reading and endangers the meter; (3) measures a circuit you already know is not completing; (4) changes an unrelated part." } ] },
      { label: "The coil resistance test reads OL, and your meter proves good on a known resistor before and after. Interpretation? 1) The coil is shorted 2) The coil is open — the contactor can never pull in; replace the contactor (or coil, where serviceable) 3) OL is the normal reading for a healthy coil 4) The contacts are welded", cells: [""], inputs: [
        { col: 1, key: "mt_coil_ol", expected: 2, hint: "OL = open winding: current can never flow, magnetism never happens. A short (1) reads near 0 Ω. Healthy coils read a definite resistance (3 is false). Welded contacts (4) are a load-side fault that would let the load run, not silence it." } ] },
      { label: "Your spare contactor's coil is rated 24 V and draws 0.5 A. Enter its coil resistance in ohms — the value you will verify on the bench before installing it.", cells: [""], inputs: [
        { col: 1, key: "mt_spare_coil_r", expected: 48, hint: "R = E ÷ I = 24 ÷ 0.5 = 48 Ω. Bench-verifying the replacement (definite reading near 48 Ω, not OL, not near zero) prevents installing a dead part." } ] },
      { label: "VA budget check before startup: the new contactor coil draws 0.5 A and the control board/thermostat load is 0.5 A, both on together at 24 V. Enter the total VA the transformer must supply.", cells: [""], inputs: [
        { col: 1, key: "mt_va_total", expected: 24, hint: "Total current = 0.5 + 0.5 = 1.0 A (parallel loads add). VA = 24 × 1.0 = 24 VA — comfortably inside the unit's 40 VA transformer (≈1.67 A capacity)." } ] },
      { label: "While the unit is open you bench-test the dual run capacitor (discharged, wires removed): it is marked 45/5 µF; C–HERM reads 44 µF and C–FAN reads 4.9 µF. Your call? 1) Replace it — any reading below the printed number fails 2) Return it to service — both sections are within a few percent of rating, i.e., within tolerance and healthy 3) Replace only the FAN section 4) Recharge it and reinstall", cells: [""], inputs: [
        { col: 1, key: "mt_cap_verdict", expected: 2, hint: "44/45 and 4.9/5 are within a few percent — healthy sections; the fault on this call was the open contactor coil, already found. (1) ignores tolerance. (3) Sections of a dual can cannot be replaced individually. (4) Capacitors are not recharged into health." } ] },
      { label: "Compressor winding check (power off, wires removed): C–R reads 1 Ω and C–S reads 4 Ω. Enter the S–R reading in ohms that would confirm consistent, healthy windings.", cells: [""], inputs: [
        { col: 1, key: "mt_winding_sum", expected: 5, hint: "S–R spans both windings in series, so it must equal the sum: 1 + 4 = 5 Ω. A materially different value means a misidentified terminal or a winding fault, and no winding terminal may show continuity to ground." } ] },
      { label: "Replacement contactor installed, unit running. You measure the voltage ACROSS one closed contactor pole under load. Enter the voltage a healthy closed contact should show.", cells: [""], inputs: [
        { col: 1, key: "mt_closed_contact_v", expected: 0, hint: "A healthy closed contact drops ~0 V — it is a conductor, not a load. Significant voltage across a closed pole means pitting/burning and a load being starved; full supply across it would mean the pole is not closed at all." } ] },
      { label: "Startup current check: the compressor clamps at 11 A and the condenser fan at 1 A, both fed from L1. Enter the total amps your clamp reads around the L1 conductor.", cells: [""], inputs: [
        { col: 1, key: "mt_total_amps", expected: 12, hint: "Both parallel loads draw through L1, so their currents add: 11 + 1 = 12 A. Clamp ONE conductor only — clamping both legs cancels the fields and lies to you with a 0.0 reading." } ] },
      { label: "The compressor's clamp reading surges at start and settles to its running value within a second. A second unit on your route holds locked-rotor-level amps for many seconds and trips its overload. Which statement is correct? 1) Both are normal starting behavior 2) The second compressor is not actually turning — sustained locked-rotor draw is a no-start fault to diagnose (capacitor, start components, voltage, mechanical seizure) 3) The first unit's capacitor is oversized 4) Locked-rotor amps cannot be measured with a clamp", cells: [""], inputs: [
        { col: 1, key: "mt_lra", expected: 2, hint: "Healthy inrush is a spike, not a plateau. Sustained LRA = a rotor that never turned, heating toward its overload. (1) normalizes a fault; (3) invents a cause; (4) is false — inrush-capable clamp meters capture it routinely." } ] },
      { label: "Final verification before you close the unit: during a steady cooling call, you confirm the new contactor's coil voltage. Enter the voltage that confirms the coil circuit is healthy.", cells: [""], inputs: [
        { col: 1, key: "mt_final_coil_v", expected: 24, hint: "Full nominal 24 V at the coil during the call — with the transformer already proven (27 V idle) — confirms the series string (thermostat and both pressure switches) is passing control power with no meaningful drop. Anything far below 24 V sends you back to Module 3's voltage-drop hunt." } ] }
    ],
    passing: 70
  },
  {
    id: "brazing-nitrogen-purge",
    title: "Brazing Prep with Nitrogen Purge — Procedure Order",
    introHtml: "<p><strong>Job ticket #4480 — Line-set joint work.</strong> New install: you are brazing a copper suction-line joint and connecting the line to a brass service valve on the outdoor unit. Fillers on the truck: phos-copper (BCuP) rod, silver (BAg) rod, and flux. A nitrogen cylinder with regulator is on site. The work will be graded on sequence: brazing procedure is an order of operations, and several steps are worthless — or dangerous — performed out of order. The numbered rows below present the procedure's actions in scrambled order; enter each action's correct step number.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=N2eCbXCZ8kM\" target=\"_blank\" rel=\"noopener\">How to Flow Nitrogen While Brazing</a> — the purge setup, flow rate, and timing this lab is built around.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Hot-work rules before anything else: safety glasses and gloves for torch work; acetylene/oxygen cylinders secured upright with caps handled per procedure and leak-checked connections; a charged fire extinguisher within reach and combustibles moved or shielded from the work area; the piping section fully depressurized and confirmed free of refrigerant (recovery is handled under EPA rules in the refrigeration courses — a torch never touches a pressurized or refrigerant-containing line); and nitrogen handled as a high-pressure cylinder: secured, correct regulator, and never used to exceed the lowest-rated component's test pressure. The first graded row is a safety decision — it always is.</p><p><strong>The procedure you are ordering (12 steps):</strong> the correct sequence runs from joint preparation, through fluxing (this joint set includes brass), support, and purge setup, to heating, filler work, cooling, and finally pressure/bubble leak testing. Enter the step number (1–12) where each action belongs.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY DECISION — before the torch is even unholstered, which setup is correct? 1) Braze the line while it still holds a low refrigerant charge so the joints stay cool 2) Confirm the section is depressurized and refrigerant-free, cylinders secured, extinguisher at hand, combustibles shielded, glasses and gloves on 3) Pressurize the line with oxygen to blow it clean first 4) Skip the extinguisher — the work is outdoors", cells: [""], inputs: [
        { col: 1, key: "bz_safety", expected: 2, hint: "A torch never touches a pressurized or refrigerant-containing line (1 is a fire/explosion scenario); oxygen (3) under pressure with oil is an explosion hazard; outdoor work (4) burns just as well as indoor work. Depressurized, protected, and equipped (2) is the only correct setup." } ] },
      { label: "MATERIALS DECISION — the brass service-valve joint in this job: which filler/flux combination is correct? 1) Phos-copper rod, no flux 2) Silver (BAg) rod with the proper flux 3) 95/5 soft solder with flux 4) Phos-copper rod with extra flux to make up the difference", cells: [""], inputs: [
        { col: 1, key: "bz_filler", expected: 2, hint: "Copper-to-brass requires the silver-bearing family WITH flux; phos-copper's chemistry does not properly wet brass and can embrittle the joint (1, 4). Soft solder (3) is prohibited in refrigerant joints regardless of flux." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Pressurize the completed piping with dry nitrogen to the specified test pressure and brush bubble solution on every joint.", cells: [""], inputs: [
        { col: 1, key: "bz_step_leaktest", expected: 12, hint: "Leak testing is the final step (12): it can only prove joints that are finished, cooled, and closed up. It also depends on every earlier step — testing a joint you later re-heat invalidates the test." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Heat the fitting and tube evenly with the torch, favoring the heavier fitting mass and keeping the flame moving.", cells: [""], inputs: [
        { col: 1, key: "bz_step_heat", expected: 8, hint: "Heating is step 8 — after cleaning (1), fitting (2)... in this procedure's numbering: clean 1, fit 2, flux 3, support 4, heat protection 5, purge connection 6, purge flow established 7, then heat 8. Heat parts, not filler." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Clean the tube end and the inside of the socket/fitting to bright metal with abrasive cloth or a fitting brush.", cells: [""], inputs: [
        { col: 1, key: "bz_step_clean", expected: 1, hint: "Cleaning is step 1 — the foundation every later step stands on. Note it follows the tubing prep from Module 11: the tube was already cut square and reamed (opening down) before this joint work begins; cleaning to bright metal is the first brazing-specific act, and cleaned surfaces are not finger-touched afterward." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Stop the nitrogen purge once the joint has cooled below oxidation temperature.", cells: [""], inputs: [
        { col: 1, key: "bz_step_purgeoff", expected: 11, hint: "Purge-off is step 11 — only after cooling (step 10) is complete. Stopping the flow at flame-off leaves hot copper exposed to air while it is still hot enough to scale internally." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Touch the filler rod to the joint edge and feed it as the hot metal melts it, drawing filler through until a continuous fillet rings the socket.", cells: [""], inputs: [
        { col: 1, key: "bz_step_feed", expected: 9, hint: "Feeding filler is step 9, immediately after heating (8): filler is fed only when the base metal — not the flame — does the melting, so capillary action pulls it through to a full fillet." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Fit the joint: insert the tube fully into the socket and confirm a snug, even capillary clearance with no wobble and no forcing.", cells: [""], inputs: [
        { col: 1, key: "bz_step_fit", expected: 2, hint: "Fitting is step 2, right after cleaning: capillary action needs a close, even gap. A wobbling or hammered fit is corrected now — no amount of filler technique rescues a bad fit later." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Establish the gentle nitrogen flow — feel it at the open exhaust end — and confirm it is flowing before any heat is applied.", cells: [""], inputs: [
        { col: 1, key: "bz_step_flow", expected: 7, hint: "Flow established is step 7 (connection at 6, flow confirmed at 7) — always BEFORE heating (8). Nitrogen must already be displacing the air when temperatures climb; starting the purge at temperature protects nothing." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Apply a thin, even coat of flux to the male surface of the brass joint (the BAg joint in this job).", cells: [""], inputs: [
        { col: 1, key: "bz_step_flux", expected: 3, hint: "Fluxing is step 3 — after the joint is cleaned and fitted (flux goes on the surfaces about to be joined) and before support and purge setup. (The copper-to-copper joints in this run use phos-copper and skip flux by alloy design.)" } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Remove the heat and let the joint cool undisturbed in air — no quenching, no moving the assembly — with the nitrogen purge still flowing.", cells: [""], inputs: [
        { col: 1, key: "bz_step_cool", expected: 10, hint: "Cooling is step 10: filler must solidify without disturbance (a shifted joint cracks internally), quenching with water stresses the joint and risks contamination, and the purge keeps flowing through cooling to protect the still-hot interior." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Support and clamp the assembly so no joint can shift while hot or while cooling.", cells: [""], inputs: [
        { col: 1, key: "bz_step_support", expected: 4, hint: "Support is step 4 — the assembly is staged and secured while cold, before heat protection, purge plumbing, and ignition make adjustments awkward or impossible." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Connect the nitrogen cylinder (with its regulator) to the assembly so gas sweeps the whole run and exits past the joints being brazed, with a free exhaust path.", cells: [""], inputs: [
        { col: 1, key: "bz_step_connect", expected: 6, hint: "Purge connection is step 6 — plumbed after heat protection (5), arranged so flow sweeps the entire assembly and exits past the work, never against a capped dead end." } ] },
      { label: "PROCEDURE ORDER — enter this action's step number: Place heat protection (wet rag / heat-absorbing compound) on the service valve body to shield its internal seals from conducted heat.", cells: [""], inputs: [
        { col: 1, key: "bz_step_heatprotect", expected: 5, hint: "Heat protection is step 5 — positioned while everything is cold and reachable, after the assembly is supported (4) and before purge connection and ignition. Retrofitting a wet rag onto a hot valve is not a plan." } ] },
      { label: "LEAK DECISION — the bubble test grows a steady crown of bubbles on one finished joint. Your move? 1) Braze over it immediately while it is still pressurized — the heat will seal it 2) Depressurize fully, re-establish the purge, reheat the joint to temperature and fill it (or cut out and remake it), then re-pressurize and re-test 3) Coat the joint with flux and soft solder as a sealant 4) Raise the nitrogen pressure until the bubbles stop", cells: [""], inputs: [
        { col: 1, key: "bz_leak_fix", expected: 2, hint: "Repairs repeat the real procedure at zero pressure (2). A torch on a pressurized line (1) is categorically dangerous; soft solder (3) is prohibited in refrigerant joints and only caps the surface; more pressure (4) enlarges leaks and hazards alike." } ] }
    ],
    passing: 70
  }
];
