// HVAC 208 — Scenario labs (numeric decision engine).
// Each row is a checked decision: option-number choices, procedure-order steps, or computed readings.

module.exports = [
  {
    id: "airflow-measurement",
    title: "Airflow Measurement & Diagnosis",
    introHtml: "<p><strong>Job ticket:</strong> Weak cooling complaint — 'runs all day, house stays warm and clammy.' Equipment: 3.5-ton split system, gas furnace air mover, R-410A. The coil has iced once this month. A previous visitor 'topped off the charge' with no improvement. Your job: measure the air side properly, in order, and reach a verdict the numbers support.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=eFmDmk1Siqc\" target=\"_blank\" rel=\"noopener\">Measuring Static Pressure on an Air Handler for Airflow CFM!</a> — measuring static pressure on an air handler and turning it into a CFM estimate with blower data.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first:</strong> Before opening any panel, switch the unit off at the disconnect and verify the blower has stopped — blower wheels and sheet-metal edges injure more technicians than refrigerant does. Treat every cabinet as energized until you have proven it is not, keep test probes on rated instruments only, and never run the system with panels off except as a brief, controlled measurement step with hands and clothing clear of the blower. If you find damaged wiring or a compromised cabinet, stop and report it before measuring anything.</p><p><strong>Your procedure for this call:</strong> Step 1 — Inspect the air path (filter, coil face, blower wheel, registers). Step 2 — Measure total external static pressure. Step 3 — Determine CFM (traverse, hood, or blower table). Step 4 — Compare with target and correct restrictions. Step 5 — Only then evaluate refrigerant charge. Answer each decision point below with the option number or the computed value.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY — Before removing the blower panel you will: 1) Reach in while it coasts down to save time 2) Switch off at the disconnect, verify the blower has stopped and the cabinet is safe to open, then proceed 3) Wedge the panel and work around the running wheel 4) Skip inspection and go straight to gauges", cells: [""], inputs: [{ col: 1, key: "af_safety", expected: 2, hint: "Safety first: power off at the disconnect and a stopped, verified-safe cabinet before hands go inside. Options 1 and 3 expose you to the wheel; option 4 skips the air-side diagnosis this call is about." }] },
      { label: "PROCEDURE ORDER — In the 5-step procedure in the task, inspecting the filter, coil face, and blower wheel is step number:", cells: [""], inputs: [{ col: 1, key: "af_order_inspect", expected: 1, hint: "Step 1 is air-path inspection. Static pressure is step 2, CFM step 3, corrections step 4, and charge evaluation step 5 — airflow first, charge last." }] },
      { label: "COMPUTED — Using the rule of thumb (400 CFM per ton), the target airflow for this 3.5-ton system is how many CFM?", cells: [""], inputs: [{ col: 1, key: "af_target", expected: 1400, hint: "3.5 × 400 = 1,400 CFM. This is the reference every later measurement is compared against." }] },
      { label: "COMPUTED — Supply static reads 0.42 in. w.c. and return static reads 0.33 in. w.c. (magnitudes). Total external static pressure is how many in. w.c.? (enter the decimal)", cells: [""], inputs: [{ col: 1, key: "af_tesp", expected: 0.75, hint: "Add the magnitudes: 0.42 + 0.33 = 0.75 in. w.c. Subtracting them (0.09) is the classic TESP error." }] },
      { label: "COMPUTED — A traverse of the 20 in × 12 in main duct (area 1.667 ft²) averages 780 FPM. The duct is carrying how many CFM?", cells: [""], inputs: [{ col: 1, key: "af_traverse", expected: 1300, hint: "CFM = area × velocity = 1.667 × 780 ≈ 1,300 CFM. Compare with the 1,400 target — close, but the traverse is in the main duct before branch losses; keep measuring." }] },
      { label: "COMPUTED — Flow-hood readings at the four supply registers: 310, 285, 295, and 310 CFM. Total delivered airflow is how many CFM?", cells: [""], inputs: [{ col: 1, key: "af_hood_total", expected: 1200, hint: "310 + 285 + 295 + 310 = 1,200 CFM delivered at the registers." }] },
      { label: "COMPUTED — Blower-table inference says 1,450 CFM leaves the air handler, but the registers deliver 1,200 CFM. How many CFM are unaccounted for (likely duct leakage)?", cells: [""], inputs: [{ col: 1, key: "af_leakage", expected: 250, hint: "1,450 − 1,200 = 250 CFM escaping between the unit and the registers — air the occupants paid to condition, cooling the attic instead." }] },
      { label: "DECISION — The return-side static is most of the excess TESP, and you find a pleated filter choked with drywall dust from a remodel. Your call: 1) Add refrigerant 2) Replace the filter, then re-measure static and airflow 3) Raise the blower speed two taps and leave 4) Close half the supply registers", cells: [""], inputs: [{ col: 1, key: "af_filter_call", expected: 2, hint: "Fix the proven restriction and re-measure. Refrigerant (1) corrupts the charge; a speed jump (3) without removing the restriction overworks the blower against a clogged path; closing registers (4) raises static further." }] },
      { label: "COMPUTED — After the filter change, measured airflow is 1,200 CFM and the air split is 19°F (return 75°F, supply 56°F). Sensible capacity = 1.08 × CFM × ΔT. Enter the Btu/h.", cells: [""], inputs: [{ col: 1, key: "af_sensible", expected: 24624, hint: "1.08 × 1,200 × 19 = 24,624 Btu/h of sensible cooling — computed from measured air, not assumed airflow." }] },
      { label: "COMPUTED — On arrival (before the filter change) delivered airflow was 1,050 CFM against the 1,400 CFM target. The shortfall was what percent?", cells: [""], inputs: [{ col: 1, key: "af_shortfall_pct", expected: 25, hint: "(1,400 − 1,050) ÷ 1,400 = 0.25 = 25% low — easily enough to ice a coil and imitate a charge fault." }] },
      { label: "DECISION — With the coil found iced on arrival, your first actions are: 1) Add refrigerant and watch it 2) Chip the ice off and restart cooling 3) Cooling off, fan on to thaw, inspect the air path while it melts 4) Replace the metering device", cells: [""], inputs: [{ col: 1, key: "af_icing_call", expected: 3, hint: "Thaw first — every reading on an iced coil is fiction. Chipping damages fins; charging an iced, airflow-starved system overcharges it; parts are condemned only by measurements on a clear coil with air moving." }] },
      { label: "PROCEDURE ORDER — In the 5-step procedure in the task, evaluating refrigerant charge (superheat/subcooling) is step number:", cells: [""], inputs: [{ col: 1, key: "af_order_charge", expected: 5, hint: "Charge is step 5 — last, at verified airflow. Superheat and subcooling are coil behaviors set by refrigerant flow AND airflow together." }] },
      { label: "DECISION — After airflow is restored to ~1,380 CFM, superheat and subcooling both read within the manufacturer's specification and capacity verifies near rating. The verdict on the previous visitor's added refrigerant is: 1) It fixed the system 2) The original problem was airflow; the system must now be checked for overcharge because refrigerant was added to an airflow fault 3) Refrigerant type caused the icing 4) The thermostat was the whole problem", cells: [""], inputs: [{ col: 1, key: "af_verdict", expected: 2, hint: "The symptoms never improved after the top-off because the fault was air-side. Any charge added to mask low airflow leaves the corrected system overcharged — verify and correct charge to specification at proper airflow." }] },
      { label: "DECISION — Closing this call properly means: 1) Leave once the house feels cooler 2) Re-measure airflow and split, confirm the coil stays clear on a full run cycle, restore all panels, and document as-found vs. final readings 3) Set the thermostat lower so it 'feels fixed' 4) Schedule a compressor replacement just in case", cells: [""], inputs: [{ col: 1, key: "af_close", expected: 2, hint: "Verification under the original fault conditions plus documentation is the professional close. Feelings (1) and setpoint tricks (3) prove nothing; an unneeded compressor (4) is not a substitute for evidence." }] }
    ],
    passing: 70
  },
  {
    id: "heat-pump-defrost",
    title: "Heat Pump Defrost Diagnosis",
    introHtml: "<p><strong>Job ticket:</strong> Heat pump heating complaint — 'blows cold sometimes, outdoor unit turns into a block of ice, and the electric bill doubled.' Equipment: split heat pump with electric auxiliary strips, time/temperature defrost board. Weather: damp, 33–36°F — prime frosting conditions. Your job: watch a defrost event like a diagnostician, find which step of the event is broken, and explain the bill.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=5c5R3uYSy5U\" target=\"_blank\" rel=\"noopener\">Heat Pump Troubleshooting- Testing Defrost Board to Force Defrost!</a> — testing a defrost board and forcing a defrost event to observe what the control actually does.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first:</strong> The outdoor unit combines line-voltage fan and compressor circuits, control wiring, and a coil you will be near while it steams and drips. Switch off at the disconnect before opening the control panel, verify power is off with your meter, and treat capacitors as charged until proven otherwise. During a running defrost observation, keep hands, leads, and clothing clear of the fan (it restarts without warning when defrost terminates) and stand clear of meltwater on icy ground. Never jumper a safety or force the compressor to run against a known fault to 'see what happens.'</p><p><strong>Your procedure for this call:</strong> Step 1 — Observe normal heating and document the frost pattern. Step 2 — Force a defrost using the manufacturer's test method. Step 3 — Confirm the reversing valve shifts. Step 4 — Confirm the outdoor fan stops and auxiliary heat starts. Step 5 — Confirm termination (valve back, fan restarts, aux drops out). Step 6 — Restore settings and verify a normal heating cycle. Answer each decision point with the option number or computed value.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY — Before opening the outdoor unit's control panel you will: 1) Open it live — it's only control wiring 2) Switch off at the disconnect and verify with your meter that power is off before reaching in 3) Pull the thermostat wire and assume the unit is safe 4) Stand in the meltwater puddle for a better view of the board", cells: [""], inputs: [{ col: 1, key: "hp_safety", expected: 2, hint: "Line-voltage circuits live in that panel. Disconnect plus meter verification is the only safe entry; a thermostat wire (3) does not remove line power, and the fan can restart without warning during defrost observation." }] },
      { label: "DECISION — The outdoor coil is evenly frosted after a long heating run in damp 34°F weather, with no defrost in the last several hours. This pattern most suggests: 1) Normal operation — frost never needs removal 2) A defrost initiation problem (board timing/logic or coil sensor not permitting defrost) 3) Low indoor airflow as the only possible cause 4) The unit is in cooling mode", cells: [""], inputs: [{ col: 1, key: "hp_frost_pattern", expected: 2, hint: "Frost itself is normal in this weather; frost that never gets melted is an initiation-family fault. The board/sensor decides when defrost starts — start the hunt there." }] },
      { label: "PROCEDURE ORDER — In the 6-step procedure in the task, forcing a defrost with the manufacturer's test method is step number:", cells: [""], inputs: [{ col: 1, key: "hp_order_force", expected: 2, hint: "Step 1 is observing normal heating/frost; step 2 forces the event so you can watch steps 3–5 happen (or fail to)." }] },
      { label: "DECISION — You force defrost. The reversing valve whooshes and frost begins melting with steam rising, but the outdoor fan keeps running and the coil melts very slowly. The failed step is: 1) Valve shift 2) Outdoor fan stop — the fan is blowing the melting heat away 3) Termination 4) Auxiliary heat, which melts the coil", cells: [""], inputs: [{ col: 1, key: "hp_fan_step", expected: 2, hint: "The valve did its step (steam proves hot gas arrived). The fan must stop during defrost; a running fan strips the heat and stretches the melt. Aux heat (4) tempers indoor air — it never melts the outdoor coil." }] },
      { label: "DECISION — During the same event, indoor supply air turns cold and the auxiliary strips never energize. The comfort fault is: 1) Normal — defrost should feel cold 2) Auxiliary heat is not tempering the air while the indoor coil absorbs house heat in defrost 3) The thermostat is set too low 4) The outdoor sensor is shorted", cells: [""], inputs: [{ col: 1, key: "hp_aux_step", expected: 2, hint: "In defrost the system air-conditions the house; aux heat exists to offset exactly that. Strips that never start during defrost are a real fault — test the aux call and the strip circuit." }] },
      { label: "COMPUTED — At 28°F the house loses 38,000 Btu/h and the heat pump delivers 29,000 Btu/h. How many Btu/h must auxiliary heat supply to hold the house?", cells: [""], inputs: [{ col: 1, key: "hp_aux_btuh", expected: 9000, hint: "38,000 − 29,000 = 9,000 Btu/h. Below the balance point the shortfall is arithmetic, not malfunction — aux heat covering it is the design working." }] },
      { label: "COMPUTED — Data for this house: at 35°F, heat loss 34,000 Btu/h and pump output 34,000 Btu/h; at 30°F, loss 37,000 and output 32,000. The thermal balance point is how many °F?", cells: [""], inputs: [{ col: 1, key: "hp_balance", expected: 35, hint: "The balance point is where capacity equals loss: 34,000 = 34,000 at 35°F. At 30°F the pump is already 5,000 Btu/h behind." }] },
      { label: "DECISION — A second unit's defrosts run the full maximum time every cycle, though the coil is visibly clear halfway through. Most likely: 1) The termination sensor never reports the coil warm (sensor/circuit/board input fault) 2) The reversing valve is too fast 3) Aux heat is oversized 4) Frost is invisible and still present", cells: [""], inputs: [{ col: 1, key: "hp_termination", expected: 1, hint: "Termination waits for the sensor's warm signal; without it, only the time limit ends the event. The clear coil proves melting finished — the report never arrived." }] },
      { label: "DECISION — The homeowner has been running EMERGENCY HEAT since a cold snap 'because it feels warmer.' The heat pump itself tests functional. Your call: 1) Leave it — comfort is king 2) Explain that emergency heat locks out the pump and runs only expensive backup heat; restore normal heat mode and show them the difference 3) Disable the aux strips so they must use the pump 4) Raise the aux lockout so emergency heat works harder", cells: [""], inputs: [{ col: 1, key: "hp_emergency", expected: 2, hint: "Emergency heat is a breakdown bridge, and it explains the doubled bill. With the pump proven functional, normal mode restores efficient heating. Never disable aux heat (3) — it is a required part of the system." }] },
      { label: "DECISION — On this dual-fuel neighbor's system (heat pump + gas furnace), at the changeover point the controls should: 1) Run both together all winter 2) Shut the heat pump down and let the furnace carry the load, per the fossil-fuel logic 3) Start a defrost 4) Switch to emergency heat manually", cells: [""], inputs: [{ col: 1, key: "hp_dualfuel", expected: 2, hint: "Changeover is a full switch to the cheaper-per-Btu source below the economic balance point, enforced by the fossil-fuel kit or thermostat logic — not simultaneous operation and not a manual mode." }] },
      { label: "DECISION — Mid-diagnosis the unit whooshes, steams for six minutes with aux heat running, then whooshes back and heats normally. This was: 1) A refrigerant leak venting 2) A normal, healthy defrost event — every step performed 3) A compressor failure recovering 4) The reversing valve failing", cells: [""], inputs: [{ col: 1, key: "hp_normal_event", expected: 2, hint: "Valve shift, steam (melting frost), tempered indoor air, clean termination — the textbook event. Recognizing normal is as much a diagnostic skill as recognizing faults; do not sell repairs for it." }] },
      { label: "PROCEDURE ORDER — In the 6-step procedure in the task, restoring settings and verifying a normal heating cycle is step number:", cells: [""], inputs: [{ col: 1, key: "hp_order_verify", expected: 6, hint: "Step 6 closes the procedure: settings restored, normal heating verified — the same verify-and-document discipline as every call in Module 12." }] },
      { label: "DECISION — Final verdict for the original ticket (heavy ice, rare defrost, cold drafts during events, doubled bill): 1) Replace the compressor 2) Defrost initiation fault (board/sensor) explains the ice; failed aux tempering explains the cold drafts; aux overuse compensating for lost capacity explains the bill — repair those, then re-observe a full event 3) The house is simply too big 4) Refrigerant is old and tired", cells: [""], inputs: [{ col: 1, key: "hp_verdict", expected: 2, hint: "Each symptom maps to a proven mechanism from this module. One root family — defrost control — plus its aux consequences explains the whole ticket without condemning major components." }] },
      { label: "DECISION — Before leaving, the one demonstration that proves this repair to the customer is: 1) A warmer thermostat setpoint 2) Forcing a defrost and letting them watch the ice melt, the fan stay off, the supply air stay warm, and the event terminate on its own 3) Showing them the old board in a parts bag 4) A promise that the bill will drop", cells: [""], inputs: [{ col: 1, key: "hp_proof", expected: 2, hint: "A witnessed, complete, self-terminating defrost event is verification under the original fault conditions — evidence, not assurances." }] }
    ],
    passing: 70
  }
];
