// HVAC 245 - Module 1: The Design Process & Psychrometric Foundations
module.exports = {
  number: 1,
  slug: "design-process-psychrometric-foundations",
  title: "The Design Process & Psychrometric Foundations",
  estTime: "3–4 hours",
  objectives: ["Describe the design sequence — load, equipment selection, duct design, air distribution — and why the order cannot be reversed.", "Define dry-bulb temperature, wet-bulb temperature, dew point, relative humidity, humidity ratio, and enthalpy in plain language.", "Explain why two air samples at the same dry-bulb temperature can demand very different cooling work.", "Convert between grains per pound and humidity ratio in pounds per pound using values given in a problem.", "Use the standard-air sensible-heat equation with the 1.08 factor and state what that factor assumes."],
  sections: [
    { heading: "Design Is a Sequence, Not a Shopping Trip", html: `<p>Good HVAC design follows a fixed order, and most comfort failures are really order failures. First you calculate the <strong>load</strong>: how much heat the building loses on the coldest design night and gains on the hot design afternoon. Second you <strong>select equipment</strong> whose tested capacity matches that load at the design conditions. Third you <strong>design the duct system</strong> so the blower can actually deliver the required air against the resistance of real fittings and runs. Fourth you <strong>distribute the air</strong> — registers, grilles, and balancing — so each room receives its share quietly. Skip or reverse a step and the error compounds: equipment chosen before the load is known is a guess, and ducts sized before the equipment's blower data is known cannot be checked against anything.</p><p>This course walks that sequence in order. Modules 1–2 build the air-science foundation, Modules 3–4 calculate loads, Module 5 selects equipment, Modules 6–7 design ducts and distribution, and Modules 8–11 handle ventilation, humidity, recovery, insulation, sound, and field verification. Module 12 assembles everything into one complete design.</p><div class="callout"><strong>Key idea:</strong> The load calculation is the foundation document. Every later decision — tons, CFM, duct inches, register sizes — traces back to it, which is why designers keep the load worksheet with the job paperwork.</div><p>One honesty rule for the whole course: real designs use the <em>current</em> ACCA Manual J, S, and D procedures, approved software, manufacturer data, and local code values. Our examples use stated, simplified teaching numbers so the arithmetic is transparent. The method is the lesson; the numbers in any example belong to that example only.</p>` },
    { heading: "Dry Bulb, Wet Bulb, and Dew Point", html: `<p>Air has several temperatures, and each one answers a different question. <strong>Dry-bulb temperature</strong> is the ordinary thermometer reading — the temperature of the air itself. <strong>Wet-bulb temperature</strong> is what a thermometer reads when its bulb is wrapped in a wet wick with air moving past it: evaporation cools the wick, and the drier the air, the stronger the cooling, so the wet bulb always reads at or below the dry bulb. The gap between them (the <em>wet-bulb depression</em>) is a quick dryness gauge. <strong>Dew point</strong> is the temperature at which the moisture in the air begins to condense — cool a surface to the dew point and water forms on it, which is why cold supply ducts sweat in humid attics and why a cooling coil must run below the air's dew point to remove moisture.</p><p><strong>Worked example — reading three temperatures.</strong> For this teaching example, a sling psychrometer in a room reads 75°F dry bulb and 63°F wet bulb, and chart reading gives a dew point of about 55°F for that air. Interpretation: the air itself is 75°F; evaporation from the wick pulled a thermometer down 12°F, showing the air is far from saturated; and any surface colder than about 55°F in that room — a cold water line, a poorly insulated duct — will collect condensation. No calculation was needed; the three numbers together describe the air completely enough for a first diagnosis.</p><div class="formula">At saturation (100% RH): dry bulb = wet bulb = dew point</div><p>That equality is your anchor. As air dries out, the three values spread apart in a fixed order: dew point lowest, wet bulb in the middle, dry bulb highest.</p>` },
    { heading: "Relative Humidity and Humidity Ratio", html: `<p><strong>Relative humidity (RH)</strong> compares the moisture in the air to the maximum that air at that temperature could hold, as a percentage. Warm air can hold far more moisture than cold air, so RH is a <em>relative</em> measure: the same actual moisture content reads as high RH on a cold morning and low RH on a hot afternoon. That is why RH alone cannot size a dehumidification load. <strong>Humidity ratio</strong> states the actual moisture content directly — pounds of water vapor per pound of dry air — and is often expressed in <strong>grains</strong>, with 7,000 grains equal to one pound. Humidity ratio stays constant when air is heated or cooled sensibly (no moisture added or removed), which makes it the bookkeeping unit for latent-load work.</p><p><strong>Worked example — grains to pounds.</strong> A problem gives indoor air at 75 grains per pound of dry air. In pounds: 75 ÷ 7,000 = 0.0107 lb of water per lb of dry air. If a ventilation airstream of 1,000 lb of dry air per hour must be dried from 75 grains to 50 grains, the moisture removed is 1,000 × (75 − 50) ÷ 7,000 = 1,000 × 25 ÷ 7,000 ≈ 3.6 lb of water per hour. Notice every value used was stated in the problem — that discipline (given grains, given airflow) is how all latent calculations in this course will work.</p><div class="callout"><strong>Key idea:</strong> Use RH to describe comfort, humidity ratio (or grains) to calculate loads. Confusing the two is the most common beginner error in humidity work.</div>` },
    { heading: "Enthalpy: The Total-Heat Ledger", html: `<p><strong>Enthalpy</strong> is the total heat content of moist air per pound of dry air, in Btu per pound. It adds the <em>sensible</em> heat (the part a thermometer feels) and the <em>latent</em> heat (the part locked in the water vapor) into one number. That single ledger is what makes total cooling calculations possible: when air passes through a cooling coil, both its temperature and its moisture content change, and only enthalpy captures both at once.</p><div class="formula">Total heat: Q<sub>total</sub> = 4.5 × CFM × Δh &nbsp;(standard-air approximation)</div><p>The 4.5 factor bundles standard air density and the minutes-per-hour conversion; like the 1.08 factor for sensible heat, it is a standard-air approximation — say so whenever you use it. <strong>Worked example.</strong> Air enters a coil at an enthalpy given as 31.5 Btu/lb and leaves at a given 24.0 Btu/lb, with 1,200 CFM moving. Q = 4.5 × 1,200 × (31.5 − 24.0) = 4.5 × 1,200 × 7.5 = 40,500 Btu/h of total cooling — about 3.4 tons, since 40,500 ÷ 12,000 ≈ 3.4. The sensible-only equation from the next section could never produce this answer, because much of that 40,500 Btu/h is moisture condensing on the coil, not temperature drop.</p><p>Enthalpy is read off the psychrometric chart along its diagonal scale — Module 2 teaches that reading directly. For now, hold the concept: <em>temperature questions use dry bulb; total-energy questions use enthalpy.</em></p>` },
    { heading: "Sensible Heat and the 1.08 Equation", html: `<p><strong>Sensible heat</strong> is heat that changes temperature; <strong>latent heat</strong> is heat that changes moisture state without changing temperature. Heating a room in winter is (mostly) a sensible problem. Cooling a humid room in summer is a mixed problem: the coil must lower temperature <em>and</em> condense moisture, which is why Module 4 insists on tracking sensible and latent loads separately and why equipment must be checked for both capacities in Module 5.</p><div class="formula">Sensible heat: Q<sub>s</sub> = 1.08 × CFM × ΔT &nbsp;(standard-air approximation)</div><p><strong>Worked example.</strong> A furnace delivers 800 CFM with supply air 50°F warmer than return air. Q = 1.08 × 800 × 50 = 43,200 Btu/h delivered to the house. Run it backward for design: a room with a sensible cooling load of 6,480 Btu/h served with a 20°F temperature difference (75°F room, 55°F supply) needs CFM = 6,480 ÷ (1.08 × 20) = 6,480 ÷ 21.6 = 300 CFM. That rearrangement — load divided by 1.08 × ΔT — is the single most-used equation in this course; the course lab is built on it.</p><div class="callout"><strong>Key idea:</strong> 1.08 is not a law of nature. It assumes air near standard density. At high altitude or extreme temperatures the true factor shifts, and real design work accounts for that — one more reason real designs follow the current manuals rather than pocket formulas.</div>` },
  ],
  keyTerms: [{ term: "Design load", def: "The calculated heating or cooling demand of a building at chosen outdoor design conditions; the basis for equipment and duct sizing." }, { term: "Dry-bulb temperature", def: "The temperature of air measured by an ordinary thermometer, unaffected by moisture evaporation." }, { term: "Wet-bulb temperature", def: "Temperature read by a thermometer with a wetted wick in moving air; at or below dry bulb, equal only at saturation." }, { term: "Wet-bulb depression", def: "Dry bulb minus wet bulb; a larger depression indicates drier air." }, { term: "Dew point", def: "The temperature at which moisture in air begins to condense on a surface cooled to that temperature." }, { term: "Relative humidity (RH)", def: "Actual moisture content as a percentage of the maximum the air could hold at the same temperature." }, { term: "Humidity ratio", def: "Pounds of water vapor per pound of dry air; stays constant during sensible-only heating or cooling." }, { term: "Grains", def: "Moisture unit: 7,000 grains = 1 pound of water; humidity ratio is often expressed in grains per pound." }, { term: "Enthalpy", def: "Total heat content of moist air per pound of dry air (Btu/lb), combining sensible and latent heat." }, { term: "Sensible heat", def: "Heat that changes air temperature when added or removed." }, { term: "Latent heat", def: "Heat that changes moisture state (condensing or evaporating) without changing air temperature." }, { term: "Standard air", def: "Reference air density behind the 1.08 and 4.5 shortcut factors; an approximation, not a constant of nature." }, { term: "Psychrometrics", def: "The study of moist-air properties and processes — the science foundation of HVAC design." }, { term: "Saturation", def: "The condition of air holding the maximum possible moisture at its temperature; RH is 100% and all three temperatures coincide." }, { term: "Sensible heat ratio (SHR)", def: "Sensible load divided by total load; describes how a load (or a coil's output) splits between temperature and moisture work." }, { term: "Ton of cooling", def: "12,000 Btu/h of cooling capacity; a nominal rating shorthand." }, { term: "Design conditions", def: "The chosen indoor and outdoor temperatures (and humidity) at which loads are calculated." }, { term: "Load calculation", def: "The procedure that converts a building description into design heating and cooling loads, room by room." }],
  video: { title: "Psychrometrics Made Simple", embedUrl: "https://www.youtube.com/embed/UKRVxEOD9t0", note: "A professional-development session from CaptiveAire that builds the chart from its fundamentals — dry bulb, wet bulb, relative humidity, dew point, moisture content, and enthalpy — then maps common HVAC processes. Watch the fundamentals part before Module 2; the sizing examples preview where this course is heading.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Air in a room is at 100% relative humidity. Rank its dry-bulb, wet-bulb, and dew-point temperatures, and explain the ranking.</p>", solution: "<p><strong>Answer: all three are equal.</strong> Step 1: At saturation the air can evaporate no more water, so the wet wick cannot cool the thermometer — wet bulb equals dry bulb. Step 2: Saturated air is already at the temperature where its moisture condenses — dew point equals dry bulb. Step 3: As air dries, the order becomes dew point &lt; wet bulb &lt; dry bulb; equality is the saturated anchor case.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A problem states outdoor air at 91 grains per pound must be dried to 56 grains per pound, with 2,000 lb of dry air per hour passing. How many pounds of water per hour must be removed?</p>", solution: "<p><strong>Answer: 10 lb/h.</strong> Step 1: Moisture drop = 91 − 56 = 35 grains per lb. Step 2: Convert: 35 ÷ 7,000 = 0.005 lb water per lb dry air. Step 3: Multiply by airflow: 2,000 × 0.005 = 10 lb/h. Step 4: Sanity check — every number used was given in the problem; no chart value was invented.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A blower moves 1,000 CFM. Supply air is 40°F warmer than return air in heating. Using the standard-air sensible equation, how much heat is delivered?</p>", solution: "<p><strong>Answer: 43,200 Btu/h.</strong> Step 1: Q<sub>s</sub> = 1.08 × CFM × ΔT. Step 2: 1.08 × 1,000 × 40 = 43,200 Btu/h. Step 3: State the assumption — 1.08 is the standard-air approximation.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A room's sensible cooling load is 4,320 Btu/h and the design supply-air difference is 20°F. What airflow does the room need?</p>", solution: "<p><strong>Answer: 200 CFM.</strong> Step 1: Rearrange Q<sub>s</sub> = 1.08 × CFM × ΔT to CFM = Q ÷ (1.08 × ΔT). Step 2: 1.08 × 20 = 21.6. Step 3: 4,320 ÷ 21.6 = 200 CFM.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Air crosses a coil at 800 CFM, entering at a given enthalpy of 30.0 Btu/lb and leaving at a given 22.5 Btu/lb. Find the total cooling done, in Btu/h and tons.</p>", solution: "<p><strong>Answer: 27,000 Btu/h = 2.25 tons.</strong> Step 1: Δh = 30.0 − 22.5 = 7.5 Btu/lb. Step 2: Q = 4.5 × 800 × 7.5 = 27,000 Btu/h. Step 3: 27,000 ÷ 12,000 = 2.25 tons. Step 4: Total heat needs enthalpy because moisture condensed as well as temperature falling.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Two rooms are both 75°F dry bulb. Room A is at 30% RH, Room B at 60% RH. A contractor says both need the same cooling because 'the temperature is the same.' Give two reasons the statement fails.</p>", solution: "<p><strong>Answer:</strong> Step 1: Cooling load includes latent work — Room B's air carries roughly double the moisture per pound, so the coil must condense far more water to reach the same target humidity. Step 2: Enthalpy differs: at the same dry bulb, higher moisture means higher total heat content, so total capacity (4.5 × CFM × Δh) required is greater for Room B. Dry bulb alone never describes an air-conditioning load.</p>" },
  ],
  quiz: [
    { q: "At 100% relative humidity, dry bulb, wet bulb, and dew point are:", choices: ["All equal", "Dry bulb highest, dew point lowest", "Wet bulb highest", "Dew point highest"], answer: 0, explanation: "Correct: (a). Saturated air cannot evaporate water from a wick, so wet bulb cannot fall below dry bulb, and the air is by definition at its condensation temperature. (b) describes unsaturated air. (c) is impossible — wet bulb never exceeds dry bulb. (d) is impossible — dew point never exceeds dry bulb." },
    { q: "Dew point is best defined as:", choices: ["The thermometer reading in moving air", "The temperature at which moisture begins to condense from the air", "The percentage of maximum moisture the air holds", "The total heat content of the air"], answer: 1, explanation: "Correct: (b). Dew point is the condensation temperature of the air's moisture. (a) describes dry bulb. (c) defines relative humidity. (d) defines enthalpy." },
    { q: "Humidity ratio stays constant when air is:", choices: ["Cooled through a wet coil", "Humidified with steam", "Heated sensibly with a furnace", "Dehumidified"], answer: 2, explanation: "Correct: (c). Sensible heating adds heat only; no moisture enters or leaves, so pounds of water per pound of dry air is unchanged (RH falls, because warm air can hold more). (a), (b), and (d) all add or remove moisture, changing the ratio." },
    { q: "7,000 grains equals:", choices: ["One pound of water", "One Btu", "One pound of dry air", "One ton of cooling"], answer: 0, explanation: "Correct: (a). Grains are a small mass unit for water vapor: 7,000 grains = 1 lb. (b) A Btu is energy, not mass. (c) Humidity ratio is measured per pound of dry air, but grains themselves measure the water. (d) A ton is 12,000 Btu/h, a rate of cooling." },
    { q: "A room needs 5,400 Btu/h of sensible cooling with a 20°F supply difference. Required CFM (standard-air approximation) is:", choices: ["100 CFM", "200 CFM", "250 CFM", "500 CFM"], answer: 2, explanation: "Correct: (c). CFM = 5,400 ÷ (1.08 × 20) = 5,400 ÷ 21.6 = 250 CFM. (a) 100 CFM would deliver only 2,160 Btu/h. (b) 200 CFM delivers 4,320 Btu/h — short of the load. (d) 500 CFM delivers 10,800 Btu/h — double, wasting blower energy and risking noise and drafts." },
    { q: "The total-heat equation Q = 4.5 × CFM × Δh requires which property?", choices: ["Dry-bulb temperature only", "Enthalpy of both airstreams", "Relative humidity only", "Static pressure"], answer: 1, explanation: "Correct: (b). Δh is the enthalpy difference between entering and leaving air; enthalpy is the ledger that includes latent heat. (a) Dry bulb captures sensible heat only. (c) RH is a ratio, not an energy content. (d) Static pressure describes duct resistance, not air energy." },
    { q: "Why can relative humidity mislead a designer sizing dehumidification?", choices: ["RH is measured in grains", "RH compares moisture to a temperature-dependent maximum, so the same RH can mean very different actual moisture", "RH never changes with temperature", "RH includes static pressure"], answer: 1, explanation: "Correct: (b). Because warm air holds much more moisture, 50% RH on a hot day is far more water per pound than 50% RH on a cold day; latent loads need humidity ratio or grains. (a) Grains measure humidity ratio, not RH. (c) RH changes strongly with temperature. (d) RH has nothing to do with pressure in the duct sense." },
    { q: "The correct design order is:", choices: ["Select equipment, then calculate load, then design ducts", "Calculate load, select equipment, design ducts, distribute air", "Design ducts, then pick equipment to fit them", "Buy the largest unit, then calculate the load to confirm"], answer: 1, explanation: "Correct: (b). Load → selection → ducts → distribution; each step consumes the previous step's output. (a) selects blind. (c) sizes ducts for unknown airflow. (d) reverses the process entirely and invites oversizing penalties taught in Module 5." },
  ],
  studyGuide: `
<h3>Module 1 — Design Process &amp; Psychrometric Foundations: Quick Reference</h3>
<p><strong>Design order:</strong> load → equipment selection → duct design → air distribution. Real designs use the current ACCA manuals, approved software, manufacturer data, and local code; course examples use stated teaching numbers.</p>
<p><strong>Three temperatures:</strong> dry bulb (air temperature) · wet bulb (evaporative, at or below dry bulb) · dew point (condensation temperature). At saturation all three are equal; otherwise dew point &lt; wet bulb &lt; dry bulb.</p>
<p><strong>Moisture:</strong> RH = percent of the maximum moisture air can hold at that temperature (comfort language). Humidity ratio = lb water per lb dry air (calculation language); 7,000 grains = 1 lb. Humidity ratio is unchanged by sensible heating/cooling.</p>
<div class="formula">Sensible: Q = 1.08 × CFM × ΔT &nbsp;·&nbsp; Total: Q = 4.5 × CFM × Δh &nbsp;(both standard-air approximations)</div>
<p><strong>Enthalpy</strong> (Btu/lb dry air) = sensible + latent heat content; use it whenever moisture changes. 1 ton = 12,000 Btu/h.</p>
<p><strong>Watch out:</strong> same dry bulb ≠ same load — humidity changes enthalpy and latent work.</p>
`
};
