// HVAC 245 - Module 10: Heat Recovery & ERV/HRV Design
module.exports = {
  number: 10,
  slug: "heat-recovery-erv-hrv-design",
  title: "Heat Recovery & ERV/HRV Design",
  estTime: "3–4 hours",
  objectives: ["Distinguish HRV (sensible only) from ERV (sensible + latent) recovery and the core behavior behind each.", "Define sensible effectiveness and use it to compute a recovered-air supply temperature.", "Compute recovered Btu/h and the remaining ventilation load after recovery.", "Estimate a simple payback from given seasonal energy and cost values, and name its limits.", "Match recovery type to climate and building using the moisture logic of Modules 8–9."],
  sections: [
    { heading: "Two Airstreams, One Core", html: `<p>A recovery ventilator is Module 8's balanced strategy with a heat exchanger in the middle. Stale indoor air is exhausted and fresh outdoor air is supplied in equal measure, and the two streams pass through a <strong>core</strong> — a stack of plates or a wheel — that transfers energy between them <em>without mixing the air itself</em>. In winter the warm exhaust preheats the cold incoming air; in summer the cool exhaust pre-cools the hot incoming air. The ventilation rate (and its indoor-air-quality job) is unchanged; what changes is how much of the ventilation energy penalty survives.</p><p>An <strong>HRV (heat recovery ventilator)</strong> transfers sensible heat only: temperature moves between streams, moisture does not. An <strong>ERV (energy recovery ventilator)</strong> transfers sensible heat <em>and</em> moisture: in summer, incoming humidity is partly handed to the exhaust stream; in winter, outgoing moisture is partly returned to the dry incoming air. Neither device creates energy and neither replaces the heating or cooling plant — each shrinks the ventilation portion of the load that the plant must meet.</p><div class="callout"><strong>Key idea:</strong> Recovery does not reduce the ventilation <em>rate</em>; it reduces the ventilation <em>load</em>. The air still changes — its temperature and moisture just arrive pre-tempered.</div><p>One boundary deserves emphasis: recovery ventilators exchange energy with air that is already being moved for IAQ. They do not ventilate 'for free' — fans consume power, which is why fan watts belong in every payback this module computes.</p>` },
    { heading: "Effectiveness: The One Number That Runs the Math", html: `<p><strong>Sensible effectiveness</strong> states what fraction of the maximum possible temperature change the core actually achieves on the incoming stream:</p><div class="formula">Effectiveness = (supply temp after core − outdoor temp) ÷ (indoor temp − outdoor temp) &nbsp;(heating case)</div><p>Rearranged, the supply temperature leaving the core is: T<sub>supply</sub> = T<sub>outdoor</sub> + effectiveness × (T<sub>indoor</sub> − T<sub>outdoor</sub>). <strong>Worked example (values given).</strong> Outdoor 20°F, indoor 70°F, effectiveness 0.75. T<sub>supply</sub> = 20 + 0.75 × (70 − 20) = 20 + 37.5 = 57.5°F. The ventilation air enters the system at 57.5°F instead of 20°F — the remaining heating for that stream is only the 12.5°F lift from 57.5 to 70, one quarter of the original 50°F. Effectiveness values are manufacturer-tested ratings at stated flows (and they vary with flow and, for ERVs, with conditions); design uses the rating at the project's design CFM, and latent effectiveness is a separate ERV rating used the same way for moisture.</p><p>Frost is the winter limit: exhaust moisture can freeze in a core at very low outdoor temperatures, and real units manage it with defrost strategies that temporarily reduce net recovery — one more reason design effectiveness at the project's conditions, not the brochure's best number, is the honest input.</p><p>Treat effectiveness as a rating with conditions attached, like capacity in Module 5. The habit transfers directly: a number without its flow and temperature conditions is a nickname, and nicknames do not size anything in this course.</p>` },
    { heading: "Recovered Energy and the Remaining Load", html: `<p>Combine effectiveness with the sensible equation and the savings become a number the load calculation can use. <strong>Worked example (values given).</strong> Ventilation 150 CFM, outdoor 20°F, indoor 70°F (ΔT 50). Without recovery, the ventilation heating load is 1.08 × 150 × 50 = 8,100 Btu/h. With sensible effectiveness 0.75, recovered energy ≈ 0.75 × 8,100 = 6,075 Btu/h, and the remaining load ≈ 8,100 − 6,075 = 2,025 Btu/h. Cross-check by temperature: supply leaves the core at 57.5°F (Section 2), so remaining load = 1.08 × 150 × (70 − 57.5) = 1.08 × 150 × 12.5 = 2,025 Btu/h. Two routes, one answer — the same consistency check the lab demands.</p><p>Summer runs the film backwards: outdoor 95°F, indoor 75°F, effectiveness 0.70 (given). Supply after core = 95 − 0.70 × (95 − 75) = 95 − 14 = 81°F. Ventilation sensible load without recovery: 1.08 × 150 × 20 = 3,240 Btu/h; with recovery: 1.08 × 150 × 6 = 972 Btu/h. An ERV additionally cuts the latent part via its moisture transfer — computed from its given latent effectiveness and the grains difference, by the same fraction logic.</p><div class="callout"><strong>Key idea:</strong> Credit recovery in the load calculation honestly: reduce the ventilation term, never the whole load, and use effectiveness at design flow.</div><p>The two-route check used here — effectiveness fraction versus supply-temperature arithmetic — is worth memorizing as a pattern. Whenever a design quantity can be reached by two independent paths, compute both; disagreement is the cheapest error detector in engineering.</p>` },
    { heading: "When Recovery Pays: A Worked Payback", html: `<p>Recovery equipment costs money, uses fan energy, and needs maintenance (cores and filters cleaned, drains checked). Whether it 'pays' is an arithmetic question with stated inputs — and a comfort/IAQ question that continues even when the arithmetic is marginal. <strong>Worked example (all values given).</strong> A ventilator installation costs $1,800 installed. Seasonal analysis (given) credits it with recovered heating energy worth $310 per year and recovered cooling value of $60 per year, while its fans and maintenance cost $90 per year. Net annual benefit = 310 + 60 − 90 = $280. Simple payback = 1,800 ÷ 280 ≈ 6.4 years. The designer reports that number <em>with</em> its assumptions: energy prices, run hours, climate severity, and equipment life all move it. Cold climates and high ventilation rates shorten payback; mild climates and small rates stretch it — which is why some codes require recovery above certain ventilation rates or building sizes, a requirement the designer verifies in the adopted code rather than assumes.</p><p>Non-energy returns belong in the conversation honestly labeled as such: balanced, filtered, distributed fresh air (better IAQ than leak-dependent strategies), winter humidity retention with an ERV, and summer latent relief that can matter more to comfort than the Btu arithmetic suggests (Module 9's muggy-house problem is often an ERV-shaped hole).</p>` },
    { heading: "Choosing HRV vs ERV — and Placing the Unit", html: `<p>The HRV/ERV choice is a moisture decision. In cold climates with dry winter indoor air problems, an <strong>ERV</strong> returns part of the exhaust moisture, softening the dryness — but a house with excess winter moisture (large family, lots of plants/cooking, tight envelope) may prefer an <strong>HRV</strong>, which lets moisture leave with the exhaust while still recovering heat. In hot-humid climates the ERV is the usual choice because its latent transfer cuts the incoming moisture load (Module 9). In mild, dry climates the moisture transfer matters little and either core serves. Occupancy and sources decide borderline cases — this is Module 8's 'know your building' rule wearing a recovery badge.</p><p>Placement and installation are design, not afterthought: the unit needs service access, a condensate drain where the core condenses, insulated ducts for the outdoor runs (a bare duct of 20°F air through a warm attic sweats and wastes the recovery), exterior hoods separated so exhaust does not short-circuit into the intake, and controls that deliver the design rate (continuous low speed or cycled higher speed per Module 8's averaging). Distribution choices — dedicated ducts vs. tying into the air-handler system — change both cost and the fan-energy line in the payback, and the air-handler-coupled variant must be checked so ventilation actually occurs when the handler would otherwise rest.</p><div class="callout"><strong>Key idea:</strong> Select the core for the moisture story, rate it at the design flow, install it so the rating survives — insulated, drained, separated hoods, serviceable.</div>` },
  ],
  keyTerms: [{ term: "Recovery ventilator", def: "A balanced ventilator whose core transfers heat (HRV) or heat plus moisture (ERV) between exhaust and supply streams without mixing them." }, { term: "HRV", def: "Heat recovery ventilator: transfers sensible heat only." }, { term: "ERV", def: "Energy recovery ventilator: transfers sensible heat and moisture (total energy)." }, { term: "Core", def: "The heat/moisture exchange element — plates or wheel — inside a recovery ventilator." }, { term: "Sensible effectiveness", def: "Fraction of the maximum possible temperature change actually achieved on the incoming stream; a tested rating at stated flow." }, { term: "Latent effectiveness", def: "An ERV's corresponding fraction for moisture transfer between streams." }, { term: "Supply temperature after core", def: "T_outdoor + effectiveness × (T_indoor − T_outdoor) in the heating case." }, { term: "Recovered energy", def: "The load avoided by recovery: effectiveness × the unrecovered ventilation load (sensible part)." }, { term: "Remaining ventilation load", def: "The ventilation load still owed by the plant after recovery credit." }, { term: "Frost control", def: "Core defrost strategies that protect against exhaust-moisture freezing at low outdoor temperatures." }, { term: "Short-circuiting (hoods)", def: "Exhaust air re-entering the outdoor intake because hoods are placed too close together." }, { term: "Simple payback", def: "Installed cost ÷ net annual benefit; a screening figure whose assumptions must be stated." }, { term: "Balanced pressure", def: "Near-neutral house pressure resulting from equal supply and exhaust flows." }, { term: "Dedicated-duct distribution", def: "Ventilation delivered through its own duct runs, independent of the air handler." }, { term: "Air-handler-coupled distribution", def: "Ventilation supply introduced through the main air handler's duct system." }, { term: "Cross-contamination", def: "Transfer of pollutants between streams; plate cores are designed to prevent air mixing." }, { term: "Tempering", def: "Pre-heating or pre-cooling incoming air toward indoor conditions." }, { term: "Net annual benefit", def: "Recovered energy value minus fan energy and maintenance cost in a payback estimate." }],
  video: { title: "What is an ERV? Energy Recovery Ventilator Explained (How it Works & Saves Energy)", embedUrl: "https://www.youtube.com/embed/SqpFXhHiFDI", note: "A manufacturer's explanation of energy recovery ventilation: two balanced airstreams exchanging sensible and latent energy through a static-plate core without mixing. Use it to picture the core while this module works the effectiveness arithmetic.", more: [{ title: "HRV vs. ERV - What's the Difference?", url: "https://www.youtube.com/watch?v=wl8sH2I1DUM" }] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Outdoor 10°F, indoor 70°F, sensible effectiveness (given) 0.80. Find the supply temperature after the core.</p>", solution: "<p><strong>Answer: 58°F.</strong> Step 1: ΔT available = 70 − 10 = 60. Step 2: Recovered rise = 0.80 × 60 = 48. Step 3: Supply = 10 + 48 = 58°F.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Ventilation is 200 CFM at ΔT 60 (same conditions as Problem 1). Find the ventilation load with no recovery, the recovered Btu/h at effectiveness 0.80, and the remaining load.</p>", solution: "<p><strong>Answer: 12,960; 10,368; 2,592 Btu/h.</strong> Step 1: No recovery: 1.08 × 200 × 60 = 12,960. Step 2: Recovered = 0.80 × 12,960 = 10,368. Step 3: Remaining = 12,960 − 10,368 = 2,592. Step 4: Check by temperature: supply at 58°F, remaining lift 12°F: 1.08 × 200 × 12 = 2,592 ✓.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Summer: outdoor 100°F, indoor 75°F, effectiveness (given) 0.60, ventilation 200 CFM. Find supply temperature after the core and the remaining sensible ventilation load.</p>", solution: "<p><strong>Answer: 85°F; 2,160 Btu/h.</strong> Step 1: Supply = 100 − 0.60 × 25 = 85°F. Step 2: Remaining ΔT = 85 − 75 = 10. Step 3: Load = 1.08 × 200 × 10 = 2,160 Btu/h (vs 5,400 unrecovered).</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Installed cost (given) $2,100. Annual recovered value (given) $390 heating + $90 cooling; fan/maintenance (given) $120/yr. Find net annual benefit and simple payback.</p>", solution: "<p><strong>Answer: $360/yr; ≈ 5.8 years.</strong> Step 1: Net = 390 + 90 − 120 = 360. Step 2: Payback = 2,100 ÷ 360 ≈ 5.8 years. Step 3: Report with assumptions (prices, hours, climate) attached.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A tight house in a cold climate has chronic excess winter moisture (window condensation daily). HRV or ERV, and why?</p>", solution: "<p><strong>Answer: HRV.</strong> Step 1: The house needs moisture to leave; an ERV would return part of the exhaust moisture to the incoming air, working against the goal. Step 2: An HRV recovers the heat while letting the moisture exit with the exhaust stream. Step 3: (Ventilation rate and source control should also be checked — recovery choice is not the only moisture lever.)</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A designer credits recovery against the <em>entire</em> house load in a sales estimate. The house load is 40,000 Btu/h of which ventilation is 8,000 (given), effectiveness 0.75. Compute the honest credit and the sales figure's error.</p>", solution: "<p><strong>Answer: honest credit 6,000 Btu/h; the sales claim overstates savings by 24,000 Btu/h.</strong> Step 1: Credit = 0.75 × 8,000 = 6,000. Step 2: Sales claim = 0.75 × 40,000 = 30,000. Step 3: Error = 30,000 − 6,000 = 24,000 — recovery only ever touches the ventilation stream.</p>" },
  ],
  quiz: [
    { q: "An ERV differs from an HRV in that the ERV also transfers:", choices: ["Air between streams", "Moisture between streams", "Pressure", "Refrigerant"], answer: 1, explanation: "Correct: (b). ERV cores pass water vapor as well as heat — total-energy recovery. (a) Neither device mixes the airstreams. (c) Pressure is balanced by the fans, not transferred by the core. (d) No refrigerant is involved." },
    { q: "Outdoor 30°F, indoor 70°F, effectiveness 0.70 (given). Supply after the core is:", choices: ["42°F", "58°F", "70°F", "30°F"], answer: 1, explanation: "Correct: (b). 30 + 0.70 × 40 = 30 + 28 = 58°F. (a) applies 0.30 instead of 0.70. (c) would require 100% effectiveness. (d) is no recovery at all." },
    { q: "Recovery reduces the ventilation load by:", choices: ["Eliminating the ventilation rate", "Effectiveness × the ventilation load", "The whole house load × effectiveness", "A fixed 50% in all cases"], answer: 1, explanation: "Correct: (b). Only the ventilation stream passes the core, and only its effectiveness fraction is recovered. (a) The rate — the IAQ point of the system — stays. (c) is the Assignment Problem 6 sales error. (d) Effectiveness is a tested rating, not a universal constant." },
    { q: "A house with excess winter moisture generally prefers:", choices: ["An ERV, to return moisture", "An HRV, to let moisture leave while recovering heat", "No ventilation", "A steam humidifier"], answer: 1, explanation: "Correct: (b). The HRV exports moisture with the exhaust while keeping most of the heat. (a) works against the moisture problem. (c) abandons IAQ and lets moisture build further. (d) adds moisture — the exact wrong direction." },
    { q: "Simple payback is computed as:", choices: ["Annual savings ÷ installed cost", "Installed cost ÷ net annual benefit", "Installed cost × equipment life", "Recovered Btu ÷ CFM"], answer: 1, explanation: "Correct: (b). Cost divided by yearly net benefit gives years. (a) inverts it (that is a rate of return). (c) is a lifetime cost product, not payback. (d) is not a financial figure." },
    { q: "Effectiveness used in design should be the rating:", choices: ["At any flow the brochure lists", "At the project's design CFM and conditions", "From a different, larger model", "Averaged with the latent rating for an HRV"], answer: 1, explanation: "Correct: (b). Effectiveness varies with flow and conditions; the rating at the actual duty is the honest input. (a) Brochure maxima flatter the design. (c) Another model's data describes another machine. (d) HRVs have no latent rating to average." },
    { q: "Outdoor runs of a recovery ventilator should be insulated because:", choices: ["The code likes insulation", "Cold air in a bare duct through a warm space sweats and wastes recovered energy", "It makes the fan quieter mainly", "Insulation adds effectiveness"], answer: 1, explanation: "Correct: (b). Condensation on (and heat gain through) an uninsulated cold duct destroys both the building's safety and the recovery the owner bought. (a) may also be true but is not the mechanism. (c) minor at best. (d) Duct insulation preserves recovery; it does not create it." },
    { q: "Frost control in a recovery core matters because:", choices: ["Occupants dislike the word frost", "Exhaust moisture can freeze in the core at low outdoor temperatures, blocking flow and cutting recovery", "Frost improves effectiveness permanently", "It is a summer-only feature"], answer: 1, explanation: "Correct: (b). Warm moist exhaust meeting a very cold core can ice it; defrost strategies manage this at some cost to net recovery. (a) is not engineering. (c) Ice blocks passages — the opposite of improvement. (d) Frost is definitionally a heating-season issue." },
  ],
  studyGuide: `
<h3>Module 10 — Heat Recovery &amp; ERV/HRV Design: Quick Reference</h3>
<div class="formula">T<sub>supply</sub> = T<sub>out</sub> + eff × (T<sub>in</sub> − T<sub>out</sub>) · Recovered = eff × ventilation load · Payback = installed cost ÷ net annual benefit</div>
<p><strong>HRV</strong> = sensible only. <strong>ERV</strong> = sensible + latent. Neither mixes airstreams; neither changes the ventilation rate — only its load.</p><p><strong>Climate/moisture logic:</strong> hot-humid → ERV (latent relief) · cold with dry house → ERV (moisture retention) · cold with wet house → HRV (moisture export) · mild/dry → either.</p>
<p><strong>Honesty rules:</strong> effectiveness at design CFM/conditions; credit only the ventilation term; state payback assumptions; account for fan energy and frost control in cold-climate claims.</p>
<p><strong>Installation:</strong> insulated outdoor runs, condensate drain, separated intake/exhaust hoods, service access, controls that actually deliver the design rate.</p>
<p><strong>Exam-style drill:</strong> effectiveness problems give you three temperatures or a load and a fraction. Anchor on the definition — actual change ÷ maximum possible change — and every variant (find supply temp, find recovered Btu, find remaining load) is one rearrangement away.</p>
`
};
