// HVAC 207 — Scenario lab (numeric decision engine).
// Lab: leak-detection-commercial — a warm walk-in, an accelerating refrigerant loss,
// and the full find-it / fix-it / verify-it sequence from Modules 8-11.

module.exports = [
  {
    id: "leak-detection-commercial",
    title: "Leak Detection on a Commercial System",
    introHtml: "<p><strong>JOB TICKET — FreshMart #12, called in 7:40 a.m.</strong> Walk-in cooler (remote condensing unit, R-404A, full charge 60 lb) is running warm: box air 46°F and climbing, dairy product probed at 45°F and rising. The manager has already moved what she could to the deli case. Service history on the account: 18 lb of R-404A added three months ago 'to get through the weekend,' 20 lb added last month the same way — no leak search either time. Your dispatcher notes the pattern in red ink: <em>third warm call in a quarter, additions accelerating.</em> On the truck: electronic detector, bubble solution, nitrogen bottle with regulator, recovery machine and certified cylinders, gauges, clamp thermometer, and a P/T app. This is a covered appliance (over 50 lb), so the EPA file matters as much as the toolbox.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=mJ2KmW4e53k\" target=\"_blank\" rel=\"noopener\">Walk In Cooler Refrigerant Leak</a> — a real walk-in leak hunt; compare its evidence-first order with the calls you are about to make.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Before any panel comes off: safety glasses and gloves on; treat every circuit as live until you have proven it dead with your meter; before working inside the unit cooler, lock out and tag out the disconnect and verify the fans cannot start. Refrigerant rules on this call: never vent — recover into certified cylinders with certified equipment; R-404A vapor is heavier than air and pools low, so ventilate low spaces and never put your head into a refrigerant-filled case or pit; nitrogen is the only test gas, always through its regulator, never oxygen and never shop air. Product safety runs in parallel: the manager owns food disposition, but you own telling her the temperatures and the 41°F standard, early and in writing on the ticket.</p><p><strong>How this lab works:</strong> Each row is a decision point on the call. For numbered-option rows, enter the option's number. For procedure-order rows, enter the step number from the closing procedure below. For computed rows, enter the number your arithmetic gives you.</p><p><strong>The closing procedure (for the order rows):</strong> Step 1 — Recover the refrigerant from the section to be opened. Step 2 — Make the repair: re-braze the failed joint with nitrogen flowing. Step 3 — Pressure-test the repair with dry nitrogen and bubble-check it. Step 4 — Evacuate to 500 microns or below and pass the standing decay test. Step 5 — Charge by weight to spec and verify superheat and subcooling. Step 6 — Initial verification already built into Steps 3–5 is documented, follow-up verification is scheduled, and every amount goes into the refrigerant record.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY — You have just arrived and the manager is urging speed. Your first move before opening any panel: 1) Start spraying bubble solution on every joint you can reach. 2) Safety glasses and gloves on, prove circuits dead with your meter before touching, and lock out/tag out before working inside the unit cooler. 3) Crack a valve and vent a little refrigerant to clear the air. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "safety_first", expected: 2, hint: "PPE, prove-dead, and lockout/tagout come before diagnosis — always. Venting (option 3) is illegal, and leak searching (option 1) happens after you are safe to work." } ] },
      { label: "SAFETY — To pressure-test the repaired section later you will need a test gas. The only acceptable choice is: 1) Oxygen from the welding cart, since it reaches higher pressure. 2) Dry nitrogen, through its regulator, kept within the lowest pressure rating in the section. 3) Shop air from the compressor in the back room. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "test_gas", expected: 2, hint: "Dry nitrogen through a regulator is the test gas. Oxygen under pressure with oil can explode; shop air pumps moisture into a system you will then have to evacuate." } ] },
      { label: "RECORDS — The ticket history shows 30 lb of R-404A added to this 60-lb system over the past 12 months. Compute the annualized leak rate as a percent of full charge. Enter the number (percent).",
        cells: [""], inputs: [ { col: 1, key: "leak_rate", expected: 50, hint: "Leak rate = added ÷ full charge = 30 ÷ 60 = 0.50 = 50% per year. That is why the additions kept growing — this system has been announcing a serious leak for months." } ] },
      { label: "EPA DUTY — Commercial refrigeration trigger rate is 20% per year. With a 50% leak rate on a 60-lb appliance, the correct statement of the duty is: 1) No duty — the trigger only applies over 100 lb. 2) The repair duty is triggered: repair within 30 days of discovery, with verification tests. 3) The duty is triggered, but the store has a full year to get around to it. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "epa_duty", expected: 2, hint: "50% exceeds the 20% commercial refrigeration trigger, the appliance is over the 50-lb coverage line, and the repair clock is 30 days from discovery — with initial verification before recharge and follow-up verification within 10 days." } ] },
      { label: "FIRST LOOK — Before any detector comes out, your eyes find one suction-line braze joint behind the insulation that is dark with oil while every other joint is clean and dry. The professional first move: 1) Ignore it — oil stains are normal. 2) Treat that joint as the prime suspect: clean it, note it, and plan to test it first under pressure. 3) Add 10 lb of refrigerant so the system has pressure to leak out. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "oil_stain", expected: 2, hint: "Oil escapes with refrigerant and deposits at the exit — an oil stain on an otherwise clean system is a leak map. Adding refrigerant first (option 3) just feeds the leak and restarts the compliance clock with nothing to show." } ] },
      { label: "DETECTOR CRAFT — You sweep the unit cooler and condensing unit with the electronic detector. Correct technique is: 1) Wave the probe quickly back and forth over each joint like a metal detector. 2) Move the probe slowly, close to the surface, and pause to confirm that an alarm repeats at the same single spot before calling it a hit. 3) Hold the probe at the ceiling, since refrigerant rises. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "detector_technique", expected: 2, hint: "Slow movement plus a repeatable, location-stable alarm separates a leak from background contamination. Refrigerant vapor is heavier than air — it pools low, so search low, not at the ceiling." } ] },
      { label: "PINPOINT — The detector brackets the leak to the corner containing that oil-stained braze joint. To identify the exact hole you use: 1) The UV lamp (no dye has ever been installed in this system). 2) Bubble solution on the joint while the section is pressurized, watching for growing bubbles at one precise point. 3) Your ear, listening harder. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "pinpoint", expected: 2, hint: "Bubbles grow at the hole itself and cannot be faked by background vapor. A UV lamp reads dye — and this system has none. The leak is too small for ears; that is why it hid for three months." } ] },
      { label: "ORDER — Procedure step number for: Recover the refrigerant from the section to be opened. Enter the step number from the closing procedure in the task description.",
        cells: [""], inputs: [ { col: 1, key: "order_recover", expected: 1, hint: "Recovery is Step 1 — nothing gets opened, brazed, or tested until the refrigerant is out and in a certified cylinder." } ] },
      { label: "ORDER — Procedure step number for: Re-braze the failed joint with nitrogen flowing through the piping. Enter the step number.",
        cells: [""], inputs: [ { col: 1, key: "order_repair", expected: 2, hint: "The repair itself is Step 2 — after recovery, before any testing. Nitrogen flowing during brazing prevents internal oxide scale that would otherwise tour the system." } ] },
      { label: "ORDER — Procedure step number for: Pressure-test the repair with dry nitrogen and bubble-check the joint. Enter the step number.",
        cells: [""], inputs: [ { col: 1, key: "order_pressuretest", expected: 3, hint: "Step 3 proves the repair before a single ounce of refrigerant is entrusted to it. A joint that bubbles at test pressure gets re-made now, not re-found in three months." } ] },
      { label: "ORDER — Procedure step number for: Evacuate to 500 microns or below and pass the standing decay test. Enter the step number.",
        cells: [""], inputs: [ { col: 1, key: "order_evacuate", expected: 4, hint: "Step 4 — after the repair is proven tight, the system is dried and proven again by the decay test before charging (Step 5)." } ] },
      { label: "DECAY VERDICT — Evacuation reached 420 microns. You isolate the pump for ten minutes: the gauge rises to 460 microns and levels off flat. The verdict: 1) There is a leak — keep hunting. 2) Tight and dry — proceed to charge. 3) The system is wet — keep pumping for hours. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "decay_verdict", expected: 2, hint: "Rise-and-level at a low value is the tight, dry signature. A leak climbs steadily toward atmosphere without leveling; moisture stalls at a much higher plateau (thousands of microns)." } ] },
      { label: "SUPERHEAT CHECK — After charging by weight, you verify at the evaporator outlet: suction pressure about 66 psig (R-404A dew point ≈ 40°F) and the suction line measures 52°F. Compute the superheat in °F. Enter the number.",
        cells: [""], inputs: [ { col: 1, key: "superheat", expected: 12, hint: "Superheat = suction line temp − dew-point saturation temp = 52 − 40 = 12°F. Liquid is fully boiled off with a safe margin — the compressor downstream gets vapor only." } ] },
      { label: "SUBCOOLING CHECK — Same verification: head pressure about 198 psig (R-404A bubble point ≈ 100°F) and the liquid line measures 90°F. Compute the subcooling in °F. Enter the number.",
        cells: [""], inputs: [ { col: 1, key: "subcooling", expected: 10, hint: "Subcooling = bubble-point saturation temp − liquid line temp = 100 − 90 = 10°F. A healthy liquid reserve at the TXV — the weighed charge is confirmed by operation, not by the sight glass alone." } ] },
      { label: "FOLLOW-UP — The repair is verified and the box is recovering. The remaining compliance items are: 1) Nothing — a fixed leak closes itself. 2) Follow-up verification under operating conditions within 10 days, scheduled leak inspections while the appliance is in the over-trigger population, and all amounts and tests filed in the records kept 3 years. 3) A thank-you note to the refrigerant supplier. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "follow_up", expected: 2, hint: "Covered-appliance repairs close with follow-up verification within 10 days, an inspection schedule, and 3-year records. The job is not done when the box gets cold; it is done when the file proves it." } ] },
      { label: "PRODUCT CALL — The dairy that stayed in the box probed at 45–46°F for an unknown number of hours. The correct professional action: 1) Say nothing — once the box is cold again the food is fine. 2) Tell the manager the temperatures and the 41°F standard now, in writing on the ticket, so product disposition is her informed decision. 3) Move the product to the freezer to freeze away the risk. Enter the option number.",
        cells: [""], inputs: [ { col: 1, key: "product_call", expected: 2, hint: "Refrigerated perishables must be held at 41°F or below; re-cooling does not rewind time above the limit, and freezing does not erase it either. Your duty is early, plain information, documented — the disposition decision belongs to the owner with that information in hand." } ] }
    ],
    passing: 70
  }
];
