// HVAC 245 - Module 2: Reading the Psychrometric Chart
module.exports = {
  number: 2,
  slug: "reading-the-psychrometric-chart",
  title: "Reading the Psychrometric Chart",
  estTime: "3–4 hours",
  objectives: ["Locate dry bulb, wet bulb, dew point, RH, humidity ratio, and enthalpy for a plotted point on the chart.", "Draw a sensible-cooling process and a cooling-with-dehumidification process and explain the direction of each line.", "Calculate a mixed-air condition from two airstreams using CFM-weighted averages of given values.", "Use given chart-read enthalpies in the total-heat equation to find coil capacity.", "Explain sensible heat ratio as the slope key that connects a room load to a process line."],
  sections: [
    { heading: "Anatomy of the Chart", html: `<p>The psychrometric chart is a map of moist air. The horizontal axis is <strong>dry-bulb temperature</strong>. The curved left boundary is the <strong>saturation curve</strong> (100% RH), and the curved lines sweeping inside it are constant-RH lines. The right-hand scale is <strong>humidity ratio</strong> (or grains), read on horizontal lines. Diagonal lines carry <strong>wet bulb</strong> and <strong>enthalpy</strong> (nearly parallel to each other), and another set of shallow diagonals shows specific volume. Any two independent properties fix a point, and once the point is plotted, every other property can be read off the line families that cross it.</p><p><strong>Worked plot (chart-read teaching values).</strong> Plot 75°F dry bulb and 50% RH. From that point, in this teaching example the chart reads approximately: wet bulb 62°F, dew point 55°F, humidity ratio about 65 grains per pound, enthalpy about 28 Btu/lb. Treat these as round chart-read values for learning to read — the skill is the path you trace (up the dry-bulb line to the RH curve, left to grains, diagonally to enthalpy, horizontally left to dew point), not memorizing this one point.</p><div class="callout"><strong>Key idea:</strong> Two properties in, everything else out. Designers plot the outdoor design point, the indoor target point, and the supply point, and the lines between them become the system's job description.</div>` },
    { heading: "Sensible Processes: Horizontal Moves", html: `<p>Any process that changes temperature without adding or removing moisture moves <strong>horizontally</strong> on the chart, because humidity ratio (the vertical scale) is constant. Heating air with a furnace moves the point right; cooling air across a dry surface (one that stays above the dew point) moves it left. RH changes during these moves — heating lowers RH, dry cooling raises it — even though the actual moisture content never changed. That single observation explains winter dryness complaints: cold outdoor air heated to room temperature keeps its tiny moisture content but its capacity grows, so RH collapses.</p><p><strong>Worked example.</strong> Outdoor air at a given 35 grains per pound is heated from 30°F to 70°F. Humidity ratio after heating: still 35 grains — the point moved straight right. Using the sensible equation for 600 CFM of that air: Q = 1.08 × 600 × (70 − 30) = 1.08 × 600 × 40 = 25,920 Btu/h of heating. The chart told us the moisture story (no change); the equation told us the energy story. Good designers use both together, chart for state, equation for rate.</p><div class="formula">Horizontal line on the chart = sensible change only (Δ humidity ratio = 0)</div><p>One more consequence follows from the horizontal move: because RH falls as air is heated, a humidistat reading alone cannot tell you whether a winter room needs moisture added or simply contains cold, dry outdoor air that was heated on arrival. The chart separates those stories instantly — find the humidity ratio first, then judge the RH.</p>` },
    { heading: "Cooling with Dehumidification: Down and to the Left", html: `<p>A real cooling coil does two jobs at once. Air crossing a cold coil drops in temperature <em>and</em> gives up moisture, because the coil surface runs below the air's dew point and water condenses on the fins. On the chart the process line slopes <strong>down and to the left</strong> — dry bulb falls (left), humidity ratio falls (down). The steeper the downward slope, the larger the share of the coil's work that is latent. After the coil, a slight reheat or fan heat may nudge the point right again before supply, which is why supply conditions are plotted as their own point rather than assumed to equal coil-leaving conditions.</p><p><strong>Worked example (given chart-read enthalpies).</strong> Air enters a coil at a chart-read enthalpy of 31.0 Btu/lb and leaves at 23.5 Btu/lb, at 1,000 CFM. Total capacity used: Q = 4.5 × 1,000 × (31.0 − 23.5) = 4.5 × 1,000 × 7.5 = 33,750 Btu/h. If the same air's sensible portion (dry bulb drop of 20°F) is Q<sub>s</sub> = 1.08 × 1,000 × 20 = 21,600 Btu/h, then the latent portion is 33,750 − 21,600 = 12,150 Btu/h — moisture work you can only see because enthalpy kept the total ledger.</p><div class="callout"><strong>Key idea:</strong> Total = sensible + latent, always. If a coil selection or a load states only one part, the other part is still there waiting to surprise you.</div><p>Notice what the coil surface temperature controls: the closer the coil runs to the air's dew point from below, the more condensation forms. A coil that is only slightly below the dew point cools mostly sensibly; a much colder coil wrings out far more moisture per pass. That is why two systems at the same supply temperature can leave a room at very different humidities.</p>` },
    { heading: "Mixing Air Streams", html: `<p>Most systems mix return air with outdoor ventilation air before the coil. The mixed condition lies on the straight line between the two points on the chart, positioned by the flow proportions: the mixed point sits closer to whichever stream carries more air. The same weighting works numerically for temperature, humidity ratio, and enthalpy when the stream values are given.</p><div class="formula">Mixed value = (CFM<sub>1</sub> × value<sub>1</sub> + CFM<sub>2</sub> × value<sub>2</sub>) ÷ (CFM<sub>1</sub> + CFM<sub>2</sub>)</div><p><strong>Worked example.</strong> 800 CFM of return air at 75°F mixes with 200 CFM of outdoor air at 95°F. Mixed dry bulb = (800 × 75 + 200 × 95) ÷ 1,000 = (60,000 + 19,000) ÷ 1,000 = 79°F. If the given humidity ratios are 65 grains (return) and 105 grains (outdoor), mixed = (800 × 65 + 200 × 105) ÷ 1,000 = (52,000 + 21,000) ÷ 1,000 = 73 grains. Check the geometry: 79°F and 73 grains both sit one-fifth of the way from the return point toward the outdoor point — exactly the 200/1,000 share of the smaller stream. If your computed mix does not lie between the two parents, the arithmetic is wrong; the chart enforces that sanity check visually.</p><p>Mixing also explains a common field reading: on a mild day the mixed air entering the coil can be closer to room temperature than either extreme suggests, which is why economizer dampers (Module 7's RTU cousin in spirit) save energy — the blend, not the raw outdoor air, is what the coil must treat. Always compute the mix before judging the coil's work.</p>` },
    { heading: "Sensible Heat Ratio and Process Lines", html: `<p>The <strong>sensible heat ratio (SHR)</strong> of a load is its sensible load divided by its total load. A dry desert load might have an SHR of 0.95 (nearly all temperature work); a humid-climate load with many occupants might sit near 0.75 (a quarter of the work is moisture). SHR matters because it sets the <em>slope</em> of the room process line on the chart: starting at the room point, the supply air must lie along the line whose slope matches the room SHR, or the room will drift to a different humidity than designed even if the temperature is perfect.</p><p><strong>Worked example.</strong> A room's sensible load is given as 18,000 Btu/h and its latent load as 6,000 Btu/h. Total = 24,000 Btu/h; SHR = 18,000 ÷ 24,000 = 0.75. Equipment for this room must deliver its capacity at roughly that same split at design conditions — a unit whose design SHR output is 0.90 would hold temperature but let humidity climb, the classic oversized/short-cycling complaint examined in Module 5. Conversely a load with SHR 0.95 needs little latent capacity, and a coil selected for heavy dehumidification would over-dry the space in mild weather.</p><div class="callout"><strong>Key idea:</strong> Temperature is controlled by sensible capacity; humidity is controlled by the <em>match</em> between load SHR and equipment SHR plus runtime. The chart is where that match is checked.</div><p>Keep the SHR habit for the rest of the course: every time a load or a coil is described, ask for its split. A single total number hides the very information humidity control runs on, and Modules 5 and 9 will both refuse to select equipment from a total alone.</p>` },
  ],
  keyTerms: [{ term: "Psychrometric chart", def: "A graph of moist-air properties: dry bulb, wet bulb, dew point, RH, humidity ratio, enthalpy, and specific volume." }, { term: "Saturation curve", def: "The 100% RH boundary on the left of the chart; points on it have dry bulb = wet bulb = dew point." }, { term: "State point", def: "A single plotted condition of air on the chart, fixed by any two independent properties." }, { term: "Process line", def: "The path drawn between two state points, showing how air changes through a coil, furnace, or mixing box." }, { term: "Sensible process", def: "A horizontal chart move: temperature changes, humidity ratio constant." }, { term: "Cooling and dehumidification", def: "A down-and-left chart move across a coil colder than the dew point: temperature and moisture both fall." }, { term: "Apparatus dew point", def: "The effective surface temperature of a cooling coil that the process line aims toward." }, { term: "Mixed air", def: "The blend of return and outdoor air; its state lies on the line between the two parent points, weighted by CFM." }, { term: "Sensible heat ratio (SHR)", def: "Sensible load divided by total load; sets the slope of the room process line." }, { term: "Room process line", def: "The line from the room point toward supply conditions whose slope matches the room SHR." }, { term: "Enthalpy scale", def: "The diagonal scale on the chart giving total heat content in Btu per pound of dry air." }, { term: "Humidity ratio scale", def: "The right-hand scale of the chart, in pounds or grains of moisture per pound of dry air." }, { term: "Specific volume", def: "Cubic feet of moist air per pound of dry air, shown by shallow diagonal lines on the chart." }, { term: "Wet-bulb lines", def: "Diagonal lines of constant wet-bulb temperature, nearly parallel to enthalpy lines." }, { term: "Dew point reading", def: "Found by moving horizontally left from a point to the saturation curve and reading the temperature." }, { term: "Coil bypass concept", def: "The idea that not all air contacts the coil surface, so leaving air is a mix of treated and untreated air." }, { term: "Supply point", def: "The plotted condition of air leaving the equipment toward the rooms." }, { term: "Grains per pound", def: "Humidity ratio expressed in grains; divide by 7,000 for pounds per pound." }],
  video: { title: "How to Read a Psychrometric Chart", embedUrl: "https://www.youtube.com/embed/hC8R7nWlMiw", note: "A step-by-step walk through plotting a point and reading every property off the chart. Follow along with a printed chart and plot each state point from this module's worked examples as the presenter plots his.", more: [{ title: "Psychrometric Chart Part 2 Beyond The Basics", url: "https://www.youtube.com/watch?v=4Z_usQB9vQ8" }] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> 600 CFM of return air at 74°F mixes with 400 CFM of outdoor air at 94°F. Find the mixed dry-bulb temperature.</p>", solution: "<p><strong>Answer: 82°F.</strong> Step 1: Weight by CFM: (600 × 74 + 400 × 94) ÷ 1,000. Step 2: (44,400 + 37,600) = 82,000. Step 3: 82,000 ÷ 1,000 = 82°F. Step 4: Check — 82 lies between 74 and 94, closer to 74 because return air is the larger share. Correct.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Using the same flows, return air is given at 60 grains and outdoor air at 100 grains. Find the mixed humidity ratio.</p>", solution: "<p><strong>Answer: 76 grains.</strong> Step 1: (600 × 60 + 400 × 100) ÷ 1,000 = (36,000 + 40,000) ÷ 1,000 = 76 grains. Step 2: Check — 76 lies between 60 and 100, 40% of the way toward the outdoor value, matching the outdoor share of flow.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A coil receives 1,200 CFM at a given enthalpy of 29.0 Btu/lb and discharges it at a given 21.5 Btu/lb. Find total cooling capacity used.</p>", solution: "<p><strong>Answer: 40,500 Btu/h.</strong> Step 1: Δh = 29.0 − 21.5 = 7.5. Step 2: Q = 4.5 × 1,200 × 7.5 = 40,500 Btu/h (≈ 3.4 tons).</p>" },
    { prompt: "<p><strong>Problem 4.</strong> For the coil in Problem 3, the dry-bulb drop is 22°F. Find the sensible and latent portions of the capacity.</p>", solution: "<p><strong>Answer: sensible 28,512 Btu/h; latent 11,988 Btu/h.</strong> Step 1: Q<sub>s</sub> = 1.08 × 1,200 × 22 = 28,512 Btu/h. Step 2: Latent = total − sensible = 40,500 − 28,512 = 11,988 Btu/h. Step 3: The split (≈ 0.70 SHR) tells you this coil is doing heavy moisture work.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A room load is given as 21,600 Btu/h sensible and 5,400 Btu/h latent. Find the room SHR and state what equipment mismatch it warns against.</p>", solution: "<p><strong>Answer: SHR = 0.80.</strong> Step 1: Total = 27,000. Step 2: 21,600 ÷ 27,000 = 0.80. Step 3: Warning — equipment delivering its capacity at a much higher SHR (say 0.95) at design conditions would satisfy the thermostat while under-removing moisture; humidity would drift up.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Air is cooled across a dry surface that stays above its dew point. Describe its path on the chart and what happens to RH and humidity ratio.</p>", solution: "<p><strong>Answer:</strong> Step 1: No condensation occurs, so no moisture leaves — humidity ratio is constant and the path is horizontal, moving left as dry bulb falls. Step 2: RH rises, because cooler air's maximum moisture capacity is smaller while the actual content is unchanged. Step 3: If cooling continued to the dew point, the path would touch the saturation curve and further cooling would bend down-left into dehumidification.</p>" },
  ],
  quiz: [
    { q: "A horizontal line on the psychrometric chart means:", choices: ["Humidity ratio is constant", "RH is constant", "Enthalpy is constant", "Wet bulb is constant"], answer: 0, explanation: "Correct: (a). Horizontal = constant height on the humidity-ratio scale: a sensible-only change. (b) RH curves are curved, not horizontal. (c) Enthalpy lines are diagonal. (d) Wet-bulb lines are also diagonal." },
    { q: "Mixing 900 CFM at 72°F with 100 CFM at 92°F gives a mixed temperature of:", choices: ["74°F", "82°F", "80°F", "73°F"], answer: 0, explanation: "Correct: (a). (900 × 72 + 100 × 92) ÷ 1,000 = (64,800 + 9,200) ÷ 1,000 = 74°F. (b) and (c) weight the small hot stream far too heavily. (d) 73°F would require the outdoor share to pull the mix only 1°F, inconsistent with a 20°F gap at 10% share (2°F pull)." },
    { q: "During cooling with dehumidification, the process line moves:", choices: ["Right and up", "Left only, horizontally", "Down and to the left", "Straight down"], answer: 2, explanation: "Correct: (c). Dry bulb falls (left) and humidity ratio falls (down) as moisture condenses on the cold coil. (a) is heating and humidifying. (b) is dry sensible cooling. (d) would be moisture removal at constant temperature, which a simple coil does not do." },
    { q: "To read a point's dew point, you move:", choices: ["Diagonally to the enthalpy scale", "Horizontally left to the saturation curve", "Vertically down to the axis", "Along an RH curve to the right scale"], answer: 1, explanation: "Correct: (b). Dew point is found at constant humidity ratio — a horizontal move left until the saturation curve, then read temperature. (a) gives enthalpy. (c) reads dry bulb only. (d) confuses RH curves with the dew-point construction." },
    { q: "A room load of 15,000 sensible and 5,000 latent has an SHR of:", choices: ["0.50", "0.67", "0.75", "0.80"], answer: 2, explanation: "Correct: (c). Total = 20,000; 15,000 ÷ 20,000 = 0.75. (a) divides latent by sensible incorrectly in spirit (5,000/10,000 nonsense). (b) is 15,000/22,500 — wrong total. (d) would need a total of 18,750." },
    { q: "Air enters a coil at a given 32.0 Btu/lb and leaves at 24.5 Btu/lb at 1,000 CFM. Total cooling is:", choices: ["27,000 Btu/h", "33,750 Btu/h", "40,500 Btu/h", "7,500 Btu/h"], answer: 1, explanation: "Correct: (b). Q = 4.5 × 1,000 × 7.5 = 33,750 Btu/h. (a) uses a Δh of 6. (c) uses Δh of 9. (d) is just Δh scaled by 1,000 — it forgets the 4.5 factor." },
    { q: "The mixed-air point on the chart lies:", choices: ["Outside the two parent points", "On the line between the parents, closer to the larger stream", "Exactly halfway, always", "On the saturation curve"], answer: 1, explanation: "Correct: (b). Mixing is a CFM-weighted average, so the point divides the line in proportion to the flows, nearer the bigger stream. (a) is physically impossible for a simple mix. (c) is true only for equal flows. (d) Mixing does not saturate air by itself." },
    { q: "Heating outdoor air sensibly from 20°F to 70°F does what to its RH?", choices: ["Raises it", "Lowers it", "Leaves it unchanged", "Sets it to 100%"], answer: 1, explanation: "Correct: (b). Humidity ratio is unchanged but warm air can hold much more moisture, so the percentage (RH) falls — the mechanism behind dry winter indoor air. (a) describes cooling toward dew point. (c) RH is temperature-dependent by definition. (d) Saturation would require adding moisture or cooling to dew point." },
  ],
  studyGuide: `
<h3>Module 2 — Reading the Psychrometric Chart: Quick Reference</h3>
<p><strong>Axes &amp; lines:</strong> dry bulb across the bottom · humidity ratio (grains) on the right, horizontal lines · RH curves sweeping inside the saturation curve · wet bulb and enthalpy on diagonals · dew point by moving horizontally left to saturation.</p><p><strong>Process directions:</strong> heating → right · dry cooling → left · cooling + dehumidifying → down-left · humidifying → up. Horizontal = sensible only.</p>
<div class="formula">Mix: value = (CFM₁v₁ + CFM₂v₂) ÷ (CFM₁ + CFM₂) — for temperature, grains, and enthalpy alike</div>
<p><strong>Capacity:</strong> total Q = 4.5 × CFM × Δh (given enthalpies) · sensible Q = 1.08 × CFM × ΔT · latent = total − sensible.</p>
<p><strong>SHR</strong> = sensible ÷ total; it sets the room process-line slope and the equipment split the room needs.</p>
<p><strong>Sanity checks:</strong> a mixed point must lie between its parents; a dew point never exceeds its dry bulb; totals must equal sensible + latent.</p>
<p><strong>Reading drill:</strong> given any two properties, plot the point and read the other four before doing any arithmetic — the chart is a calculator you can see. If a computed mix or process endpoint lands somewhere the chart says it cannot, believe the chart and re-check the numbers.</p>
`
};
