// HVAC 245 - Module 3: Load Calculations I: Heat Loss
module.exports = {
  number: 3,
  slug: "load-calculations-heat-loss",
  title: "Load Calculations I: Heat Loss",
  estTime: "3–4 hours",
  objectives: ["Explain the heat-loss equation Q = U × A × ΔT and where each factor comes from in a building survey.", "Convert an assembly R-value to a U-factor and explain the inverse relationship in design terms.", "Compute conduction losses for walls, ceilings, floors, windows, and doors from given teaching-example values.", "Explain what a design temperature is, why the coldest-ever temperature is not used, and where real values come from.", "Add infiltration as a separate load path and combine it with conduction into a block heating load."],
  sections: [
    { heading: "Heat Leaves by Conduction: Q = U × A × ΔT", html: `<p>On a cold night the house is a warm box leaking heat through every surface. For each assembly — wall, ceiling, floor, window, door — the conduction loss follows one equation:</p><div class="formula">Q = U × A × ΔT</div><p><strong>U</strong> is the assembly's overall heat-transfer coefficient (Btu per hour per square foot per degree), <strong>A</strong> is its area, and <strong>ΔT</strong> is the indoor-to-outdoor temperature difference across it. Big area, leaky assembly, or bitter night — each multiplies the loss directly, which is why the equation is such a good design teacher: it ranks your insulation dollars. Double the area or halve the insulation quality and the loss doubles; there are no hidden terms.</p><p><strong>Worked example.</strong> A teaching-example wall of 900 sq ft with U = 0.08, indoors 70°F, outdoors 10°F (ΔT = 60): Q = 0.08 × 900 × 60 = 4,320 Btu/h. A ceiling of 1,200 sq ft with U = 0.04 at the same ΔT: Q = 0.04 × 1,200 × 60 = 2,880 Btu/h. The wall has less area but loses 50% more heat, because its U-factor is twice as large. Always compare U × A products, not areas alone.</p><div class="callout"><strong>Key idea:</strong> Real design values for U-factors and design temperatures come from the current ACCA Manual J procedure and local data. Every U and ΔT in this module is a stated teaching-example value — the method, not the number, is what transfers to real work.</div>` },
    { heading: "R-Value and U-Factor: Two Views of the Same Wall", html: `<p>Insulation is sold by <strong>R-value</strong>, resistance to heat flow; loads are calculated with <strong>U-factor</strong>, conductance. They are inverses:</p><div class="formula">U = 1 ÷ R<sub>total</sub></div><p>An assembly's total R is the sum of its layers' resistances — films, sheathing, cavity insulation, drywall — as accounted by the design procedure being used. <strong>Worked example.</strong> A teaching-example assembly totals R-20: U = 1 ÷ 20 = 0.05. An older assembly at R-5: U = 1 ÷ 5 = 0.20. Across 500 sq ft at ΔT 60, the R-20 assembly loses 0.05 × 500 × 60 = 1,500 Btu/h; the R-5 assembly loses 0.20 × 500 × 60 = 6,000 Btu/h — four times the heat for one quarter of the resistance, exactly as the inverse relationship predicts.</p><p>The design lesson is diminishing returns. Going from R-5 to R-10 halves the loss; going from R-30 to R-35 trims a small slice more. Designers therefore check windows and infiltration before gold-plating wall R: the worst U × A product in the building deserves the first dollar. Framing also matters — studs interrupt cavity insulation, which is why assembly R (the whole wall as built) is always lower than the batt's label R, and why honest load procedures use assembly values rather than package labels.</p><p>A practical survey note follows: when you record an assembly, record the whole assembly as built — including obvious thermal shortcuts such as uninsulated rim areas or a kneewall treated as interior partition. The U-factor you choose is a claim about the building as it stands, not as the brochure described it.</p>` },
    { heading: "Design Temperatures: Cold, but Not the Coldest Ever", html: `<p>A <strong>design temperature</strong> is the outdoor condition chosen for sizing: cold enough that the system keeps up on nearly every winter night, but not the once-a-decade record low. Sizing to the record would leave the equipment oversized for its entire life to survive a few hours — oversizing penalties (Module 5) paid every day to insure against a rare night. Design procedures draw outdoor design values from long-term weather statistics for the location, and the indoor design temperature from the occupants' needs and applicable standards or code.</p><p><strong>Worked example.</strong> For a teaching example, take indoor 70°F and an outdoor design value of 0°F: ΔT = 70. A wall of 800 sq ft at U = 0.07 loses 0.07 × 800 × 70 = 3,920 Btu/h. If a record-chasing designer instead used −15°F (ΔT = 85), the same wall would compute to 0.07 × 800 × 85 = 4,760 Btu/h — about 21% more load from a paperwork choice, multiplied across every assembly and carried into equipment size, duct size, and fuel use for decades.</p><div class="callout"><strong>Key idea:</strong> The design temperature is a statistical, professional choice made from current published data for the site — never a guess, a memory, or a number copied from a course example. In this course ΔT values are always stated in the problem.</div><p>Design conditions also carry a humidity story in cooling work (the outdoor design dew point governs latent infiltration), but for heat loss the temperature difference is the whole driver — one more reason winter and summer calculations are kept in separate worksheets with separate stated conditions.</p>` },
    { heading: "Windows, Doors, Floors: The Supporting Cast That Steals the Show", html: `<p>Windows are the thermal holes in most walls. Even a modest window area can lose more heat than the entire opaque wall around it, because glass assemblies have far higher U-factors than insulated framing. <strong>Worked example.</strong> In a teaching example, 120 sq ft of windows at U = 0.50 with ΔT 70 lose 0.50 × 120 × 70 = 4,200 Btu/h, while 800 sq ft of wall at U = 0.07 loses 3,920 Btu/h. The windows are 13% of the combined area and more than half the combined loss. Doors behave like thick windows: 40 sq ft at U = 0.30 and ΔT 70 lose 840 Btu/h.</p><p>Floors need a ΔT judgment: a floor over a vented crawlspace may see nearly the full outdoor ΔT, while a floor over an unheated but enclosed basement sees a smaller difference because the basement floats between indoor and outdoor temperatures. In the course lab, the floor's ΔT is given as 40°F against a 70°F whole-house design difference for exactly this reason. Slab edges are a special case handled by perimeter methods in real procedures — noted here so you recognize the term, with its values taken from the current manual on real jobs, not invented here.</p><p>The survey discipline: measure gross wall, subtract window and door areas to get <em>net</em> wall, and list every assembly with its own area, U, and ΔT. Most load errors are bookkeeping errors, not physics errors.</p><p>Survey habit: photograph each elevation and the window schedule as you measure. When a total looks wrong weeks later, the photo settles whether the 120 sq ft of glass was real — bookkeeping errors are far easier to catch against a picture than against a memory.</p>` },
    { heading: "Infiltration and the Block Load", html: `<p>Conduction is only half the winter story. Cold air also leaks in through cracks, seams, and penetrations — <strong>infiltration</strong> — and every cubic foot that enters must be heated to room temperature. The sensible equation sizes it: Q = 1.08 × CFM<sub>infiltration</sub> × ΔT. <strong>Worked example.</strong> A teaching-example leakage rate of 150 CFM at ΔT 70: Q = 1.08 × 150 × 70 = 11,340 Btu/h — larger than any single conduction path in Section 4's house. That comparison is the point: air sealing is load reduction, and a blower-door-guided sealing job can shrink the required furnace before any equipment is chosen.</p><p>The <strong>block load</strong> is the whole-building total at design conditions: sum every conduction path, add infiltration, and (in real procedures) account for items such as duct losses where ducts run outside the thermal envelope. Room-by-room loads then apportion that total for airflow assignment — a room's share of CFM follows its share of load. This module's lab practices exactly this arithmetic: five conduction rows, one total, then room airflows from room loads.</p><div class="callout"><strong>Key idea:</strong> Heat loss = conduction + infiltration. Forgetting infiltration understates the load; double-counting a surface (gross wall <em>plus</em> its windows) overstates it. Both errors survive into equipment selection if the worksheet is sloppy.</div>` },
  ],
  keyTerms: [{ term: "Conduction", def: "Heat transfer through a solid assembly from its warm side to its cold side." }, { term: "U-factor", def: "Overall conductance of an assembly: Btu/h per sq ft per °F of temperature difference." }, { term: "R-value", def: "Thermal resistance of a material or assembly; the inverse of U-factor for the complete assembly." }, { term: "Assembly", def: "A complete building section as built — e.g., a framed wall with all its layers — rated by its overall U or R." }, { term: "Design temperature", def: "The outdoor (and indoor) conditions selected from published statistical data for sizing a system." }, { term: "ΔT (delta T)", def: "The temperature difference driving a heat flow; indoor minus outdoor for winter loss." }, { term: "Net wall area", def: "Gross wall area minus window and door openings, used for the opaque-wall conduction calculation." }, { term: "Fenestration", def: "The windows and glazed areas of a building; typically its highest-U assemblies." }, { term: "Infiltration", def: "Uncontrolled leakage of outdoor air into the building through cracks and openings." }, { term: "Block load", def: "The whole-building design load at a single coincident condition." }, { term: "Room load", def: "One room's share of the block load, used to assign its airflow." }, { term: "Thermal envelope", def: "The boundary of assemblies separating conditioned space from outdoors or unconditioned space." }, { term: "Air changes per hour (ACH)", def: "A way of expressing leakage or ventilation as volume flow relative to building volume." }, { term: "Duct loss", def: "Load added when ducts run outside the thermal envelope and lose (or gain) heat to their surroundings." }, { term: "Heat loss", def: "Total rate at which a building loses heat at design conditions, in Btu/h." }, { term: "Gross wall area", def: "Full wall area before subtracting openings." }, { term: "Slab perimeter loss", def: "Heat loss at the edge of a slab-on-grade floor, handled by perimeter methods in real procedures." }, { term: "Blower door", def: "A calibrated fan used to measure building leakage, guiding air sealing and infiltration estimates." }],
  video: { title: "Mastering Manual J and COMcheck – Austin Energy Green Building Webinar", embedUrl: "https://www.youtube.com/embed/5IqGqjj49YA", note: "An Austin Energy Green Building webinar in which instructors walk through a Manual J load calculation for residential sizing and discuss code compliance. Use it to see the order of a real load calculation — survey, envelope, gains — before this module's simplified teaching examples. This course teaches the method only; real designs use the current ACCA manual and approved software.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A wall assembly totals R-25 in a teaching example. Find its U-factor.</p>", solution: "<p><strong>Answer: U = 0.04.</strong> Step 1: U = 1 ÷ R. Step 2: 1 ÷ 25 = 0.04 Btu/h·sq ft·°F.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Compute the heat loss through 600 sq ft of ceiling at U = 0.06 with ΔT = 65°F.</p>", solution: "<p><strong>Answer: 2,340 Btu/h.</strong> Step 1: Q = U × A × ΔT. Step 2: 0.06 × 600 × 65 = 2,340 Btu/h.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Gross wall is 1,000 sq ft. Windows total 150 sq ft and doors 40 sq ft. Find net wall area, then its loss at U = 0.07, ΔT = 70°F.</p>", solution: "<p><strong>Answer: net 810 sq ft; loss 3,969 Btu/h.</strong> Step 1: Net = 1,000 − 150 − 40 = 810 sq ft. Step 2: Q = 0.07 × 810 × 70 = 3,969 Btu/h. Step 3: Using gross area would have double-counted the openings.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Infiltration is given as 120 CFM at ΔT 70°F. Find the infiltration heat loss.</p>", solution: "<p><strong>Answer: 9,072 Btu/h.</strong> Step 1: Q = 1.08 × CFM × ΔT. Step 2: 1.08 × 120 × 70 = 9,072 Btu/h.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A small house has conduction losses: walls 3,920; ceiling 3,500; floor 2,400; windows 4,200; doors 840; plus infiltration 9,072 Btu/h. Find the block heating load.</p>", solution: "<p><strong>Answer: 23,932 Btu/h.</strong> Step 1: Conduction sum = 3,920 + 3,500 + 2,400 + 4,200 + 840 = 14,860. Step 2: Add infiltration: 14,860 + 9,072 = 23,932 Btu/h. Step 3: Note infiltration is 38% of this load — sealing would pay.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A designer sizes a furnace using a record low of −20°F instead of the location's design value of 0°F (indoor 70°F). For a total U × A product of 300 Btu/h·°F, compute both loads and the percent oversize created by the paperwork choice alone.</p>", solution: "<p><strong>Answer: 21,000 vs 27,000 Btu/h — about 29% oversize.</strong> Step 1: At design ΔT 70: 300 × 70 = 21,000 Btu/h. Step 2: At record ΔT 90: 300 × 90 = 27,000 Btu/h. Step 3: Excess = 6,000 ÷ 21,000 ≈ 29%. Step 4: That excess follows the equipment for its whole life, while the record night may occur a few hours in a decade.</p>" },
  ],
  quiz: [
    { q: "The conduction heat-loss equation is:", choices: ["Q = 1.08 × CFM × ΔT", "Q = U × A × ΔT", "Q = 4.5 × CFM × Δh", "Q = R × A × ΔT"], answer: 1, explanation: "Correct: (b). Conduction through an assembly is conductance × area × temperature difference. (a) is the sensible-air equation for moving airstreams, used for infiltration. (c) is the total-heat air equation needing enthalpies. (d) uses R, which is resistance — heat flow rises with U, not with R." },
    { q: "An assembly with total R-10 has a U-factor of:", choices: ["10", "0.10", "1.0", "0.01"], answer: 1, explanation: "Correct: (b). U = 1 ÷ R = 1 ÷ 10 = 0.10. (a) repeats R itself. (c) would be R-1. (d) would be R-100." },
    { q: "Why is the record-low temperature not used as the heating design temperature?", choices: ["Records are kept secret", "Sizing to a rare extreme oversizes equipment for its whole life", "Codes forbid thermometers", "The furnace cannot be that large"], answer: 1, explanation: "Correct: (b). Design values come from long-term statistics so the system fits the climate it actually serves; extremes occur too rarely to justify permanent oversizing penalties. (a) Weather records are public. (c) is nonsense. (d) Large furnaces exist — the objection is performance and cost, not availability." },
    { q: "Net wall area is found by:", choices: ["Adding window area to gross wall", "Subtracting window and door areas from gross wall", "Multiplying wall length by ceiling height twice", "Ignoring openings"], answer: 1, explanation: "Correct: (b). Openings are calculated with their own U-factors, so they must be removed from the opaque wall area to avoid double counting. (a) inflates the wall. (c) double-counts geometry. (d) double-counts the openings' area at the wall's U." },
    { q: "120 sq ft of windows at U = 0.50, ΔT 70, lose:", choices: ["840 Btu/h", "4,200 Btu/h", "42,000 Btu/h", "600 Btu/h"], answer: 1, explanation: "Correct: (b). 0.50 × 120 × 70 = 4,200 Btu/h. (a) 840 Btu/h is the doors example (U 0.30 × 40 × 70). (c) multiplies by 700 instead of 70. (d) is U × A without ΔT." },
    { q: "Infiltration load is calculated with:", choices: ["Q = U × A × ΔT on the cracks", "Q = 1.08 × CFM × ΔT", "Q = 4.5 × CFM × Δh, always", "The window schedule"], answer: 1, explanation: "Correct: (b). Infiltration is a moving airstream being heated, so the sensible-air equation applies with the leakage CFM. (a) Crack 'area × U' is not how air leakage is modeled. (c) The total-heat form would need enthalpies and is unnecessary for a winter sensible problem. (d) The window schedule covers fenestration conduction and solar, not leakage." },
    { q: "Doubling an assembly's R-value (with everything else fixed) does what to its conduction loss?", choices: ["Doubles it", "Halves it", "Leaves it unchanged", "Squares it"], answer: 1, explanation: "Correct: (b). U = 1/R, so doubling R halves U, and Q = U × A × ΔT halves with it. (a) reverses the relationship. (c) ignores that U changed. (d) The relationship is a simple inverse, not a power law." },
    { q: "A floor over an enclosed unheated basement is assigned a smaller ΔT than the exterior walls because:", choices: ["Floors lose no heat", "The basement temperature floats between indoor and outdoor conditions", "Basements are always 70°F", "U-factors do not apply to floors"], answer: 1, explanation: "Correct: (b). The space below the floor is buffered, so the difference across the floor assembly is smaller than the full indoor-outdoor difference. (a) Floors do lose heat — the lab's floor row is 2,400 Btu/h. (c) Basements vary; the point is they are intermediate, not room temperature. (d) U-factors apply to every assembly." },
  ],
  studyGuide: `
<h3>Module 3 — Load Calculations I: Heat Loss: Quick Reference</h3>
<div class="formula">Q = U × A × ΔT &nbsp;·&nbsp; U = 1 ÷ R<sub>total</sub> &nbsp;·&nbsp; Infiltration Q = 1.08 × CFM × ΔT</div>
<p><strong>Survey order:</strong> gross wall → subtract windows/doors → net wall; list every assembly with its own A, U, ΔT; add infiltration last; sum for the block load.</p><p><strong>Design temperatures</strong> come from current published statistical data and the applicable procedure — not records, memory, or course examples. All values in this course's problems are stated teaching values.</p>
<p><strong>Ranking rule:</strong> compare U × A products. Small high-U areas (windows) routinely beat large low-U areas (walls) for total loss.</p>
<p><strong>Diminishing returns:</strong> doubling R halves that assembly's loss, but each added R buys less absolute savings than the last.</p>
<p><strong>Watch out:</strong> double-counting openings (gross wall + windows), forgetting infiltration, and using a buffered-space ΔT for an exterior assembly (or vice versa).</p>
<p><strong>Exam-style drill:</strong> given any three of U, A, ΔT, Q, solve for the fourth without looking: Q = U × A × ΔT rearranges cleanly for each variable, and U = 1 ÷ R converts either direction. Most heat-loss errors on tests are unit or net-area slips, not concept failures — write the assembly list first, then compute.</p>
`
};
