// HVAC 245 - Module 4: Load Calculations II: Heat Gain
module.exports = {
  number: 4,
  slug: "load-calculations-heat-gain",
  title: "Load Calculations II: Heat Gain",
  estTime: "3–4 hours",
  objectives: ["List the heat-gain paths — conduction, solar through glass, infiltration, ventilation, and internal gains — and the direction each pushes the load.", "Separate any cooling load into sensible and latent parts and explain why the split, not just the total, drives design.", "Compute solar-plus-conduction gain for a window from given teaching-example factors.", "Compute internal gains from given occupant and appliance values without inventing rates.", "Explain why the cooling design hour and orientation change which room peaks, and why block and room peaks differ."],
  sections: [
    { heading: "Heat Gain Is Heat Loss Running Backwards — Plus the Sun", html: `<p>Summer gain uses the same physics as winter loss, with the sign reversed and one giant addition. Conduction still obeys Q = U × A × ΔT, but now the outdoors is hotter, so heat flows <em>in</em>. <strong>Worked example.</strong> The lab house's wall (800 sq ft, U = 0.07) at an outdoor design of 95°F and indoor 75°F (ΔT = 20) gains 0.07 × 800 × 20 = 1,120 Btu/h — far smaller than its winter loss of 3,920 Btu/h at ΔT 70. That asymmetry surprises beginners: summer conduction is modest because design ΔT is small. The summer load is dominated instead by <strong>solar gain through glass</strong>, infiltration of hot humid air, and <strong>internal gains</strong> from people, lights, and appliances.</p><p>Solar gain is directional and time-dependent: east glass peaks in the morning, west glass late in the afternoon, and the building's peak is the hour when the combination of all orientations, conduction, and internal gains is largest. A room-by-room calculation exists precisely because rooms peak differently — the west bedroom may drive its own airflow even if it is small.</p><div class="callout"><strong>Key idea:</strong> Never recycle the heating load as the cooling load. Different ΔT, plus solar and latent terms that winter never sees, make cooling its own calculation.</div><p>The solar asymmetry matters for equipment behavior as well: the cooling plant's hardest hour is a sunny late afternoon, while the heating plant's hardest hour is a clear cold night. A building is really two buildings — a night box and a sun box — and the load calculation is where both get described honestly.</p>` },
    { heading: "Solar Gain Through Glass", html: `<p>Sunlight through a window delivers energy in two steps: some is reflected and absorbed by the glass, and the transmitted portion lands on floors and furniture and becomes room heat. Real procedures fold glass type, shading, orientation, and hour into published factors. In this course, solar factors are always <em>given</em> in the problem, in Btu/h per square foot of glass, so the arithmetic stays honest:</p><div class="formula">Solar gain = given solar factor × glass area</div><p><strong>Worked example.</strong> West glass of 40 sq ft with a given late-afternoon factor of 150 Btu/h·sq ft gains 40 × 150 = 6,000 Btu/h at its peak hour. The same glass also conducts: at U = 0.50 and ΔT 20, that is 0.50 × 40 × 20 = 400 Btu/h. Solar outweighs conduction 15-to-1 for sunlit glass — the module in one comparison. Interior shading (blinds) and exterior shading (overhangs, trees) change the given factor dramatically, which is why the survey records shading honestly instead of assuming the favorable case.</p><p>North glass in northern latitudes receives mostly diffuse light and carries a much smaller factor; a designer who applies a west factor to every orientation overstates the block load and oversizes the plant — Module 5's penalties arriving early, wearing a solar disguise.</p><p>Shading cuts both ways seasonally: the overhang that trims July's west gain also trims January's welcome solar help. Designers note shading as found and let the annual picture emerge from the two seasonal calculations rather than optimizing one season by reflex.</p>` },
    { heading: "Internal Gains: The Building Heats Itself", html: `<p>People, lights, motors, and appliances convert energy into room heat. In cooling season every watt and every occupant is a small heater working against the air conditioner. Rates vary enormously with activity and equipment, so — as with solar factors — this course always <em>gives</em> internal-gain values in the problem rather than asking you to recall a table.</p><p><strong>Worked example.</strong> A teaching example gives: occupants contribute 250 Btu/h sensible and 200 Btu/h latent per person; a kitchen's appliances contribute a given 1,200 Btu/h sensible during the design hour. Four occupants plus the kitchen give sensible 4 × 250 + 1,200 = 2,200 Btu/h and latent 4 × 200 = 800 Btu/h. Note the split appearing naturally: people add both sensible and latent (breath and perspiration), most appliances add sensible only. Refrigerators deserve a survey note: their heat is real but their motors cycle, and real procedures treat such details with their own rules — the teaching point is that internal gains are <em>scheduled</em> (cooking hour ≠ sleeping hour), so the design hour must match the assumed activity.</p><div class="callout"><strong>Key idea:</strong> An empty, dark house and the same house during a dinner party are two different cooling loads. The load calculation designs for a stated, reasonable occupancy scenario — and says what it assumed.</div><p>Diversity applies inside this section too: the full appliance line-up rarely runs at once. The design scenario states which equipment is on at the design hour — a stated assumption, recorded with the calculation, not a silent hope.</p>` },
    { heading: "Sensible vs. Latent: The Split That Runs the Design", html: `<p>Every cooling load is two loads wearing one coat. The <strong>sensible</strong> part (conduction, solar, appliance heat, the temperature part of infiltration) lowers air temperature. The <strong>latent</strong> part is moisture: occupants, cooking, plants, and above all infiltrating or ventilating humid outdoor air, whose water vapor must be condensed out at the coil. Latent gain is computed from moisture differences, not temperatures — given humidity ratios and airflow, the latent rate follows the same bookkeeping as Module 1's moisture-removal example.</p><p><strong>Worked example.</strong> Ventilation air of 200 CFM enters at a given 105 grains and must be held at 55 grains indoors. Using standard air (≈ 4.5 lb/h per CFM at standard density in the total-heat factor's terms — here computed by mass): airflow mass = 200 CFM × 60 min × 0.075 lb/cu ft = 900 lb/h of dry air (0.075 is the stated standard-air density for this example). Moisture to remove = 900 × (105 − 55) ÷ 7,000 = 900 × 50 ÷ 7,000 ≈ 6.4 lb/h. At roughly 1,060 Btu per pound of condensed water (a stated teaching value in this example), latent load ≈ 6,800 Btu/h. Every input was given or stated — that is the standard you should hold any latent calculation to, including your own.</p><p>The total cooling load is then sensible + latent, and the sensible heat ratio follows: it will govern airflow (sensible side) and equipment latent capability (Module 5) simultaneously.</p>` },
    { heading: "Peaks, Blocks, and Rooms", html: `<p>A <strong>block load</strong> sums all rooms at one coincident hour — the worst hour for the whole building — and sizes the equipment. <strong>Room loads</strong> are computed at each room's own peak and size that room's airflow and outlet. The two totals legitimately differ: the sum of room peaks exceeds the block peak whenever rooms peak at different hours, because east rooms fade as west rooms flare. Using the room-peak sum to size the equipment oversizes it; using block shares to set room airflows starves the west bedroom at 5 p.m. Real procedures keep both books; this course's lab uses room loads for CFM and would use a block total for equipment.</p><p><strong>Worked example.</strong> Room peaks (sensible, given): east bedroom 3,000 (peaks 9 a.m.), living room 6,480 (peaks 3 p.m.), west bedroom 4,500 (peaks 6 p.m.). Sum of peaks = 13,980 Btu/h. At the building's block hour (3 p.m.), the east room has faded to a given 1,800 and the west room has risen only to 3,200, so block = 1,800 + 6,480 + 3,200 = 11,480 Btu/h. Equipment sized on 13,980 would be about 22% oversized for the coincident load — before any other error. Diversity is not a fudge factor; it is the arithmetic of clocks and compass points.</p><div class="callout"><strong>Key idea:</strong> Block load → equipment size. Room peak loads → room airflow. Mixing the two books is a classic, avoidable design error.</div>` },
  ],
  keyTerms: [{ term: "Heat gain", def: "The rate at which heat enters or is generated in a space at design conditions, in Btu/h." }, { term: "Solar gain", def: "Heat entering through glass from sunlight, depending on orientation, hour, glass, and shading." }, { term: "Solar factor (teaching value)", def: "A given Btu/h per sq ft figure bundling orientation, hour, and glass properties for a worked example." }, { term: "Internal gains", def: "Heat released inside the space by occupants, lights, and appliances." }, { term: "Sensible load", def: "The portion of cooling load that changes air temperature." }, { term: "Latent load", def: "The portion of cooling load that is moisture removal, driven by humidity-ratio differences." }, { term: "Design hour", def: "The hour at which the block (or a given room's) cooling load peaks." }, { term: "Diversity", def: "The reduction of a coincident block peak below the sum of individual room peaks because peaks occur at different times." }, { term: "Block cooling load", def: "Whole-building cooling load at its coincident peak hour; sizes equipment." }, { term: "Room peak load", def: "A single room's load at its own worst hour; sizes that room's airflow." }, { term: "Shading", def: "Interior or exterior devices and obstructions that reduce solar gain through glass." }, { term: "Orientation", def: "The compass direction a wall or window faces; sets its solar timing and size." }, { term: "Occupant gain", def: "Heat (sensible and latent) released by people, at rates that depend on activity." }, { term: "Appliance gain", def: "Heat released by equipment in the space; largely sensible." }, { term: "Infiltration gain", def: "Summer load from leaking outdoor air: sensible (hot) plus latent (humid)." }, { term: "Thermal storage effect", def: "The delay between solar energy entering a room and its appearance as air load, as mass absorbs and re-releases heat." }, { term: "Coincident peak", def: "The simultaneous total when all rooms are evaluated at the same hour." }, { term: "East/west glass", def: "Orientations with strong morning/afternoon solar peaks respectively; prime drivers of room peaks." }],
  video: { title: "Encapsulated vs. Conditioned Attic: HVAC Design Tricks to Get More Accuracy from Manual J Wrightsoft", embedUrl: "https://www.youtube.com/embed/zglA0txQimk", note: "A design-focused session on how attic construction choices change a Manual J result in Wrightsoft software. Watch how moving the thermal boundary changes the load — it is the clearest demonstration that a load calculation is only as honest as the building description fed into it.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A wall of 800 sq ft at U = 0.07 sees ΔT = 20°F in summer. Find its conduction gain and compare it with the same wall's winter loss at ΔT 70.</p>", solution: "<p><strong>Answer: 1,120 Btu/h summer vs 3,920 Btu/h winter.</strong> Step 1: Summer: 0.07 × 800 × 20 = 1,120. Step 2: Winter: 0.07 × 800 × 70 = 3,920. Step 3: Conduction alone would suggest a much smaller summer load — solar, internal, and latent gains are what close the gap.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> South glass of 30 sq ft has a given solar factor of 90 Btu/h·sq ft at the design hour. Find the solar gain, and add its conduction gain at U = 0.50, ΔT 20.</p>", solution: "<p><strong>Answer: solar 2,700; conduction 300; total 3,000 Btu/h.</strong> Step 1: 30 × 90 = 2,700. Step 2: 0.50 × 30 × 20 = 300. Step 3: Sum = 3,000 Btu/h. Solar is 90% of this window's gain.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Given per-person gains of 250 sensible / 200 latent Btu/h, find the total occupant gain for 5 people, split by type.</p>", solution: "<p><strong>Answer: sensible 1,250; latent 1,000; total 2,250 Btu/h.</strong> Step 1: 5 × 250 = 1,250 sensible. Step 2: 5 × 200 = 1,000 latent. Step 3: The latent share (44%) is why occupancy-heavy spaces challenge humidity control.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A room's gains are: conduction 1,500; solar 3,000; internal sensible 1,100; internal latent 800; infiltration latent 600 (all Btu/h, as given). Find total sensible, total latent, total load, and SHR.</p>", solution: "<p><strong>Answer: sensible 5,600; latent 1,400; total 7,000; SHR 0.80.</strong> Step 1: Sensible = 1,500 + 3,000 + 1,100 = 5,600. Step 2: Latent = 800 + 600 = 1,400. Step 3: Total = 7,000. Step 4: SHR = 5,600 ÷ 7,000 = 0.80.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Three rooms peak at different hours: A 4,000, B 5,000, C 3,500. At the 4 p.m. block hour their simultaneous loads are given as A 2,500, B 5,000, C 2,000. Find the sum of peaks, the block load, and the oversize if equipment were chosen from the sum.</p>", solution: "<p><strong>Answer: sum 12,500; block 9,500; oversize ≈ 32%.</strong> Step 1: Sum = 12,500. Step 2: Block = 2,500 + 5,000 + 2,000 = 9,500. Step 3: Excess = 3,000 ÷ 9,500 ≈ 32%.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Explain, with the numbers from Problem 2, why replacing clear west glass with shaded glass helps the cooling load far more than adding the same money to wall insulation in summer.</p>", solution: "<p><strong>Answer:</strong> Step 1: The window's gain is 3,000 Btu/h, of which 2,700 (90%) is solar — a shading-driven term. Step 2: Wall conduction for a big wall at summer ΔT 20 was only 1,120 Btu/h in Problem 1's scale, and insulation trims only a fraction of that fraction. Step 3: Attacking the dominant term (solar) beats trimming a minor term (summer conduction) — load-path ranking, again.</p>" },
  ],
  quiz: [
    { q: "Summer conduction through a wall is usually much smaller than its winter loss mainly because:", choices: ["U-factors change with season", "The summer design ΔT is much smaller than the winter design ΔT", "Walls stop conducting in summer", "Solar cancels conduction"], answer: 1, explanation: "Correct: (b). The example wall: ΔT 20 in summer vs 70 in winter, so gain 1,120 vs loss 3,920 Btu/h with the same U and A. (a) U is an assembly property, essentially season-independent here. (c) Conduction follows ΔT in either direction. (d) Solar adds its own separate gain; it does not cancel conduction." },
    { q: "Solar gain through sunlit glass compared with that glass's conduction gain is typically:", choices: ["Far smaller", "Roughly equal", "Far larger", "Zero"], answer: 2, explanation: "Correct: (c). The worked example: 6,000 Btu/h solar vs 400 Btu/h conduction for the same west glass. (a) and (b) contradict the factor arithmetic. (d) Sunlit glass always transmits solar energy." },
    { q: "Which gain is latent?", choices: ["Sunlight through glass", "Heat from a stove burner warming air", "Moisture released by occupants", "Conduction through a ceiling"], answer: 2, explanation: "Correct: (c). Occupants release water vapor that must be condensed at the coil — latent work. (a), (b), and (d) all raise temperature directly and are sensible gains." },
    { q: "A solar factor given as 150 Btu/h·sq ft applied to 40 sq ft of glass yields:", choices: ["190 Btu/h", "6,000 Btu/h", "3,750 Btu/h", "150 Btu/h"], answer: 1, explanation: "Correct: (b). 40 × 150 = 6,000 Btu/h. (a) adds instead of multiplying. (c) divides 150,000 by 40 — wrong operation and wrong inputs. (d) forgets the area entirely." },
    { q: "Diversity in cooling loads means:", choices: ["All rooms peak at the same hour", "The block peak is less than the sum of room peaks when peaks occur at different hours", "Designers may skip room calculations", "Loads can be averaged across seasons"], answer: 1, explanation: "Correct: (b). Non-coincident room peaks make the simultaneous total smaller than the sum of individual maxima. (a) is the opposite of diversity. (c) Room loads are still needed for airflow. (d) Seasons are never averaged in design." },
    { q: "Equipment should be sized from the:", choices: ["Sum of all room peaks", "Block load at the coincident design hour", "Largest single room load", "Heating load, doubled"], answer: 1, explanation: "Correct: (b). The plant serves the simultaneous whole-building peak. (a) double-counts hours that never coincide, oversizing the plant. (c) ignores every other room. (d) Heating and cooling loads are separate calculations." },
    { q: "Room airflow should be assigned from the:", choices: ["Block load divided by number of rooms", "Room's own peak load", "Equipment nameplate alone", "Window area only"], answer: 1, explanation: "Correct: (b). Each room's CFM follows its own peak so it holds temperature at its worst hour. (a) gives every room an equal share regardless of need. (c) Nameplate CFM is a total, not a distribution. (d) Windows matter to a room's load but are not the load." },
    { q: "Internal gains during the design hour depend most on:", choices: ["Wall color", "The stated occupancy and appliance scenario for that hour", "The furnace size", "Duct length"], answer: 1, explanation: "Correct: (b). People and appliances present at the design hour set the internal gain; the scenario must be stated. (a) Exterior color affects solar absorption of opaque surfaces marginally, not internal gains. (c) Furnace size is an output of the heating design, not an input here. (d) Ducts distribute air; they do not create internal gains." },
  ],
  studyGuide: `
<h3>Module 4 — Load Calculations II: Heat Gain: Quick Reference</h3>
<p><strong>Gain paths:</strong> conduction (U × A × ΔT, small summer ΔT) · solar through glass (given factor × area — usually the big term) · infiltration (sensible + latent) · internal gains (people: sensible + latent; appliances: mostly sensible).</p>
<p><strong>Always split the load:</strong> total = sensible + latent; SHR = sensible ÷ total. Airflow follows sensible; humidity control follows the split.</p>
<div class="formula">Solar gain = given factor (Btu/h·sq ft) × glass area</div>
<p><strong>Two books:</strong> block load at the coincident hour → equipment size. Room peak loads → room CFM. Sum of room peaks &gt; block peak whenever peaks are non-coincident (diversity).</p>
<p><strong>Orientation &amp; hour:</strong> east peaks morning, west peaks late afternoon; the design hour is whichever hour maximizes the block total.</p>
<p><strong>Watch out:</strong> reusing the heating load as the cooling load; applying one orientation's solar factor to all glass; inventing internal-gain rates instead of using stated values.</p>
<p><strong>One-line summary:</strong> summer load = small-ΔT conduction + solar (the giant) + internal gains + latent moisture work — computed separately from winter, split sensible/latent, and booked twice: block for equipment, room peaks for air.</p>
`
};
