// HVAC 245 - Module 6: Manual D: Duct Design
module.exports = {
  number: 6,
  slug: "manual-d-duct-design",
  title: "Manual D: Duct Design",
  estTime: "3–4 hours",
  objectives: ["Explain total external static pressure, available static pressure, and component pressure drops in the duct-design budget.", "Compute total effective length from given measured length and fitting equivalent lengths.", "Compute a design friction rate from available static pressure and total effective length.", "Allocate room CFM from room loads and state how trunk sections step down as branches leave.", "Explain why the friction-rate method sizes every section at one design friction rate."],
  sections: [
    { heading: "The Blower Has a Pressure Budget", html: `<p>A blower does not 'push CFM' into a house the way a pump fills a tank; it develops a pressure difference, and the duct system decides how much air that pressure can move. Every element the air crosses — coil, filter, supply ducts, registers, return ducts, grilles — spends some of that pressure. Duct design (ACCA Manual D territory in real practice) is budgeting: start with the blower's rated <strong>total external static pressure (TESP)</strong> at the design CFM, subtract the drops of the components that are not duct, and what remains is the <strong>available static pressure (ASP)</strong> the duct runs themselves may spend.</p><p><strong>Worked example (all values given).</strong> Blower rated at 0.80 in. w.c. TESP at design CFM. Component drops: wet coil 0.25, filter 0.10, supply register 0.03, return grille 0.02 — total 0.40. ASP = 0.80 − 0.40 = 0.40 in. w.c. That 0.40 is the entire allowance for friction in the longest duct path. Spend more and the blower delivers less than design CFM; spend far less and you bought bigger ducts than needed (not a failure, but a cost and space choice). Real jobs take component drops from manufacturer data; the arithmetic — budget minus components equals duct allowance — is the durable skill.</p><div class="callout"><strong>Key idea:</strong> Duct design starts at the blower's data plate, not at a duct chart. No ASP, no design.</div><p>Notice the budget's built-in fairness: every component spends from the same account, so an extravagant filter or a long duct run is paid for by everything else. Design arguments get shorter once all parties can see the one budget they share.</p>` },
    { heading: "Total Effective Length: Fittings Count as Feet", html: `<p>Straight duct resists air in proportion to its length, but fittings — elbows, takeoffs, tees, boots — resist far out of proportion to their size. The method converts each fitting into an <strong>equivalent length</strong> of straight duct that would cause the same drop, then adds everything along the longest complete path (supply side plus return side) into the <strong>total effective length (TEL)</strong>.</p><div class="formula">TEL = measured length (longest path) + Σ fitting equivalent lengths</div><p><strong>Worked example (equivalents given).</strong> Longest path measures 80 ft of straight duct. Fittings on that path, with given equivalent lengths: supply plenum takeoff 35 ft, two elbows at 15 ft each (30), branch takeoff 20 ft, register boot 10 ft, return grille 30 ft, return plenum entry 25 ft. Fitting sum = 35 + 30 + 20 + 10 + 30 + 25 = 150 ft. TEL = 80 + 150 = 230 ft. The fittings contribute almost twice the resistance of the straight duct — the normal case, and the reason 'the duct is only 80 feet' is never the design length. Real equivalent lengths come from the current procedure's fitting tables; here they are given so the method stays visible.</p><p>Design also works in reverse: a greedy fitting (a sharp takeoff where a smooth one fits) spends TEL you could have kept, so layout — fewer, gentler fittings — is design, not decoration.</p><p>When a path offers two fitting choices, the equivalent-length difference is the price tag of convenience. A takeoff moved two feet to allow a gentler elbow can repay its trouble in TEL many times over the system's life.</p>` },
    { heading: "The Friction Rate: Spending the Budget Evenly", html: `<p>With ASP and TEL known, the design <strong>friction rate</strong> spreads the available pressure evenly over the effective length:</p><div class="formula">Friction rate = ASP × 100 ÷ TEL &nbsp;(in. w.c. per 100 ft)</div><p><strong>Worked example.</strong> ASP = 0.40 in. w.c., TEL = 230 ft: FR = 0.40 × 100 ÷ 230 = 40 ÷ 230 ≈ 0.17 in. w.c. per 100 ft. Every duct section is then sized, using a friction chart or duct calculator (from the current procedure on real jobs), to lose pressure at that rate for its assigned CFM. A section carrying 300 CFM at FR 0.17 is a smaller duct than one carrying 300 CFM at FR 0.08 — the rate, not habit, sets the size. If the computed FR comes out very high, the honest responses are to shorten the path, smooth the fittings, raise the blower budget, or accept larger noise — not to quietly size at a friendlier rate and hope.</p><p>Sanity check with the lab: the lab worksheet's trunk carries 900 CFM. If that house's design FR were a given 0.10 per 100 ft, the trunk size would be read from the friction chart at 900 CFM and 0.10 — a chart lookup in real work, never a memorized diameter in this course.</p><div class="callout"><strong>Key idea:</strong> One FR for the whole system is what makes sections compatible: each spends pressure at the same rate, so the blower's budget balances at every branch.</div><p>Record the friction rate on the drawing, not just the sizes. A future modifier who knows the design FR can extend or rebalance intelligently; one who finds only diameters must reverse-engineer your entire budget before touching a duct.</p>` },
    { heading: "Trunks Step Down; Branches Take Their Share", html: `<p>Air leaves the trunk at every branch, so each successive trunk section carries less air and is sized smaller — at the same friction rate. <strong>Worked example.</strong> Total design airflow 900 CFM (the lab house). Branches leave in this order: living room 300, kitchen 250, bedroom 1 200, bedroom 2 150. Trunk sections: leaving the plenum 900; after the living room takeoff 900 − 300 = 600; after the kitchen 600 − 250 = 350; after bedroom 1, 350 − 200 = 150, which is the final branch itself. Each section is chart-sized at its own CFM and the common FR. A trunk that never steps down wastes material and can drop velocity so low at the far end that the last registers dribble; a trunk stepped down too aggressively starves downstream branches.</p><p>Branch ducts are sized the same way, at the branch's room CFM and the system FR, and the longest-path TEL already includes the worst branch's fittings — which is why the path chosen for TEL must be the genuinely longest route, supply plus return, not the most convenient one.</p><p>Return design mirrors supply with one emphasis: returns are chronically undersized in the field, and a starved return spends the budget before the supply side gets its share (the Step 0 safety point in the lab: return starvation also threatens furnace temperature rise). Give the return path the same TEL and FR discipline as the supply.</p><p>The same stepping logic protects the return side: a return trunk collecting several room returns grows toward the blower, section by section, each sized for what it carries. Undersized final return sections near the blower are a recurring field find — check them first in Module 11's work.</p>` },
    { heading: "From Worksheet to Installed Duct", html: `<p>The design product is a takeoff list: each section's CFM, size (from the friction chart at the design FR), length, and fittings — plus the room CFM schedule that Module 7 turns into registers and balancing. Field reality then audits the paper: flexible duct pulled slack or crushed adds resistance the worksheet never budgeted, kinked elbows multiply their equivalent length, and a filter upgraded to a much denser media spends ASP the components list never included. Module 11 returns to verification measurements; the design-side defense is margin honesty — budget the components you actually specified, at the airflow you actually designed.</p><p><strong>Worked example — a budget blown by one part.</strong> ASP was computed as 0.40 with a filter drop of 0.10. The installed premium filter's given drop at design CFM is 0.30. New ASP = 0.80 − (0.25 + 0.30 + 0.03 + 0.02) = 0.80 − 0.60 = 0.20. At the unchanged TEL of 230 ft, the honest FR becomes 0.20 × 100 ÷ 230 ≈ 0.09 — but the ducts were sized at 0.17. The installed system now cannot deliver design CFM; the symptom (weak airflow, long runtimes) will be diagnosed in the field, but the cause was created at a purchasing desk. Design the system you will actually install.</p><div class="callout"><strong>Key idea:</strong> Manual D's real product is a pressure budget that survives contact with real components and real installation. Keep the budget, the TEL, and the FR on one worksheet where changes force recalculation.</div>` },
  ],
  keyTerms: [{ term: "Total external static pressure (TESP)", def: "The pressure difference the blower is rated to work against at a given CFM, per its data." }, { term: "Available static pressure (ASP)", def: "TESP minus the pressure drops of non-duct components; the budget left for duct friction." }, { term: "Component pressure drop", def: "Pressure consumed by a coil, filter, register, or grille at a stated airflow." }, { term: "Equivalent length", def: "The length of straight duct that would cause the same pressure drop as a given fitting." }, { term: "Total effective length (TEL)", def: "Measured length of the longest path plus all its fittings' equivalent lengths." }, { term: "Friction rate (FR)", def: "Design pressure drop per 100 ft of effective length: ASP × 100 ÷ TEL." }, { term: "Friction chart / duct calculator", def: "The tool that converts a section's CFM and the design FR into a duct size." }, { term: "Trunk", def: "The main duct carrying air from the plenum toward the branches; stepped down as branches leave." }, { term: "Branch", def: "A duct serving one room or outlet, sized at that room's CFM." }, { term: "Plenum", def: "The air chamber at the blower outlet (or return inlet) from which trunks or branches take off." }, { term: "Takeoff", def: "The fitting where a branch or trunk leaves a larger duct or plenum." }, { term: "Register boot", def: "The fitting connecting a branch duct to a supply register." }, { term: "Longest path", def: "The supply-plus-return route with the greatest total effective length; governs the FR budget." }, { term: "Return duct", def: "The duct path bringing air back to the blower; undersizing it starves the whole system." }, { term: "Static pressure", def: "Pressure exerted equally in all directions in the duct, measured in inches of water column." }, { term: "Velocity", def: "Air speed in a duct (fpm); rises as size shrinks for the same CFM, bringing noise with it." }, { term: "Balancing damper", def: "An adjustable plate in a branch used to trim its airflow to the design CFM." }, { term: "Flex duct", def: "Flexible duct whose installed resistance depends heavily on being pulled tight and supported." }],
  video: { title: "HVAC Duct Design: Manual D, Fittings, Friction Rate, Pressure Loss, & Static Pressure w/ Alex Meaney", embedUrl: "https://www.youtube.com/embed/Bq9yTn31qRw", note: "A deep dive on duct design calculations with a design trainer: friction rate, fittings, pressure loss, and static pressure, comparing the Manual D approach with the ASHRAE approach. This is the module's core method shown at full professional depth; our worked examples use the same steps with rounder teaching numbers.", more: [{ title: "Duct Design for Great Results w/ Ed Janowiak (ACCA)", url: "https://www.youtube.com/watch?v=-KqmAQgUXY4" }] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Blower TESP at design CFM (given): 0.70 in. w.c. Components (given): coil 0.20, filter 0.08, register 0.03, grille 0.02. Find ASP.</p>", solution: "<p><strong>Answer: 0.37 in. w.c.</strong> Step 1: Component sum = 0.20 + 0.08 + 0.03 + 0.02 = 0.33. Step 2: ASP = 0.70 − 0.33 = 0.37 in. w.c.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A longest path measures 60 ft. Fitting equivalent lengths (given): 30, 15, 15, 20, 25 ft. Find TEL.</p>", solution: "<p><strong>Answer: 165 ft.</strong> Step 1: Fittings sum = 30 + 15 + 15 + 20 + 25 = 105. Step 2: TEL = 60 + 105 = 165 ft.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> ASP is 0.33 in. w.c. and TEL is 165 ft. Find the design friction rate.</p>", solution: "<p><strong>Answer: 0.20 in. w.c. per 100 ft.</strong> Step 1: FR = ASP × 100 ÷ TEL = 33 ÷ 165 = 0.20. Step 2: Every section is then sized at this rate for its own CFM.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A trunk starts at 1,200 CFM. Branches leave in order: 400, 300, 300, 200. List each trunk section's CFM.</p>", solution: "<p><strong>Answer: 1,200 → 800 → 500 → 200.</strong> Step 1: 1,200 − 400 = 800. Step 2: 800 − 300 = 500. Step 3: 500 − 300 = 200, which equals the last branch — the trunk ends there.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A system's ASP is 0.50 and TEL is 250 ft, giving FR = 0.20. A redesign removes fittings worth 50 ft of equivalent length. Find the new TEL and FR, and state what the change permits.</p>", solution: "<p><strong>Answer: TEL 200 ft; FR 0.25.</strong> Step 1: TEL = 250 − 50 = 200. Step 2: FR = 0.50 × 100 ÷ 200 = 0.25. Step 3: The smoother layout permits smaller ducts at the same budget — or the designer may keep sizes and bank the margin as lower noise and better delivered CFM.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> An installer swaps the specified filter (drop 0.10) for one with a given drop of 0.35 at design CFM, in a system whose TESP is 0.80 and other components total 0.30. Compute ASP before and after, and explain the field symptom.</p>", solution: "<p><strong>Answer: ASP 0.40 → 0.15.</strong> Step 1: Before: 0.80 − (0.30 + 0.10) = 0.40. Step 2: After: 0.80 − (0.30 + 0.35) = 0.15. Step 3: The ducts were sized to spend 0.40; with only 0.15 available, delivered CFM falls — weak airflow at registers, long runtimes, possible coil icing in cooling or high temperature rise in heating.</p>" },
  ],
  quiz: [
    { q: "Available static pressure is:", choices: ["The blower's TESP", "TESP minus non-duct component drops", "The friction rate", "Static pressure at one register"], answer: 1, explanation: "Correct: (b). ASP is what remains for duct friction after coil, filter, and terminal devices spend their shares. (a) TESP is the whole budget before components. (c) FR is derived from ASP and TEL. (d) A local reading is a measurement, not the design budget." },
    { q: "TEL includes:", choices: ["Only straight duct length", "Measured length plus fitting equivalent lengths along the longest path", "Every duct in the building added together", "The return path only"], answer: 1, explanation: "Correct: (b). The longest supply-plus-return path, with fittings converted to equivalent feet, sets the resistance the blower must beat. (a) ignores fittings, usually the larger share. (c) sums parallel paths as if they were in series. (d) omits the supply half." },
    { q: "With ASP 0.45 and TEL 150 ft, the friction rate is:", choices: ["0.03 per 100 ft", "0.30 per 100 ft", "3.00 per 100 ft", "0.45 per 100 ft"], answer: 1, explanation: "Correct: (b). FR = 0.45 × 100 ÷ 150 = 45 ÷ 150 = 0.30 in. w.c. per 100 ft. (a) divides by 1,500. (c) multiplies instead of dividing. (d) just repeats ASP without the TEL step." },
    { q: "All duct sections are sized at the same design friction rate so that:", choices: ["Every duct is the same size", "Each path spends pressure at the same rate and the budget balances", "Fittings become unnecessary", "Velocity is identical everywhere"], answer: 1, explanation: "Correct: (b). A common FR makes parallel paths compatible with one blower budget. (a) Sizes differ because CFM differs. (c) Fittings still exist and are counted in TEL. (d) Velocity varies with size choices; pressure rate is the constant." },
    { q: "A trunk's sections step down in size along its run because:", choices: ["Duct material gets cheaper", "Each section carries less CFM after branches take their shares", "Friction rate increases downstream", "Returns join the trunk"], answer: 1, explanation: "Correct: (b). Section CFM falls by each branch's amount, and the section is sized for what it actually carries at the design FR. (a) Cost is incidental. (c) FR is held constant by design. (d) Returns are a separate path." },
    { q: "Fittings' equivalent lengths in a typical design:", choices: ["Are negligible", "Often exceed the straight-duct length of the path", "Apply only to elbows", "Are measured in CFM"], answer: 1, explanation: "Correct: (b). In the worked example, 150 ft of fittings vs 80 ft of straight duct. (a) is the classic beginner error. (c) Takeoffs, tees, boots, and grilles all carry equivalents. (d) Equivalent length is measured in feet." },
    { q: "If a much denser filter is installed without redesigning, the expected result is:", choices: ["More airflow", "Less delivered CFM and higher system resistance", "Lower static pressure", "No change — filters are free"], answer: 1, explanation: "Correct: (b). The filter spends more of a fixed blower budget, leaving less for ducts sized on the old ASP. (a) is backwards. (c) Total resistance rises, not falls. (d) Every component spends pressure; the budget proves it." },
    { q: "The path used for TEL must be:", choices: ["The shortest route", "The longest supply-plus-return route", "Any convenient branch", "The route with the fewest registers"], answer: 1, explanation: "Correct: (b). The blower must serve the worst path; sizing to a shorter path starves the longest one. (a) and (c) understate resistance. (d) Register count is not the criterion — effective length is." },
  ],
  studyGuide: `
<h3>Module 6 — Manual D: Duct Design: Quick Reference</h3>
<div class="formula">ASP = TESP − Σ component drops · TEL = measured longest path + Σ fitting equivalents · FR = ASP × 100 ÷ TEL</div>
<p><strong>Sequence:</strong> blower data at design CFM → subtract components → ASP → survey longest path and fittings → TEL → FR → size every section at its CFM and the common FR (chart/calculator from the current procedure on real jobs).</p><p><strong>Trunks</strong> step down as branches leave: section CFM = previous CFM − branch CFM. <strong>Branches</strong> are sized at room CFM. <strong>Returns</strong> get the same discipline — undersized returns starve everything.</p>
<p><strong>Fittings dominate:</strong> equivalent lengths commonly exceed straight length; smoother layout is real design margin.</p>
<p><strong>Watch out:</strong> component swaps (dense filters) silently spending ASP; sizing to a short path; flex duct installed slack adding unbudgeted resistance.</p>
<p><strong>Field translation:</strong> on an existing system, the same three formulas run in reverse — measure TESP, subtract known component drops, and the remainder tells you what the installed ducts are actually spending; a TEL far above the design value points at crushed or added fittings before it points at the blower.</p>
`
};
