// HVAC 245 - Module 8: Ventilation & Applicable Codes
module.exports = {
  number: 8,
  slug: "ventilation-and-applicable-codes",
  title: "Ventilation & Applicable Codes",
  estTime: "3–4 hours",
  objectives: ["Explain why ventilation is a designed system, not an accident of leakage, in modern tight construction.", "Distinguish supply, exhaust, and balanced ventilation strategies and where each fits.", "Compute a simple whole-house ventilation rate from given per-person and per-area components.", "Describe kitchen exhaust design concepts: capture at the source, make-up air, and why restaurant hoods are a specialty.", "Name where applicable requirements actually come from and the designer's duty to verify the current adopted code."],
  sections: [
    { heading: "Ventilation on Purpose", html: `<p>Older houses ventilated by accident: leaky envelopes diluted indoor pollutants with uncontrolled outdoor air — at an energy cost Module 3 priced as infiltration load. Modern construction seals the envelope for efficiency, which removes the accident and creates the obligation: ventilation must now be <strong>provided deliberately, at a controlled rate, in the right places</strong>. Ventilation dilutes pollutants the building and occupants generate (moisture, odors, cooking byproducts, off-gassing), and it does so at a rate the designer chooses and the equipment enforces — unlike infiltration, which over-ventilates on windy nights and under-ventilates on calm ones.</p><p>The design questions are always the same four: How much air? From where (which rooms get exhaust, which get supply)? By what strategy (exhaust-only, supply-only, balanced)? And with what energy consequence (Module 10's recovery ventilators exist to answer this one)? Applicable standards and the locally adopted code set the required rates and methods for a real project — this module teaches the structure and the arithmetic pattern with given rates; the numbers for a real building come from the current adopted requirements for that building, verified by the designer.</p><div class="callout"><strong>Key idea:</strong> Tighten the envelope, then ventilate on purpose. 'Build tight, ventilate right' is a pair — either half alone fails.</div>` },
    { heading: "Three Strategies: Exhaust, Supply, Balanced", html: `<p><strong>Exhaust-only</strong> systems use fans (often the bath/kitchen fans, or a central exhaust fan) to pull air out; replacement air infiltrates through the envelope. Simple and cheap, but the incoming air is unfiltered, undistributed, and the house runs slightly depressurized. <strong>Supply-only</strong> systems push outdoor air in (often through the air handler with a controlled damper); the house runs slightly pressurized, incoming air can be filtered, but exfiltration through the envelope can push moist indoor air into wall cavities in cold weather. <strong>Balanced</strong> systems move equal air in and out with dedicated equipment — the natural partner for heat/energy recovery (Module 10) — keeping pressures near neutral and both streams controlled.</p><p><strong>Worked comparison.</strong> A given design rate of 60 CFM continuous: exhaust-only spends fan energy only; supply-only spends fan energy and conditions incoming air at the coil; balanced with a given 70% sensible recovery (Module 10's arithmetic) pre-tempers the incoming stream and cuts the conditioning penalty by roughly that fraction of the temperature-driven part. Strategy choice is climate- and building-driven: moisture risk in assemblies, pollutant sources outdoors, and pressure-sensitive appliances (a depressurized house with a naturally vented water heater deserves the same caution as the lab's Step 0 combustion-air check).</p><div class="callout"><strong>Key idea:</strong> Pressure is a design output. Know which way your strategy pushes, and what (appliances, cavities) lives on the other side of that pressure.</div>` },
    { heading: "Sizing the Rate: People Plus Area (Pattern)", html: `<p>Residential ventilation rates in modern standards are commonly built from two parts: a component for the building's size (diluting building-source pollutants) and a component for its occupants (diluting people-source pollutants). The exact factors belong to the current standard and adopted code; the <em>pattern</em> is what this course teaches, with given factors:</p><div class="formula">Ventilation rate = (given rate per sq ft × floor area) + (given rate per person × design occupants)</div><p><strong>Worked example (factors given for this example).</strong> Area component 0.03 CFM per sq ft; occupant component 7.5 CFM per person. House: 1,800 sq ft, design occupancy 4. Rate = 0.03 × 1,800 + 7.5 × 4 = 54 + 30 = 84 CFM continuous-equivalent. If the selected fan runs intermittently at a given 140 CFM, the duty fraction to average 84 CFM is 84 ÷ 140 = 0.60 — the fan runs about 60% of each hour (or an equivalent cycle the controls allow). Every number here is a stated example value; the takeaway is the two-part structure and the averaging arithmetic, which you will meet again in every ventilation standard you open.</p><p>Local exhaust is separate from whole-house dilution: baths and kitchens need source capture at higher rates during use, addressed next.</p><p>Intermittent operation has a distribution footnote: a cycled fan should still run long enough per cycle to actually exchange air in the far rooms, and controls that track cumulative runtime keep the average honest across weather and occupancy swings.</p>` },
    { heading: "Kitchen and Restaurant Exhaust Concepts", html: `<p>Cooking generates heat, moisture, grease, and combustion byproducts at one point — the range — so kitchen ventilation is a <strong>capture</strong> problem, not a dilution problem. A range hood's job is to catch the rising plume before it escapes into the room; capture depends on hood size relative to the range, mounting height, and airflow, and a hood that is too small or too high fails at any CFM. Residential design coordinates hood exhaust with <strong>make-up air</strong>: large exhaust flows depressurize a tight house (pulling the Step 0 venting concern back into view), so bigger residential hoods trigger make-up-air provisions in applicable codes — again, verified from the current adopted code, not from memory.</p><p>Commercial kitchens scale the same physics into a specialty: Type I hoods over grease-producing appliances, engineered capture rates, grease duct construction, fire suppression integration, and make-up air often nearly equal to exhaust, temperately supplied so the kitchen does not freeze or swelter. <strong>Worked concept example (values given).</strong> A small commercial line exhausts a given 2,400 CFM and its make-up unit supplies 2,000 CFM; the remaining 400 CFM transfers from the dining area, keeping the kitchen negative to the dining room (odors stay in the kitchen) while the building as a whole stays near neutral. The design lesson generalizes: exhaust without a planned replacement path is not a system, it is a leak with a motor.</p><div class="callout"><strong>Key idea:</strong> Every CFM exhausted must be a CFM replaced — by design, from a chosen source, at a chosen condition.</div>` },
    { heading: "Codes and Standards: Where Requirements Actually Live", html: `<p>Designers answer to a stack of authorities, and knowing <em>which document governs what</em> is itself a design skill. Building and mechanical <strong>codes</strong> are law as adopted (and amended) by the local jurisdiction — they set minimums for ventilation, combustion air, venting, and installation. <strong>Standards</strong> from bodies such as ASHRAE (ventilation and energy) and ACCA (design procedures: Manual J for loads, S for selection, D for ducts) become binding when a code or contract references them. <strong>Manufacturer instructions</strong> govern the listed equipment and are enforceable through the listing. When documents appear to conflict, the designer's duty is to satisfy the most stringent applicable requirement and to confirm interpretations with the local authority having jurisdiction (AHJ).</p><p>Two disciplines follow. First, <strong>currency</strong>: codes and standards revise on cycles, so a rate or rule recalled from an old job — or from a course — is a lead to verify, never an answer; that is why this course gives rates in problems instead of teaching a table. Second, <strong>scope</strong>: this course's programs prepare you toward industry certifications such as EPA 608 and NATE, which are separate from state and local licensing; licensing for HVAC work varies by state and sometimes by city or county, and no course certificate substitutes for a required license. Design competence and legal permission are different documents — a professional holds both.</p><div class="callout"><strong>Key idea:</strong> The code book on the shelf, as adopted where the building stands, outranks every memory, habit, and course example — including this one.</div>` },
  ],
  keyTerms: [{ term: "Ventilation", def: "The deliberate introduction of outdoor air (and exhaust of indoor air) at controlled rates for indoor air quality." }, { term: "Dilution", def: "Reducing indoor pollutant concentration by mixing with cleaner outdoor air." }, { term: "Exhaust-only ventilation", def: "Strategy exhausting air mechanically while replacement air infiltrates; house runs slightly negative." }, { term: "Supply-only ventilation", def: "Strategy supplying outdoor air mechanically; house runs slightly positive." }, { term: "Balanced ventilation", def: "Strategy moving equal supply and exhaust flows mechanically; near-neutral pressure, recovery-ready." }, { term: "Continuous rate", def: "The average ventilation rate maintained over time, whether by constant or cycled operation." }, { term: "Design occupancy", def: "The number of occupants assumed for sizing ventilation and internal gains." }, { term: "Source capture", def: "Removing a pollutant at its point of generation, as a range hood does, before it mixes into room air." }, { term: "Make-up air", def: "Replacement air deliberately supplied to offset exhaust airflow." }, { term: "Type I hood", def: "A commercial kitchen hood for grease-producing appliances, with grease-rated duct and fire protection provisions." }, { term: "Authority having jurisdiction (AHJ)", def: "The local official or body that interprets and enforces the adopted code." }, { term: "Adopted code", def: "The edition of a model code enacted (possibly amended) by the local jurisdiction — the legally binding version." }, { term: "Standard", def: "A published technical requirement (e.g., ventilation or energy) that becomes binding when referenced by code or contract." }, { term: "Listing", def: "A manufacturer's certified product approval; installation must follow the listed instructions." }, { term: "Depressurization", def: "Indoor pressure below outdoor, caused by exhaust exceeding supply; can disturb natural venting of fuel appliances." }, { term: "Local exhaust", def: "Higher-rate exhaust at pollutant sources such as baths and kitchens, separate from whole-house dilution ventilation." }, { term: "Intermittent operation", def: "Running a larger fan part-time to average a required continuous rate." }, { term: "Combustion air", def: "Air required by fuel-burning appliances for safe burning and venting; a code-governed design input." }],
  video: { title: "HRV vs. ERV - What's the Difference?", embedUrl: "https://www.youtube.com/embed/wl8sH2I1DUM", note: "A clear comparison of heat recovery and energy recovery ventilators: how each core works, why HRVs transfer heat only while ERVs transfer heat and moisture, and which climates each suits. It frames this module's ventilation discussion and Module 10's recovery design.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Using given factors of 0.03 CFM/sq ft and 7.5 CFM/person, find the ventilation rate for a 2,000 sq ft home with design occupancy of 5.</p>", solution: "<p><strong>Answer: 97.5 CFM.</strong> Step 1: Area part = 0.03 × 2,000 = 60. Step 2: People part = 7.5 × 5 = 37.5. Step 3: Total = 60 + 37.5 = 97.5 CFM.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A fan rated (given) 150 CFM must average 90 CFM continuous-equivalent. What duty fraction is required, and what is that in minutes per hour?</p>", solution: "<p><strong>Answer: 0.60 — about 36 minutes per hour.</strong> Step 1: 90 ÷ 150 = 0.60. Step 2: 0.60 × 60 = 36 min/h on average.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A tight house has a large range hood and a naturally vented water heater. The hood runs with no make-up air provision. Name the pressure condition created and the appliance risk it raises.</p>", solution: "<p><strong>Answer:</strong> Step 1: Exhaust with no planned replacement depressurizes the house. Step 2: Negative pressure can oppose the natural draft of the water heater's vent, risking spillage of flue gases (including carbon monoxide) into the space. Step 3: This is the same mechanism behind the lab's Step 0 combustion-air warning; the design fix is coordinated make-up air and code verification.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A small café kitchen exhausts a given 1,800 CFM. Its make-up unit supplies 1,500 CFM at the kitchen; the rest transfers from the dining room. How much transfers, and why is the kitchen kept slightly negative to dining?</p>", solution: "<p><strong>Answer: 300 CFM transfers.</strong> Step 1: 1,800 − 1,500 = 300. Step 2: Kitchen-negative means air drifts dining → kitchen, so cooking odors and heat are carried toward the hood instead of into the seating area.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Compare exhaust-only, supply-only, and balanced strategies on two axes: pressure effect and incoming-air control.</p>", solution: "<p><strong>Answer:</strong> Step 1: Exhaust-only — house negative; incoming air uncontrolled (leaks, unfiltered). Step 2: Supply-only — house positive; incoming air filtered and located, but moist air can be pushed into cavities in cold weather. Step 3: Balanced — near neutral; both streams controlled and filterable, and recovery equipment can temper the incoming stream.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A designer recalls a ventilation rate 'from the last job' and applies it without checking. List what could be wrong with that number.</p>", solution: "<p><strong>Answer:</strong> Step 1: It may come from a superseded edition — codes/standards revise on cycles. Step 2: The other job's jurisdiction may have amended the model code differently. Step 3: The buildings may differ in occupancy, sources, or applicable scope. Step 4: The professional step is verifying the current adopted requirement for this building with the AHJ where needed — course examples and memories are leads, not authorities.</p>" },
  ],
  quiz: [
    { q: "'Build tight, ventilate right' means:", choices: ["Seal the envelope and rely on leaks for air", "Seal the envelope and provide deliberate, controlled ventilation", "Ventilate by opening windows on a schedule", "Tight buildings need no ventilation"], answer: 1, explanation: "Correct: (b). Airtight construction removes accidental ventilation, so controlled ventilation must replace it. (a) contradicts the tightening half. (c) Windows are uncontrolled and weather-dependent. (d) is the dangerous opposite of the principle." },
    { q: "A balanced ventilation system is characterized by:", choices: ["Exhaust only", "Supply only", "Mechanically moved supply and exhaust in roughly equal amounts", "No fans at all"], answer: 2, explanation: "Correct: (c). Balanced systems control both streams and hold near-neutral pressure — the recovery-ventilator configuration. (a) and (b) are the one-sided strategies. (d) describes passive leakage, not a system." },
    { q: "With given factors 0.03 CFM/sq ft and 7.5 CFM/person, a 1,500 sq ft, 3-person home needs:", choices: ["45 CFM", "67.5 CFM", "22.5 CFM", "90 CFM"], answer: 1, explanation: "Correct: (b). 0.03 × 1,500 = 45; 7.5 × 3 = 22.5; total 67.5 CFM. (a) is the area part alone. (c) is the people part alone. (d) misapplies the factors." },
    { q: "Make-up air is:", choices: ["Air supplied to replace exhausted air by design", "Extra air from envelope leaks", "Air stored in the ducts", "A type of filter"], answer: 0, explanation: "Correct: (a). Make-up air is the planned replacement stream that keeps pressures and capture working. (b) Leaks are the unplanned path a design should not depend on. (c) Ducts store no meaningful air. (d) Filters clean air; they do not supply it." },
    { q: "A large kitchen hood in a tight house without make-up air most risks:", choices: ["Overcooling the kitchen", "Depressurizing the house and disturbing natural appliance venting", "Raising humidity outdoors", "Silencing the hood"], answer: 1, explanation: "Correct: (b). Strong exhaust against a sealed envelope drives the house negative, which can oppose draft and spill flue gases. (a) Exhaust removes kitchen heat — the opposite complaint. (c) Outdoor humidity is unaffected. (d) Noise is not the safety issue here." },
    { q: "The legally binding ventilation requirement for a project comes from:", choices: ["This course's examples", "The code as adopted by the local jurisdiction (with referenced standards)", "The oldest edition anyone owns", "The equipment brochure"], answer: 1, explanation: "Correct: (b). Adoption by the jurisdiction makes a code law; referenced standards ride along. (a) Course numbers are stated teaching values. (c) Superseded editions do not govern. (d) Manufacturer instructions govern the equipment's installation, not the building's ventilation rate." },
    { q: "Local bath/kitchen exhaust differs from whole-house ventilation in that it is:", choices: ["Unnecessary in tight houses", "Source capture at higher rates during use", "Always balanced", "Only for commercial buildings"], answer: 1, explanation: "Correct: (b). Spot exhaust removes pollutants at generation points, intermittently and at higher rates; whole-house ventilation dilutes continuously at lower rates. (a) Tight houses need it most. (c) Local exhaust is usually exhaust-only at the device. (d) Homes have it in every bath and kitchen." },
    { q: "State/local HVAC licensing, compared with industry certifications like NATE or EPA 608:", choices: ["Is the same thing", "Is separate, varies by jurisdiction, and is not replaced by a certification", "Is granted by NATE", "Expires with the EPA card"], answer: 1, explanation: "Correct: (b). Certifications attest knowledge; licensing is legal permission, set by state/local law and varying widely. (a) They are different instruments. (c) NATE certifies technicians; it does not license. (d) EPA 608 certification does not expire, and licensing cycles are their own." },
  ],
  studyGuide: `
<h3>Module 8 — Ventilation &amp; Applicable Codes: Quick Reference</h3>
<p><strong>Principle:</strong> tight envelope + deliberate ventilation. Rates are structured (pattern): area component + occupant component, from the <em>current adopted</em> requirements — course problems always give the factors.</p>
<div class="formula">Rate = (given CFM/sq ft × area) + (given CFM/person × occupants) · Duty fraction = required average ÷ fan CFM</div>
<p><strong>Strategies:</strong> exhaust-only (negative house, uncontrolled inlet) · supply-only (positive house, filtered inlet) · balanced (neutral, both streams controlled, recovery-ready).</p>
<p><strong>Kitchens:</strong> capture at the source; every exhausted CFM must be replaced by design; large hoods + tight envelopes + natural-draft appliances = depressurization hazard (see Lab Step 0). Commercial hoods are an engineered specialty with make-up air near exhaust volume.</p>
<p><strong>Authority stack:</strong> adopted local code (law) → referenced standards (ASHRAE, ACCA procedures) → manufacturer listing instructions. Verify current editions with the AHJ. Licensing is separate from certification and varies by jurisdiction.</p>
<p><strong>One-line summary:</strong> decide the rate from the current adopted requirement, choose the strategy by its pressure and control consequences, and account for every exhausted CFM's replacement path.</p>
`
};
