// HVAC 245 - Module 9: Humidity Control by Design
module.exports = {
  number: 9,
  slug: "humidity-control-by-design",
  title: "Humidity Control by Design",
  estTime: "3–4 hours",
  objectives: ["Explain why humidity is controlled by design decisions (load split, equipment SHR, runtime, envelope, ventilation) rather than by a thermostat setting alone.", "Compute a humidification load from given airflow and humidity-ratio change.", "Compute a dehumidification requirement in pounds per hour from given values.", "Compare humidity equipment choices: cooling-coil dehumidification, dedicated dehumidifiers, steam/resistive and evaporative humidifiers, in energy terms.", "Identify design moves that prevent humidity problems instead of treating them."],
  sections: [
    { heading: "Humidity Is a Design Output", html: `<p>Indoor humidity is not a dial setting; it is the result of sources, sinks, and runtime. Sources: occupants, cooking, bathing, plants, unvented combustion, and moisture carried in by ventilation and infiltration. Sinks: the cooling coil (only while it runs and only while its surface is below the dew point), dedicated dehumidifiers, and dry winter air exchange. The designer's levers are mostly upstream: a tight envelope (less humid infiltration), right-sized equipment (long coil runtime), an honest latent load in the calculation (Module 4), and ventilation with recovery (Module 10, which keeps much of the moisture outside in summer or inside in winter, as desired).</p><p><strong>Worked diagnosis.</strong> A house holds 75°F but feels clammy at a measured 65% RH on mild rainy days. The system is grossly oversized (Module 5): on mild days the small sensible load is met in short bursts, the coil barely wets, and latent removal collapses while moisture sources continue. The thermostat reports success; the psychrometrics report failure. Fixes follow the levers: right-size at replacement, verify airflow and charge so the coil runs cold enough, seal the envelope leaks feeding humid air, and consider a dedicated dehumidifier for the shoulder seasons when sensible load nearly vanishes but moisture does not.</p><div class="callout"><strong>Key idea:</strong> If the latent load was never calculated, its failure will be diagnosed as a comfort complaint. Design counts moisture in Btu and pounds, not in adjectives.</div>` },
    { heading: "Humidification Load: Winter's Mirror Problem", html: `<p>Winter air arrives dry and heating drops its RH further (Module 2's horizontal move). Holding a target indoor humidity ratio against a leaky or ventilated envelope requires adding water at the rate it is lost. The bookkeeping is Module 1's moisture arithmetic aimed the other way:</p><div class="formula">Water to add (lb/h) = airflow (lb dry air/h) × (target grains − incoming grains) ÷ 7,000</div><p><strong>Worked example (values given).</strong> Ventilation plus infiltration totals 150 CFM. Convert to mass with the stated standard density 0.075 lb/cu ft: 150 × 60 × 0.075 = 675 lb dry air/h. Incoming air is given at 15 grains; the indoor target is 55 grains. Water required = 675 × (55 − 15) ÷ 7,000 = 675 × 40 ÷ 7,000 ≈ 3.9 lb/h — roughly 11 gallons per day if run continuously at design dryness (3.9 × 24 ÷ 8.3 lb per gallon ≈ 11.2). That number sizes the humidifier and predicts its water and energy appetite before it is purchased.</p><p>Restraint is part of the design: pushing indoor humidity too high in cold weather drives condensation inside wall cavities and on windows (the dew-point lesson from Module 1, now happening inside the assembly). The target is a balance between occupant comfort, building durability, and applicable guidance — another value the designer verifies rather than assumes.</p><p>Water quality and maintenance ride along with humidification design: mineral-heavy water shortens evaporative media life and can dust ducts from some atomizing types, so the selected technology must match the home's water and the owner's willingness to service it — stated in the design notes, not discovered in year two.</p>` },
    { heading: "Dehumidification Load and Equipment SHR", html: `<p>Summer moisture removal is the coil's second job, and Module 5's three-check selection is where it is won or lost: the unit's latent capacity at design conditions must meet the latent load, and its SHR behavior across part-load conditions decides the rainy-day outcome. The load side is computed exactly like the humidifier case with the sign flipped.</p><p><strong>Worked example (values given).</strong> Outdoor design air at 105 grains must be held at 55 grains indoors; total outdoor-air-driven flow (ventilation + infiltration) is 250 CFM = 250 × 60 × 0.075 = 1,125 lb dry air/h. Moisture to remove from that stream = 1,125 × 50 ÷ 7,000 ≈ 8.0 lb/h. Using the stated latent heat of condensation ≈ 1,060 Btu/lb, that stream alone represents ≈ 8,500 Btu/h of latent load — before occupants and cooking add theirs. A selected unit whose design latent capacity is 7,000 Btu/h fails this building on paper, however impressive its total tonnage looks.</p><p>Airflow is a humidity lever, too: within manufacturer limits, somewhat lower coil airflow deepens moisture removal per pass (colder coil, more condensation) at some sensible-capacity cost — a trade the manufacturer's data, not folklore, quantifies. Designers state the chosen airflow with the selection for exactly this reason.</p><div class="callout"><strong>Key idea:</strong> Latent capacity is a number on the same footing as tonnage. 'Total capacity met' with latent unmet is a failed selection (Module 5, Problem 2).</div>` },
    { heading: "Equipment Choices for Humidity", html: `<p><strong>Cooling coil (standard):</strong> no extra appliance; dehumidifies only while cooling runs, so shoulder seasons and mild humid days expose its limit. <strong>Dedicated dehumidifier:</strong> removes moisture independent of cooling, returning its heat to the space (slightly warming it) — the right tool for basements, tight houses, and humid climates with long mild seasons. <strong>Ventilating dehumidifier:</strong> combines the dehumidifier with controlled outdoor air. On the winter side: <strong>evaporative (bypass/powered) humidifiers</strong> use the furnace's heat to evaporate water — cheap energy per pound, dependent on heating runtime; <strong>steam humidifiers</strong> boil water electrically regardless of heating runtime — precise control at a higher energy cost per pound.</p><p><strong>Worked energy comparison (values given).</strong> Adding 4 lb/h of water: a steam unit drawing a given 1.2 kW for that output uses 1.2 kWh per hour of operation. An evaporative unit on the furnace uses the heat already being generated, adding mainly fan and water costs — but stops adding moisture whenever the furnace rests, so a house with long off-cycles may never reach target on the coldest, windiest design night without supplemental capacity. The professional choice weighs duty cycle and control, not slogans: state the required lb/h (Section 2), check each candidate's given output and input at design conditions, and select like any other equipment in this course.</p><p>Safety and maintenance belong in the selection too: humidifiers and dehumidifiers involve water, drains, and filters; a design without a condensate plan and service access is a leak and a mold farm in waiting.</p>` },
    { heading: "Prevention Beats Treatment", html: `<p>The cheapest humidity control is the moisture that never enters. Design prevention list, in load order: <strong>envelope</strong> — seal the leaks Module 3 priced, so humid infiltration shrinks before equipment is sized; <strong>source exhaust</strong> — vent baths and range hoods outdoors (never into attics), capturing moisture at generation (Module 8); <strong>ground and drainage</strong> — keep bulk water away from foundations so basements stop feeding the house moisture through slabs and walls; <strong>ventilation with recovery</strong> — an ERV in summer transfers incoming moisture back outdoors (Module 10), cutting the latent load the coil must meet; <strong>right-sizing and airflow setup</strong> — the runtime and coil conditions Sections 1 and 3 established.</p><p><strong>Worked priority example.</strong> A design's latent load totals 10,000 Btu/h, of which a given 5,500 is infiltration-driven. Sealing work projected (given) to cut infiltration moisture by 40% removes 2,200 Btu/h of latent load — which may move the equipment selection down a nominal size, improving runtime and humidity control again: prevention compounds. Only after those moves does the designer size supplemental dehumidification for what remains. Treat-first design — a big dehumidifier bolted onto a leaky, oversized system — spends the most money to keep the most problems.</p><div class="callout"><strong>Key idea:</strong> Sequence humidity design like the whole course: reduce the load, then select equipment for what honestly remains.</div>` },
  ],
  keyTerms: [{ term: "Humidity control", def: "Keeping indoor moisture within a target band by design: sources, sinks, runtime, and equipment working together." }, { term: "Moisture source", def: "Anything adding water vapor indoors: people, cooking, bathing, plants, infiltration, unvented combustion." }, { term: "Moisture sink", def: "Anything removing water vapor: a cold coil, a dehumidifier, exchange with drier air." }, { term: "Humidification load", def: "The rate (lb/h) at which water must be added to hold the target indoor humidity ratio." }, { term: "Dehumidification load", def: "The rate (lb/h or latent Btu/h) at which water must be removed to hold the target." }, { term: "Dedicated dehumidifier", def: "An appliance that removes moisture independent of the cooling system, rejecting its heat to the space." }, { term: "Ventilating dehumidifier", def: "A dehumidifier that also introduces controlled outdoor air." }, { term: "Evaporative humidifier", def: "A humidifier that evaporates water using furnace heat and airflow; output follows heating runtime." }, { term: "Steam humidifier", def: "A humidifier that boils water with its own heat source; output is independent of heating runtime." }, { term: "Latent heat of condensation", def: "The heat released when water vapor condenses (≈1,060 Btu/lb in this course's stated examples)." }, { term: "Shoulder season", def: "Mild spring/fall periods with small sensible loads but continuing moisture loads — the hardest humidity conditions." }, { term: "Coil runtime", def: "The operating time during which the coil is cold enough to condense moisture; the engine of dehumidification." }, { term: "Target humidity ratio", def: "The indoor grains/lb the design intends to hold." }, { term: "Condensation risk", def: "The danger of moisture condensing on or inside assemblies when humid indoor air meets cold surfaces." }, { term: "Source exhaust", def: "Venting moisture at its generation point (baths, range) directly outdoors." }, { term: "Airflow-latent trade", def: "Lower coil airflow generally deepens moisture removal per pass while trimming sensible capacity, per manufacturer data." }, { term: "Gallons per day", def: "A practical humidifier sizing expression: lb/h × 24 ÷ 8.3 lb per gallon." }, { term: "Enthalpy recovery (preview)", def: "Transferring moisture (and heat) between airstreams to cut latent load — Module 10's subject." }],
  video: { title: "Psychrometric Chart Part 2 Beyond The Basics", embedUrl: "https://www.youtube.com/embed/4Z_usQB9vQ8", note: "The follow-up session: mixing air streams, sensible heat ratio, finding CFM with the sensible-heat equation, and finding tonnage with the total-heat (enthalpy) equation — exactly the calculations this module practices. Note it uses 1.085 in one equation where this course uses the rounded standard-air factor 1.08; both are the same standard-air approximation.", more: [] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Air exchange is 200 CFM (use 0.075 lb/cu ft). Incoming air is given at 20 grains, target 50 grains. Find the humidification rate in lb/h and gallons/day.</p>", solution: "<p><strong>Answer: ≈ 3.9 lb/h, ≈ 11 gal/day.</strong> Step 1: Mass flow = 200 × 60 × 0.075 = 900 lb dry air/h. Step 2: Δgrains = 50 − 20 = 30. Step 3: Water = 900 × 30 ÷ 7,000 = 27,000 ÷ 7,000 ≈ 3.86 lb/h. Step 4: Gallons/day = 3.86 × 24 ÷ 8.3 ≈ 11.2.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Outdoor-driven airflow is 300 CFM (0.075 lb/cu ft). Air enters at a given 110 grains and must be held at 55. Find moisture removal in lb/h and latent Btu/h at 1,060 Btu/lb.</p>", solution: "<p><strong>Answer: ≈ 10.6 lb/h; ≈ 11,250 Btu/h.</strong> Step 1: Mass = 300 × 60 × 0.075 = 1,350 lb/h. Step 2: Δ = 55 grains. Step 3: 1,350 × 55 ÷ 7,000 ≈ 10.6 lb/h. Step 4: 10.6 × 1,060 ≈ 11,250 Btu/h latent.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A unit's given design capacities are total 36,000 and sensible 27,000 Btu/h. The load (given) is total 33,000, latent 8,500. Run all three selection checks.</p>", solution: "<p><strong>Answer: pass — all three checks succeed.</strong> Step 1: Total: 36,000 ≥ 33,000 ✓. Step 2: Unit latent = 36,000 − 27,000 = 9,000 ≥ 8,500 ✓. Step 3: Load sensible = 33,000 − 8,500 = 24,500 ≤ unit sensible 27,000 ✓. Step 4: Accept. The discipline is running all three checks rather than stopping at a guessed verdict.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A tight, well-sealed house in a humid climate is comfortable at design peak but muggy on mild rainy days. Diagnose the mechanism and name two design-level remedies.</p>", solution: "<p><strong>Answer:</strong> Step 1: Mild days shrink the sensible load, so cooling runtime collapses while moisture sources and humid infiltration continue — latent removal starves. Step 2: Remedy one: a dedicated (or ventilating) dehumidifier that removes moisture independent of cooling runtime. Step 3: Remedy two: ERV ventilation and further source control to cut the incoming latent load itself. (Oversizing the A/C would make it worse.)</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A steam humidifier is rated (given) to deliver 5 lb/h at 1.5 kW. An evaporative model delivers up to 5 lb/h but only while the furnace runs, and the furnace's design duty cycle is given as 60%. Compare their effective design-night delivery.</p>", solution: "<p><strong>Answer:</strong> Step 1: Steam: 5 lb/h regardless of furnace state. Step 2: Evaporative effective average = 5 × 0.60 = 3 lb/h across the design night. Step 3: If the humidification load (Section 2 method) is 4 lb/h, the evaporative unit falls short at design despite the equal nameplate rate — duty cycle is part of capacity.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Rank these interventions for a house whose latent load is 60% infiltration-driven: (a) larger air conditioner, (b) envelope sealing, (c) dedicated dehumidifier sized after other measures. Justify the order.</p>", solution: "<p><strong>Answer: (b) → (c) → never (a).</strong> Step 1: Sealing attacks 60% of the load at its source and shrinks the remaining equipment duty. Step 2: The dehumidifier is then sized for the honestly reduced load and covers shoulder seasons. Step 3: A larger A/C shortens coil runtime and worsens humidity — it treats the symptom in the wrong direction.</p>" },
  ],
  quiz: [
    { q: "Indoor humidity problems in an oversized system arise mainly because:", choices: ["The coil is too cold", "Short runtimes give the coil too little time to condense moisture", "The thermostat reads humidity", "Big filters absorb moisture"], answer: 1, explanation: "Correct: (b). Dehumidification needs sustained wet-coil time; oversizing trades it away. (a) A colder coil would help if it ran — runtime is the failure. (c) Most thermostats only sense temperature; even a humidistat cannot create runtime. (d) Filters do not meaningfully absorb household moisture." },
    { q: "Humidification rate is calculated from:", choices: ["RH readings alone", "Air mass flow × humidity-ratio difference ÷ 7,000 (when grains are used)", "Duct length", "Furnace input"], answer: 1, explanation: "Correct: (b). Pounds of water = pounds of dry air × Δ(lb water/lb air); grains convert by 7,000. (a) RH gives no mass without airflow and temperature context. (c) and (d) are unrelated to the moisture balance." },
    { q: "A dehumidifier's advantage over the cooling coil is that it:", choices: ["Cools the air as well", "Removes moisture independent of cooling runtime", "Uses no energy", "Lowers the latent load itself"], answer: 1, explanation: "Correct: (b). It runs when moisture demands, including mild days when the A/C rests. (a) It actually returns its heat to the space. (c) It uses energy like any appliance. (d) It treats moisture; load reduction comes from sealing, source control, and recovery." },
    { q: "Pushing winter indoor humidity too high risks:", choices: ["Dry skin", "Condensation on windows and inside wall assemblies", "Lower heating bills guaranteed", "Quieter ducts"], answer: 1, explanation: "Correct: (b). Humid air reaching surfaces below its dew point condenses — inside cavities where it feeds decay and mold. (a) is the low-humidity complaint. (c) Humidification costs energy and water. (d) Duct sound is unrelated." },
    { q: "An ERV helps summer humidity control by:", choices: ["Adding moisture to supply air", "Transferring part of the incoming air's moisture back to the exhaust stream", "Cooling the outdoor air", "Sealing the envelope"], answer: 1, explanation: "Correct: (b). The energy-recovery core passes moisture as well as heat, so incoming air arrives drier than outdoors. (a) is backwards for summer. (c) It tempers but does not refrigerate. (d) Sealing is envelope work, separate from the ventilator." },
    { q: "In Problem-3-style selection, the correct habit is:", choices: ["Check total capacity only", "Check total, sensible, and latent — all three, at design conditions", "Check latent only", "Trust the tonnage"], answer: 1, explanation: "Correct: (b). Any single unchecked split can fail the building while the total looks fine (and, as the assignment showed, a suspected failure must be verified by actually running all the numbers). (a) and (c) each leave a failure mode invisible. (d) Tonnage is a label." },
    { q: "Ventilating a bath fan into the attic is wrong because it:", choices: ["Wastes a fan", "Dumps the room's moisture into a cold structure where it condenses", "Breaks the fan's listing in all cases", "Raises attic humidity only in summer"], answer: 1, explanation: "Correct: (b). Source exhaust must terminate outdoors; attic dumping trades a room problem for a roof-deck rot and mold problem. (a) understates the harm. (c) may or may not be a listing issue — the moisture damage is the certain one. (d) Winter, with cold decking, is the worst season, not the only one." },
    { q: "Lowering coil airflow (within manufacturer limits) generally:", choices: ["Reduces moisture removal", "Deepens moisture removal per pass while trimming some sensible capacity", "Has no effect on humidity", "Increases latent load"], answer: 1, explanation: "Correct: (b). Slower air over a cold coil leaves colder and drier; the trade is quantified in manufacturer data. (a) is backwards. (c) Airflow is a primary coil-behavior variable. (d) Load is a building property; airflow changes the equipment's split, not the load." },
  ],
  studyGuide: `
<h3>Module 9 — Humidity Control by Design: Quick Reference</h3>
<div class="formula">lb/h water = (CFM × 60 × 0.075) × Δgrains ÷ 7,000 · Latent Btu/h ≈ lb/h × 1,060 (stated example value) · gal/day = lb/h × 24 ÷ 8.3</div>
<p><strong>Levers, in order:</strong> seal the envelope → exhaust at sources (outdoors!) → recover with ERV → right-size for runtime → then size supplemental equipment for what remains.</p><p><strong>Equipment:</strong> coil (free but runtime-bound) · dedicated/ventilating dehumidifier (independent of cooling) · evaporative humidifier (cheap, follows furnace runtime) · steam humidifier (independent, higher energy per pound).</p>
<p><strong>Traps:</strong> oversized A/C (clammy at setpoint) · winter over-humidification (condensation in assemblies) · latent capacity never checked at selection · bath fans vented into attics.</p>
<p><strong>Discipline:</strong> moisture loads are computed from given grains and flows — pounds and Btu, never adjectives.</p>
<p><strong>Exam-style drill:</strong> any moisture problem reduces to mass of dry air × change in moisture content. Convert CFM to lb/h (× 60 × 0.075), convert grains differences to pounds (÷ 7,000), multiply — then, if Btu are asked, multiply pounds by the stated latent heat value. No other machinery is needed.</p>
`
};
