// HVAC 245 - Module 12: Design Project
module.exports = {
  number: 12,
  slug: "design-project",
  title: "Design Project",
  estTime: "4–5 hours",
  objectives: ["Execute the full design sequence on one house: survey, heat loss, heat gain, selection, airflow, ducts, distribution, ventilation, and verification plan.", "Carry one consistent set of numbers through every step and cross-check each handoff.", "Document assumptions and teaching-value sources the way a professional worksheet does.", "Identify the point in the sequence where each Module 1–11 skill is exercised.", "Present a finished design summary a reviewer can audit line by line."],
  sections: [
    { heading: "The Project House and the Survey", html: `<p>Our project is the lab house, completed: a one-story, 1,000 sq ft teaching-example home, four conditioned rooms in the airflow schedule (living room, kitchen, bedroom 1, bedroom 2) plus the envelope from the lab worksheet. Stated survey values (teaching example throughout): net walls 800 sq ft at U 0.07; ceiling 1,000 sq ft at U 0.05; floor 1,000 sq ft at U 0.06 over an unheated space; windows 120 sq ft at U 0.50; doors 40 sq ft at U 0.30. Winter design (given): 70°F in, 0°F out — ΔT 70 for above-grade assemblies, ΔT 40 across the floor (buffered space at 30°F). Summer design (given): 95°F out, 75°F in. Occupancy (given): 4 people. Every figure that follows traces to this paragraph — that traceability is the professional habit the whole course has been rehearsing.</p><p>The survey also records what arithmetic cannot: window orientation and shading notes, the attic and crawl conditions, existing appliance types (a naturally vented water heater shares the house — flag it for the ventilation and Step 0 combustion-air checks), and the occupants' quiet-room priority (bedroom wing). Design is numbers plus notes; the notes decide several later judgment calls.</p><div class="callout"><strong>Key idea:</strong> One project, one set of stated assumptions, used by every step. Changing an assumption mid-design without re-running the downstream steps is how real projects quietly break.</div>` },
    { heading: "Step 1–2: Heat Loss and Heat Gain", html: `<p><strong>Heat loss</strong> (Module 3 method, lab arithmetic): walls 0.07 × 800 × 70 = 3,920; ceiling 0.05 × 1,000 × 70 = 3,500; floor 0.06 × 1,000 × 40 = 2,400; windows 0.50 × 120 × 70 = 4,200; doors 0.30 × 40 × 70 = 840. Conduction total = 14,860 Btu/h. Infiltration (given for the project): 120 CFM → 1.08 × 120 × 70 = 9,072. <strong>Block heating load = 23,932 Btu/h.</strong></p><p><strong>Heat gain</strong> (Module 4 method; all component values given for the project): room sensible loads — living 6,480; kitchen 5,400; bedroom 1 4,320; bedroom 2 3,240 — total sensible 19,440 Btu/h (these are the lab's room values, built from the project's given solar, conduction, and internal components). Latent load (given): 5,600 Btu/h, dominated by humid infiltration and the four occupants. <strong>Block cooling load = 25,040 Btu/h total; SHR = 19,440 ÷ 25,040 ≈ 0.78.</strong> Cross-checks: cooling total and heating total are different numbers from different physics (Module 4's warning honored); the latent share (22%) is plausible for a humid-infiltration-driven example and is large enough that Module 5's latent check will matter.</p><p>Room CFM follows from sensible loads at the project's 20°F design ΔT: living 300, kitchen 250, bedroom 1 200, bedroom 2 150 — total 900 CFM (lab rows 8–12). Airflow is settled <em>before</em> equipment selection here deliberately, because the selected unit must move 900 CFM at the duct system's static — the handoff Module 5 and 6 share.</p>` },
    { heading: "Step 3–4: Selection and Duct Design", html: `<p><strong>Selection</strong> (Module 5's three checks; candidate data given for the project). Cooling load: total 25,040, sensible 19,440, latent 5,600. Candidate 2.5-ton nominal (30,000 nominal) with design-condition data (given): total 27,500, sensible 20,500, latent available 7,000. Checks: total 27,500 ≥ 25,040 ✓ (≈10% margin); sensible 20,500 ≥ 19,440 ✓; latent 7,000 ≥ 5,600 ✓. Heating: a furnace with given output 26,400 Btu/h against the 23,932 loss ✓ (≈10% margin) — or, in a heat-pump variant, balance-point arithmetic per Module 5. The candidate passes all checks with modest margins; its blower is rated (given) 0.80 in. w.c. TESP at 900 CFM. Selected and recorded by model — no nickname-only selection anywhere in the file.</p><p><strong>Duct design</strong> (Module 6). Components (given): coil 0.25, filter 0.10, register 0.03, grille 0.02 → ASP = 0.80 − 0.40 = 0.40. Longest path (given): measured 80 ft + fittings 150 ft equivalent = TEL 230 ft. FR = 0.40 × 100 ÷ 230 ≈ 0.17 per 100 ft. Sections at FR 0.17 and their CFM — trunk 900 → 600 → 350 → 150 as branches leave (Module 6's stepping), branches at room CFM — sized from the friction chart in real work. Return path sized with the same budget discipline; the Step 0 rule (never undersize the return) is initialed on the worksheet beside the combustion-air confirmation for the water heater's space.</p><p>Note the margin pattern across both selections: roughly ten percent over the calculated load, achieved at design conditions. That is what 'right-sized with a modest margin' looks like in numbers — a world away from the 50–100% oversizes Module 5 dissected.</p>` },
    { heading: "Step 5–6: Distribution, Ventilation, and Humidity", html: `<p><strong>Distribution</strong> (Module 7). Room schedule: living 300 CFM across two registers (150 each) on the exterior wall; kitchen 250 at one register selected for its given throw to cross the work zone; bedrooms 200 and 150 at single registers chosen by bedroom-quiet face velocities. Return: a central return grille with given free area 2.25 sq ft passes 900 CFM at 900 ÷ 2.25 = 400 fpm, plus transfer grilles at both bedroom doors sized from Problem-5 arithmetic (200 CFM at ≤300 fpm needs ≥ 0.67 sq ft; 150 CFM needs ≥ 0.50 sq ft) so closed doors cannot pressurize the bedrooms. Balancing dampers are specified in every branch, with a balancing appointment in the verification plan.</p><p><strong>Ventilation &amp; recovery</strong> (Modules 8 &amp; 10). Project rate by the pattern with given factors (0.03 CFM/sq ft, 7.5 CFM/person): 0.03 × 1,000 + 7.5 × 4 = 30 + 30 = 60 CFM continuous. Strategy: balanced ERV (humid summers in the project's stated climate; winter moisture export is acceptable because the survey noted generous cooking/bathing sources). At a given sensible effectiveness of 0.75, winter ventilation load falls from 1.08 × 60 × 70 = 4,536 to about 1,134 Btu/h — and that recovered 3,402 Btu/h is credited <em>only</em> against the ventilation term, per Module 10's honesty rule; the heating selection above was made without the credit, banking it as margin. Make-up air for the range hood is coordinated per Module 8, and the water heater's combustion air is confirmed — Step 0, closed in design, not discovered in the field.</p><p><strong>Humidity</strong> (Module 9): latent selection margin (7,000 vs 5,600) plus ERV latent transfer covers the design day; the worksheet flags shoulder-season monitoring in the verification plan rather than bolting on a dehumidifier the numbers do not yet justify.</p>` },
    { heading: "Step 7: The Verification Plan and the Design Summary", html: `<p>The design ships with its own audit (Module 11). Verification plan for this project: (1) TESP measured and split; budget 0.80 total with ASP 0.40 for ducts — acceptance at or under the blower rating at 900 CFM. (2) Total CFM by flow hood (register sum) cross-checked against a traverse of the trunk. (3) Room CFMs balanced to the 300/250/200/150 schedule; damper positions marked. (4) Ventilation measured at 60 CFM; ERV core and drain inspected; hoods confirmed separated. (5) RH logged across a cooling afternoon; target band per the design brief. (6) Model/serial plates photographed against the selection worksheet. (7) Sound pass in bedroom 1 at design airflow.</p><p><strong>Design summary (the audit table).</strong> Heating load 23,932 → selected output (given) 26,400. Cooling load 25,040 total / 19,440 sensible / 5,600 latent → selected at design 27,500 / 20,500 / 7,000 latent. Airflow 900 CFM; rooms 300/250/200/150. Ducts: ASP 0.40, TEL 230, FR ≈ 0.17. Ventilation 60 CFM balanced ERV, eff. 0.75 (given). Every number in this paragraph can be re-derived from this module's stated givens in under five minutes — run the audit yourself as the final exercise. That is what 'designed' means, and it is the standard to carry into the certification study that follows this program: EPA 608 and NATE test whether you know systems; this course's project proves you can assemble one.</p><div class="callout"><strong>Key idea:</strong> A design is finished when a stranger can verify it — every figure sourced, every handoff checked, every assumption on the page.</div>` },
  ],
  keyTerms: [{ term: "Design sequence", def: "The ordered workflow: survey → loads → selection → airflow → ducts → distribution → ventilation → verification." }, { term: "Design brief", def: "The document recording the project's stated assumptions, conditions, and occupant priorities." }, { term: "Audit trail", def: "The chain of worksheets letting a reviewer re-derive every design figure from its givens." }, { term: "Handoff", def: "A value passed between design steps (e.g., load → selection, CFM → ducts) that must be checked at the boundary." }, { term: "Rated combination (project)", def: "The specific equipment pairing selected and recorded by model number." }, { term: "Room schedule", def: "The table of design CFM per room used for distribution and balancing." }, { term: "Verification plan", def: "The written list of measurements and acceptance values shipped with the design." }, { term: "Acceptance value", def: "A measured quantity's pass/fail threshold taken from the design budget." }, { term: "Design margin", def: "The deliberate, modest excess of capacity or budget over the calculated requirement." }, { term: "Assumption log", def: "The record of every stated teaching/example value and its source, kept with the design." }, { term: "Block load (project)", def: "The whole-building coincident load used for equipment selection." }, { term: "Transfer grille sizing", def: "Choosing return-path free area from CFM and a target face velocity." }, { term: "Recovery credit", def: "The load reduction taken for heat/energy recovery, applied only to the ventilation term." }, { term: "Shoulder-season monitoring", def: "Planned humidity observation during mild weather, when latent control is hardest." }, { term: "As-designed", def: "The system's intended state as documented, against which as-built verification compares." }, { term: "Closeout paperwork", def: "The load worksheet, selection, duct budget, and verification results left with the job." }, { term: "Step 0 (project)", def: "The safety gate — combustion air, clearances, return adequacy — confirmed before sizing proceeds." }, { term: "Capstone design", def: "A complete worked design integrating all prior modules, as this module presents." }],
  video: { title: "HVAC Duct Design: Manual D, Fittings, Friction Rate, Pressure Loss, & Static Pressure w/ Alex Meaney", embedUrl: "https://www.youtube.com/embed/Bq9yTn31qRw", note: "A deep dive on duct design calculations with a design trainer: friction rate, fittings, pressure loss, and static pressure, comparing the Manual D approach with the ASHRAE approach. This is the module's core method shown at full professional depth; our worked examples use the same steps with rounder teaching numbers.", more: [{ title: "Duct Design for Great Results w/ Ed Janowiak (ACCA)", url: "https://www.youtube.com/watch?v=-KqmAQgUXY4" }] },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Re-derive the project's block heating load from the survey values, showing each assembly.</p>", solution: "<p><strong>Answer: 23,932 Btu/h.</strong> Step 1: Walls 0.07 × 800 × 70 = 3,920. Step 2: Ceiling 0.05 × 1,000 × 70 = 3,500. Step 3: Floor 0.06 × 1,000 × 40 = 2,400. Step 4: Windows 0.50 × 120 × 70 = 4,200. Step 5: Doors 0.30 × 40 × 70 = 840. Step 6: Conduction 14,860 + infiltration 1.08 × 120 × 70 = 9,072 → 23,932 Btu/h.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Verify the project's cooling SHR and state which selection check it most directly informs.</p>", solution: "<p><strong>Answer: SHR ≈ 0.78.</strong> Step 1: Total = 19,440 + 5,600 = 25,040. Step 2: 19,440 ÷ 25,040 ≈ 0.78. Step 3: It informs the latent/sensible split checks — a candidate whose design split is far from 0.78 will fail one side while passing total.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A substitute unit is proposed with design data (given): total 26,000, sensible 18,900, latent 7,100. Accept or reject for this project?</p>", solution: "<p><strong>Answer: reject — sensible fails.</strong> Step 1: Total 26,000 ≥ 25,040 ✓. Step 2: Latent 7,100 ≥ 5,600 ✓. Step 3: Sensible 18,900 &lt; 19,440 ✗. The house would drift warm on the design afternoon despite two passes.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Recompute the project's friction rate if the installed filter change raises component drops to a given total of 0.55 (TESP still 0.80, TEL 230).</p>", solution: "<p><strong>Answer: FR ≈ 0.11 per 100 ft.</strong> Step 1: ASP = 0.80 − 0.55 = 0.25. Step 2: FR = 0.25 × 100 ÷ 230 ≈ 0.109 ≈ 0.11. Step 3: The ducts as sized at 0.17 would under-deliver — the change must be caught at design review, exactly the Module 6 filter lesson.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Size the transfer grille free area for bedroom 2 (150 CFM) at a target face velocity of 250 fpm.</p>", solution: "<p><strong>Answer: 0.6 sq ft.</strong> Step 1: Area = CFM ÷ velocity = 150 ÷ 250 = 0.6 sq ft. Step 2: Select the next available grille whose given free area meets or exceeds 0.6 sq ft.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Write the one-paragraph audit of the ventilation design: rate, strategy, winter load effect, and the two safety coordinations.</p>", solution: "<p><strong>Answer (model):</strong> 'Ventilation is 60 CFM continuous by the given two-part factors (30 area + 30 occupants), delivered balanced through an ERV at given sensible effectiveness 0.75, cutting the winter ventilation load from 4,536 to ≈1,134 Btu/h; the credit is not taken in equipment sizing. Range-hood make-up air is coordinated so the house does not depressurize, and combustion air for the naturally vented water heater is confirmed — both per the project's Step 0 safety gate.'</p>" },
  ],
  quiz: [
    { q: "The project's heating and cooling block loads are 23,932 and 25,040 Btu/h. Their closeness is:", choices: ["Required — they must match", "Coincidence of this example — they come from different physics and need not match", "Proof the load calc is wrong", "A reason to use one number for both"], answer: 1, explanation: "Correct: (b). Winter loss (conduction + infiltration at ΔT 70) and summer gain (small-ΔT conduction + solar + internal + latent) are independent calculations. (a) No rule equates them. (c) Different inputs can honestly land near each other. (d) Selection checks each load against its own equipment data." },
    { q: "In the project sequence, room CFM is fixed before equipment selection because:", choices: ["Registers are bought first", "The selected equipment must be verified to move the design CFM against the duct system's static pressure", "CFM never changes", "The code requires the paperwork order"], answer: 1, explanation: "Correct: (b). Airflow is a shared handoff: loads set it, selection must deliver it, ducts must pass it. (a) Purchasing order is logistics, not design logic. (c) CFM is revised if loads or assumptions change — with downstream steps re-run. (d) The sequence is engineering logic, not a paperwork rule." },
    { q: "The ERV's winter recovery credit in the project was:", choices: ["Applied to the whole heating load", "Applied only to the ventilation term — and not even taken in sizing, banking it as margin", "Ignored entirely as worthless", "Doubled for safety"], answer: 1, explanation: "Correct: (b). Honest credit touches only the stream through the core; the project chose extra conservatism by not spending it in selection. (a) is the Module 10 sales error. (c) understates a real 3,402 Btu/h effect. (d) invents a factor with no basis." },
    { q: "A reviewer auditing this design should be able to:", choices: ["Re-derive every figure from the stated givens", "Trust the designer's reputation", "Find at least one undocumented assumption", "Skip the latent check"], answer: 0, explanation: "Correct: (a). Auditability — givens on the page, arithmetic reproducible — is the definition of a finished design in this course. (b) Reputation is not evidence. (c) Undocumented assumptions are defects, not expectations. (d) The latent check is where this project's selection was most nearly lost." },
    { q: "The Step 0 gate appears in the project as:", choices: ["A decorative paragraph", "Confirmations of combustion air, clearances, and return adequacy recorded before sizing proceeds", "A post-installation inspection only", "A sales disclosure"], answer: 1, explanation: "Correct: (b). Safety decisions are design inputs with a worksheet location, closed before arithmetic — the same discipline as the lab. (a) understates a signed checkpoint. (c) Field checks matter too, but Step 0 exists to catch these on paper first. (d) It is an engineering gate, not a disclosure form." },
    { q: "If the as-built TESP measures 0.95 against the 0.80 budget in verification, the design response is:", choices: ["Accept — close enough", "Diagnose by side split, correct the restriction, and re-measure before closeout", "Raise the thermostat setpoint", "Remove the filter permanently"], answer: 1, explanation: "Correct: (b). Verification exists to find and fix exactly this; the split localizes the cause. (a) abandons the acceptance value the design shipped with. (c) treats a symptom with comfort settings. (d) trades a pressure problem for an air-quality and coil-fouling problem." },
    { q: "Changing the project's window assumption mid-design without re-running later steps would most likely break:", choices: ["Only the window line", "Every downstream figure that consumed the load — selection, CFM, ducts, and distribution", "Nothing, if the change is small", "Only the paperwork's appearance"], answer: 1, explanation: "Correct: (b). Loads feed selection, airflow, duct sizing, and outlet schedules; a silent upstream change invalidates the chain. (a) ignores the handoffs. (c) 'Small' changes compound through five steps. (d) The breakage is physical, not cosmetic." },
    { q: "The single sentence that best states this course's design philosophy is:", choices: ["'Bigger equipment forgives small calculations.'", "'Every figure sourced, every handoff checked, every assumption on the page.'", "'Rules of thumb are faster than worksheets.'", "'If it cools, it is designed.'"], answer: 1, explanation: "Correct: (b). Modules 1–12 built that discipline step by step — given values, checked arithmetic, verified installation. (a) is Module 5's refuted claim. (c) is what the friction-rate and load methods replaced. (d) confuses operation with design — Module 11's 'seems fine' fallacy." },
  ],
  studyGuide: `
<h3>Module 12 — Design Project: Quick Reference</h3>
<p><strong>Project audit table:</strong> heating 23,932 (conduction 14,860 + infiltration 9,072) → output 26,400 (given) · cooling 25,040 total / 19,440 sensible / 5,600 latent, SHR ≈ 0.78 → selected at design 27,500 / 20,500 / 7,000 · airflow 900 CFM (300/250/200/150) · ducts ASP 0.40, TEL 230, FR ≈ 0.17 · ventilation 60 CFM balanced ERV (eff. 0.75 given), winter ventilation load 4,536 → ≈1,134 Btu/h, credit not spent in sizing.</p><p><strong>Sequence:</strong> survey (numbers + notes) → loss → gain (split!) → CFM → selection (3 checks) → ducts (budget → TEL → FR) → distribution (throw, free area, return paths) → ventilation + recovery + humidity → verification plan.</p>
<p><strong>Step 0 is in the design:</strong> combustion air, clearances, return adequacy — confirmed on paper before sizing.</p>
<p><strong>Finish line:</strong> a stranger can re-derive every figure from the stated givens. If they cannot, the design is not done.</p>
<p><strong>Carry-forward:</strong> keep this project's worksheet format as your template for real jobs — survey givens boxed at the top, each step's outputs boxed at its handoff, Step 0 signed before Step 1 begins. The format is the quality system.</p>
`
};
