// HVAC 102 — Scenario lab: Charging by Superheat & Subcooling.
// All P/T values use the program anchors: R-410A 118 psig ≈ 40°F, 317 psig ≈ 100°F;
// R-22 68.5 psig ≈ 40°F, 196 psig ≈ 100°F; R-134a 35 psig ≈ 40°F.
module.exports = [
  {
    id: "charging-superheat-subcooling",
    title: "Charging by Superheat & Subcooling",
    introHtml: "<p><strong>Job ticket — two calls, one afternoon.</strong> Call A: a 3-ton R-410A split system with a TXV, nameplate subcooling target 10°F, complaint 'not cooling like last summer.' Call B (same property): an older R-22 fixed-orifice system, also weak. You will work both calls the way this course teaches: safety first, airflow verified, then pressures, temperatures, and arithmetic. P/T anchors provided on the truck tablet: R-410A — 118 psig ≈ 40°F saturation, 317 psig ≈ 100°F saturation. R-22 — 68.5 psig ≈ 40°F, 196 psig ≈ 100°F. R-134a — 35 psig ≈ 40°F.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=0zsckt86Who\" target=\"_blank\" rel=\"noopener\">Practice Checking the Charge of an R-410A Air Conditioner with Subcooling Method! 4 Scenarios!</a> — worked subcooling scenarios with real readings, the same computation this lab grades.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Before any panel comes off: eye and hand protection on; verify the disconnect and apply lockout/tagout before opening electrical compartments; treat every circuit as pressurized; refrigerant is recovered with certified equipment and is <strong>never vented</strong>; cylinders stay within fill limits and are labeled. Electrical checks on live circuits follow the electricity-course discipline.</p><p><strong>Visit sequence (used by the procedure-order rows):</strong> Step 1 — Verify airflow and coil condition. Step 2 — Record baseline pressures and line temperatures on a stabilized system. Step 3 — Compute superheat and subcooling from the P/T anchors. Step 4 — Match the pattern and decide the fault. Step 5 — Adjust charge in small increments (or correct the non-charge fault). Step 6 — Re-measure everything and document refrigerant type, amounts, and final readings.</p><p>For each row, enter the number of the correct option, the procedure step number, or the computed value, as the row directs.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY — You arrive at Call A. Before removing any panel or connecting gauges, what is your first action? 1) Connect the manifold immediately while the system runs. 2) Put on PPE, then verify the disconnect / apply lockout-tagout before opening any electrical compartment. 3) Open the liquid service valve to check for pressure by ear. 4) Remove the compressor terminal cover to inspect wiring.", cells: [""], inputs: [
        { col: 1, key: "safety_first", expected: 2, hint: "Safety precedes diagnosis: PPE plus verified disconnect/lockout-tagout before opening electrical spaces. Gauges come later; venting a valve 'by ear' releases refrigerant and is prohibited." } ] },
      { label: "LEGAL/SAFETY — Call A's repair will require opening the refrigerant circuit. What is the lawful plan for the refrigerant in the system? 1) Vent it — R-410A does not deplete ozone. 2) Crack a fitting and let it escape slowly. 3) Recover it with certified recovery equipment into a labeled cylinder, to the required level, before opening the circuit. 4) Pump it into the atmosphere side of the condenser fan.", cells: [""], inputs: [
        { col: 1, key: "recovery_plan", expected: 3, hint: "The venting prohibition covers HFC substitutes such as R-410A, not just ozone-depleting refrigerants. Certified equipment, a labeled cylinder, and a measured endpoint — every time." } ] },
      { label: "PROCEDURE ORDER — In the visit sequence in the task description, at which step do you compute superheat and subcooling from the baseline readings? Enter the step number.", cells: [""], inputs: [
        { col: 1, key: "order_compute", expected: 3, hint: "Step 1 airflow, Step 2 baseline readings, Step 3 compute SH/SC — arithmetic comes after honest measurements, never before." } ] },
      { label: "PROCEDURE ORDER — In the visit sequence, at which step do you adjust the charge (in small increments, with stabilization waits)? Enter the step number.", cells: [""], inputs: [
        { col: 1, key: "order_adjust", expected: 5, hint: "Step 4 is the pattern decision; Step 5 is the adjustment. Charging before the Step 4 verdict is how good refrigerant gets added to restriction faults." } ] },
      { label: "COMPUTE — Call A (R-410A, TXV): head pressure 317 psig, liquid line temperature 90°F. Using the anchor (317 psig ≈ 100°F saturation), what is the subcooling in °F?", cells: [""], inputs: [
        { col: 1, key: "sc_r410a", expected: 10, hint: "Subcooling = saturation temp − liquid line temp = 100 − 90 = 10°F — exactly the nameplate target for this TXV system." } ] },
      { label: "COMPUTE — Call A: suction pressure 118 psig, suction line temperature 50°F. Using the anchor (118 psig ≈ 40°F saturation), what is the superheat in °F?", cells: [""], inputs: [
        { col: 1, key: "sh_r410a", expected: 10, hint: "Superheat = suction line temp − saturation temp = 50 − 40 = 10°F — the TXV holding its setting, consistent with the on-target subcooling." } ] },
      { label: "DECIDE — Call A results: subcooling 10°F (target 10°F), superheat 10°F, airflow verified good, yet cooling is weak and the temperature split is poor. What is the correct verdict? 1) Undercharged — add refrigerant. 2) Overcharged — recover refrigerant. 3) Charge is correct — the fault is not charge; keep diagnosing (airside/duct/load side). 4) The TXV has failed — replace it.", cells: [""], inputs: [
        { col: 1, key: "decide_calla", expected: 3, hint: "Both charge witnesses are exactly on target and the valve is doing its job — by definition the charge is not the fault. Honest numbers redirect the search instead of decorating the circuit with extra refrigerant." } ] },
      { label: "COMPUTE — Call B (R-22, fixed orifice): suction pressure 68.5 psig, suction line temperature 61°F. Using the anchor (68.5 psig ≈ 40°F saturation), what is the superheat in °F?", cells: [""], inputs: [
        { col: 1, key: "sh_r22", expected: 21, hint: "Superheat = 61 − 40 = 21°F — high for a fixed-orifice system under load: the coil is boiling its charge off early (starved pattern)." } ] },
      { label: "DECIDE — Call B also shows subcooling of only 2°F with low head pressure. A fixed-orifice system with superheat 21°F and subcooling 2°F matches which pattern? 1) Undercharge. 2) Restriction. 3) Overcharge. 4) Non-condensables.", cells: [""], inputs: [
        { col: 1, key: "decide_undercharge", expected: 1, hint: "Starved coil (high SH) + empty condenser (low SC) = undercharge. A restriction would show the same high superheat but with subcooling stacked HIGH — the subcooling witness separates the twins." } ] },
      { label: "COMPUTE — A third system (R-22) on the same property shows head pressure 196 psig and liquid line temperature 84°F. Using the anchor (196 psig ≈ 100°F saturation), what is its subcooling in °F?", cells: [""], inputs: [
        { col: 1, key: "sc_r22", expected: 16, hint: "Subcooling = 100 − 84 = 16°F — high stacking. Paired with this system's very high superheat (next row), it tells the restriction story." } ] },
      { label: "DECIDE — That third system: superheat 26°F, subcooling 16°F, frost beginning at the liquid-line drier outlet. The pattern is: 1) Undercharge — add 2 lb. 2) Restriction at the drier — recover/weigh to confirm, replace the drier, hunt the debris source. 3) Overcharge — the frost proves it. 4) A failed compressor — replace it.", cells: [""], inputs: [
        { col: 1, key: "decide_restriction", expected: 2, hint: "High SH + high SC is the restriction fingerprint, and the frost line localizes it at the drier. Adding charge would raise the stack; the weigh-out will prove the charge was already full." } ] },
      { label: "COMPUTE — The shop's R-134a reach-in: suction pressure 35 psig, suction line temperature 48°F. Using the anchor (35 psig ≈ 40°F saturation), what is the superheat in °F?", cells: [""], inputs: [
        { col: 1, key: "sh_r134a", expected: 13, hint: "Superheat = 48 − 40 = 13°F. Same ritual on every refrigerant: pressure → saturation temperature → subtract." } ] },
      { label: "COMPUTE (BLEND) — A zeotropic blend system: at the measured suction pressure the P/T app gives a DEW point of 44°F (bubble point 37°F). The suction line reads 54°F. What is the superheat in °F?", cells: [""], inputs: [
        { col: 1, key: "sh_blend", expected: 10, hint: "Superheat always uses the DEW point for blends: 54 − 44 = 10°F. Using the bubble point would have claimed 17°F and misjudged the system by the full glide." } ] },
      { label: "DECIDE — During Call A's repair the system was opened, so it was evacuated. The standing (decay) test rises from 420 microns and levels off at 900 microns, holding there. What is the correct next action? 1) Charge now — under 1,000 is close enough. 2) Break the vacuum with dry nitrogen, sweep, and re-evacuate (triple evacuation), then repeat the decay test. 3) Pressurize and bubble-test every joint — it is certainly a leak. 4) Replace the vacuum pump.", cells: [""], inputs: [
        { col: 1, key: "decide_decay", expected: 2, hint: "A rise that PLATEAUS is the moisture/outgassing signature — the system is tight but wet. A leak rises without leveling. Dilute with dry nitrogen and pull again; charging over moisture manufactures acid." } ] },
      { label: "COMPUTE (EPA) — Call A's owner also operates a 60 lb comfort-cooling appliance. Records show 6 lb was added today, exactly 365 days after the last addition. Using leak rate = (lb added ÷ full charge) × (365 ÷ days) × 100, what is the annualized leak rate in %?", cells: [""], inputs: [
        { col: 1, key: "leak_rate", expected: 10, hint: "(6 ÷ 60) × (365 ÷ 365) × 100 = 10% — exactly the comfort-cooling trigger rate for appliances at or above 50 lb. Any faster and the 30-day repair obligation engages." } ] },
      { label: "DECIDE — How many years must the service records from these calls (dates, refrigerant types and quantities, repairs, verifications) be kept? Enter the number of years.", cells: [""], inputs: [
        { col: 1, key: "records_years", expected: 3, hint: "Three years — the recurring Section 608 retention standard for service, disposal, and sales records. If it is not written down with a date, an amount, and a name, it did not happen." } ] }
    ],
    passing: 70
  }
];
