// HVAC 208 - Module 1: A/C Equipment Families
module.exports = {
  number: 1,
  slug: "ac-equipment-families",
  title: "A/C Equipment Families",
  estTime: "3–4 hours",
  objectives: [
    "Identify the three main A/C equipment families — split systems, packaged units, and rooftop units — and where each is used.",
    "Explain what 'matched components' means and why an indoor coil and outdoor unit must be selected as a rated combination.",
    "Describe how refrigerant lines, air handlers, and furnaces combine in split-system configurations.",
    "Compare service access, installation constraints, and typical applications of each family.",
    "Read a model-number-style equipment description and state the family, capacity in tons, and configuration.",
    "Explain why replacing only one half of a split system with an unmatched component can reduce capacity and efficiency."
  ],
  sections: [
    {
      heading: "Three Families, One Refrigeration Cycle",
      html: `<p>Every air conditioner in this course runs the same vapor-compression cycle you already know: the compressor raises refrigerant pressure, the condenser rejects heat, the metering device drops pressure, and the evaporator absorbs heat. What changes between jobs is <strong>how the hardware is packaged</strong>. Equipment falls into three families, and recognizing the family in the first minute of a call tells you where components live, how air moves, and where you will connect your tools.</p><p>A <strong>split system</strong> divides the equipment between indoors and outdoors: a condensing unit outside (compressor and condenser coil) and an evaporator coil with an air handler or furnace inside, joined by refrigerant piping — the line set. A <strong>packaged unit</strong> puts the entire refrigeration circuit in one outdoor cabinet; only ductwork enters the building. A <strong>rooftop unit (RTU)</strong> is a packaged unit designed to sit on a roof curb and serve commercial space, usually with economizer dampers and larger tonnages.</p><div class="callout"><strong>Key idea:</strong> The family describes the packaging, not the cycle. A 3-ton split system and a 3-ton packaged unit move roughly the same amount of heat; they differ in where the parts sit, who can service them, and how the air is delivered.</div><p><strong>Worked example — sizing by family.</strong> A small office needs about 60,000 Btu/h of cooling. Dividing by 12,000 Btu/h per ton gives 5 tons. That load could be served by one 5-ton packaged RTU or by a 5-ton split system with the air handler in a closet. The capacity math is identical; the choice turns on roof access, duct layout, noise, and service clearances — application thinking, which is what this course is about.</p>`
    },
    {
      heading: "Split Systems in Depth",
      html: `<p>The split system is the most common residential and light-commercial arrangement. Outdoors, the condensing unit contains the compressor, condenser coil, condenser fan, and the unit's main controls. Indoors, the evaporator coil sits in the airstream of either a dedicated <strong>air handler</strong> (with its own blower and often electric heat) or a <strong>furnace</strong> whose blower moves air for both heating and cooling. Two copper lines connect them: the larger, insulated <strong>suction line</strong> carrying cool low-pressure vapor back to the compressor, and the smaller <strong>liquid line</strong> carrying high-pressure liquid to the metering device.</p><p>Because the two halves are separate, the line set becomes part of the application. Long runs and vertical lifts affect oil return, charge amount, and capacity, and the manufacturer's piping instructions — not habit — set the limits for a given model. Splits also let the noisy compressor sit outside while air distribution stays inside, which is why they dominate homes.</p><ul><li><strong>Strengths:</strong> flexible placement, quiet indoor air delivery, wide range of matched indoor options.</li><li><strong>Watch-outs:</strong> line-set length and leaks, two locations to service, indoor coil access for cleaning.</li></ul><div class="formula">Nominal tons = rated Btu/h ÷ 12,000 &nbsp;·&nbsp; Example: 36,000 Btu/h ÷ 12,000 = 3 tons</div><p>Nominal tonnage is a nameplate shorthand, not a promise: actual delivered capacity shifts with indoor airflow, outdoor temperature, and how well the two halves are matched — the subject of the next section.</p>`
    },
    {
      heading: "Matched Components: Why Halves Must Belong Together",
      html: `<p>A split system is not two independent products; it is one engineered system tested as a combination. The outdoor unit's compressor and condenser were rated with a specific indoor coil and airflow. The indoor coil's size and circuiting set how much refrigerant it can evaporate and how much superheat the metering device must control. Put an oversized or undersized coil on a condensing unit and the pair may still run — but capacity, efficiency, humidity removal, and even compressor reliability all drift away from the rating.</p><p>This is why manufacturers publish <strong>matched-system ratings</strong>: a listed combination of outdoor model, indoor model, and airflow setting with a tested capacity and efficiency. When you replace a failed condensing unit, the professional question is not just "what tonnage?" but "what is this unit rated to pair with, and does the existing indoor coil match?" An old coil designed for a different refrigerant or metering style is a common hidden problem in replacement work.</p><div class="callout"><strong>Key idea:</strong> Mismatching shows up as symptoms you will chase in Module 12 — weak capacity, poor dehumidification, abnormal pressures — even though no single part has "failed." Always verify the combination before condemning a component.</div><p><strong>Worked example.</strong> A 3-ton outdoor unit is paired with an indoor coil whose rating plate lists it for a smaller system and a different metering device. On a hot day the suction pressure runs low and the supply air is barely cool. Before adding refrigerant, the application check — is this coil a listed match, and is the metering device the type the outdoor unit expects? — prevents turning a matching problem into an overcharge problem.</p>`
    },
    {
      heading: "Packaged Units and Rooftop Units",
      html: `<p>In a <strong>packaged unit</strong>, compressor, condenser, evaporator, metering device, and blower all live in one weatherproof cabinet outside the conditioned space. Conditioned air travels through supply and return ducts connected directly to the cabinet. Packaged units serve homes without indoor equipment space, small shops, and additions. Because the whole refrigerant circuit is factory-assembled and factory-charged, there is no line set to evacuate and charge in the field — but the cabinet must still be level, sealed to its duct connections, and accessible for coil cleaning and blower service.</p><p><strong>Rooftop units</strong> scale the packaged idea up for commercial buildings. An RTU sits on a <strong>roof curb</strong> that supports it and seals it to the ductwork below. Larger RTUs add features a house never needs: an <strong>economizer</strong> that brings in cool outdoor air when it can cool for free, multiple compressors or stages for part-load operation, and powered exhaust. Servicing an RTU means roof safety, panel discipline in wind, and checking that condensate cannot pool where it damages the roof or the unit.</p><ul><li><strong>Gas/electric packaged:</strong> gas heat plus electric cooling in one cabinet.</li><li><strong>Packaged heat pump:</strong> one cabinet that heats and cools by reversing.</li><li><strong>RTU:</strong> packaged cooling (often with heat) built for curb mounting and commercial controls.</li></ul><p>Application rule: choose the family that fits the building's structure and service reality, then match components inside that family — never the other way around.</p>`
    },
    {
      heading: "Choosing and Verifying on a Real Call",
      html: `<p>On a service or survey call, run this family check before gauges come out. First, name the family: split, packaged, or rooftop. Second, record both nameplates on a split — outdoor model and indoor model — plus the metering device type. Third, note the air mover: air handler or furnace, and its blower setting if accessible. Fourth, look at the distribution: duct connections on a packaged unit, curb and economizer on an RTU, line-set route on a split. These four observations frame every measurement that follows.</p><p><strong>Worked example — a survey.</strong> You are asked to quote a replacement for a 20-year-old split system. The outdoor plate reads 48,000 Btu/h nominal (4 tons), the furnace is older than the coil, and the homeowner wants "the same size." Your application answer: verify the actual load and duct capacity, confirm a listed matched combination for the new outdoor unit and coil, and flag that reusing the old coil risks the mismatch symptoms from Section 3. Same-size thinking ignores that the original may have been oversized all along.</p><div class="callout"><strong>Key idea:</strong> Equipment selection is an application decision: building, ducts, service access, and matched ratings — in that order. Modules 8–10 will show how airflow and capacity testing prove whether the chosen family is actually delivering what its nameplate promises.</div><p>Keep one discipline from day one: write down model and serial numbers for <em>every</em> component, not just the box that failed. Most "mystery" performance problems stop being mysterious once the combination on paper is compared with the combination in the building.</p>`
    }
  ],
  keyTerms: [
    { term: "Split system", def: "A/C system with the condenser/compressor outdoors and the evaporator coil and air mover indoors, joined by a line set." },
    { term: "Packaged unit", def: "Self-contained unit with the complete refrigeration circuit and blower in one outdoor cabinet; only ducts enter the building." },
    { term: "Rooftop unit (RTU)", def: "A packaged unit designed to mount on a roof curb and serve commercial space." },
    { term: "Roof curb", def: "The raised frame that supports an RTU and seals it to the ductwork below." },
    { term: "Condensing unit", def: "The outdoor half of a split system: compressor, condenser coil, fan, and controls." },
    { term: "Air handler", def: "Indoor unit with a blower and evaporator coil (and often electric heat) that moves conditioned air." },
    { term: "Line set", def: "The suction and liquid refrigerant lines connecting a split system's indoor and outdoor sections." },
    { term: "Suction line", def: "The larger, insulated line carrying low-pressure vapor from the evaporator to the compressor." },
    { term: "Liquid line", def: "The smaller line carrying high-pressure liquid refrigerant to the metering device." },
    { term: "Matched system", def: "An outdoor unit and indoor coil combination tested and rated together by the manufacturer." },
    { term: "Nominal tonnage", def: "Nameplate capacity shorthand: rated Btu/h divided by 12,000." },
    { term: "Economizer", def: "RTU damper system that uses cool outdoor air for cooling when conditions allow." },
    { term: "Metering device", def: "Component that drops refrigerant pressure before the evaporator; type must suit the matched combination." },
    { term: "Evaporator coil", def: "Indoor coil where refrigerant absorbs heat from the air passing over it." },
    { term: "Condenser coil", def: "Outdoor coil where refrigerant rejects heat to outdoor air." },
    { term: "Gas/electric packaged unit", def: "Packaged unit combining gas heating with electric air conditioning." },
    { term: "Packaged heat pump", def: "Single-cabinet unit that provides both heating and cooling by reversing the cycle." },
    { term: "Application", def: "Matching equipment type, capacity, and configuration to the building, ducts, and service conditions." }
  ],
  video: {
    title: "3D How Refrigeration and Air Conditioning Works P1 - Components",
    embedUrl: "https://www.youtube.com/embed/p6GXJdRUz9E",
    note: "A 3D component tour of the refrigeration cycle from HVAC School. Use it to anchor where the compressor, condenser, metering device, and evaporator sit — then picture those same parts rearranged into split, packaged, and rooftop cabinets as this module describes.",
    more: []
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A condensing unit nameplate lists 42,000 Btu/h nominal capacity. What is its nominal tonnage?</p>", solution: "<p><strong>Answer: 3.5 tons.</strong> Step 1: Use nominal tons = Btu/h ÷ 12,000. Step 2: 42,000 ÷ 12,000 = 3.5. Step 3: Remember this is a rating shorthand; delivered capacity varies with conditions and matching.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A technician finds the compressor and condenser outdoors and the coil and blower in a basement closet, joined by two copper lines. Name the family and the two lines.</p>", solution: "<p><strong>Answer: a split system.</strong> Step 1: Components in two locations = split. Step 2: The larger insulated line is the suction line (low-pressure vapor to the compressor). Step 3: The smaller line is the liquid line (high-pressure liquid to the metering device).</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Why can replacing only the outdoor unit of a split system, while keeping an old unmatched indoor coil, reduce performance even if the new unit works perfectly?</p>", solution: "<p><strong>Answer:</strong> Step 1: Capacity and efficiency ratings are tested for a listed combination of outdoor unit, indoor coil, and airflow. Step 2: A coil sized or circuited for another unit changes evaporation and metering behavior. Step 3: The result can be low capacity, poor humidity removal, and abnormal pressures — with no single failed part.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A small retail shop has no indoor mechanical room and a flat roof with ductwork below. Which family fits best, and what mounting part does it need?</p>", solution: "<p><strong>Answer: a rooftop unit on a roof curb.</strong> Step 1: No indoor space rules out a split air handler. Step 2: A packaged RTU keeps all equipment on the roof. Step 3: The curb supports the unit and seals it to the supply and return ducts below.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> An RTU's economizer is stuck closed on a mild day when outdoor air is cool and dry. What is lost?</p>", solution: "<p><strong>Answer: free cooling.</strong> Step 1: An economizer brings in suitable outdoor air so the compressors can stay off or unload. Step 2: Stuck closed, the unit must run mechanical cooling for a load the outdoor air could have carried. Step 3: Energy use rises even though the space may still reach setpoint — an application fault, not a refrigeration failure.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> List the four observations of the family check in order.</p>", solution: "<p><strong>Answer:</strong> Step 1: Name the family (split, packaged, rooftop). Step 2: Record all nameplates — outdoor and indoor on a split — plus metering type. Step 3: Identify the air mover and its setting. Step 4: Inspect distribution: ducts, curb/economizer, or line-set route. These frame every later measurement.</p>" }
  ],
  quiz: [
    { q: "A system with the compressor outdoors and the evaporator coil in an indoor air handler is a:", choices: ["Packaged unit", "Split system", "Rooftop unit", "Chiller"], answer: 1, explanation: "Correct: (b). Separating condensing unit and indoor section, joined by a line set, defines a split system. (a) A packaged unit keeps the whole circuit in one cabinet. (c) An RTU is a packaged unit on a roof curb. (d) A chiller cools water, not air directly at the coil." },
    { q: "The larger, insulated refrigerant line in a split system is the:", choices: ["Liquid line", "Discharge line", "Suction line", "Condensate line"], answer: 2, explanation: "Correct: (c). The suction line carries low-pressure vapor to the compressor and is insulated to limit heat gain. (a) The liquid line is the smaller, usually uninsulated line. (b) The discharge line is internal between compressor and condenser. (d) The condensate line carries water, not refrigerant." },
    { q: "A 'matched system' means:", choices: ["Both units are the same color and brand year", "The outdoor unit and indoor coil are a manufacturer-listed, tested combination", "The tonnage of the coil is always one size larger", "Any coil of equal tonnage may be used"], answer: 1, explanation: "Correct: (b). Ratings are published for specific tested combinations. (a) Appearance is irrelevant. (c) Oversizing the coil by rule is not matching. (d) Equal nominal tonnage alone does not make a tested combination." },
    { q: "Nominal tonnage of a 60,000 Btu/h unit is:", choices: ["4 tons", "6 tons", "5 tons", "3 tons"], answer: 2, explanation: "Correct: (c). 60,000 ÷ 12,000 = 5 tons. (a) 4 tons would be 48,000 Btu/h. (b) 6 tons would be 72,000 Btu/h. (d) 3 tons would be 36,000 Btu/h." },
    { q: "An economizer on an RTU is used to:", choices: ["Add humidity in winter", "Use suitable outdoor air for cooling", "Boost refrigerant pressure", "Drain condensate"], answer: 1, explanation: "Correct: (b). Economizer dampers bring in cool outdoor air to carry the cooling load with less compressor work. (a) Humidification is a separate accessory. (c) Dampers do not affect refrigerant pressure. (d) Condensate is handled by the drain pan and trap." },
    { q: "Which is a packaged-unit characteristic?", choices: ["Factory-assembled complete refrigerant circuit in one cabinet", "A line set charged in the field", "Indoor compressor", "Two nameplates that must be matched"], answer: 0, explanation: "Correct: (a). A packaged unit contains the full circuit, factory-charged. (b) Field line sets belong to split systems. (c) The compressor sits in the outdoor cabinet. (d) Matching two separate halves is a split-system concern." },
    { q: "Reusing an old, unmatched indoor coil on a new condensing unit most risks:", choices: ["Higher-than-rated efficiency", "No effect if tonnage matches", "Reduced capacity and abnormal pressures", "Automatic warranty improvement"], answer: 2, explanation: "Correct: (c). Coil size, circuiting, and metering type change system behavior, causing weak capacity and odd pressures. (a) Mismatches reduce, not raise, tested efficiency. (b) Equal tonnage does not equal a tested match. (d) Unlisted combinations typically jeopardize, not improve, coverage." },
    { q: "The roof curb's main jobs are to:", choices: ["Filter the air and silence the fan", "Support the RTU and seal it to the ductwork", "Store refrigerant", "Step down control voltage"], answer: 1, explanation: "Correct: (b). The curb carries the unit's weight and provides the sealed transition to ducts below. (a) Filtration happens inside the unit. (c) Refrigerant stays in the unit's circuit. (d) Voltage is handled by the unit's transformer." }
  ],
  studyGuide: `
<h3>Module 1 — A/C Equipment Families: Quick Reference</h3>
<p><strong>Three families:</strong> Split (condensing unit out, coil + air mover in, line set between) · Packaged (whole circuit in one outdoor cabinet) · Rooftop unit (packaged, curb-mounted, commercial features like economizers).</p>
<div class="formula">Nominal tons = rated Btu/h ÷ 12,000</div>
<p><strong>Line set:</strong> suction line = large, insulated, low-pressure vapor to compressor; liquid line = small, high-pressure liquid to metering device.</p>
<p><strong>Matched system:</strong> outdoor unit + indoor coil + airflow tested and listed together. Mismatch = weak capacity, poor dehumidification, abnormal pressures, no single failed part.</p>
<p><strong>Family check on every call:</strong> 1) name the family, 2) record every nameplate + metering type, 3) identify the air mover, 4) inspect distribution (ducts, curb/economizer, line-set route).</p>
<p><strong>Economizer:</strong> uses suitable outdoor air for free cooling on RTUs; stuck dampers waste energy without necessarily losing setpoint.</p>
<p><strong>Watch out:</strong> nominal tonnage is a shorthand, not delivered capacity — Modules 8–10 prove delivery with airflow and capacity measurements.</p>
`
};
