// HVAC 208 - Module 3: Heat Pump Defrost, Auxiliary & Emergency Heat
module.exports = {
  number: 3,
  slug: "heat-pump-defrost-auxiliary-emergency-heat",
  title: "Heat Pump Defrost, Auxiliary & Emergency Heat",
  estTime: "3–4 hours",
  objectives: [
    "Explain why frost forms on the outdoor coil in heating and how it degrades capacity and airflow.",
    "Compare time/temperature and demand defrost initiation and describe normal termination.",
    "Describe the full defrost event sequence: reversing valve shift, outdoor fan stop, auxiliary heat start.",
    "Explain auxiliary heat staging and the role of outdoor thermostats and control logic.",
    "Distinguish auxiliary heat from emergency heat and state how each is selected and used.",
    "Explain dual-fuel (hybrid) changeover logic and the role of the fossil-fuel kit and lockouts."
  ],
  sections: [
    {
      heading: "Why Heat Pumps Frost — and Why It Matters",
      html: `<p>In heating mode the outdoor coil is an evaporator running colder than the outdoor air — cold enough that its surface sits below freezing whenever the weather is cool and damp. Moisture in the air condenses on the coil and freezes, building <strong>frost</strong> between the fins. Frost is an insulator and an airflow blocker at the same time: the coil absorbs less heat, the outdoor fan moves less air, capacity falls, run times stretch, and the compressor works across a wider lift for less result.</p><p>Frosting is worst not on the coldest dry days but in damp weather near freezing, when the air carries plenty of moisture and the coil is well below freezing. A heat pump that never defrosted would eventually become a block of ice that moves almost no air and delivers almost no heat. So every air-source heat pump has a <strong>defrost control</strong> whose job is to notice frost (directly or by schedule) and melt it before performance collapses.</p><div class="callout"><strong>Key idea:</strong> Some frost between defrosts is normal heat pump behavior. The faults are defrosting too rarely (ice build-up, lost capacity), too often (wasted energy, cold drafts, high bills), or never terminating properly. Diagnosis starts by watching one complete defrost event, as the lab for this course requires.</div><p>Defrost is simply the cooling cycle run briefly in reverse: hot discharge gas goes to the outdoor coil and melts the frost from the inside out. That one fact explains the whole event sequence in Section 3.</p>`
    },
    {
      heading: "Initiation and Termination: Time/Temperature vs. Demand",
      html: `<p>The traditional control is <strong>time/temperature defrost</strong>. A timer accumulates compressor run time in heating; when a chosen interval is reached, the board checks a <strong>defrost thermostat (sensor)</strong> on the outdoor coil. If the coil is cold enough to suggest frost, defrost starts. If the coil is warm, the board waits and checks again later. Intervals are set with board jumpers or switches per the manufacturer's instructions — the right interval is the one that matches the climate and the unit, not a universal number.</p><p><strong>Demand defrost</strong> systems measure conditions — typically coil temperature compared with outdoor air temperature — and start defrost only when the gap indicates real frost is choking the coil. Demand control avoids the wasted defrosts a timer orders on cold, dry days when there is little moisture to freeze.</p><p><strong>Termination</strong> is the mirror decision: defrost ends when the coil sensor warms enough to show the frost is gone, or when a maximum time limit forces an end so the house is not left without heat. A sensor that never reports "warm" produces marathon defrosts and cold indoor air; a sensor that reports warm too early leaves ice behind that grows cycle after cycle.</p><ul><li><strong>Initiation fault signs:</strong> heavy ice, long run times, rising bills in damp near-freezing weather.</li><li><strong>Termination fault signs:</strong> frequent long defrosts, cold supply air, auxiliary heat running constantly.</li></ul><p>Always test sensors and board logic against the manufacturer's procedure for that model — sensor values and pin tests are model-specific, and this course deliberately teaches the method rather than invented universal test numbers.</p>`
    },
    {
      heading: "Anatomy of One Defrost Event",
      html: `<p>Watch a healthy defrost and you will see four coordinated actions. <strong>First,</strong> the defrost board shifts the reversing valve into the cooling position, sending hot discharge gas into the frosted outdoor coil. <strong>Second,</strong> the outdoor fan stops — running it would blow the melting heat away and slow the melt. <strong>Third,</strong> the board (through the thermostat's auxiliary heat call) brings on <strong>auxiliary heat</strong> indoors, because the indoor coil is now absorbing heat from the house air; without aux heat the supply air turns cold and occupants feel the system "blowing cold." <strong>Fourth,</strong> when the coil sensor reports the frost is melted (or the safety time limit hits), the valve shifts back, the outdoor fan restarts, and aux heat drops out.</p><p>The visible signatures of a normal event: a whoosh as the valve shifts, steam rising off the outdoor coil as frost melts, water running from under the unit, then a second whoosh as heating resumes. The event typically lasts minutes, not seconds and not half an hour.</p><div class="callout"><strong>Key idea:</strong> During defrost the system is literally air-conditioning the house while melting ice. Auxiliary heat during defrost is not waste — it tempers the air the indoor coil is chilling. Aux heat that fails to start during defrost is a comfort fault even when heating works normally otherwise.</div><p>Field skill: before replacing a board, force a defrost using the manufacturer's test method (many boards have speed-up/test pins) and observe all four actions. The step that fails names the component to test next — board, valve solenoid, fan circuit, sensor, or aux heat circuit.</p>`
    },
    {
      heading: "Auxiliary Heat: Staging and Control",
      html: `<p><strong>Auxiliary heat</strong> is the supplemental heat source — usually electric resistance strips in the air handler, sometimes a furnace — that the controls stage in automatically. It has three jobs: cover the load below the balance point (Module 2), temper the air during defrost (Section 3), and recover when the thermostat is raised several degrees at once. Controls stage aux heat in steps rather than all at once, so only the capacity actually needed runs; many systems also use an <strong>outdoor thermostat or board lockout</strong> that limits aux heat use when outdoor temperatures are mild and the heat pump alone should be able to carry the load.</p><p>Staging faults cut both ways. Aux heat that never stages leaves the house cold below the balance point and untempered during defrost. Aux heat that stages too eagerly — a mis-set lockout, a thermostat calling aux on every small droop — silently converts an efficient heat pump into an expensive resistance heater, and the only symptom may be the electric bill.</p><div class="callout"><strong>Key idea:</strong> The classic "heat pump works but bills are huge" complaint is usually auxiliary heat running when it should not — or running because the heat pump is underperforming from low airflow or frost and the controls are compensating. Measure before you blame the strips: check heat pump performance and aux status separately, as the defrost lab drills.</div><p>Never disable auxiliary heat as a "fix" for high bills. It is a required part of the system design; the fix is finding why it is being called.</p>`
    },
    {
      heading: "Emergency Heat and Dual-Fuel Changeover",
      html: `<p><strong>Emergency heat</strong> is not a separate heater — it is a manual thermostat mode that locks out the heat pump completely and runs only the auxiliary source. It exists for breakdowns: if the compressor or refrigeration circuit fails, the occupant selects emergency heat and stays warm on the backup source until service arrives. The trade-off is cost — resistance heat is the most expensive way to heat — so emergency heat is a bridge, not a setting. A system left in emergency heat for weeks after a repair quote is a customer-education opportunity, not a control fault.</p><p><strong>Dual fuel (hybrid)</strong> systems pair a heat pump with a gas or oil furnace as the auxiliary source. Here the changeover logic matters more: the heat pump and furnace must never try to heat the indoor coil at the same time in a way the manufacturer prohibits, and at the <strong>changeover (economic balance) point</strong> the controls switch fully to the furnace because fuel heat is cheaper per delivered Btu below that temperature. A <strong>fossil-fuel kit</strong> or the thermostat's dual-fuel logic enforces the switchover and any outdoor lockouts.</p><ul><li><strong>Auxiliary:</strong> automatic, stages alongside the heat pump.</li><li><strong>Emergency:</strong> manual, heat pump locked out, backup heat only.</li><li><strong>Dual-fuel changeover:</strong> automatic full switch to the furnace at the set balance point.</li></ul><p>On every heat pump call, end by confirming the thermostat mode with the customer: correct mode, correct aux behavior, and what emergency heat is for. Half of "heat pump emergencies" are settings, and the other half get clearer once settings are eliminated.</p>`
    }
  ],
  keyTerms: [
    { term: "Defrost cycle", def: "Brief reversal into the cooling position that sends hot gas to the outdoor coil to melt accumulated frost." },
    { term: "Defrost board", def: "Control that times or senses the need for defrost and coordinates the valve, fan, and auxiliary heat." },
    { term: "Defrost thermostat/sensor", def: "Coil-mounted temperature sensor the board uses to permit initiation and command termination." },
    { term: "Time/temperature defrost", def: "Control method that checks for defrost need at timed intervals and initiates only if the coil is cold enough." },
    { term: "Demand defrost", def: "Control method that initiates defrost based on measured conditions indicating actual frost, not just elapsed time." },
    { term: "Termination", def: "Ending defrost when the coil sensor reports frost is melted, or when a maximum time limit is reached." },
    { term: "Auxiliary heat", def: "Supplemental heat staged automatically to help below the balance point, during defrost, and on recovery." },
    { term: "Emergency heat", def: "Manual thermostat mode that locks out the heat pump and runs only the auxiliary heat source." },
    { term: "Staging", def: "Bringing auxiliary heat capacity on in steps so only the needed amount runs." },
    { term: "Outdoor thermostat lockout", def: "Control that limits auxiliary heat use at mild outdoor temperatures where the pump should carry the load." },
    { term: "Dual fuel (hybrid)", def: "System pairing a heat pump with a fossil-fuel furnace as the auxiliary/changeover heat source." },
    { term: "Fossil-fuel kit", def: "Control package that manages dual-fuel changeover and prevents prohibited simultaneous operation." },
    { term: "Changeover point", def: "Outdoor temperature setting where a dual-fuel system switches fully from heat pump to furnace heat." },
    { term: "Tempering", def: "Using auxiliary heat during defrost to offset the cooling effect at the indoor coil so supply air stays warm." },
    { term: "Frost accumulation", def: "Ice built on the outdoor coil in heating that insulates the coil and blocks airflow until defrosted." },
    { term: "Test pins / speed-up", def: "Manufacturer-provided board terminals or method for forcing a defrost event during diagnosis." }
  ],
  video: {
    title: "Heat Pump Troubleshooting- Testing Defrost Board to Force Defrost!",
    embedUrl: "https://www.youtube.com/embed/5c5R3uYSy5U",
    note: "A field video from AC Service Tech on testing a defrost board and forcing a defrost event. Watch how the technician makes the board reveal which step of the event works and which fails — the same observe-first method this module teaches.",
    more: [
      { title: "Heat Pump Defrost Thermostat Sensor DFT Testing!", url: "https://www.youtube.com/watch?v=U-U2offDWg0" },
      { title: "How To Troubleshoot a Time Temperature Defrost Failure on a Heat Pump", url: "https://www.youtube.com/watch?v=hfJXpPhlYtg" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Put these defrost-event actions in order: (a) outdoor fan restarts and aux heat drops out, (b) reversing valve shifts to the cooling position, (c) auxiliary heat starts indoors, (d) outdoor fan stops.</p>", solution: "<p><strong>Answer: b, d, c, then a.</strong> Step 1: The board shifts the valve to send hot gas outdoors. Step 2: The outdoor fan stops so it does not blow the melting heat away. Step 3: Aux heat tempers indoor air. Step 4: On termination the valve shifts back, the fan restarts, and aux drops out.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A heat pump defrosts on schedule even on cold, dry days with no frost on the coil. Which control type is it probably using, and what does the upgrade alternative do differently?</p>", solution: "<p><strong>Answer: time/temperature; demand defrost measures actual frost conditions.</strong> Step 1: A timer checks at intervals and, if the coil sensor is cold, defrosts — cold coil alone does not prove frost. Step 2: Demand defrost compares coil and outdoor-air conditions to infer real frost. Step 3: Result: fewer wasted defrosts on dry days.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> During every defrost, a home's supply air turns cold for several minutes, though heating is normal otherwise. What should you check first?</p>", solution: "<p><strong>Answer: whether auxiliary heat is being brought on during defrost.</strong> Step 1: In defrost the indoor coil absorbs house heat, chilling supply air. Step 2: Aux heat is supposed to temper that air. Step 3: Test the aux call from the board/thermostat and the strip circuit before suspecting the refrigeration side.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A defrost sensor never reports the coil as warm. Predict two symptoms.</p>", solution: "<p><strong>Answer: over-long defrosts and cold indoor air / high aux use.</strong> Step 1: Termination depends on the sensor reporting warm (or the maximum-time limit). Step 2: Without that signal, defrost runs to the time limit every cycle. Step 3: The house is cooled longer each event and aux heat runs longer to compensate.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A customer has run emergency heat for two months after a compressor failure because 'it works fine.' Explain the problem with this plan.</p>", solution: "<p><strong>Answer: emergency heat is a bridge, not a heating plan.</strong> Step 1: Emergency mode locks out the heat pump and runs only the backup source. Step 2: If the backup is electric resistance, it is the most expensive heat available. Step 3: The correct path is repairing the heat pump and returning the thermostat to normal heat mode.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> On a dual-fuel system, why must the heat pump shut down at the changeover point instead of both sources heating together?</p>", solution: "<p><strong>Answer:</strong> Step 1: At the changeover (economic balance) point, furnace heat is the cheaper source per delivered Btu. Step 2: Manufacturer logic — via the fossil-fuel kit or thermostat — switches fully to the furnace. Step 3: Simultaneous operation in prohibited configurations can overheat the indoor coil/plenum and wastes the cheaper-source advantage.</p>" }
  ],
  quiz: [
    { q: "Frost builds on the outdoor coil in heating because:", choices: ["The coil runs below freezing in cool, damp air and airborne moisture freezes on it", "The condenser fan runs backward", "Auxiliary heat leaks outdoors", "The refrigerant is overcharged"], answer: 0, explanation: "Correct: (a). The outdoor coil is a cold evaporator; moisture condenses and freezes on its surface. (b) Fan direction affects airflow, not the freezing of moisture. (c) Aux heat is indoors and does not frost the coil. (d) Charge level does not create the moisture-freezing mechanism." },
    { q: "During defrost, the outdoor fan stops in order to:", choices: ["Save the fan motor", "Avoid blowing away the heat that is melting the frost", "Start auxiliary heat", "Raise indoor airflow"], answer: 1, explanation: "Correct: (b). Hot gas must heat the coil, not the neighborhood; a running fan would strip the heat away. (a) Motor wear is not the reason for the stop. (c) Aux heat is started by the board/thermostat circuit, not by the fan stopping. (d) The outdoor fan has no effect on indoor airflow." },
    { q: "Demand defrost differs from time/temperature defrost because it:", choices: ["Defrosts every 30 minutes exactly", "Never uses a coil sensor", "Initiates based on measured conditions indicating actual frost", "Runs the outdoor fan during defrost"], answer: 2, explanation: "Correct: (c). Demand control compares conditions (typically coil vs. outdoor air) to detect real frost. (a) Fixed-interval initiation describes a timer approach. (b) Demand systems still rely on sensors — more of them, not fewer. (d) The fan still stops during the melt in either method." },
    { q: "Auxiliary heat during defrost serves to:", choices: ["Melt the outdoor frost faster", "Temper indoor air that the indoor coil is chilling", "Charge the system", "Defrost the indoor coil"], answer: 1, explanation: "Correct: (b). In defrost the indoor coil absorbs house heat; aux strips offset that so supply air stays warm. (a) Melting is done by hot discharge gas outdoors. (c) Aux heat plays no role in charging. (d) The indoor coil does not frost in this mode — it is absorbing heat, not below the room's dew point in a frosting sense." },
    { q: "Emergency heat mode:", choices: ["Stages the heat pump and strips together", "Is selected automatically by the board", "Locks out the heat pump and runs only the auxiliary source, selected manually", "Is the same as demand defrost"], answer: 2, explanation: "Correct: (c). Emergency heat is a manual thermostat selection for breakdowns. (a) Staging both sources describes auxiliary operation. (b) No board selects it automatically. (d) Defrost is a refrigeration event, unrelated to the emergency setting." },
    { q: "A sensor that reports the coil warm too early will cause:", choices: ["Marathon defrosts", "Defrosts that end before the ice is gone, so ice grows cycle by cycle", "A tripped high-pressure switch", "Emergency heat to engage"], answer: 1, explanation: "Correct: (b). Early termination leaves frost behind; residue builds each cycle. (a) Marathon defrosts come from a sensor that never reports warm. (c) Pressure switches are not driven by the defrost sensor. (d) Emergency heat is manual and unrelated." },
    { q: "The most likely cause of 'heat pump heats fine but the electric bill doubled' is:", choices: ["Auxiliary heat running when it should not", "The reversing valve shifting", "Normal defrost steam", "A clean outdoor coil"], answer: 0, explanation: "Correct: (a). Resistance aux heat is expensive; eager staging or a heat pump fault that forces aux reliance doubles bills quietly. (b) Valve shifts are normal operation. (c) Steam is the visible sign of a normal melt. (d) A clean coil improves efficiency, lowering bills." },
    { q: "In a dual-fuel system, the fossil-fuel kit's job is to:", choices: ["Burn fuel more cleanly", "Manage changeover between heat pump and furnace and prevent prohibited simultaneous operation", "Replace the defrost board", "Meter refrigerant to the outdoor coil"], answer: 1, explanation: "Correct: (b). The kit (or thermostat logic) enforces switchover at the set point and lockouts. (a) Combustion quality is set by the furnace itself. (c) The defrost board remains a separate control. (d) Metering is done by the outdoor metering device." }
  ],
  studyGuide: `
<h3>Module 3 — Defrost, Auxiliary & Emergency Heat: Quick Reference</h3>
<p><strong>Frost:</strong> outdoor coil in heating is a below-freezing evaporator; damp near-freezing weather frosts fastest. Frost insulates the coil and blocks airflow.</p>
<p><strong>Initiation:</strong> time/temperature (timer + cold-coil permission) vs. demand (measured coil-vs-air conditions = real frost). <strong>Termination:</strong> coil sensor warm, or maximum-time limit.</p>
<p><strong>One defrost event, in order:</strong> 1) reversing valve shifts to cooling position, 2) outdoor fan stops, 3) auxiliary heat tempers indoor air, 4) termination — valve back, fan on, aux off. Steam off the coil is normal.</p>
<p><strong>Auxiliary heat:</strong> automatic, staged — balance-point help, defrost tempering, recovery. Never disable it as a fix; find why it is being called.</p>
<p><strong>Emergency heat:</strong> manual mode, heat pump locked out, backup heat only — a bridge during breakdowns.</p>
<p><strong>Dual fuel:</strong> full changeover to the furnace at the economic balance point, enforced by a fossil-fuel kit or thermostat logic.</p>
<p><strong>Diagnose by watching:</strong> force a defrost by the manufacturer's method and observe all four actions; the failed step names the part to test.</p>
`
};
