// HVAC 208 - Module 5: Absorption Refrigeration & Evaporative Cooling
module.exports = {
  number: 5,
  slug: "absorption-refrigeration-evaporative-cooling",
  title: "Absorption Refrigeration & Evaporative Cooling",
  estTime: "3–4 hours",
  objectives: [
    "Explain how an absorption cycle produces cooling using heat input instead of a compressor.",
    "Identify the lithium bromide–water pair and the roles of generator, absorber, condenser, and evaporator.",
    "Describe crystallization risk in lithium bromide systems and what conditions promote it.",
    "Explain why absorption fits applications with waste heat, steam, or cogeneration.",
    "Explain direct and indirect evaporative cooling and the wet-bulb limit on both.",
    "Select between vapor-compression, absorption, and evaporative approaches for a stated application."
  ],
  sections: [
    {
      heading: "Cooling Driven by Heat: The Absorption Idea",
      html: `<p>Every system so far in this course compresses refrigerant vapor with a machine. An <strong>absorption</strong> system replaces the compressor with chemistry and heat. It uses two fluids: a <strong>refrigerant</strong> that evaporates to produce cooling, and an <strong>absorbent</strong> that soaks up that refrigerant vapor the way a sponge takes water. Heat applied later drives the refrigerant back out of the absorbent, and the cycle repeats. The only moving part of consequence is a small solution pump — the "compression" is done by absorbing and then boiling the refrigerant out of solution.</p><p>The most common large-system pair is <strong>water as refrigerant and lithium bromide (LiBr) as absorbent</strong>. Water evaporating under deep vacuum in the evaporator chills the chilled-water loop; the LiBr solution in the absorber eagerly absorbs that water vapor, which keeps the evaporation going. Heat in the <strong>generator</strong> — from steam, hot water, direct firing, or recovered waste heat — boils the water back out of the diluted solution so it can be condensed and evaporated again.</p><div class="callout"><strong>Key idea:</strong> Absorption trades electricity for heat. Where heat is cheap or free — waste heat from a process, exhaust heat from a generator (cogeneration/trigeneration), district steam — an absorption chiller can be the economical machine even though it needs more heat input per ton than a compressor needs electricity.</div><p>Because the refrigerant is water evaporating under vacuum, absorption machines operate at very low pressures throughout — a service world of vacuum integrity rather than high-pressure gauges.</p>`
    },
    {
      heading: "Walking the Absorption Cycle",
      html: `<p>Follow the refrigerant (water) first. In the <strong>evaporator</strong>, liquid water refrigerant sprays over chilled-water tubes under vacuum and evaporates at low temperature, absorbing heat from the building loop — the cooling effect. The vapor flows to the <strong>absorber</strong>, where concentrated LiBr solution absorbs it; the heat released by absorption is carried away by cooling (tower) water, and the now-diluted solution is pumped to the <strong>generator</strong>. Heat there boils the water out of the solution; the vapor goes to the <strong>condenser</strong>, condenses on tower-water tubes, and returns through an expansion device to the evaporator. The reconcentrated LiBr flows back to the absorber.</p><p>A <strong>heat exchanger</strong> between the hot concentrated solution leaving the generator and the cooler diluted solution heading to it recovers heat internally and is essential to the machine's efficiency. Solution concentration is the control variable: too concentrated, or cooled too far in the wrong place, and the LiBr can <strong>crystallize</strong> — literally solidify in the piping — shutting the machine down until it is carefully heated and diluted back into solution.</p><ul><li><strong>Evaporator:</strong> water refrigerant evaporates under vacuum → cooling.</li><li><strong>Absorber:</strong> LiBr absorbs vapor; tower water removes absorption heat.</li><li><strong>Generator:</strong> applied heat boils refrigerant out of solution.</li><li><strong>Condenser:</strong> refrigerant vapor condenses on tower-water tubes.</li></ul><div class="callout"><strong>Key idea:</strong> Crystallization is the signature absorption fault: high solution concentration plus low temperature in the heat exchanger or absorber path. Prevention is control of generator heat input and cooling-water temperatures per the manufacturer — never improvised.</div>`
    },
    {
      heading: "Where Absorption Earns Its Place",
      html: `<p>Absorption is not competing with vapor-compression on a level field; it wins where the field tilts. <strong>Waste heat:</strong> a factory exhausting steam or hot water it cannot use can turn that liability into cooling. <strong>Cogeneration:</strong> a site generating its own electricity produces engine or turbine exhaust heat — pairing it with absorption (trigeneration: power + heating + cooling) uses fuel far more completely. <strong>Demand economics:</strong> where electric demand charges punish summer compressor peaks, shifting cooling load to gas or steam heat can cut operating cost even at lower thermal efficiency.</p><p>Absorption also appears in small, compressor-free applications through the related ammonia–water cycle: propane-fired refrigerators in recreational vehicles and off-grid cabins cool silently with a small flame and no compressor at all. Same principle — heat drives the cycle, an absorbent captures the refrigerant vapor — different fluid pair and scale.</p><div class="callout"><strong>Key idea:</strong> Ask "what energy is cheap or free here?" before asking "which machine is most efficient?" An absorption chiller fed on heat that would otherwise be vented can beat a high-efficiency electric chiller on total operating cost — and lose badly where heat must be bought at full price solely to run it.</div><p>Service reality: absorption work emphasizes vacuum tightness, solution chemistry checks by specialists, cooling-water temperature control, and crystallization prevention — a different daily skill set from compressor work, but the same load-and-loops plant thinking from Module 4.</p>`
    },
    {
      heading: "Evaporative Cooling: The Wet-Bulb Limit",
      html: `<p><strong>Evaporative cooling</strong> cools air directly with water: pass air through wetted media, some water evaporates into the air, and the evaporation absorbs heat from the air itself, dropping its dry-bulb temperature while raising its humidity. This is the cooling tower's trick applied to the airstream, and it is also how a residential "swamp cooler" works in dry climates. The floor on how cold the air can get is the outdoor <strong>wet-bulb temperature</strong>: evaporation stops being effective as air approaches saturation.</p><p><strong>Direct evaporative cooling</strong> puts the wetted media in the supply airstream — simplest and cheapest, but it adds all that moisture to the space. <strong>Indirect evaporative cooling</strong> cools a secondary airstream or a heat-exchange surface and cools the supply air without adding moisture to it; it cannot go as far alone, but it preserves indoor humidity control and is often combined with direct stages or conventional cooling in commercial air handlers.</p><div class="formula">Evaporative cooling limit: supply air can approach, but never go below, the outdoor wet-bulb temperature</div><p><strong>Worked reasoning — climate decides.</strong> On a dry desert afternoon the gap between dry-bulb and wet-bulb is wide, so evaporation has a lot of cooling to give. On a humid Gulf-Coast afternoon the gap is narrow — the air is already nearly saturated — and evaporative cooling can do very little. Same equipment, opposite applications: the psychrometrics, not the catalog, makes the call.</p>`
    },
    {
      heading: "Choosing Among the Three Approaches",
      html: `<p>Pull the module together as an application decision table in words. <strong>Vapor-compression</strong> (Modules 1–4) is the default: works in any climate, any humidity, precise control, powered by electricity. <strong>Absorption</strong> is the heat-powered specialist: chosen where waste heat, steam, or cogeneration tilts the economics, or where electric capacity is constrained. <strong>Evaporative</strong> is the climate specialist: powerful and simple where air is dry, limited by the wet bulb, and (in direct form) it adds moisture the space must accept.</p><p>Real plants blend them: evaporative pre-cooling of condenser air on an air-cooled chiller on peak days; indirect evaporative stages ahead of a DX coil in a dry-climate air handler; an absorption machine carrying base load on waste heat while an electric chiller trims peaks. The technician who understands all three can read any of those plants without surprise.</p><div class="callout"><strong>Key idea:</strong> There is no "best cooling technology" — there is the best fit among energy source, climate, and load. State your selection logic in those three terms on any application question and you will reason like a designer, not a parts catalog.</div><p>Safety and scope note: absorption and large evaporative systems involve water treatment, vacuum vessels, and (for ammonia systems) a toxic refrigerant handled under its own rules. This course teaches principles and application recognition; hands-on work follows manufacturer and site procedures under qualified supervision.</p>`
    }
  ],
  keyTerms: [
    { term: "Absorption refrigeration", def: "Cooling cycle driven by heat input and an absorbent fluid instead of a mechanical compressor." },
    { term: "Absorbent", def: "Fluid that captures refrigerant vapor in the absorber; lithium bromide in large water-refrigerant systems." },
    { term: "Lithium bromide (LiBr)", def: "Salt solution with a strong affinity for water vapor, used as the absorbent paired with water refrigerant." },
    { term: "Generator (absorption)", def: "Vessel where applied heat boils refrigerant out of the diluted solution, reconcentrating it." },
    { term: "Absorber", def: "Vessel where concentrated solution absorbs refrigerant vapor from the evaporator; absorption heat is removed by cooling water." },
    { term: "Solution pump", def: "Small pump that moves diluted solution from absorber to generator — the absorption cycle's main moving part." },
    { term: "Crystallization", def: "Solidification of lithium bromide solution in piping when concentration is too high and temperature too low; a shutdown fault." },
    { term: "Solution heat exchanger", def: "Internal exchanger recovering heat between hot concentrated and cool diluted solution streams." },
    { term: "Cogeneration / trigeneration", def: "Producing electricity plus useful heat (and, with absorption, cooling) from one fuel source." },
    { term: "Ammonia–water absorption", def: "Absorption pair used in small gas-fired units such as RV refrigerators; ammonia is the refrigerant." },
    { term: "Evaporative cooling", def: "Cooling air by evaporating water into it; the evaporation absorbs heat from the air itself." },
    { term: "Direct evaporative cooling", def: "Wetted media in the supply airstream; cools the air and adds moisture to it." },
    { term: "Indirect evaporative cooling", def: "Cooling supply air through a heat-exchange surface using evaporation in a secondary stream, without adding moisture to the supply." },
    { term: "Wet-bulb temperature", def: "Lowest temperature reachable by evaporative cooling of air; the hard limit for towers and evaporative coolers." },
    { term: "Swamp cooler", def: "Common name for a direct evaporative cooler used in dry climates." },
    { term: "Waste heat", def: "Heat rejected by a process or engine that can be productively used, e.g., to drive an absorption chiller." }
  ],
  video: {
    title: "Absorption Chiller, How it works - working principle hvac",
    embedUrl: "https://www.youtube.com/embed/0R84hLprO5s",
    note: "An animated walk-through of the lithium bromide absorption cycle — evaporator, absorber, generator, and condenser — using 3D models and real examples. Follow the water refrigerant around the loop and match each vessel to Section 2's walk-through.",
    more: []
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> In a LiBr absorption chiller, which fluid is the refrigerant and which is the absorbent? What component replaces the compressor's role?</p>", solution: "<p><strong>Answer: water = refrigerant; lithium bromide = absorbent.</strong> Step 1: Water evaporates in the evaporator to make cooling. Step 2: LiBr absorbs that vapor in the absorber. Step 3: The absorber/generator pair plus the solution pump does the 'compression' work — absorption captures vapor, generator heat drives it back out at condensing pressure.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A solution sample path in an absorption machine is found blocked with solid salt-like material. Name the fault and its two promoting conditions.</p>", solution: "<p><strong>Answer: crystallization.</strong> Step 1: LiBr solidifies out of solution as crystals. Step 2: It is promoted by solution concentration that is too high. Step 3: And by that concentrated solution being cooled too far (classically in the heat exchanger/absorber path). Recovery follows the manufacturer's dilution and heating procedure only.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A campus generates its own power; engine exhaust heat is currently vented. Propose a cooling application and justify it.</p>", solution: "<p><strong>Answer: an absorption chiller on the waste heat (trigeneration).</strong> Step 1: The exhaust heat is free energy already being discarded. Step 2: Absorption converts heat directly into chilled water. Step 3: Total fuel use improves versus venting the heat and buying electricity to run compressors for the same cooling.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Outdoor air is 100°F dry bulb with a 68°F wet bulb in one city, and 95°F dry bulb with a 90°F wet bulb in another. Where will direct evaporative cooling work well, and why?</p>", solution: "<p><strong>Answer: the first city.</strong> Step 1: Evaporative cooling can drive air toward, but not below, the wet bulb. Step 2: City one offers a potential drop of roughly 100 → toward 68°F — a wide margin. Step 3: City two's air is nearly saturated (95/90), so evaporation adds little cooling. Climate, not equipment, decides.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> An office cannot accept added indoor moisture. Direct or indirect evaporative cooling — and what is the trade?</p>", solution: "<p><strong>Answer: indirect.</strong> Step 1: Direct cooling adds all evaporated moisture to the supply air. Step 2: Indirect cools through a surface using a secondary wetted stream, adding no moisture to supply air. Step 3: The trade is less cooling reach used alone — it is often paired with another stage.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> Why do absorption machines place such emphasis on vacuum integrity?</p>", solution: "<p><strong>Answer:</strong> Step 1: The refrigerant is water, which must evaporate at low temperature — possible only under deep vacuum. Step 2: Air leaking in raises evaporator pressure and temperature, killing capacity. Step 3: Non-condensables also collect in the absorber and block absorption, so tightness and purging protect the whole cycle.</p>" }
  ],
  quiz: [
    { q: "In a lithium bromide absorption chiller, the refrigerant is:", choices: ["Lithium bromide", "Water", "Ammonia", "R-410A"], answer: 1, explanation: "Correct: (b). Water evaporates under vacuum to produce cooling; LiBr is the absorbent. (a) LiBr absorbs the vapor — it is not evaporated for cooling. (c) Ammonia is the refrigerant in ammonia–water systems, not LiBr machines. (d) R-410A belongs to vapor-compression systems." },
    { q: "The generator's job in an absorption system is to:", choices: ["Compress vapor mechanically", "Use heat to boil refrigerant out of the diluted solution", "Absorb vapor into solution", "Evaporate refrigerant for cooling"], answer: 1, explanation: "Correct: (b). Applied heat reconcentrates the solution and sends refrigerant vapor to the condenser. (a) No mechanical compressor does this in absorption. (c) That is the absorber's job. (d) Evaporation for cooling happens in the evaporator." },
    { q: "Crystallization in a LiBr machine is promoted by:", choices: ["Low concentration and high temperature", "High concentration combined with low solution temperature", "Excessive chilled-water flow", "A running solution pump"], answer: 1, explanation: "Correct: (b). Concentrated solution cooled too far solidifies in piping and exchangers. (a) Dilute, warm solution stays liquid — the opposite conditions. (c) Chilled-water flow does not set solution concentration. (d) The pump circulates solution; it does not crystallize it." },
    { q: "Absorption cooling is most attractive when:", choices: ["Electricity is the cheapest energy on site", "Waste heat or steam is available at little cost", "The site has no water for a tower", "Loads are tiny and intermittent"], answer: 1, explanation: "Correct: (b). Free or cheap heat offsets absorption's higher heat input per ton. (a) Cheap electricity favors efficient vapor-compression. (c) Absorption chillers still need heat rejection, typically a tower. (d) Small intermittent loads suit simple DX equipment better." },
    { q: "The hard lower limit for evaporative cooling of air is the:", choices: ["Dew point of the supply air", "Outdoor dry-bulb temperature", "Outdoor wet-bulb temperature", "Indoor setpoint"], answer: 2, explanation: "Correct: (c). Evaporation can drive air toward wet bulb but never below it. (a) Dew point governs condensation, not the evaporative limit. (b) Dry bulb is the starting temperature, not the limit. (d) Setpoint is a control choice and may be unreachable by evaporation alone." },
    { q: "Direct evaporative cooling differs from indirect because direct:", choices: ["Adds moisture to the supply air", "Cannot cool at all", "Uses a compressor", "Works best in humid climates"], answer: 0, explanation: "Correct: (a). Wetted media sits in the supply stream, so evaporated water enters the space. (b) Direct cooling is effective — in dry air. (c) Neither type uses a compressor. (d) High humidity shrinks the wet-bulb margin and cripples both types." },
    { q: "Trigeneration means producing, from one fuel source:", choices: ["Three refrigerants", "Power, heating, and cooling (the cooling often via absorption)", "Cooling at three temperatures", "Three stages of compression"], answer: 1, explanation: "Correct: (b). A generator's waste heat drives heating and an absorption chiller. (a) Refrigerant count is irrelevant. (c) Temperature levels are not the concept. (d) Compressor staging belongs to vapor-compression plants." },
    { q: "The small solution pump in an absorption machine moves:", choices: ["Refrigerant vapor to the condenser", "Diluted solution from the absorber to the generator", "Chilled water to the building", "Tower water to the absorber only"], answer: 1, explanation: "Correct: (b). It lifts the diluted solution to generator pressure — the cycle's main mechanical work. (a) Refrigerant vapor flows by pressure difference, not the pump. (c) Building water is moved by the plant's chilled-water pumps. (d) Tower water is circulated by its own pump to absorber and condenser." }
  ],
  studyGuide: `
<h3>Module 5 — Absorption & Evaporative Cooling: Quick Reference</h3>
<p><strong>Absorption:</strong> heat replaces the compressor. Pair: water = refrigerant, lithium bromide = absorbent. Vessels: evaporator (cooling under vacuum) → absorber (LiBr captures vapor) → generator (heat boils refrigerant out) → condenser.</p>
<p><strong>Crystallization:</strong> LiBr solidifies when concentration is too high and solution gets too cold — controlled by managing heat input and cooling-water temperatures per the manufacturer.</p>
<p><strong>Where absorption wins:</strong> waste heat, steam, cogeneration/trigeneration, punishing electric demand charges. Where it loses: heat bought at full price just to run it.</p>
<div class="formula">Evaporative limit: cooled air approaches — never beats — the outdoor wet-bulb temperature</div>
<p><strong>Evaporative:</strong> direct = wetted media in supply air (adds moisture); indirect = cooling through a surface (no added moisture, less reach). Dry climates: strong. Humid climates: weak.</p>
<p><strong>Selection logic:</strong> energy source + climate + load. Vapor-compression = default; absorption = cheap-heat specialist; evaporative = dry-climate specialist.</p>
`
};
