// HVAC 208 - Module 6: Cooling Towers
module.exports = {
  number: 6,
  slug: "cooling-towers",
  title: "Cooling Towers",
  estTime: "3–4 hours",
  objectives: [
    "Explain how a cooling tower rejects heat by evaporation and identify its main components.",
    "Distinguish open (direct-contact) from closed-circuit (closed-loop) towers and their applications.",
    "Define and compute cooling tower range and approach from measured temperatures.",
    "Explain why wet-bulb temperature — not dry-bulb — governs tower performance.",
    "Describe makeup water, evaporation loss, drift, and blowdown and why each matters.",
    "Summarize water treatment basics: scale, corrosion, and biological control, and the technician's role."
  ],
  sections: [
    {
      heading: "How a Tower Throws Heat Away",
      html: `<p>A <strong>cooling tower</strong> is the water-cooled plant's radiator — except it does most of its work by evaporation rather than by warming air. Warm condenser water from the chiller is sprayed or flowed over <strong>fill</strong> (a honeycomb of surfaces that spreads the water into thin films and droplets) while a fan draws or blows air through it. A small portion of the water evaporates into that air; evaporation steals heat from the water that remains, and the cooled water collects in the <strong>basin</strong> and returns to the condenser.</p><p>The major parts to know on sight: the <strong>fill</strong>, the <strong>spray distribution</strong> system or distribution basin that wets it evenly, <strong>drift eliminators</strong> that strip water droplets out of the leaving air, the <strong>fan</strong> and its drive, the cold-water <strong>basin</strong>, and the <strong>makeup</strong> connection with its float or level control that replaces water the tower loses.</p><div class="callout"><strong>Key idea:</strong> A tower does not "make cold" — it rejects heat to the atmosphere by sacrificing a little water to evaporation. Everything that interferes with even water distribution, clean fill surfaces, or airflow (clogged nozzles, scaled fill, a slipping fan belt) shows up directly as warmer condenser water and a harder-working chiller.</div><p>That is why tower inspection — distribution pattern, fill condition, fan operation, basin level — belongs in every water-cooled plant's routine rounds.</p>`
    },
    {
      heading: "Open vs. Closed-Circuit Towers",
      html: `<p>In an <strong>open tower</strong>, the condenser water itself is exposed to the air: it is sprayed over the fill, contacts the atmosphere directly, and picks up whatever the air carries — dust, pollen, and oxygen. The advantage is direct, efficient contact; the cost is that the entire condenser loop is open to contamination, so the whole loop needs water treatment and strainers, and it cannot hold a corrosion-sensitive fluid.</p><p>In a <strong>closed-circuit tower</strong> (fluid cooler), the process fluid stays inside a coil. Spray water wets the outside of the coil and air cools the coil, while the process fluid never touches the atmosphere. Only the small spray loop is exposed. Closed-circuit designs protect the process loop — valuable for water-source heat pump loops, process fluids, or any system where the main loop must stay clean and sealed — at the price of an extra heat-transfer step (fluid → coil wall → spray water → air) and higher first cost.</p><ul><li><strong>Open:</strong> most efficient contact; whole loop exposed; treatment critical.</li><li><strong>Closed:</strong> process loop sealed and clean; extra temperature step; spray loop still needs care.</li></ul><div class="callout"><strong>Key idea:</strong> "Closed" describes the process fluid's isolation, not the absence of evaporation — a closed-circuit tower still evaporates spray water and still needs makeup, blowdown, and biological control for that spray loop.</div>`
    },
    {
      heading: "Range and Approach: The Two Tower Numbers",
      html: `<p>Two temperature differences describe everything a tower is doing, and their definitions are exact — memorize them as formulas, not impressions.</p><div class="formula">Range = hot water in − cold water out &nbsp;·&nbsp; Approach = cold water out − outdoor wet-bulb temperature</div><p>The <strong>range</strong> is set mainly by the heat load and the water flow: it is how much the water is cooled passing through the tower. The <strong>approach</strong> is how close the tower gets the cold water to the wet bulb — the quality measure of the tower itself, since no tower can cool water below the wet bulb. A small approach means a hard-working (or generously sized) tower; the approach can never reach zero, and chasing the last degrees costs disproportionate tower size and fan energy.</p><p><strong>Worked example.</strong> Condenser water enters the tower at 95°F and leaves at 85°F, on a day when the outdoor wet bulb is 78°F. Range = 95 − 85 = 10°F. Approach = 85 − 78 = 7°F. If the fill fouls over a season and the same load now leaves at 88°F, the approach has widened to 10°F while the range shrank to 7°F — the plant's heat rejection is degrading, and the chiller will pay for it in head pressure and energy.</p><div class="callout"><strong>Key idea:</strong> Measure range and approach together on rounds. Range tells you about load and flow; approach tells you about tower health relative to the day's wet bulb. Comparing approach across days only makes sense against the wet bulb measured that day.</div>`
    },
    {
      heading: "Water Losses: Evaporation, Drift, Blowdown, Makeup",
      html: `<p>A tower continuously loses water three ways, and a fourth stream replaces it. <strong>Evaporation</strong> is the intended loss — it is the cooling mechanism itself; that water leaves as vapor and cannot be recovered. <strong>Drift</strong> is liquid droplets carried out with the exhaust air despite the drift eliminators — a small but real loss, and the reason tower placement relative to air intakes matters. <strong>Blowdown</strong> is deliberate draining: as pure water evaporates, the minerals in the remaining water concentrate, so a portion is bled off to keep dissolved solids in check.</p><p><strong>Makeup</strong> water replaces all three losses together, admitted by a float valve or electronic level control into the basin. A technician reading the plant should be able to account for the basin level: a chronically dropping level with the makeup shut or failed means leaks or excessive blowdown; a constantly overflowing basin wastes treated water and chemicals. Rising mineral concentration despite blowdown points at the treatment program, which is the next section.</p><ul><li><strong>Evaporation:</strong> unavoidable — it is the cooling.</li><li><strong>Drift:</strong> minimized by eliminators; a placement and maintenance issue.</li><li><strong>Blowdown:</strong> controlled on purpose to cap dissolved solids.</li><li><strong>Makeup:</strong> replaces the total; its meter is a diagnostic tool in itself.</li></ul><p>Water is a real operating cost and, in many regions, a regulated one — towers are among a building's largest water users, which is why their upkeep is an application skill and not an afterthought.</p>`
    },
    {
      heading: "Water Treatment Basics and the Technician's Role",
      html: `<p>Untreated tower water wages three kinds of war on the plant. <strong>Scale:</strong> concentrated minerals deposit on condenser tubes, insulating them and raising head pressure — a thin deposit does outsized damage because it sits exactly where heat must pass. <strong>Corrosion:</strong> oxygenated, warm, circulating water attacks metals, thinning piping and fouling the system with corrosion products. <strong>Biological growth:</strong> warm sunlit water grows algae and bacteria that clog fill and nozzles; most seriously, towers must be managed to control <em>Legionella</em> risk, the bacterium behind Legionnaires' disease, which can spread in drift aerosols — the reason towers follow written water-management and cleaning programs rather than casual hosing.</p><p>Treatment combines chemical programs (scale and corrosion inhibitors, biocides) administered by qualified water-treatment providers, with mechanical hygiene: keeping the basin clean, the fill free of debris, and drift eliminators intact. The HVAC technician's role is the plant-side discipline: log temperatures and makeup use, report abnormal levels or visible fouling, keep access panels and screens in place, coordinate shutdowns for cleaning, and never improvise chemical dosing outside the site's program.</p><div class="callout"><strong>Key idea:</strong> Water treatment is a program, not an event. The numbers you log — range, approach, basin level, makeup behavior — are how the program's success or failure first becomes visible, often months before a fouled condenser announces it as a chiller problem.</div><p>Freeze protection closes the topic for cold climates: basin heaters, indoor sumps, or draining procedures protect idle towers and exposed piping, per the manufacturer and site plan.</p>`
    }
  ],
  keyTerms: [
    { term: "Cooling tower", def: "Heat-rejection device that cools condenser water primarily by evaporating a small portion of it into moving air." },
    { term: "Fill", def: "Structured media that spreads water into films/droplets to maximize air-water contact area." },
    { term: "Drift eliminators", def: "Passages that strip liquid droplets from the leaving airstream to reduce water loss and aerosol spread." },
    { term: "Basin (sump)", def: "The cold-water collection reservoir at the tower's base." },
    { term: "Open tower", def: "Tower in which the process (condenser) water directly contacts the air and atmosphere." },
    { term: "Closed-circuit tower", def: "Tower/fluid cooler where process fluid stays in a sealed coil cooled externally by spray water and air." },
    { term: "Range", def: "Hot water entering temperature minus cold water leaving temperature across the tower." },
    { term: "Approach", def: "Cold water leaving temperature minus the outdoor wet-bulb temperature; measures how close the tower gets to its limit." },
    { term: "Wet-bulb temperature", def: "The lowest temperature to which evaporation can cool water; governs tower capability on a given day." },
    { term: "Evaporation loss", def: "Water lost as vapor — the tower's intended cooling mechanism." },
    { term: "Drift", def: "Liquid droplets carried out of the tower with exhaust air." },
    { term: "Blowdown", def: "Deliberate draining of concentrated tower water to control dissolved solids." },
    { term: "Makeup water", def: "Fresh water added to replace evaporation, drift, and blowdown losses." },
    { term: "Scale", def: "Mineral deposit on heat-transfer surfaces that insulates them and raises energy use." },
    { term: "Biocide", def: "Treatment chemical used within a managed program to control biological growth in tower water." },
    { term: "Legionella", def: "Bacterium that can grow in poorly managed warm water systems and spread via aerosols; drives tower water-management programs." }
  ],
  video: {
    title: "How Cooling Towers Work (Working Principle)",
    embedUrl: "https://www.youtube.com/embed/sWJCWDpY9is",
    note: "A working-principle walk-through of a counterflow induced-draft tower: spray distribution, fill, evaporation, drift eliminators, and the basin. Match each part named in the video to Section 1's component list as you watch.",
    more: [
      { title: "HVAC Cooling Tower Kaise Kaam Karta Hai? | Working, Range, Approach & Important Parameters", url: "https://www.youtube.com/watch?v=UYfsQGsckx4" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Water enters a tower at 96°F and leaves at 86°F; wet bulb is 79°F. Compute range and approach.</p>", solution: "<p><strong>Answer: range 10°F; approach 7°F.</strong> Step 1: Range = 96 − 86 = 10°F. Step 2: Approach = 86 − 79 = 7°F. Step 3: The 7°F approach is the tower-health figure; the 10°F range reflects load and flow.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A tower's approach has widened over the season at similar loads and wet bulbs. List three field checks before blaming the chiller.</p>", solution: "<p><strong>Answer:</strong> Step 1: Check spray distribution — clogged nozzles leave dry fill streaks. Step 2: Inspect fill for scale, algae, and debris restricting air and water flow. Step 3: Verify fan operation and belt/drive condition for full airflow. Each directly degrades the tower's ability to approach the wet bulb.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Why can a tower never cool water below the wet-bulb temperature?</p>", solution: "<p><strong>Answer:</strong> Step 1: The tower cools by evaporation into air. Step 2: As water approaches the wet bulb, the air at the water surface is effectively saturated for that condition and net evaporation stops. Step 3: With no net evaporation there is no further cooling — the wet bulb is the thermodynamic floor.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A water-source heat pump loop must stay sealed and clean. Open or closed-circuit tower, and why?</p>", solution: "<p><strong>Answer: closed-circuit.</strong> Step 1: The process fluid stays inside the tower's coil, never contacting air. Step 2: Only the external spray loop is exposed to the atmosphere. Step 3: The trade is an extra heat-transfer step and higher first cost, accepted to protect the sealed loop.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Explain blowdown in one paragraph a building owner would understand.</p>", solution: "<p><strong>Answer:</strong> Step 1: Evaporation leaves minerals behind, so tower water gets more concentrated over time. Step 2: Blowdown deliberately drains some of that concentrated water. Step 3: Makeup replaces it with fresher water, holding dissolved solids low enough to prevent scale and corrosion damage.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A basin is constantly overflowing though the plant runs normally. What are the likely causes and first checks?</p>", solution: "<p><strong>Answer: makeup control fault.</strong> Step 1: Check the float valve or level control — stuck open or set too high. Step 2: Check for a leaking makeup solenoid/valve passing water continuously. Step 3: Confirm blowdown is not shut while makeup overfeeds. Overflowing wastes treated water and dilutes the chemical program.</p>" }
  ],
  quiz: [
    { q: "Cooling tower range is defined as:", choices: ["Cold water out minus wet bulb", "Hot water in minus cold water out", "Dry bulb minus wet bulb", "Condenser water in minus chilled water out"], answer: 1, explanation: "Correct: (b). Range = entering hot water − leaving cold water; it reflects load and flow. (a) That difference is the approach. (c) Dry bulb minus wet bulb is the wet-bulb depression, an air property. (d) Mixing two different loops produces a meaningless number." },
    { q: "Approach is defined as:", choices: ["Hot water in minus wet bulb", "Cold water out minus wet bulb", "Hot water in minus cold water out", "Wet bulb minus cold water out"], answer: 1, explanation: "Correct: (b). Approach = cold water out − wet bulb; it grades the tower against its limit. (a) Hot water in is not part of the approach. (c) That is the range. (d) Reversed — approach is positive when the tower leaves water warmer than wet bulb, which is always." },
    { q: "Water enters at 94°F, leaves at 84°F, wet bulb 77°F. Range and approach are:", choices: ["Range 10°F, approach 7°F", "Range 7°F, approach 10°F", "Range 17°F, approach 10°F", "Range 10°F, approach 17°F"], answer: 0, explanation: "Correct: (a). Range = 94−84 = 10; approach = 84−77 = 7. (b) swaps the two definitions. (c) adds wet bulb into the range incorrectly. (d) uses hot-water-to-wet-bulb (17) as the approach, which is not the definition." },
    { q: "In a closed-circuit tower, the process fluid:", choices: ["Is sprayed over the fill", "Stays sealed inside a coil cooled by external spray and air", "Evaporates directly to the atmosphere", "Never needs makeup water anywhere in the unit"], answer: 1, explanation: "Correct: (b). The coil isolates the process loop; the spray loop does the evaporating. (a) Spraying the process fluid describes an open tower. (c) Direct process evaporation is also open-tower behavior. (d) The spray loop still loses water and needs makeup." },
    { q: "Drift is:", choices: ["The intended evaporation loss", "Liquid droplets carried out with the exhaust air", "The deliberate drain of concentrated water", "Mineral deposit on tubes"], answer: 1, explanation: "Correct: (b). Drift is liquid water escaping as droplets despite eliminators. (a) Evaporation leaves as vapor — that is the cooling mechanism. (c) That drain is blowdown. (d) Deposits are scale, a water-treatment issue." },
    { q: "The main purpose of blowdown is to:", choices: ["Cool the water faster", "Limit dissolved-solids concentration as evaporation concentrates minerals", "Feed the basin in winter", "Clean the fill mechanically"], answer: 1, explanation: "Correct: (b). Controlled draining caps mineral concentration, protecting against scale and corrosion. (a) Blowdown does not change tower cooling physics. (c) Makeup, not blowdown, adds water. (d) Fill cleaning is a separate maintenance task." },
    { q: "A widening approach at constant load most likely indicates:", choices: ["Improving tower health", "A tower-side problem: fouling, distribution, or airflow", "A lower wet bulb that day", "Overcharged refrigerant"], answer: 1, explanation: "Correct: (b). Approach grades the tower against the day's wet bulb; widening means the tower is falling behind — check nozzles, fill, and fan. (a) Improvement would narrow the approach. (c) A lower wet bulb with the same cold-water temperature widens the arithmetic but at constant load the field checks come first; the trend across similar days is the signal. (d) Refrigerant charge is chiller-side and does not define tower approach." },
    { q: "Why do towers follow written water-management programs?", choices: ["To satisfy the fan manufacturer", "To control scale, corrosion, and biological risks including Legionella", "To eliminate makeup water", "To raise the approach"], answer: 1, explanation: "Correct: (b). Managed chemistry plus cleaning controls deposits, metal loss, and microbial growth that can spread in aerosols. (a) Fan warranties are unrelated. (c) Evaporation loss cannot be eliminated. (d) A larger approach is worse performance, not a goal." }
  ],
  studyGuide: `
<h3>Module 6 — Cooling Towers: Quick Reference</h3>
<p><strong>Mechanism:</strong> spray condenser water over fill, move air through it, evaporate a small portion — the remainder cools. Parts: fill, sprays, drift eliminators, fan, basin, makeup.</p>
<p><strong>Open tower:</strong> process water contacts air (efficient, whole loop exposed). <strong>Closed-circuit:</strong> process fluid sealed in a coil; spray loop outside (protects the loop, extra temperature step).</p>
<div class="formula">Range = hot in − cold out · Approach = cold out − wet bulb</div>
<p><strong>Example:</strong> 95 in / 85 out / 78 WB → range 10°F, approach 7°F. Range = load & flow story; approach = tower health vs. that day's wet bulb.</p>
<p><strong>Water streams:</strong> evaporation (the cooling) + drift (droplets out) + blowdown (deliberate, caps minerals) = makeup (replaces all).</p>
<p><strong>Treatment trio:</strong> scale, corrosion, biological control (incl. Legionella management) — a continuous program; technician logs temperatures/levels and reports fouling early.</p>
<p><strong>Rounds checklist:</strong> distribution pattern even? fill clean? fan and drive sound? basin level steady with sensible makeup behavior? Log range and approach with the day's wet bulb — every visit, no exceptions.</p>
`
};
