// HVAC 208 - Module 7: Compressor Types & Capacity Control
module.exports = {
  number: 7,
  slug: "compressor-types-capacity-control",
  title: "Compressor Types & Capacity Control",
  estTime: "3–4 hours",
  objectives: [
    "Describe how reciprocating, scroll, rotary, screw, and centrifugal compressors each compress refrigerant.",
    "Match each compressor type to its typical application range in A/C and chiller service.",
    "Explain the main capacity-control methods: staging, cylinder unloading, slide valves, guide vanes, and variable-speed drives.",
    "Compare on/off cycling, staging, and modulation for comfort, efficiency, and wear.",
    "Explain what a VFD changes about compressor and motor operation and why it suits part-load hours.",
    "Identify compressor protection concerns that capacity control must respect, including oil return and minimum speed/load limits."
  ],
  sections: [
    {
      heading: "Five Ways to Squeeze a Gas",
      html: `<p>All compressors do one job — take in low-pressure vapor and discharge it at higher pressure — but they squeeze differently, and the mechanism decides where each belongs. <strong>Reciprocating</strong> compressors use pistons driven by a crankshaft, with suction and discharge valves opening and closing each stroke: the oldest design, still common in smaller and serviceable (semi-hermetic) machines. <strong>Scroll</strong> compressors trap vapor between a fixed spiral and an orbiting spiral; the pockets shrink continuously toward the center discharge — few moving parts, quiet, and the default in residential and light-commercial A/C.</p><p><strong>Rotary</strong> compressors (rolling-piston and vane designs) compress vapor with a rotating element inside a cylinder; they are compact and dominate window units and many mini-splits. <strong>Screw</strong> compressors mesh two helical rotors that carry vapor from one end to the other in ever-smaller spaces — smooth, continuous flow for mid-to-large capacities. <strong>Centrifugal</strong> compressors are not positive-displacement at all: a high-speed impeller throws vapor outward, and a diffuser converts that velocity into pressure; they move huge volumes in large chillers (Module 4).</p><div class="callout"><strong>Key idea:</strong> Positive-displacement machines (reciprocating, scroll, rotary, screw) trap a volume and shrink it. Dynamic machines (centrifugal) add velocity and convert it to pressure. That single distinction explains their capacity control, their surge behavior, and their typical sizes.</div><p>When a customer or a nameplate names the compressor type, you immediately know the machine's likely capacity-control method — the rest of this module.</p>`
    },
    {
      heading: "Staging and Unloading: Capacity in Steps",
      html: `<p>The simplest capacity control is <strong>staging</strong>: multiple compressors (or multiple scrolls in one shell circuit) switched on and off in steps. A packaged unit with two equal compressors offers roughly 50% or 100% capacity. Tandem scroll sets in larger A/C equipment work the same way — capacity in blocks, controlled by the thermostat or unit board. Staging is rugged and cheap, but the steps are coarse: between steps, the running equipment cycles to make up the difference.</p><p><strong>Cylinder unloading</strong> gives a reciprocating compressor internal steps: an unloader holds suction valves open (or blocks a cylinder bank) so one or more cylinders pump nothing while the motor keeps running. The compressor's capacity drops in fractions without stopping the machine — kinder to the motor than short-cycling and smoother for the space. <strong>Screw compressors</strong> achieve the same idea continuously with the <strong>slide valve</strong> from Module 4, which opens a bypass that returns part of the vapor to suction before compression, sliding capacity down smoothly from full load.</p><div class="callout"><strong>Key idea:</strong> Steps beat single-speed on/off for comfort and wear, but every step is still a compromise the controls must average out. The finer the steps — or the smoother the modulation — the steadier the space temperature and humidity removal.</div><p>Application note: a "two-stage" residential system and a four-compressor RTU are the same idea at different scales. Diagnose staging complaints by verifying each stage actually starts and loads in sequence — a dead second stage looks exactly like an undersized system on the hottest days.</p>`
    },
    {
      heading: "Modulation and Variable-Speed Drives",
      html: `<p>A <strong>variable-frequency drive (VFD)</strong> changes the frequency of power feeding the compressor motor, so motor speed — and therefore compressor capacity — varies continuously. Instead of slamming between 0% and 100%, an inverter-driven scroll or screw slows to match the load, running long, gentle cycles. The application wins are real: tighter temperature control, far better humidity removal from long evaporator runtimes, soft starts with no inrush slam, and strong part-load efficiency — and most systems spend most hours at part load.</p><p>VFD control has boundaries the technician must respect. Compressors have <strong>minimum speeds</strong> for oil management and motor cooling; drives have their own fault codes and heat limits; and a VFD cannot rescue an oversized system whose minimum capacity still exceeds a mild-day load. In large centrifugals, speed control works alongside <strong>inlet guide vanes</strong>, and the controls coordinate both to stay clear of surge (Module 4).</p><div class="formula">Capacity follows speed (approximately, for a given compressor): slower motor → less vapor pumped per minute → lower Btu/h</div><div class="callout"><strong>Key idea:</strong> Match the control method to the load profile. Buildings live at part load, so the winning question is rarely "how efficient at full load?" but "how gracefully does it turn down?" — staging, unloading, and VFDs are three answers at three price points.</div>`
    },
    {
      heading: "Digital and Bypass Methods — and Their Limits",
      html: `<p>Two more methods round out the picture. A <strong>digital scroll</strong> achieves modulation with a fixed-speed motor by periodically unloading the scroll set: a solenoid separates the scrolls axially for part of each short cycle, so the compressor pumps during the loaded fraction and idles during the unloaded fraction. Time-averaged capacity varies smoothly while the motor runs steadily — a clever middle path between staging and full inverter control.</p><p><strong>Hot-gas bypass</strong> takes the opposite philosophy: the compressor keeps pumping fully, and a valve routes discharge gas into the low side to fake a load so the machine does not short-cycle at low demand. It protects the compressor and stabilizes operation, but the bypassed capacity is pure waste — the energy was spent compressing gas whose cooling is thrown away. Treat hot-gas bypass as a stability tool for specific low-load situations, not an efficiency strategy.</p><ul><li><strong>Staging/unloading:</strong> steps; simple, durable, coarse.</li><li><strong>Digital scroll:</strong> time-sliced unloading; smooth average capacity, steady motor.</li><li><strong>VFD:</strong> true speed modulation; best part-load behavior, most electronics.</li><li><strong>Hot-gas bypass:</strong> stability at low load; wastes the bypassed work.</li></ul><div class="callout"><strong>Key idea:</strong> When you find a hot-gas bypass valve piped on a system, ask why it is there before adjusting anything — it is usually compensating for an oversized machine or a very low minimum load, and closing it off can trade a stable system for a short-cycling one.</div>`
    },
    {
      heading: "Protection Limits Every Method Must Respect",
      html: `<p>Capacity control is never free to do anything it wants; it operates inside the compressor's protection envelope. <strong>Oil return:</strong> refrigerant velocity in suction piping must stay high enough to carry oil back — a system modulated very low for long periods on piping sized for full load can starve the compressor of oil. <strong>Motor cooling:</strong> many hermetic motors are cooled by the suction vapor they pump; sustained low mass flow can overheat them. <strong>Minimum run and off times:</strong> controls enforce these to let oil settle, pressures equalize, and motors avoid destructive rapid restarting.</p><p><strong>Worked reasoning — a short-cycling complaint.</strong> A single-stage unit on a mild day satisfies the thermostat in a few minutes, stops, and restarts soon after. Nothing is "broken": the load is a fraction of capacity, so the only control available — on/off — cycles. The application fixes are control-side (cycle-rate/anticipator settings, wider differential where appropriate) or equipment-side at replacement time (two-stage or variable-speed equipment). Condemning the compressor for doing exactly what a single stage must do wastes the customer's money.</p><div class="callout"><strong>Key idea:</strong> Diagnose capacity-control complaints in order: (1) Is the load simply small? (2) Are all stages/drives actually responding in sequence? (3) Is a protection limit (low speed, surge line, oil return) correctly constraining output? Only then suspect a failed component.</div><p>Module 11 returns to the switches and boards that enforce these limits; Module 12 uses them in full troubleshooting cases.</p>`
    }
  ],
  keyTerms: [
    { term: "Reciprocating compressor", def: "Piston-and-valve positive-displacement compressor driven by a crankshaft." },
    { term: "Scroll compressor", def: "Compressor using a fixed and an orbiting spiral to trap and shrink vapor pockets continuously." },
    { term: "Rotary compressor", def: "Compact rotating-element compressor common in window units and mini-splits." },
    { term: "Screw compressor", def: "Twin helical-rotor positive-displacement compressor for mid-to-large capacities." },
    { term: "Centrifugal compressor", def: "Dynamic compressor using a high-speed impeller; velocity is converted to pressure in a diffuser." },
    { term: "Positive displacement", def: "Compression by trapping a volume of vapor and mechanically reducing it." },
    { term: "Staging", def: "Switching multiple compressors or circuits on/off in steps to vary capacity." },
    { term: "Cylinder unloading", def: "Holding reciprocating cylinders inactive (valves held open or bank blocked) to cut capacity without stopping the motor." },
    { term: "Slide valve", def: "Screw-compressor bypass device that varies capacity smoothly by returning vapor to suction." },
    { term: "Inlet guide vanes", def: "Adjustable vanes controlling flow into a centrifugal compressor while pre-swirling the vapor." },
    { term: "Variable-frequency drive (VFD)", def: "Power electronics that vary motor frequency and speed to modulate compressor capacity continuously." },
    { term: "Digital scroll", def: "Scroll that modulates by periodically separating the scrolls, time-averaging capacity at constant motor speed." },
    { term: "Hot-gas bypass", def: "Valve routing discharge gas to the low side to simulate load and prevent short-cycling at low demand; wastes the bypassed work." },
    { term: "Short-cycling", def: "Rapid repeated starting and stopping of a compressor, harmful to motors and poor for comfort and dehumidification." },
    { term: "Part load", def: "Operation below full capacity, where systems spend most of their hours." },
    { term: "Oil return", def: "Carrying lubricating oil back to the compressor with refrigerant flow; requires adequate vapor velocity." },
    { term: "Surge line", def: "Operating boundary for centrifugal compressors below which flow becomes unstable." },
    { term: "Turndown", def: "How low a compressor/system can modulate capacity while still operating stably and safely." }
  ],
  video: {
    title: "Inside a Scroll Compressor",
    embedUrl: "https://www.youtube.com/embed/JLejG6V5Kgc",
    note: "A cutaway look inside a scroll compressor showing the fixed and orbiting scrolls and how the pockets shrink toward discharge. It also corrects a common myth — scrolls do not have suction/discharge valves like a reciprocating machine — a distinction Section 1 leans on.",
    more: []
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Match each compressor to its mechanism: (a) pistons and valves, (b) fixed + orbiting spirals, (c) meshing helical rotors, (d) high-speed impeller.</p>", solution: "<p><strong>Answer:</strong> Step 1: (a) = reciprocating. Step 2: (b) = scroll. Step 3: (c) = screw. Step 4: (d) = centrifugal — the only dynamic (non-positive-displacement) machine in the list.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> An RTU has four equal compressors. The load needs about 60% capacity. How will the controls most likely respond, and what happens between steps?</p>", solution: "<p><strong>Answer:</strong> Step 1: Two compressors give 50%, three give 75% — no exact 60% step exists. Step 2: Controls run two steadily and cycle the third as needed. Step 3: The space sees averaged capacity; the cycling stage absorbs the mismatch.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Why does a VFD-driven system usually remove humidity better than a single-stage system of the same tonnage?</p>", solution: "<p><strong>Answer:</strong> Step 1: The inverter slows the compressor to match part load instead of cycling off. Step 2: Long runtimes keep the evaporator cold and wet for more hours. Step 3: More hours of moisture condensing on the coil = more dehumidification, without overcooling the space.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A technician finds a hot-gas bypass valve and proposes removing it to 'save energy.' Give the caution.</p>", solution: "<p><strong>Answer:</strong> Step 1: The bypass exists to keep the compressor stable at low load and prevent short-cycling. Step 2: Removing it may save the bypassed energy but expose the machine to destructive cycling. Step 3: First find why minimum load is so low (oversizing? zoning?) and fix the cause or adjust per the manufacturer.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Explain how a digital scroll modulates capacity without changing motor speed.</p>", solution: "<p><strong>Answer:</strong> Step 1: A solenoid periodically lifts the orbiting scroll so the scrolls separate and pumping stops. Step 2: Over each short cycle, the loaded fraction of time sets the average capacity. Step 3: The motor runs steadily while delivered capacity varies smoothly in time-average.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A variable-speed system runs at very low speed for hours on piping sized for full load. Name the compressor risk and why it occurs.</p>", solution: "<p><strong>Answer: oil starvation from poor oil return.</strong> Step 1: Oil travels back to the compressor carried by suction vapor velocity. Step 2: At low speed, vapor velocity in oversized-for-the-moment piping may fall below what lifts oil, especially in risers. Step 3: Oil logs in the piping while the compressor runs dry — a protection-envelope violation, addressed by manufacturer minimum-speed and piping rules.</p>" }
  ],
  quiz: [
    { q: "Which compressor is NOT positive-displacement?", choices: ["Scroll", "Reciprocating", "Centrifugal", "Screw"], answer: 2, explanation: "Correct: (c). Centrifugal machines add velocity with an impeller and convert it to pressure. (a), (b), and (d) all trap a volume of vapor and mechanically shrink it." },
    { q: "Cylinder unloading reduces capacity by:", choices: ["Slowing the motor", "Making selected cylinders pump nothing while the motor runs", "Bypassing discharge gas to the space", "Closing the liquid line"], answer: 1, explanation: "Correct: (b). Unloaders hold valves open or block banks so those cylinders idle. (a) Speed change is VFD control. (c) Discharge gas never goes to the space; bypass goes to the low side in hot-gas bypass. (d) Closing the liquid line is pump-down/service, not capacity control." },
    { q: "A slide valve is the capacity-control device of a:", choices: ["Scroll", "Screw compressor", "Rotary vane", "Reciprocating compressor"], answer: 1, explanation: "Correct: (b). The slide valve opens a bypass along the rotors to vary effective compression. (a) Scrolls use staging, digital unloading, or speed. (c) Rotary designs are generally fixed or speed-controlled. (d) Reciprocating machines use cylinder unloaders." },
    { q: "The main part-load advantage of a VFD compressor is:", choices: ["It eliminates the need for airflow", "Continuous speed matching: long gentle cycles, tight control, better dehumidification", "It removes all minimum-speed limits", "It makes surge impossible in any machine"], answer: 1, explanation: "Correct: (b). Modulating speed matches output to load for most operating hours. (a) Airflow requirements remain — evaporators still need design CFM. (c) Minimum speeds for oil and motor cooling still apply. (d) Centrifugal surge is managed, not abolished, by coordinated vanes and speed." },
    { q: "Hot-gas bypass protects against short-cycling but:", choices: ["Improves efficiency greatly", "Wastes the energy spent compressing the bypassed gas", "Raises system capacity", "Eliminates the need for staging"], answer: 1, explanation: "Correct: (b). The compressor does full work while part of its output is thrown back to the low side. (a) It costs efficiency by design. (c) Delivered capacity is unchanged or reduced, never raised. (d) It complements, not replaces, staging strategy." },
    { q: "A digital scroll modulates by:", choices: ["Changing supply frequency", "Periodically separating the scrolls so pumping pauses for part of each cycle", "Opening a discharge bypass continuously", "Switching between two motors"], answer: 1, explanation: "Correct: (b). Time-sliced unloading at constant speed averages capacity smoothly. (a) That is inverter/VFD operation. (c) Continuous bypass describes hot-gas bypass. (d) Multiple motors describe staging, not digital operation." },
    { q: "Short-cycling on a mild day with a single-stage unit most often means:", choices: ["A failed compressor", "Capacity far exceeds the small load, so on/off control cycles — a control/application issue", "Low refrigerant charge", "A stuck reversing valve"], answer: 1, explanation: "Correct: (b). With only on/off available, a fractional load must cycle. (a) The compressor is doing what single-stage control requires. (c) Charge faults show in pressures/superheat patterns, not clean satisfaction cycling. (d) A stuck valve causes mode/capacity loss, not normal setpoint cycling." },
    { q: "Why do drives and controls enforce a minimum compressor speed?", choices: ["To keep the space from overcooling only", "To protect oil return and motor cooling that depend on refrigerant flow", "To satisfy the thermostat warranty", "To maximize noise"], answer: 1, explanation: "Correct: (b). Low mass flow starves oil return and suction-cooled motors. (a) Overcooling is handled by cycling/modulation logic, not the protection floor. (c) Warranties do not set physics limits. (d) Lower speed is quieter — the limit is protection, not noise." }
  ],
  studyGuide: `
<h3>Module 7 — Compressor Types & Capacity Control: Quick Reference</h3>
<p><strong>Mechanisms:</strong> reciprocating = pistons/valves · scroll = fixed + orbiting spirals · rotary = rotating element, compact · screw = meshing helical rotors · centrifugal = impeller (dynamic, not positive displacement).</p>
<p><strong>Control methods:</strong> staging (steps of compressors) · cylinder unloading (reciprocating steps) · slide valve (screw, smooth) · guide vanes + speed (centrifugal) · digital scroll (time-sliced unloading) · VFD (true speed modulation) · hot-gas bypass (stability, wastes work).</p>
<p><strong>Part-load truth:</strong> systems live at part load — judge turndown and part-load behavior, not just full-load rating.</p>
<p><strong>Protection envelope:</strong> minimum speed for oil return and motor cooling, anti-short-cycle timing, surge avoidance on centrifugals.</p>
<p><strong>Diagnose in order:</strong> small load? → stages/drives responding in sequence? → protection limit correctly constraining? → then suspect a component.</p>
<p><strong>Application fit:</strong> reciprocating = small/serviceable · scroll = residential & light commercial default · rotary = compact units · screw = mid/large chillers · centrifugal = largest plants.</p>
`
};
