// HVAC 208 - Module 10: Capacity Testing & Performance Verification
module.exports = {
  number: 10,
  slug: "capacity-testing-performance-verification",
  title: "Capacity Testing & Performance Verification",
  estTime: "3–4 hours",
  objectives: [
    "Compute sensible capacity from measured CFM and air temperature split using the 1.08 formula and state its assumption.",
    "Compute total capacity from measured CFM and enthalpy difference using the 4.5 formula with stated enthalpy values.",
    "Derive latent capacity and sensible heat ratio from sensible and total capacity results.",
    "Compare measured delivered capacity with nameplate rating and interpret the gap correctly.",
    "Plan a full performance-verification visit: stabilize, measure airflow, measure air conditions, compute, compare.",
    "Explain how wet-bulb measurements enter capacity verification (NATE Core: temperature and humidity measurement)."
  ],
  sections: [
    {
      heading: "From Nameplate Promises to Delivered Btu/h",
      html: `<p>A nameplate says what a system delivered on a test stand at rating conditions. The customer lives with what it delivers in their building, through their ducts, at today's weather and indoor load. <strong>Capacity testing</strong> closes that gap using only air-side measurements — no gauges required — by exploiting a simple truth: all the cooling the system does shows up in the airstream. Measure how much air moves and how much heat that air loses crossing the coil, and you have measured the system's real total capacity.</p><p>That total divides into the two jobs air conditioning does. <strong>Sensible capacity</strong> lowers air temperature — the part a thermometer sees. <strong>Latent capacity</strong> removes moisture — invisible to a dry-bulb thermometer, but very visible on a humid day and on the customer's comfort. A system can post a fine total number while failing at one of the two jobs (Module 8's high-airflow humidity failure), which is why verification computes all three figures: sensible, latent, and total.</p><div class="callout"><strong>Key idea:</strong> Capacity verification is the capstone measurement skill of this course and a direct NATE Core expectation (Taking Temperature and Humidity Measurements; Achieving Desired Conditions). It converts "it feels weak" into "it delivers 31,400 of a rated 36,000 Btu/h, with the shortfall traced to airflow" — a sentence a customer and a supervisor can both act on.</div>`
    },
    {
      heading: "Sensible Capacity: The 1.08 Formula",
      html: `<p>Sensible heat carried by an airstream computes from flow and temperature change:</p><div class="formula">Sensible Btu/h = 1.08 × CFM × ΔT &nbsp;(ΔT = return − supply dry-bulb, °F)</div><p>The 1.08 factor bundles standard air's density and specific heat; state it honestly as the <strong>standard-air approximation</strong> — fine for field verification at typical conditions, not a laboratory constant for altitude or extreme temperatures. <strong>Worked example.</strong> A system moves a measured 1,200 CFM with return air at 75°F and supply air at 55°F (ΔT = 20°F). Sensible capacity = 1.08 × 1,200 × 20 = 25,920 Btu/h. Notice what drives the result: if airflow sags, the split usually widens, and the two errors partially mask each other — one more reason airflow itself is measured, never assumed (Module 9).</p><p>Technique notes that decide whether the number means anything: measure return temperature at the unit's return inlet (not at a grille across a hot attic duct unless delivered performance is what you intend), supply temperature in the supply plenum or averaged at the coil outlet, and let the system run long enough to stabilize with a wet coil before recording anything.</p><div class="callout"><strong>Key idea:</strong> Both inputs are averages with conditions attached — stabilized runtime, wet coil, representative sensor placement. A split measured two minutes after startup on a dry coil is a number about startup, not about capacity.</div>`
    },
    {
      heading: "Total Capacity: The 4.5 Formula and Enthalpy",
      html: `<p>Total heat — sensible plus latent — is tracked by the air's <strong>enthalpy</strong> (total heat content per pound of dry air, Btu/lb), which rises with both temperature and moisture. Wet-bulb temperature is the field key to enthalpy: measure return and supply <strong>wet-bulb</strong> temperatures, convert each to enthalpy with a psychrometric chart, app, or table, and compute:</p><div class="formula">Total Btu/h = 4.5 × CFM × Δh &nbsp;(Δh = return enthalpy − supply enthalpy, Btu/lb)</div><p><strong>Worked example (enthalpies given).</strong> Measured airflow is 1,200 CFM. Return air enthalpy is 28.0 Btu/lb and supply air enthalpy is 21.0 Btu/lb, so Δh = 7.0. Total capacity = 4.5 × 1,200 × 7.0 = 37,800 Btu/h ≈ 3.15 tons. Using Section 2's sensible result for the same run (25,920 Btu/h), latent capacity = 37,800 − 25,920 = 11,880 Btu/h — the moisture-removal work the dry-bulb split could not see. (In your own field work the enthalpies come from your wet-bulb readings; in this course's problems they are stated so the arithmetic is checkable.)</p><div class="callout"><strong>Key idea:</strong> The 4.5 factor is the mass flow of standard air per CFM-hour (0.075 lb/ft³ × 60 min) — which is why enthalpy difference, a per-pound quantity, turns into Btu per hour when multiplied by CFM and 4.5. Knowing where constants come from keeps you from applying them where they do not belong.</div>`
    },
    {
      heading: "Sensible Heat Ratio and Interpreting the Split of Work",
      html: `<p>The <strong>sensible heat ratio (SHR)</strong> is the sensible share of total capacity:</p><div class="formula">SHR = Sensible Btu/h ÷ Total Btu/h &nbsp;·&nbsp; Latent = Total − Sensible</div><p>For the worked system: SHR = 25,920 ÷ 37,800 ≈ 0.69 — about 69% of its work is temperature reduction and 31% is moisture removal, a plausible picture for a humid day's load. Interpretation is comparative: the building also has a required SHR set by its loads (people, infiltration, and activities add latent load). A system whose delivered SHR is far above the space's required SHR will satisfy the thermostat while the humidity climbs — the equipment is doing the wrong mix of work, usually because of excessive airflow, short runtimes, or oversizing. A very low SHR with weak temperature pull-down suggests the opposite extreme.</p><p><strong>Worked check.</strong> Suppose the same 1,200 CFM system on a dry, mild day shows Δh = 5.0 (total = 4.5 × 1,200 × 5.0 = 27,000 Btu/h) and ΔT = 19°F (sensible = 1.08 × 1,200 × 19 ≈ 24,624). SHR ≈ 0.91 — the day is dry, the coil has little moisture to remove, and the capacity mix correctly followed the load. SHR judges the match to the day's load, not the machine's virtue.</p><div class="callout"><strong>Key idea:</strong> Never quote an SHR without its conditions. It is a snapshot of machine-meets-load, and its diagnostic power comes from comparing it with what the space needed that day.</div>`
    },
    {
      heading: "The Verification Visit: Procedure and Verdicts",
      html: `<p>Run verification as a fixed procedure. <strong>Step 1 — Stabilize:</strong> system running steadily in cooling, wet coil, indoor conditions representative; note outdoor conditions. <strong>Step 2 — Airflow:</strong> measure CFM by hood, traverse, or static/table (Module 9); correct airflow faults first (Module 8) or report that capacity was measured <em>as found, airflow-limited</em>. <strong>Step 3 — Air conditions:</strong> return and supply dry-bulb and wet-bulb at the unit. <strong>Step 4 — Compute:</strong> sensible (1.08), total (4.5), latent (difference), SHR. <strong>Step 5 — Compare:</strong> against nameplate capacity with conditions in mind — ratings are at standard test conditions, so a hot-day shortfall against rating is expected to a degree; a large shortfall at mild conditions is a finding.</p><p><strong>Verdict patterns.</strong> Total capacity near rating, SHR mismatched to the day → distribution/airflow tuning issue. Total well under rating with airflow verified → now the refrigerant side earns investigation (superheat/subcooling at correct airflow, per earlier modules). Total under rating <em>and</em> airflow under target → fix airflow and re-verify before any refrigerant conclusion. That ordering discipline is the whole course in one paragraph.</p><div class="callout"><strong>Key idea:</strong> A verification report states: measured CFM, the four air conditions, the three capacities, SHR, the conditions of the test, and the verdict. Anything less is a feeling with decimals.</div>`
    }
  ],
  keyTerms: [
    { term: "Capacity testing", def: "Measuring a system's actually delivered cooling from air-side flow and condition measurements." },
    { term: "Sensible capacity", def: "The temperature-lowering portion of total capacity, Btu/h." },
    { term: "Latent capacity", def: "The moisture-removing portion of total capacity, Btu/h; equals total minus sensible." },
    { term: "Total capacity", def: "Sensible plus latent cooling delivered, Btu/h." },
    { term: "Enthalpy", def: "Total heat content of air per pound of dry air (Btu/lb), combining temperature and moisture effects." },
    { term: "Wet-bulb temperature", def: "Temperature measured with a wetted thermometer bulb; with dry bulb it determines air enthalpy and humidity." },
    { term: "1.08 factor", def: "Standard-air constant in the sensible-heat formula Btu/h = 1.08 × CFM × ΔT." },
    { term: "4.5 factor", def: "Standard-air constant in the total-heat formula Btu/h = 4.5 × CFM × Δh." },
    { term: "Sensible heat ratio (SHR)", def: "Sensible capacity divided by total capacity; the share of work spent on temperature vs. moisture." },
    { term: "Nameplate capacity", def: "Rated capacity at standard test conditions; the comparison reference for verification." },
    { term: "Stabilized operation", def: "Steady running with a wet coil and representative conditions, required before capacity readings mean anything." },
    { term: "Delivered capacity", def: "Capacity actually provided to the space under as-found conditions." },
    { term: "Psychrometric chart", def: "Graphical map of air properties used to find enthalpy from dry-bulb/wet-bulb measurements." },
    { term: "As-found condition", def: "The state measurements were taken in, documented so results can be interpreted and compared later." },
    { term: "Dry-bulb temperature", def: "Ordinary thermometer temperature of the air; pairs with wet bulb to fix air enthalpy." },
    { term: "Rating conditions", def: "The standard indoor/outdoor test conditions at which nameplate capacity is certified." },
  ],
  video: {
    title: "HVAC Delta T Explained!",
    embedUrl: "https://www.youtube.com/embed/9lDl5cfFSzs",
    note: "An AC Service Tech explanation of temperature split (Delta T): what it measures, what moves it, and why it must be read alongside humidity and airflow. It is the screening half of this module; Sections 2–3 supply the full capacity arithmetic the video motivates.",
    more: [
      { title: "How to Read a Psychrometric Chart", url: "https://www.youtube.com/watch?v=hC8R7nWlMiw" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A system moves 1,600 CFM with a 19°F air ΔT. Compute sensible capacity.</p>", solution: "<p><strong>Answer: 32,832 Btu/h.</strong> Step 1: Sensible = 1.08 × CFM × ΔT. Step 2: 1.08 × 1,600 × 19 = 32,832 Btu/h. Step 3: This is sensible only — latent work is not included in a dry-bulb split.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Airflow is 1,000 CFM; return enthalpy 29.5 Btu/lb, supply enthalpy 22.5 Btu/lb. Compute total capacity and tons.</p>", solution: "<p><strong>Answer: 31,500 Btu/h ≈ 2.63 tons.</strong> Step 1: Δh = 29.5 − 22.5 = 7.0 Btu/lb. Step 2: Total = 4.5 × 1,000 × 7.0 = 31,500 Btu/h. Step 3: Tons = 31,500 ÷ 12,000 ≈ 2.63.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> For Problem 2's run, the dry-bulb ΔT was 18°F. Compute sensible, latent, and SHR.</p>", solution: "<p><strong>Answer: sensible 19,440; latent 12,060 Btu/h; SHR ≈ 0.62.</strong> Step 1: Sensible = 1.08 × 1,000 × 18 = 19,440. Step 2: Latent = 31,500 − 19,440 = 12,060. Step 3: SHR = 19,440 ÷ 31,500 ≈ 0.62 — a moisture-heavy day, consistent with the large enthalpy difference.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A nominal 3-ton (36,000 Btu/h) system verifies at 29,000 Btu/h total, but airflow measures only 950 CFM. State the correct verdict and next step.</p>", solution: "<p><strong>Answer: capacity as found is airflow-limited; fix airflow and re-verify.</strong> Step 1: Target airflow ≈ 1,200 CFM; 950 is ~21% low. Step 2: Low airflow suppresses delivered capacity and corrupts charge indicators. Step 3: Correct the air path, re-measure CFM, then re-run capacity before touching refrigerant.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Why must the coil be wet and the system stabilized before capacity readings are recorded?</p>", solution: "<p><strong>Answer:</strong> Step 1: Early in a run, the coil is still cooling down and dry — temperatures and splits are still moving. Step 2: Latent work only appears once condensation is established. Step 3: Readings taken early describe startup transients, understating (or mis-stating) true steady capacity.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A system delivers total capacity near rating but the space stays humid, with SHR 0.95 on a humid day. Interpret.</p>", solution: "<p><strong>Answer: wrong work mix — almost all sensible, little latent.</strong> Step 1: Total is fine, so refrigeration capacity exists. Step 2: SHR 0.95 on a humid day means moisture is barely being removed. Step 3: Suspect excessive airflow, short runtimes, or oversizing; tune airflow/runtime rather than refrigerant.</p>" }
  ],
  quiz: [
    { q: "Sensible capacity is computed as:", choices: ["4.5 × CFM × Δh", "1.08 × CFM × ΔT (dry-bulb)", "500 × GPM × ΔT", "CFM × area"], answer: 1, explanation: "Correct: (b). The 1.08 formula uses the dry-bulb split for sensible heat. (a) That is total capacity from enthalpy difference. (c) That is the water-side formula from Module 4. (d) Area × velocity gives CFM, not heat." },
    { q: "At 1,200 CFM and ΔT 20°F, sensible capacity is:", choices: ["24,000 Btu/h", "25,920 Btu/h", "27,000 Btu/h", "12,960 Btu/h"], answer: 1, explanation: "Correct: (b). 1.08 × 1,200 × 20 = 25,920. (a) 24,000 drops the 1.08 factor (uses 1.0). (c) 27,000 comes from misapplying the 4.5 formula with wrong inputs. (d) 12,960 is half the correct product." },
    { q: "Total capacity requires which air property difference?", choices: ["Dry-bulb only", "Enthalpy difference from wet-bulb-based measurements", "Static pressure difference", "Velocity difference"], answer: 1, explanation: "Correct: (b). Total heat includes moisture, tracked by enthalpy via wet bulb. (a) Dry bulb alone sees only sensible work. (c) Static pressure informs airflow inference, not heat content. (d) Velocity yields CFM, one input — not the heat difference." },
    { q: "At 1,200 CFM with Δh = 7.0 Btu/lb, total capacity is:", choices: ["35,000 Btu/h", "37,800 Btu/h", "8,400 Btu/h", "25,920 Btu/h"], answer: 1, explanation: "Correct: (b). 4.5 × 1,200 × 7.0 = 37,800 Btu/h. (a) 35,000 does not follow the product. (c) 8,400 is CFM × Δh with no 4.5 factor. (d) 25,920 is the sensible result for ΔT 20°F — a different quantity." },
    { q: "Latent capacity is found by:", choices: ["Reading it from the nameplate", "Total capacity minus sensible capacity", "1.08 × CFM × wet bulb", "Doubling the sensible capacity"], answer: 1, explanation: "Correct: (b). Latent is the remainder of total work after sensible is known. (a) Nameplates do not split the day's delivered work. (c) No such formula exists — wet bulb feeds enthalpy, not a direct product. (d) The latent share varies with the day's moisture load." },
    { q: "SHR of a run with sensible 25,920 and total 37,800 is about:", choices: ["0.31", "0.69", "1.46", "0.50"], answer: 1, explanation: "Correct: (b). 25,920 ÷ 37,800 ≈ 0.69. (a) 0.31 is the latent share (1 − SHR). (c) 1.46 inverts the ratio and exceeds 1, impossible for a share. (d) 0.50 would require sensible to equal latent, which the figures contradict." },
    { q: "A verified total capacity far below rating, with airflow confirmed correct, directs you next to:", choices: ["Add refrigerant immediately", "Refrigerant-side diagnosis: superheat/subcooling by the manufacturer's method", "Replace the thermostat", "Close supply registers to raise capacity"], answer: 1, explanation: "Correct: (b). With airflow proven, charge indicators are now trustworthy evidence. (a) Adding before measuring repeats the guessing this course forbids. (c) Thermostats do not create capacity. (d) Closing registers reduces airflow and capacity further." },
    { q: "The 1.08 and 4.5 constants are:", choices: ["Exact physical constants for all conditions", "Standard-air approximations appropriate for field verification", "Manufacturer-specific ratings", "EPA regulatory values"], answer: 1, explanation: "Correct: (b). They bundle standard air density/properties and serve field work at typical conditions. (a) Air density varies with altitude and temperature, so they are not universal constants. (c) They are general air properties, not brand data. (d) Regulators do not set heat-formula constants." }
  ],
  studyGuide: `
<h3>Module 10 — Capacity Testing & Performance Verification: Quick Reference</h3>
<div class="formula">Sensible = 1.08 × CFM × ΔT · Total = 4.5 × CFM × Δh · Latent = Total − Sensible · SHR = Sensible ÷ Total</div>
<p><strong>Anchor example:</strong> 1,200 CFM, ΔT 20°F → sensible 25,920 Btu/h. Δh 7.0 (28.0 → 21.0 Btu/lb) → total 37,800 Btu/h ≈ 3.15 tons. Latent 11,880; SHR ≈ 0.69.</p>
<p><strong>Enthalpy comes from wet bulb</strong> (chart/app/table). In course problems enthalpies are stated; in the field they come from your wet-bulb readings.</p>
<p><strong>Procedure:</strong> stabilize (wet coil) → measure CFM → measure return/supply dry & wet bulb at the unit → compute → compare with rating, conditions noted.</p>
<p><strong>Verdicts:</strong> total OK + SHR wrong = work-mix/airflow issue. Total low + airflow low = fix air, re-verify. Total low + airflow right = refrigerant-side diagnosis next.</p>
<p><strong>Honesty notes:</strong> 1.08 and 4.5 are standard-air approximations; report as-found conditions with every result.</p>
<p><strong>Report template:</strong> CFM (method) · return/supply DB & WB · sensible · total · latent · SHR · rating comparison · conditions · verdict. If a line is missing, the verification is not finished.</p>
`
};
