// HVAC 208 - Module 11: A/C Controls & Safeties in Applications
module.exports = {
  number: 11,
  slug: "ac-controls-safeties-in-applications",
  title: "A/C Controls & Safeties in Applications",
  estTime: "3–4 hours",
  objectives: [
    "Distinguish operating controls from safety controls and give examples of each in an A/C system.",
    "Explain how high- and low-pressure switches protect the compressor and what conditions trip each.",
    "Describe freeze protection: coil temperature sensing and freeze stats on larger air handlers.",
    "Explain condensate safeties — float switches and overflow protection — and the damage they prevent.",
    "Read a unit control board's behavior: inputs, outputs, fault codes, and anti-short-cycle timing.",
    "Diagnose a tripped safety by finding its cause instead of resetting and leaving."
  ],
  sections: [
    {
      heading: "Two Families of Controls: Operating vs. Safety",
      html: `<p>Every control on an A/C system answers to one of two masters. <strong>Operating controls</strong> run the show in normal life: the thermostat calls for cooling, the board starts the indoor blower and the outdoor unit, staging and fan delays happen on schedule. <strong>Safety controls</strong> stand guard over abnormal life: they interrupt operation when a measured condition leaves the safe envelope — pressure too high, pressure too low, coil freezing, condensate about to overflow. Safeties are wired so their action overrides the operating controls; a thermostat can call all day, but an open safety keeps the compressor off.</p><p>The diagnostic value of the distinction is immediate. "The thermostat is calling but nothing runs" splits into two hunts: is an operating command missing (no call, no power, board fault), or is a safety holding the system off (and if so, what real condition opened it)? Technicians who blur the families waste hours; technicians who separate them halve every no-cool call — Module 12 is built on exactly this split.</p><div class="callout"><strong>Key idea:</strong> A tripped safety is a <em>report</em>, not a failure. The switch that opened is almost never the problem; the condition that opened it is. Resetting without finding the cause converts a protective shutdown into repeated equipment abuse — the defining amateur move in this trade.</div><p>Safeties come in two reset styles: <strong>automatic reset</strong> (the switch recloses when the condition normalizes — convenient, but it can mask a recurring fault as intermittent operation) and <strong>manual reset</strong> (a human must inspect before restarting — used where the condition is dangerous enough to demand eyes on the equipment).</p>`
    },
    {
      heading: "Pressure Switches: Guarding the Refrigerant Circuit",
      html: `<p>The <strong>high-pressure switch</strong> watches discharge pressure and opens if it climbs beyond its setting — protecting the compressor and components from the mechanical and thermal stress of excessive head pressure. Its trip causes are a greatest-hits of condenser neglect: dirty condenser coil, failed or slow condenser fan, overcharge, non-condensables, or extreme ambient heat overwhelming the system. Each cause leaves head pressure high for a physical reason the switch is reporting faithfully.</p><p>The <strong>low-pressure switch</strong> watches suction pressure and opens when it falls too low — the signature of lost charge, a restriction, or a badly starved evaporator (including severe airflow loss). On many systems it doubles as loss-of-charge protection, preventing the compressor from running in a near-vacuum where its motor cooling (suction-cooled) and lubrication fail. Note the trap: low airflow can drag suction pressure down to the switch's doorstep, so a low-pressure trip still routes you through the Module 8 airflow checks before refrigerant conclusions.</p><div class="callout"><strong>Key idea:</strong> Pressure switches have manufacturer-set cut-out and cut-in points — they are not adjustment opportunities. If a switch trips, measure the actual pressure with gauges and find why it is out of range; if the switch trips at a <em>normal</em> measured pressure, then — and only then — condemn the switch, and prove it by comparing its action to the gauge.</div><p>Some systems add a <strong>low-ambient control</strong> (fan cycling or speed control) that deliberately manages head pressure in cool weather — an operating control borrowing the same pressure signal; do not mistake its normal fan cycling for a fault.</p>`
    },
    {
      heading: "Freeze Protection and Coil Temperature Sensing",
      html: `<p>Ice on an evaporator is both a symptom and a hazard: it blocks airflow, and meltwater or continued operation can damage the coil and send liquid toward the compressor. Small systems rely on the low-pressure switch and thermostat behavior to limit freezing, but larger air handlers add a dedicated <strong>freeze stat</strong>: a temperature sensor (often a long averaging element snaking across the coil face, on chilled-water and large DX equipment) that stops the fan and/or closes valves and alarms when coil-area temperature approaches freezing.</p><p>Freeze-stat trips in the field most often trace back to the usual suspects wearing winter clothes: low airflow across the coil, low load with long runtimes, a chilled-water valve stuck open at low load, or — on DX — low charge. The averaging element matters: it must sense the <em>coldest</em> region of the coil, because a single warm spot can hide a freezing corner. A freeze stat that has been jumpered out by a previous technician is a finding to report and correct, not a technique to copy.</p><div class="callout"><strong>Key idea:</strong> Freeze protection exists because a coil can freeze locally while system averages look acceptable. Respect averaging sensors' placement: a sensor re-taped to a convenient warm pipe during a past repair may have silently disarmed the protection.</div><p>On heat pumps, the defrost controls of Module 3 are the freeze-management system for the outdoor coil — same physics, opposite coil, dedicated control.</p>`
    },
    {
      heading: "Condensate Safeties: Small Switches, Expensive Water",
      html: `<p>Every cooling coil wrings moisture out of the air, and that water must drain. When a drain clogs, a trap dries or plugs, or a pan cracks, the water goes somewhere — into ceilings, walls, and equipment. The <strong>condensate float switch</strong> (overflow safety) sits in the drain pan or a secondary pan and opens its contacts when water rises to a set level, shutting down cooling (or at minimum the compressor) before the overflow becomes a building claim. Auxiliary drain pans under attic air handlers pair with these switches because attic installs put the building at maximum risk.</p><p>Wiring choices matter: a float switch wired to stop the whole system announces itself as a no-cool call — annoying but safe and diagnosable; one wired only to an alarm depends on someone hearing it. After any float-switch trip, the job is not done at reset: clear the drain, verify the trap and slope, pour water through the path to prove drainage, and check for the algae and debris source. A switch that trips monthly is a drain-maintenance finding, not a defective switch.</p><div class="callout"><strong>Key idea:</strong> Condensate is the only A/C product that damages buildings by the gallon. Treat every float-switch trip as a plumbing diagnosis attached to an electrical symptom: prove the drain flows freely before returning the system to service.</div><p>Condensate pumps add their own safety: many include an overflow contact wired the same way when the pump fails or its discharge blocks.</p>`
    },
    {
      heading: "Board Logic: Inputs, Outputs, Codes, and Timers",
      html: `<p>The modern unit control board is the referee between operating and safety controls. Its world is inputs and outputs: <strong>inputs</strong> — thermostat calls, safety switch states, sensor temperatures and pressures (increasingly as electronic transducers and thermistors rather than simple switches); <strong>outputs</strong> — contactor, blower commands, reversing valve (heat pumps), staging relays; and <strong>logic</strong> — anti-short-cycle timers that enforce minimum off-time, blower on/off delays, staging delays, defrost coordination on heat pumps, and lockout behavior after repeated safety trips (many boards lock out after a set number of trips in a run period and report a fault code).</p><p>Fault codes — LED flash patterns or displayed numbers, decoded by the chart on the unit or in its manual — are the board narrating which input it dislikes. Read them before resetting anything: a lockout code pointing at the low-pressure switch sends you to gauges and airflow, not to the parts counter for a board. And respect the timers during diagnosis: a board in its anti-short-cycle delay is not "dead," and repeatedly power-cycling to defeat the delay is how compressors get hurt during testing.</p><div class="callout"><strong>Key idea:</strong> Diagnose boards by their evidence: correct inputs present? Outputs commanded? Code stored? A board is condemned last, after its inputs are proven good and its outputs proven absent — boards are replaced far more often than they fail.</div><p>Close every controls call by restoring all safeties to service — no jumpers left behind, ever — and noting any safety that tripped in your report, even if the cause was found and fixed.</p>`
    }
  ],
  keyTerms: [
    { term: "Operating control", def: "Control that runs equipment in normal operation, e.g., the thermostat and board sequencing." },
    { term: "Safety control", def: "Control that interrupts operation when a condition leaves the safe envelope; overrides operating controls." },
    { term: "High-pressure switch", def: "Safety that opens on excessive discharge pressure, reporting condenser-side problems such as dirt, fan failure, or overcharge." },
    { term: "Low-pressure switch", def: "Safety that opens on abnormally low suction pressure; also loss-of-charge protection on many systems." },
    { term: "Automatic reset", def: "Safety that recloses when its condition normalizes; can make a recurring fault look intermittent." },
    { term: "Manual reset", def: "Safety requiring human inspection and reset before restart, used for serious conditions." },
    { term: "Freeze stat", def: "Coil-area temperature safety, often an averaging element, that stops operation before a coil freezes." },
    { term: "Averaging element", def: "Long sensing element that reads temperature across a coil face so cold spots are not missed." },
    { term: "Condensate float switch", def: "Overflow safety that shuts down cooling when drain water rises to its set level." },
    { term: "Auxiliary drain pan", def: "Secondary pan under equipment (e.g., attic air handlers) catching overflow, usually paired with a float switch." },
    { term: "Anti-short-cycle timer", def: "Board logic enforcing minimum compressor off-time between runs." },
    { term: "Lockout", def: "Board state after repeated safety trips that prevents further operation until reset/inspection." },
    { term: "Fault code", def: "LED pattern or display number by which a board reports which input or condition it is acting on." },
    { term: "Thermistor", def: "Temperature-sensitive resistor used as an electronic sensor input to a control board." },
    { term: "Transducer", def: "Sensor converting pressure into an electronic signal read by a board." },
    { term: "Low-ambient control", def: "Operating control that cycles or slows the condenser fan to maintain head pressure in cool weather." }
  ],
  video: {
    title: "Thermostat Terminals Fully Explained",
    embedUrl: "https://www.youtube.com/embed/4ERgdc_RRBE",
    note: "A terminal-by-terminal explanation of thermostat wiring — the operating-control inputs every board decision starts from. Use it to ground Section 5's inputs/outputs picture before Module 12's no-cool cases, where 'is there even a call?' is step one.",
    more: [
      { title: "Intro to HVAC Controls Class 1 Webinar", url: "https://www.youtube.com/watch?v=cCFIBw7zU6k" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Classify each as operating or safety control: thermostat, high-pressure switch, freeze stat, defrost board timer, float switch.</p>", solution: "<p><strong>Answer:</strong> Step 1: Thermostat — operating (issues normal calls). Step 2: High-pressure switch and freeze stat — safeties (interrupt on abnormal conditions). Step 3: Defrost timer — operating for the heat pump's normal frost management (it sequences a normal function). Step 4: Float switch — safety (stops operation to prevent water damage).</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A high-pressure switch trips repeatedly on hot afternoons. List the physical causes to check before touching the switch.</p>", solution: "<p><strong>Answer:</strong> Step 1: Dirty condenser coil restricting heat rejection. Step 2: Condenser fan failed, slow, or obstructed airflow. Step 3: Overcharge or non-condensables raising head pressure. Step 4: Only if gauges show normal pressure during trips do you test the switch itself.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Why can a low-pressure trip be an airflow finding rather than a charge finding?</p>", solution: "<p><strong>Answer:</strong> Step 1: Severe indoor airflow loss starves the evaporator of heat. Step 2: Evaporating temperature and suction pressure fall toward the switch's cut-out. Step 3: Therefore airflow is measured (Module 8 sequence) before charge is judged — the switch reports a pressure, not its cause.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A float switch trips every few weeks; each time the drain 'looks clear.' What is the thorough response?</p>", solution: "<p><strong>Answer:</strong> Step 1: Actually clear and flush the drain and trap; remove algae/debris at the source. Step 2: Verify drain slope and trap condition; correct any sagging or double-trapping. Step 3: Pour water through the full path to prove free drainage. Step 4: Check pan condition and switch placement. Recurrence means an uncorrected drain fault, not a bad switch.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A board shows a lockout code for the low-pressure switch, but the system runs fine whenever it is reset — for a day. Explain what is happening and the risk of just resetting it.</p>", solution: "<p><strong>Answer:</strong> Step 1: An automatic condition (e.g., marginal charge or airflow) repeatedly drags suction pressure to cut-out; the board locks out after repeated trips. Step 2: Resetting restarts the cycle without removing the cause. Step 3: Repeated low-pressure running risks compressor cooling/lubrication damage — the lockout is the board insisting on a diagnosis.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> During diagnosis a board sits silent for several minutes after power is restored, then starts normally. Fault or feature? How do you confirm?</p>", solution: "<p><strong>Answer: feature — anti-short-cycle delay.</strong> Step 1: Boards enforce minimum off-time after power loss or a stop. Step 2: Confirm by timing the delay against the manufacturer's stated value and watching for a normal start. Step 3: Do not power-cycle repeatedly to 'test' — that defeats the protection the timer provides.</p>" }
  ],
  quiz: [
    { q: "A safety control's defining trait is that it:", choices: ["Sets the space temperature", "Overrides operating controls to stop operation on abnormal conditions", "Runs the blower continuously", "Replaces the thermostat"], answer: 1, explanation: "Correct: (b). Safeties interrupt operation outside the safe envelope regardless of calls. (a) Temperature setting is the thermostat's operating role. (c) Continuous blower is an operating setting. (d) Safeties supplement, never replace, normal controls." },
    { q: "A high-pressure switch trip most likely reports:", choices: ["Low charge", "Condenser-side trouble: dirty coil, fan failure, overcharge, or non-condensables", "A clogged drain", "Low indoor airflow"], answer: 1, explanation: "Correct: (b). All raise discharge pressure by impairing heat rejection or adding pressure. (a) Low charge lowers pressures. (c) Drains are condensate-side. (d) Indoor airflow loss lowers suction pressure primarily." },
    { q: "The low-pressure switch on many systems doubles as:", choices: ["The defrost control", "Loss-of-charge protection for the compressor", "The thermostat", "A condensate safety"], answer: 1, explanation: "Correct: (b). It stops the compressor from running dry and uncooled on lost charge. (a) Defrost is board/sensor work on heat pumps. (c) It issues no comfort calls. (d) Condensate protection is the float switch's job." },
    { q: "A freeze stat with an averaging element is used because:", choices: ["Averages are cheaper", "A coil can freeze in one region while a single-point sensor reads a warm spot", "It measures refrigerant pressure", "It replaces the filter"], answer: 1, explanation: "Correct: (b). The long element senses the coldest area across the coil face. (a) Cost is not the engineering reason. (c) It senses temperature, not pressure. (d) Filtration is unrelated to freeze sensing." },
    { q: "After a float-switch trip, the job is complete when:", choices: ["The switch is reset", "The drain is cleared, trap/slope verified, and water poured through to prove drainage", "The thermostat is raised", "The pan is emptied once"], answer: 1, explanation: "Correct: (b). The trip is a drain diagnosis; proving flow prevents the repeat overflow. (a) Reset alone guarantees a repeat. (c) Thermostat changes do nothing for drainage. (d) Emptying treats the symptom once; the blockage remains." },
    { q: "An automatic-reset safety can make a real fault appear as:", choices: ["A permanent lockout", "Intermittent operation that 'fixes itself'", "A fault code that never clears", "Higher efficiency"], answer: 1, explanation: "Correct: (b). The switch recloses when conditions normalize, so the system cycles between trip and recovery. (a) Permanent lockout is the opposite behavior. (c) Auto-reset devices typically store no code. (d) Tripping never improves efficiency." },
    { q: "Before condemning a control board, you should prove:", choices: ["That a new board is in stock", "Its inputs are good and its commanded outputs are absent", "The thermostat batteries are new", "The refrigerant charge is correct"], answer: 1, explanation: "Correct: (b). Boards fail less often than their inputs; evidence order protects the customer. (a) Stock is logistics, not diagnosis. (c) Batteries are one small input check among many. (d) Charge is proven by its own sequence and does not indict a board." },
    { q: "Finding a jumpered-out safety during a call, the correct action is:", choices: ["Leave it — someone had a reason", "Restore the safety to service, find why it was bypassed, and document it", "Jumper the remaining safeties to match", "Remove the safety entirely"], answer: 1, explanation: "Correct: (b). A bypassed safety is a hazard and a clue that its root cause was never fixed. (a) Leaving it accepts the risk silently. (c) Compounding bypasses multiplies danger. (d) Removal defeats the protection the equipment was listed with." }
  ],
  studyGuide: `
<h3>Module 11 — A/C Controls & Safeties: Quick Reference</h3>
<p><strong>Operating controls</strong> run normal life (thermostat, board sequencing). <strong>Safeties</strong> override them on abnormal conditions. A tripped safety is a report — find the condition, never just reset.</p>
<p><strong>High-pressure switch:</strong> condenser-side causes — dirty coil, fan failure, overcharge, non-condensables, extreme heat. <strong>Low-pressure switch:</strong> low charge, restriction, or severe airflow loss; doubles as loss-of-charge protection.</p>
<p><strong>Freeze stat:</strong> averaging element across the coil face; trips route to airflow/load/valve causes. <strong>Float switch:</strong> condensate overflow protection; job ends only when the drain is proven flowing.</p>
<p><strong>Resets:</strong> automatic (can masquerade as intermittent faults) vs. manual (demands inspection). <strong>Lockout:</strong> board gives up after repeated trips and stores a code — read it before resetting.</p>
<p><strong>Board diagnosis order:</strong> inputs proven → outputs checked → code read → board condemned last. Respect anti-short-cycle timers; restore every safety; leave no jumpers.</p>
<p><strong>Golden rule:</strong> safeties protect equipment and buildings; a diagnosis that ends with a safety bypassed has not ended — it has created the next call, and possibly the damage claim that follows it.</p>
`
};
