// HVAC 208 - Module 12: A/C Troubleshooting Masterclass
module.exports = {
  number: 12,
  slug: "ac-troubleshooting-masterclass",
  title: "A/C Troubleshooting Masterclass",
  estTime: "3–4 hours",
  objectives: [
    "Run a fixed diagnostic sequence for no-cool calls: call, power, safeties, air side, refrigerant side.",
    "Separate weak-cool complaints into airflow, capacity-mix, and refrigerant causes using Module 10 verification.",
    "Diagnose icing calls by identifying which of the classic causes is present before thawing conclusions are drawn.",
    "Recognize the look-alike symptom patterns — low airflow vs. undercharge vs. restriction — and the measurements that separate them.",
    "Apply heat pump mode-specific reasoning to wrong-temperature and defrost-related complaints.",
    "Close a call with verification: re-measure after repair and document conditions, readings, and the proven cause."
  ],
  sections: [
    {
      heading: "The Master Sequence: Never Diagnose Out of Order",
      html: `<p>Every call in this masterclass obeys one sequence, assembled from the whole course. <strong>Step 1 — The call:</strong> is the thermostat actually requesting cooling, in the right mode, with a sane setpoint? <strong>Step 2 — Power and controls:</strong> line voltage present, control power present, board behavior and codes read (Module 11). <strong>Step 3 — Safeties:</strong> is a safety holding the system off, and what condition does it report? <strong>Step 4 — Air side:</strong> blower runs, filter/coil/ducts inspected, airflow measured (Modules 8–9). <strong>Step 5 — Refrigerant side:</strong> only now, gauges and temperatures — superheat/subcooling by the manufacturer's method, at verified airflow. <strong>Step 6 — Verify and document:</strong> repair, re-measure, prove the fix under the same conditions that exposed the fault.</p><p>The sequence is not bureaucracy; it is economics. Each step rules out a family of causes with cheap observations before expensive ones, and it prevents the classic self-inflicted wounds: charging an airflow problem (Module 8), replacing a board that was reporting a safety (Module 11), condemning a compressor for a staging fault (Module 7).</p><div class="callout"><strong>Key idea:</strong> Experts are not faster guessers; they are stricter sequencers. When a call confuses you, do not think harder at the step you are on — go back to the step you skipped.</div>`
    },
    {
      heading: "No-Cool Calls, End to End",
      html: `<p><strong>Case 1 — Nothing runs.</strong> Thermostat calls for cooling; indoor and outdoor units are silent. Sequence at work: confirm the call at the board's input terminals (operating control present?), confirm power, then read the board. A stored low-pressure lockout code reframes the call instantly — the system ran, tripped repeatedly, and locked out; the hunt is now the pressure's cause, not the silence. No code and no call at the board moves the hunt to the thermostat and its wiring. Each branch was chosen by evidence, not by habit.</p><p><strong>Case 2 — Blower runs, outdoor unit silent.</strong> The air side is alive; the refrigeration side is not. Check the outdoor unit's power and its own controls: contactor pulled in? A float switch (Module 11) wired into the outdoor-unit circuit is a classic silent killer here — pan full of water, drain clogged, system blasting unconditioned air while the customer reports "it runs but doesn't cool." Prove the drain, clear it, and the "electrical fault" is fixed with a wet vac and a brush.</p><p><strong>Case 3 — Everything runs, nothing cools.</strong> Compressor and fans run but suction pressure sits near zero-ish behavior with a frosty suction line pattern of a massive restriction or near-total charge loss — or the reversing valve on a heat pump is stuck mid-position bleeding discharge to suction (Module 2). Temperatures across the reversing valve's tubes separate the valve case; superheat/subcooling patterns at verified airflow separate the rest. Notice: gauges appear in case 3, at step 5 — after three cheaper families were cleared.</p><div class="callout"><strong>Key idea:</strong> "No-cool" is three different calls wearing one coat: nothing runs, half runs, or everything runs without cooling. Naming which one you are on — out loud, in your notes — is the first diagnostic act.</div>`
    },
    {
      heading: "Weak-Cool Calls: Capacity Thinking",
      html: `<p>Weak-cool — "it runs all day and never quite gets there" — is where Module 10 earns its keep. Do not reach for gauges first; run the verification visit: stabilize, measure CFM, measure the four air conditions, compute sensible/total/latent and SHR, compare with rating. The pattern of numbers names the family. <strong>Low CFM with wide split and low total:</strong> airflow fault — hunt the Module 8 restriction list. <strong>Good CFM, total capacity low, SHR plausible:</strong> refrigerant-side fault — now superheat/subcooling at this verified airflow separates undercharge (low subcooling pattern with TXV behavior per earlier modules) from restriction and other faults. <strong>Total near rating, SHR far too high for the day, space clammy:</strong> work-mix fault — airflow too high, runtimes too short, or equipment oversized.</p><p><strong>Worked case.</strong> A 3-ton system (rating 36,000 Btu/h) verifies at 1,150 CFM (target ≈ 1,200 — acceptable), total capacity 26,500 Btu/h. Airflow is essentially exonerated; the 26% capacity shortfall is real and refrigerant-side. Superheat/subcooling measured now will be meaningful — and they point to the specific fault rather than to "maybe a little low on gas." Contrast the same 26,500 Btu/h measured at 850 CFM: there, the identical capacity number belongs to the air side, and refrigerant readings would have lied about it.</p><div class="callout"><strong>Key idea:</strong> A capacity number without its CFM is uninterpretable. Weak-cool diagnosis is the disciplined pairing of Module 9's airflow with Module 10's arithmetic — feelings and gauge-only hunches are both demoted.</div>`
    },
    {
      heading: "Icing Calls: The Coil That Froze",
      html: `<p>Ice on the coil or suction line is a conclusion, not a cause — the coil ran below freezing with moisture present, and a short list of mechanisms can do that. Work the list with measurements. <strong>Low airflow</strong> (Module 8's list: filter, coil fouling, blower, ducts, registers closed by occupants "to push air elsewhere"). <strong>Low charge or restriction</strong> starving the coil so its temperature crashes (judged only at correct airflow — thaw the coil, fix airflow, then measure). <strong>Low load operation:</strong> cooling run in cool weather or against a very cold space, where even a healthy system can drift toward freezing — check what the thermostat and the calendar are asking for. <strong>Blower faults in disguise:</strong> a blower that stops while the compressor runs (failed motor, board relay, or a belt on older equipment) ices a coil in minutes.</p><p>Procedure matters as much as diagnosis: shut the cooling off, run the fan to thaw completely, and find the meltwater path clear (a thawing coil makes a lot of water — Module 11's float switch may do its job mid-thaw, which is information, not a second fault). Never chip ice mechanically; never restart cooling "to see if it does it again" before the cause hunt; and never add refrigerant to a system whose coil is still a block of ice — every reading is fiction until the coil is clear and the air is moving.</p><div class="callout"><strong>Key idea:</strong> The thaw is part of the diagnosis: watch how the system behaves from a clean, dry start with airflow verified, and the icing mechanism usually announces itself in the first run cycle's measurements.</div>`
    },
    {
      heading: "Look-Alikes, Heat Pump Twists, and Closing the Call",
      html: `<p>The course's three great look-alikes share low suction pressure and weak cooling: <strong>low airflow</strong>, <strong>undercharge</strong>, and <strong>restriction</strong>. They separate on evidence collected in sequence: airflow measured (separates the first), then superheat/subcooling and the pattern across the metering device and filter-drier (separates the other two — a restriction shows a temperature/pressure story localized at the blockage, undercharge shows a system-wide story). Memorize the method, not a symptom chart: charts fail on combined faults; sequence handles them one family at a time.</p><p><strong>Heat pump twists.</strong> Wrong-temperature complaints add mode logic: heating on a cooling call points at the reversing-valve signal (Module 2); cold air in defrost points at aux tempering (Module 3); "steam and a whoosh" is normal defrost, best fixed by explaining it. Each twist is a previous module wearing a service uniform — which is the point of a masterclass.</p><div class="callout"><strong>Key idea:</strong> Close every call the same way: repair the proven cause, re-run the failing conditions, re-measure the numbers that condemned the fault (CFM, pressures, split, capacity), confirm safeties restored and panels replaced, and write down cause + evidence + verification. The next technician — often future you — inherits your notes, not your memory.</div><p>You now hold the full application toolkit: equipment families, heat pumps and defrost, chillers, towers, compressors, airflow, measurement, capacity verification, and controls. The exams and the two scenario labs test exactly this: sequence, arithmetic, and the discipline to measure before concluding.</p>`
    }
  ],
  keyTerms: [
    { term: "Master sequence", def: "The fixed diagnostic order: call → power/controls → safeties → air side → refrigerant side → verify and document." },
    { term: "No-cool call", def: "Service call where no cooling is delivered; subdivides into nothing-runs, partial-runs, and runs-without-cooling." },
    { term: "Weak-cool call", def: "Service call where cooling is delivered but insufficient; diagnosed by capacity verification." },
    { term: "Look-alike faults", def: "Faults sharing symptoms (low airflow, undercharge, restriction) that require measurements in sequence to separate." },
    { term: "Restriction", def: "A partial blockage in the refrigerant path (metering device, drier, kink) starving the evaporator." },
    { term: "Temperature drop across a component", def: "Measured temperature change indicating a restriction location (e.g., across a filter-drier)." },
    { term: "Thaw procedure", def: "Cooling off, fan running, until coil ice fully melts and drains before further measurement." },
    { term: "Verification after repair", def: "Re-measuring the condemning values under the original fault conditions to prove the fix." },
    { term: "As-found readings", def: "Measurements taken before any adjustment, preserved as the baseline evidence of the fault." },
    { term: "Combined fault", def: "Two independent faults present at once; handled by fixing one family at a time in sequence." },
    { term: "Stuck reversing valve (field signs)", def: "Capacity loss in both modes with discharge bleeding toward suction; checked by tube temperature comparison." },
    { term: "Documentation", def: "Written record of cause, evidence, repair, and verification readings closing a service call." },
    { term: "Board lockout code", def: "Stored board report reframing a no-cool call as a prior safety-trip history." },
    { term: "Work-mix fault", def: "Capacity present but split wrongly between sensible and latent work for the day's load (SHR mismatch)." },
    { term: "Filter-drier", def: "Refrigerant-line filter and moisture remover; a temperature drop across it can reveal a restriction." },
    { term: "Metering-device starvation", def: "Condition where too little refrigerant is fed to the evaporator, crashing coil temperature and suction pressure." },
  ],
  video: {
    title: "HVAC Training Basics for New Techs: Gauges, Pressures, Temps, Check the Charge!",
    embedUrl: "https://www.youtube.com/embed/NOWQsrjm4AY",
    note: "An AC Service Tech fundamentals session tying gauges, pressures, and temperatures together on a real charge check. Watch how readings are gathered as a set and interpreted against conditions — the refrigerant-side step of the master sequence, performed after the air side is settled.",
    more: [
      { title: "Explaining Superheat and Subcooling to Your Apprentice!", url: "https://www.youtube.com/watch?v=2SEDe0v8VPY" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A no-cool call: thermostat calls, nothing runs anywhere, and the board shows a low-pressure lockout code. Restate the real problem and the next two steps.</p>", solution: "<p><strong>Answer: the silence is a lockout; the fault is whatever kept tripping the low-pressure switch.</strong> Step 1: Record the code before resetting. Step 2: Follow the sequence — safeties' cause hunt: check airflow family first (filter/coil/blower), then, at verified airflow, evaluate charge/restriction with gauges. Step 3: Verify by running through the trip conditions without a repeat trip.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> Blower runs, outdoor unit never starts, and the indoor pan is full of water. Connect the findings.</p>", solution: "<p><strong>Answer: the float switch has shut down the outdoor unit on a clogged drain.</strong> Step 1: The pan full of water is the safety's condition, found in the safeties step. Step 2: Clear the drain, verify trap and slope, pour water through to prove flow. Step 3: Confirm normal start and drainage in operation; document the drain as the cause.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Weak-cool: CFM measures 1,180 on a 3-ton (target ≈ 1,200), total capacity 27,000 Btu/h vs. 36,000 rating. Which family owns the fault, and what do you measure next?</p>", solution: "<p><strong>Answer: refrigerant side.</strong> Step 1: Airflow is within a few percent of target — exonerated. Step 2: A ~25% capacity shortfall at correct airflow is a genuine refrigeration problem. Step 3: Measure superheat and subcooling by the manufacturer's method to separate undercharge from restriction and related faults.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Same numbers as Problem 3, except CFM measures 830. How does the verdict change?</p>", solution: "<p><strong>Answer: the air side owns it until proven otherwise.</strong> Step 1: 830 CFM is ~31% below target — enough to suppress capacity and mimic charge faults. Step 2: Hunt the restriction list (filter, coil, blower, ducts) and restore airflow. Step 3: Re-verify capacity at correct CFM; only a remaining shortfall earns refrigerant-side diagnosis.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> You arrive to a coil encased in ice. Write the first three actions in order.</p>", solution: "<p><strong>Answer:</strong> Step 1: Cooling off; fan on to thaw; protect the drain path for meltwater. Step 2: While thawing, inspect the air path (filter, registers, blower evidence) without refrigerant conclusions. Step 3: Once thawed and dry, start a monitored run with airflow verified and watch pressures/split develop — the mechanism reveals itself in the first cycle.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> A heat pump blows cold air for a few minutes several times a day in winter, with steam rising from the outdoor unit. The customer wants it 'fixed.' Respond.</p>", solution: "<p><strong>Answer: this is normal defrost — but verify aux tempering.</strong> Step 1: Steam + periodic brief reversal = a defrost event (Module 3). Step 2: Check that auxiliary heat tempers the indoor air during events; if aux fails, that is a real fault to repair. Step 3: If aux works, educate the customer on what they are seeing and log the system as operating normally.</p>" }
  ],
  quiz: [
    { q: "In the master sequence, refrigerant-side measurements come:", choices: ["First, before anything else", "After call, power/controls, safeties, and air side are checked", "Only if the customer requests them", "Instead of airflow measurement"], answer: 1, explanation: "Correct: (b). Gauges at step 5 interpret correctly only at verified airflow with safeties understood. (a) Gauge-first is the guessing habit the course replaces. (c) The sequence is professional discipline, not a menu. (d) Airflow measurement is a prerequisite, not an alternative." },
    { q: "'Nothing runs' with a stored low-pressure lockout code means the first hunt is:", choices: ["A new thermostat", "The cause of the repeated low-pressure trips", "A new control board", "The condensate drain"], answer: 1, explanation: "Correct: (b). The code reframes silence as a trip history needing a cause. (a) The thermostat was calling — the call existed. (c) The board is reporting, not failing. (d) Drains cause float-switch shutdowns, a different code/path." },
    { q: "Blower running, outdoor unit off, drain pan full — the likely interruption is:", choices: ["High-pressure switch", "Condensate float switch", "Freeze stat", "Defrost board"], answer: 1, explanation: "Correct: (b). The float switch stops cooling on high water — and the pan proves its condition. (a) High-pressure trips need a running compressor to develop pressure. (c) Freeze stats guard coil temperature, not drain water. (d) Defrost boards serve heat pump outdoor coils." },
    { q: "Two systems both deliver 27,000 Btu/h against a 36,000 rating; one at 1,180 CFM, one at 830 CFM (3-ton). The correct read is:", choices: ["Both need refrigerant", "The 1,180 CFM unit has a refrigerant-side fault; the 830 CFM unit has an airflow fault to fix first", "Both need bigger equipment", "CFM is irrelevant to capacity verdicts"], answer: 1, explanation: "Correct: (b). Identical capacity numbers mean opposite things at different airflow — context is the diagnosis. (a) Charging the 830 CFM unit overcharges it once airflow is fixed. (c) Neither verdict is about sizing until faults are cleared. (d) The comparison itself proves CFM's relevance." },
    { q: "On an icing call, the first actions are:", choices: ["Add refrigerant and observe", "Chip the ice off and restart cooling", "Cooling off, fan on to thaw, inspect the air path", "Replace the metering device"], answer: 2, explanation: "Correct: (c). Thaw first; every reading on an iced coil is fiction. (a) Charging an iced system corrupts a possibly good charge. (b) Chipping damages fins and solves nothing. (d) Parts are condemned by measurements that require a thawed, air-moving coil." },
    { q: "Low airflow, undercharge, and restriction are separated primarily by:", choices: ["Guessing from experience", "Measuring airflow first, then superheat/subcooling patterns and localized temperature drops at verified airflow", "Replacing the cheapest part first", "Checking the thermostat batteries"], answer: 1, explanation: "Correct: (b). Sequence plus localized evidence separates the look-alikes, including combined faults. (a) Guessing is what the patterns exist to replace. (c) Parts-swapping is not diagnosis. (d) Batteries affect calls, not these running symptoms." },
    { q: "Steam rising from a heat pump's outdoor unit in winter with a brief cold draft indoors most likely indicates:", choices: ["A refrigerant leak", "A normal defrost event — verify auxiliary tempering", "A failed compressor", "A stuck contactor"], answer: 1, explanation: "Correct: (b). Steam is melting frost; the draft is the indoor coil in defrost, which aux heat should temper. (a) Refrigerant leaks do not make steam. (c) A failed compressor makes no defrost at all. (d) A stuck contactor causes continuous running, not periodic steaming." },
    { q: "A call is properly closed when:", choices: ["The system starts once", "The part is replaced", "The proven cause is repaired, the condemning measurements are re-taken under the fault conditions and now pass, safeties are restored, and the work is documented", "The customer stops calling"], answer: 2, explanation: "Correct: (c). Verification under the original conditions is the proof; documentation is the handoff. (a) One start proves nothing about the fault conditions. (b) Replacement without verification leaves combined faults alive. (d) Silence is not evidence." }
  ],
  studyGuide: `
<h3>Module 12 — A/C Troubleshooting Masterclass: Quick Reference</h3>
<p><strong>Master sequence:</strong> 1) the call, 2) power & controls, 3) safeties (what are they reporting?), 4) air side (measure CFM), 5) refrigerant side (superheat/subcooling at verified airflow), 6) verify & document.</p>
<p><strong>No-cool = three calls:</strong> nothing runs (call/power/lockout codes) · half runs (which half? float switches, contactors) · everything runs, no cooling (valve stuck, restriction, charge — at step 5).</p>
<p><strong>Weak-cool:</strong> verify capacity (Module 10). Low CFM → air side. Good CFM + low total → refrigerant side. Good total + wrong SHR → work-mix.</p>
<p><strong>Icing:</strong> thaw first (cooling off, fan on); causes = airflow, starved coil, low-load operation, blower failure. No readings until the coil is clear and air moves.</p>
<p><strong>Look-alikes</strong> (low airflow / undercharge / restriction) separate by sequence + localized drops, never by symptom charts alone.</p>
<p><strong>Close the call:</strong> repair the proven cause, re-measure under fault conditions, restore all safeties, document cause + evidence + verification.</p>
<p><strong>When stuck:</strong> name which no-cool subtype you are on, return to the earliest skipped sequence step, and re-measure — confusion is usually a skipped step, not a strange fault.</p>
`
};
