// HVAC 117 — Scenario lab: Motor & Start-Component Diagnosis.
// Scenario lab on the numeric engine: each row has one checked input at col 1.
// Decision rows: enter the correct option number. Order rows: enter the step number.
// Computed rows: enter the numeric answer.

module.exports = [
  {
    id: "motor-start-diagnosis",
    title: "Motor & Start-Component Diagnosis",
    introHtml: "<p><strong>Job ticket — No-cool call, residential split system.</strong> Customer reports: 'Outside unit fan runs, but it just hums every few minutes and the house keeps getting hotter.' Equipment: 3-ton split air conditioner with a PSC hermetic compressor and a dual run capacitor. Your first live checks, taken with a cooling call active: supply voltage at the contactor line side is a steady <strong>240 V</strong>; the condenser fan runs normally; the compressor hums for a few seconds, then goes silent (its internal overload has opened), cools, and retries. With the compressor trying to run, you also measured <strong>9 V across one closed contactor pole</strong>. Nameplate and component data you will need: dual run capacitor marked <strong>45/5 µF, tolerance ±6%</strong>. Everything else, you are about to measure yourself — in the right order.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=m2wHS4uJUfU\" target=\"_blank\" rel=\"noopener\">HVAC: How To Check a DUAL CAPACITOR With A Multimeter (HVAC Training - Dual Run Capacitor)</a> — the dual-capacitor capacitance test at the heart of this diagnosis, shown step by step.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Before any panel or component work: wear your PPE (safety glasses and electrically rated gloves appropriate to the task). Open the disconnect, apply your lock and tag, and <strong>prove the circuit dead</strong> with your meter (test the meter on a known live source, test the circuit, re-test the meter). Treat every capacitor as charged until you have <strong>discharged it</strong> through a resistor or approved discharge tool — never with a screwdriver short. Only then touch terminals, and only measure resistance or capacitance on de-energized, isolated components.</p><p><strong>Your procedure, in correct order:</strong> Step 1 — Lockout/tagout and prove dead. Step 2 — Visual inspection (bulged or leaking capacitor, burned terminals, damaged wires). Step 3 — Discharge the capacitor, then tag and remove its wires. Step 4 — Measure the capacitance of both capacitor sections and compare with the marked rating and tolerance. Step 5 — Measure compressor winding resistances (all three terminal pairs) and test each terminal to ground. Step 6 — Only after repairs: restore power and verify under load (voltage delivered, voltage-drop across contacts, running current versus nameplate) through a full cooling cycle.</p><p>For each row: read the situation, then enter the correct option number, step number, or computed value in the 'Your call' column.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY — You have arrived and verified the complaint. What is your FIRST action before opening the unit's wiring compartment to work? 1) Open the disconnect, lock it out and tag it, prove the circuit dead with a verified meter, with PPE on 2) Pull the wires off the capacitor so it cannot surprise you 3) Measure winding resistances at the compressor terminals 4) Jumper the contactor to watch the compressor try to start", cells: [""], inputs: [
        { col: 1, key: "safety_first", expected: 1, hint: "Step 0 governs everything: PPE, lockout/tagout at the disconnect, and proving dead with a meter you have verified on a known source. Options 2 and 3 touch components on a circuit not yet proven dead, and option 4 deliberately energizes a faulting compressor — defeating the overload's protection." } ] },
      { label: "PROCEDURE ORDER — The full procedure is listed in the task above (Steps 1–6). At what step number do you MEASURE THE CAPACITANCE of both capacitor sections? Enter the step number.", cells: [""], inputs: [
        { col: 1, key: "order_cap_test", expected: 4, hint: "Capacitance is Step 4: it can only happen after lockout (Step 1), visual inspection (Step 2), and discharging plus tagging/removing the capacitor wires (Step 3). Measuring capacitance on a connected or charged capacitor gives false readings and can damage the meter." } ] },
      { label: "PROCEDURE ORDER — At what step number do you DISCHARGE the capacitor and tag/remove its wires? Enter the step number.", cells: [""], inputs: [
        { col: 1, key: "order_discharge", expected: 3, hint: "Discharging and wire removal is Step 3 — after the circuit is locked out and proven dead (Step 1) and inspected (Step 2), and before any capacitance measurement (Step 4). Tagging the wires matters: a dual capacitor landed wrong on reassembly creates a brand-new fault." } ] },
      { label: "PROCEDURE ORDER — At what step number do you perform LOCKOUT/TAGOUT and prove the circuit dead? Enter the step number.", cells: [""], inputs: [
        { col: 1, key: "order_loto", expected: 1, hint: "Lockout/tagout and proving dead is Step 1 — the first hands-on act of the procedure, immediately after the Step 0 safety briefing. Every later step depends on it." } ] },
      { label: "COMPUTED READING — The capacitor's compressor (HERM) section is marked 45 µF with a tolerance of ±6%. What is the LOWEST capacitance (in µF) that section may measure and still be within tolerance? Enter the number.", cells: [""], inputs: [
        { col: 1, key: "herm_min", expected: 42.3, hint: "Lowest acceptable = marked rating × (1 − tolerance) = 45 × 0.94 = 42.3 µF. Judge the capacitor against its own marked rating and marked tolerance — never against a rule of thumb." } ] },
      { label: "DECISION — Your meter reads the HERM section at 37 µF. What is the correct call? 1) It is within tolerance — reinstall it 2) It is below the 42.3 µF minimum — the capacitor has lost capacitance and must be replaced 3) It is above the maximum — the capacitor is overcharged 4) Capacitance cannot be judged without the fan section's reading", cells: [""], inputs: [
        { col: 1, key: "herm_verdict", expected: 2, hint: "37 µF is well below the 42.3 µF floor from the previous row. A weakened capacitor's reactance (XC) rises, the start (auxiliary) winding is starved of current, and starting torque collapses — exactly the hum-and-trip pattern on the ticket. Each section is judged against its own rating, so option 4 is wrong." } ] },
      { label: "COMPUTED READING — The capacitor's fan (FAN) section is marked 5 µF, tolerance ±6%. What is the HIGHEST capacitance (in µF) that section may measure and still be within tolerance? Enter the number.", cells: [""], inputs: [
        { col: 1, key: "fan_max", expected: 5.3, hint: "Highest acceptable = marked rating × (1 + tolerance) = 5 × 1.06 = 5.3 µF." } ] },
      { label: "DECISION — The FAN section measures 4.9 µF, inside its 4.7–5.3 µF tolerance band. The fan runs fine. What is the correct repair decision for the capacitor? 1) Leave the capacitor in place, since one section tests good 2) Replace the dual capacitor — it is a single can, so the failed HERM section condemns the whole part 3) Wire the fan section to the compressor instead, since it tests good 4) Add a second capacitor in series to raise the HERM value", cells: [""], inputs: [
        { col: 1, key: "cap_repair", expected: 2, hint: "A dual run capacitor is one sealed can with two sections; sections are not separately replaceable, and the failed HERM section condemns the part. Option 1 leaves the no-start fault in place. Option 3 would feed the compressor a 5 µF section — hopelessly below its 45 µF requirement. Option 4: series capacitors reduce total capacitance, the opposite of what is needed, and improvised capacitor wiring is never the repair." } ] },
      { label: "COMPUTED READING — Winding tests (power off, wires isolated): Common-to-Run reads 2 Ω and Common-to-Start reads 6 Ω. By the sum rule, what MUST Start-to-Run read on healthy windings? Enter the number of ohms.", cells: [""], inputs: [
        { col: 1, key: "sr_expected", expected: 8, hint: "The sum rule: C–R + C–S = S–R, so 2 + 6 = 8 Ω. Your meter does in fact read 8 Ω — the windings are internally consistent, with no open or shorted section." } ] },
      { label: "DECISION — The three winding readings are C–R = 2 Ω, C–S = 6 Ω, S–R = 8 Ω, and no terminal shows continuity to the compressor shell. What do the readings prove? 1) The start winding is open 2) The windings are consistent (2 + 6 = 8), the high-resistance side from Common is Start, and the compressor is neither open nor grounded — the windings are acquitted 3) The compressor is grounded 4) The terminals cannot be identified from resistance", cells: [""], inputs: [
        { col: 1, key: "winding_verdict", expected: 2, hint: "The sum rule holds exactly, the larger reading from Common (6 Ω) identifies Start (fine wire, higher resistance), the smaller (2 Ω) identifies Run, and the terminal-to-shell test is open — so the motor itself passes every test. Combined with the failed capacitor, the diagnosis is complete: good motor, starved start circuit." } ] },
      { label: "COMPUTED READING — From the winding data (C–R = 2 Ω, S–R = 8 Ω), what is the resistance of the START winding alone? Enter the number of ohms.", cells: [""], inputs: [
        { col: 1, key: "start_winding", expected: 6, hint: "The Start-to-Run path runs through both windings in series: S–R = (start winding) + (run winding). So start winding = 8 − 2 = 6 Ω — which is also exactly what the direct C–S measurement read, a good cross-check." } ] },
      { label: "COMPUTED READING — From the ticket: supply at the contactor line side is 240 V, and one closed contactor pole drops 9 V under load. How many volts are actually delivered past that pole toward the compressor? Enter the number.", cells: [""], inputs: [
        { col: 1, key: "delivered_v", expected: 231, hint: "Delivered voltage = supply − drops along the path = 240 − 9 = 231 V. Nine volts across a closed contact is not a rounding error — a healthy closed pole drops essentially 0 V." } ] },
      { label: "DECISION — That 9 V drop was measured across a CLOSED contactor pole while the unit tried to run. What is the correct call on the contactor? 1) Normal — closed contacts always drop several volts 2) The pole's contacts are pitted/burned and acting as a resistor — the contactor must be replaced (or its contacts renewed where the design allows) 3) The meter leads were reversed 4) The contactor is fine; only capacitors cause hum-and-trip faults", cells: [""], inputs: [
        { col: 1, key: "contactor_verdict", expected: 2, hint: "A closed contact should drop ~0 V under load; 9 V means burned contact material is stealing voltage and heating itself (P = I²R at the pole). This is the layered fault: even with a new capacitor, this pole would keep abusing the compressor's starts. Option 4 ignores measured evidence — this call has two faults, and both get fixed." } ] },
      { label: "DECISION — Repairs are complete: new dual capacitor (correct µF and voltage rating), new contactor. What is the correct FINAL verification before you close the ticket? 1) Sign the ticket — the parts are new, so the unit is fixed 2) Run a full cooling cycle under load: confirm a clean start, measure delivered voltage and the drop across the new contactor poles (≈0 V), and compare running current with the nameplate — then document the old readings and the cause 3) Cycle the disconnect once to hear it start 4) Set the thermostat 5 degrees lower and leave quickly while it is running", cells: [""], inputs: [
        { col: 1, key: "final_verify", expected: 2, hint: "A repair is proven, not assumed: re-run the original complaint (a full cooling cycle), re-measure the numbers that convicted the faults — pole drop back to ~0 V, healthy voltage at the compressor, current consistent with the nameplate — and write down what failed and why. Options 1, 3, and 4 all leave before the evidence does." } ] }
    ],
    passing: 70
  }
];
