// HVAC 208 - Module 2: Heat Pump Systems
module.exports = {
  number: 2,
  slug: "heat-pump-systems",
  title: "Heat Pump Systems",
  estTime: "3–4 hours",
  objectives: [
    "Explain how a heat pump moves heat in both directions using the same refrigeration cycle.",
    "Describe reversing valve construction and how the solenoid shifts the valve between heating and cooling.",
    "Trace refrigerant flow through a heat pump in both modes, identifying which coil acts as evaporator and which as condenser.",
    "Explain why outdoor and indoor metering and check valves are needed in a heat pump.",
    "Define thermal balance point and explain what happens above and below it.",
    "Explain why heat pump capacity and efficiency fall as outdoor temperature drops."
  ],
  sections: [
    {
      heading: "One Cycle, Two Directions",
      html: `<p>A <strong>heat pump</strong> is an air conditioner that can run its refrigeration cycle in reverse. In cooling, it absorbs heat indoors and rejects it outdoors — exactly the system from Module 1. In heating, it absorbs heat from outdoor air (even cold air contains heat energy) and rejects that heat indoors. Nothing about the four core processes changes; a single special component, the <strong>reversing valve</strong>, reroutes the compressor's discharge gas so the two coils swap jobs.</p><p>In heating mode the <strong>outdoor coil becomes the evaporator</strong>: cold liquid refrigerant enters it, absorbs heat from outdoor air, and boils into vapor. The <strong>indoor coil becomes the condenser</strong>: hot high-pressure vapor gives up its heat to indoor air and condenses. The compressor still only compresses, the metering device still only drops pressure — but "the evaporator" and "the condenser" are now roles that swap with the mode, not fixed boxes.</p><div class="callout"><strong>Key idea:</strong> A heat pump does not create most of the heat it delivers — it <em>moves</em> heat from outdoors to indoors and adds the compressor's work to it. That is why it can deliver more heat energy than the electrical energy it consumes, a relationship measured as COP (coefficient of performance).</div><p>Because the heat is moved rather than made, a heat pump's heating capacity depends on how much heat the outdoor air offers and how hard the compressor must work to lift it — the reason capacity falls on the coldest days, covered in Section 5.</p>`
    },
    {
      heading: "The Reversing Valve: The Traffic Cop",
      html: `<p>The <strong>reversing valve</strong> (also called a four-way or changeover valve) sits at the compressor discharge. It has one inlet from the compressor, one outlet back to the compressor suction, and two connections to the coils. Inside, a sliding piston (the slide) is moved by refrigerant pressure differences directed by a small <strong>solenoid-operated pilot valve</strong>. The solenoid itself does not move the slide; it opens tiny pilot passages that let system pressure do the heavy work.</p><p>Manufacturers differ on which mode energizes the solenoid: on many systems the solenoid is energized in <strong>cooling</strong> (the thermostat's O terminal), so a failed solenoid or lost O signal drops the unit into heating on a cooling call — a classic diagnostic clue. On others it is energized in heating (B terminal). Never assume: check the unit's documentation and the thermostat setup together.</p><ul><li><strong>Energized-in-cooling (O):</strong> loss of the signal = unit heats on a cooling call.</li><li><strong>Energized-in-heating (B):</strong> loss of the signal = unit cools on a heating call.</li></ul><div class="callout"><strong>Key idea:</strong> A valve stuck mid-position bleeds hot discharge gas toward suction, collapsing capacity in <em>both</em> modes while pressures look "almost normal." Comparing the temperatures of the valve's tubes is a fast field check taught in the defrost lab and Module 12.</div><p>The valve shifts only when the system runs and pressure can build; a unit that is off cannot change modes, which is why mode tests always start with a running compressor.</p>`
    },
    {
      heading: "Tracing Flow in Both Modes",
      html: `<p><strong>Cooling mode, step by step:</strong> the compressor sends hot discharge gas through the reversing valve to the <strong>outdoor coil</strong>, which condenses it. Liquid flows through the outdoor check valve path (bypassing the outdoor metering device), travels indoors, passes the indoor metering device (TXV or piston), enters the <strong>indoor coil</strong> as cold low-pressure mixture, evaporates, and returns as vapor through the reversing valve and the accumulator to the compressor.</p><p><strong>Heating mode, step by step:</strong> the reversing valve sends discharge gas to the <strong>indoor coil</strong> first, where it condenses and heats the house air. Liquid travels outdoors, bypasses the indoor metering device through its check valve, passes the <strong>outdoor metering device</strong>, enters the outdoor coil as a cold mixture, evaporates by absorbing outdoor heat, and returns through the reversing valve to the compressor.</p><div class="formula">In heating: indoor coil = condenser · outdoor coil = evaporator &nbsp;|&nbsp; In cooling the roles reverse</div><p>Two application details follow from the trace. First, heat pumps need a metering device and a bypass check valve <em>at each coil</em>, because flow reverses. Second, many heat pumps carry a <strong>suction accumulator</strong> as standard protection, because heating-mode operation — especially around defrost — can send liquid refrigerant back toward the compressor.</p>`
    },
    {
      heading: "Metering, Check Valves, and Charge Sensitivity",
      html: `<p>Each coil's metering device only works in one flow direction, so a <strong>check valve</strong> in parallel lets refrigerant bypass it when flow reverses. If a check valve leaks internally, liquid sneaks past a metering device and the active coil is overfed or starved — presenting as charge-like symptoms that adding refrigerant cannot fix. When you evaluate charge on a heat pump, first confirm you are testing in the mode and conditions the manufacturer's charging chart specifies; many charts are written for cooling mode at stated outdoor temperatures.</p><p>Heat pumps are also less forgiving of airflow faults than straight-cool systems, because the same indoor coil and blower must serve both modes and the outdoor coil in heating is an evaporator working in cold, damp air — the setup for frost, which Module 3 handles. Indoor airflow that is merely "a little low" in cooling can mean poor heating capacity and frequent defrosts in winter.</p><div class="callout"><strong>Key idea:</strong> Charge a heat pump by the manufacturer's stated method and mode, with airflow verified first (Modules 8–9). Guessing at charge in the wrong mode is one of the most common — and most expensive — heat pump service errors.</div><p><strong>Worked check.</strong> On a cooling call, an R-410A heat pump shows a suction pressure near 118 psig. That corresponds to roughly a 40°F evaporating temperature — a plausible cooling value. The number alone neither proves correct charge nor condemns it; superheat or subcooling per the unit's method, with verified airflow, completes the picture.</p>`
    },
    {
      heading: "The Balance Point: Where Capacity Meets the Load",
      html: `<p>A building loses heat faster as outdoor temperature falls, while a heat pump produces <em>less</em> heat as outdoor temperature falls. Plot those two lines and they cross at the <strong>thermal balance point</strong>: the outdoor temperature where heat pump capacity exactly equals the building's heat loss. Above the balance point, the heat pump carries the load alone and cycles off when satisfied. Below it, the heat pump runs continuously and still falls behind, so <strong>auxiliary heat</strong> must make up the difference.</p><p><strong>Worked example.</strong> At 35°F outdoors, a house loses 30,000 Btu/h and its heat pump delivers 30,000 Btu/h — that is its balance point for this house. At 25°F the house loses more heat and the pump delivers less; the shortfall is not a malfunction, it is arithmetic, and the controls should stage auxiliary heat to cover it. The same pump on a tighter, better-insulated house would have a lower balance point, because the load line is lower.</p><div class="callout"><strong>Key idea:</strong> Balance point is a property of the <em>pairing</em> — this heat pump on this building — not of the heat pump alone. Complaints of "it can't keep up in January" are often balance-point reality plus an auxiliary-heat fault, not a failed compressor.</div><p>There is also an <em>economic</em> balance point for dual-fuel systems — the temperature where gas heat becomes cheaper per delivered Btu than the heat pump — which Module 3 uses when setting changeover controls. Keep the two ideas separate: thermal is about capacity, economic is about cost.</p>`
    }
  ],
  keyTerms: [
    { term: "Heat pump", def: "A reversible refrigeration system that cools in one mode and heats by moving outdoor heat indoors in the other." },
    { term: "Reversing valve", def: "Four-way valve that reroutes compressor discharge gas to swap the coils' roles between heating and cooling." },
    { term: "Solenoid pilot valve", def: "Small electrically operated valve that directs pressure to slide the reversing valve's internal piston." },
    { term: "O terminal", def: "Thermostat terminal that energizes the reversing valve solenoid in cooling on O-type systems." },
    { term: "B terminal", def: "Thermostat terminal used on systems whose reversing valve is energized in heating." },
    { term: "Check valve", def: "One-way valve that lets refrigerant bypass a metering device when flow reverses in a heat pump." },
    { term: "Suction accumulator", def: "Vessel in the suction line that traps liquid refrigerant and protects the compressor from slugging." },
    { term: "COP (coefficient of performance)", def: "Heat delivered divided by energy input; heat pumps in heating can have a COP above 1 because they move heat." },
    { term: "Thermal balance point", def: "Outdoor temperature where heat pump heating capacity exactly equals the building's heat loss." },
    { term: "Economic balance point", def: "Outdoor temperature where an alternate fuel becomes cheaper per delivered unit of heat than the heat pump." },
    { term: "Auxiliary heat", def: "Supplemental heat (electric strips or a furnace) staged to cover the load below the balance point and during defrost." },
    { term: "Outdoor metering device", def: "The metering device that feeds the outdoor coil when it acts as the evaporator in heating mode." },
    { term: "Indoor metering device", def: "The metering device that feeds the indoor coil when it acts as the evaporator in cooling mode." },
    { term: "Stuck reversing valve", def: "A valve lodged mid-travel that bleeds discharge gas toward suction and collapses capacity in both modes." },
    { term: "Changeover", def: "The switching of a heat pump system between heating and cooling modes." },
    { term: "Heat lift", def: "The temperature difference the compressor must pump heat across; larger lift means lower capacity and efficiency." }
  ],
  video: {
    title: "HVAC Heat Pump Basics",
    embedUrl: "https://www.youtube.com/embed/vQohvbck0pw",
    note: "An HVAC School overview of how heat pumps heat and cool with one refrigeration cycle. Watch the flow path in each mode and compare it with the step-by-step traces in Section 3, especially which coil is evaporating in heating.",
    more: [
      { title: "Heat Pump Reversing Valve Troubleshooting Tips (Switchover Valve)", url: "https://www.youtube.com/watch?v=uRmjNcmdmm0" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> In heating mode, which coil is the evaporator and which is the condenser? Where does the absorbed heat come from?</p>", solution: "<p><strong>Answer:</strong> Step 1: In heating, the outdoor coil is the evaporator, absorbing heat from outdoor air. Step 2: The indoor coil is the condenser, rejecting that heat (plus compressor work) to indoor air. Step 3: The roles are the reverse of cooling mode.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> An O-type heat pump heats on a cooling call after a thermostat replacement. Give the most likely cause.</p>", solution: "<p><strong>Answer: the reversing-valve solenoid is not being energized in cooling.</strong> Step 1: On O systems the solenoid is energized in cooling. Step 2: Loss of the O signal leaves the valve in its de-energized (heating) position. Step 3: Verify thermostat configuration and the O wire before condemning the valve itself.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> A house loses 36,000 Btu/h at 30°F, where its heat pump delivers 36,000 Btu/h. At 20°F the house loses 42,000 Btu/h and the pump delivers 30,000 Btu/h. What is the balance point and the shortfall at 20°F?</p>", solution: "<p><strong>Answer: balance point 30°F; shortfall 12,000 Btu/h.</strong> Step 1: Balance point is where capacity equals loss: 36,000 = 36,000 at 30°F. Step 2: At 20°F, shortfall = 42,000 − 30,000 = 12,000 Btu/h. Step 3: Auxiliary heat must supply that 12,000 Btu/h difference.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Why does a heat pump have a metering device at each coil, each with a parallel check valve?</p>", solution: "<p><strong>Answer:</strong> Step 1: Refrigerant flow reverses between modes, so whichever coil is evaporating needs its own metering device. Step 2: A metering device only meters in one direction. Step 3: The parallel check valve lets liquid bypass the idle device when flow runs the other way.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A heat pump delivers 24,000 Btu/h of heat while drawing electrical input equivalent to 8,000 Btu/h. What is its COP, and why can it exceed 1?</p>", solution: "<p><strong>Answer: COP = 3.0.</strong> Step 1: COP = heat delivered ÷ energy input = 24,000 ÷ 8,000 = 3. Step 2: The pump moves outdoor heat rather than converting electricity directly into heat. Step 3: Delivered heat = moved heat + compressor work, so the ratio can exceed 1.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> An R-410A heat pump in cooling shows 118 psig suction pressure. What evaporating temperature does that correspond to, and what else must be checked before judging charge?</p>", solution: "<p><strong>Answer: about 40°F; check airflow and superheat/subcooling by the manufacturer's method.</strong> Step 1: Use the P/T anchor: R-410A at 40°F ≈ 118 psig. Step 2: Pressure alone does not prove charge. Step 3: Verify indoor airflow, then take superheat (fixed orifice) or subcooling (TXV) as the unit specifies.</p>" }
  ],
  quiz: [
    { q: "In heating mode, the outdoor coil of a heat pump acts as the:", choices: ["Condenser", "Evaporator", "Receiver", "Accumulator"], answer: 1, explanation: "Correct: (b). In heating, refrigerant evaporates in the outdoor coil, absorbing heat from outdoor air. (a) The indoor coil is the condenser in heating. (c) A receiver stores liquid in some commercial systems, unrelated to coil roles. (d) The accumulator is a separate suction-line vessel, not a coil." },
    { q: "The reversing valve slide is actually moved by:", choices: ["The solenoid plunger pushing it directly", "A small electric motor", "Refrigerant pressure differences directed by the pilot solenoid", "The thermostat's anticipator"], answer: 2, explanation: "Correct: (c). The solenoid only opens pilot passages; system pressure slides the piston. (a) The plunger is far too small to move the slide against system forces. (b) No motor drives a standard reversing valve. (d) Anticipators were a thermostat feature and never moved valves." },
    { q: "On an O-type system, losing the reversing-valve signal during a cooling call causes:", choices: ["Normal cooling", "The unit to heat", "The compressor to lock out permanently", "Defrost to start"], answer: 1, explanation: "Correct: (b). O systems energize the solenoid in cooling, so losing the signal leaves the valve in heating position. (a) Cooling requires the energized position on this type. (c) No permanent lockout results from a signal loss. (d) Defrost is a timed/temperature function of the defrost control, not the changeover signal." },
    { q: "The thermal balance point is where:", choices: ["Supply and return air temperatures are equal", "Heat pump capacity equals the building's heat loss", "Gas heat becomes cheaper than the heat pump", "The reversing valve shifts"], answer: 1, explanation: "Correct: (b). Above it the pump carries the load alone; below it auxiliary heat must help. (a) Equal air temperatures would mean no heating at all. (c) That is the economic balance point, a cost concept. (d) The valve shifts on mode calls, unrelated to load balance." },
    { q: "Heat pump heating capacity falls as outdoor temperature drops mainly because:", choices: ["The thermostat loses calibration", "There is less heat available in the outdoor air and the lift increases", "The reversing valve leaks more in winter", "Indoor airflow increases"], answer: 1, explanation: "Correct: (b). Colder air offers less heat to absorb and forces the compressor to work across a bigger temperature lift. (a) Calibration does not change seasonal capacity. (c) Valve leakage is a fault, not the normal seasonal trend. (d) Indoor airflow does not automatically rise in winter." },
    { q: "A check valve leaking internally past the active metering device would most likely present as:", choices: ["A tripped breaker", "Charge-like symptoms that adding refrigerant does not fix", "A failed defrost board", "High indoor humidity only in heating"], answer: 1, explanation: "Correct: (b). Refrigerant bypassing the metering device overfeeds or starves the coil in ways that imitate charge problems. (a) Electrical symptoms come from electrical faults. (c) Defrost control is a separate circuit. (d) The fault affects refrigerant flow in the active mode, not humidity alone." },
    { q: "Why do many heat pumps include a suction accumulator as standard equipment?", choices: ["To store spare refrigerant for winter", "To protect the compressor from liquid floodback, especially around defrost", "To raise suction pressure", "To replace the filter-drier"], answer: 1, explanation: "Correct: (b). The accumulator traps liquid and meters vapor (with a small oil-return opening) to the compressor. (a) It is not a storage tank for seasonal charge. (c) It does not raise pressure; it sits in the suction path. (d) Filtration is the filter-drier's separate job." },
    { q: "A COP of 3 for a heat pump in heating means:", choices: ["It uses three times the energy of electric strips for the same heat", "It delivers three units of heat per unit of electrical energy input", "It has three compressors", "Its capacity is 3 tons"], answer: 1, explanation: "Correct: (b). COP = heat delivered ÷ energy in; COP 3 delivers 3 units of heat per unit purchased. (a) That would be COP below 1 — the opposite. (c) COP says nothing about compressor count. (d) Tonnage is capacity in Btu/h ÷ 12,000, a different figure entirely." }
  ],
  studyGuide: `
<h3>Module 2 — Heat Pump Systems: Quick Reference</h3>
<p><strong>One cycle, two directions:</strong> the reversing valve swaps coil roles. Heating: outdoor coil = evaporator, indoor coil = condenser. Cooling: the reverse.</p>
<p><strong>Reversing valve:</strong> solenoid only pilots pressure; system pressure slides the valve. O systems energize in cooling — losing O = heating on a cooling call. Stuck mid-position bleeds discharge to suction and kills capacity in both modes.</p>
<p><strong>Flow hardware:</strong> a metering device plus a parallel check valve at each coil; suction accumulator protects against floodback, especially around defrost.</p>
<div class="formula">COP = heat delivered ÷ energy input · Thermal balance point: heat pump capacity = building heat loss</div>
<p><strong>Balance point</strong> belongs to the pump-plus-building pairing; below it, auxiliary heat covers the shortfall. Economic balance point (dual fuel) is about cost, not capacity.</p>
<p><strong>Charge discipline:</strong> verify airflow first, then test in the manufacturer's specified mode and method. P/T anchor: R-410A 40°F ≈ 118 psig.</p>
<p><strong>Field habit:</strong> on any heat pump call, state the mode, the valve position evidence, and the airflow status before quoting pressures — the three facts that keep heat pump diagnosis honest in both seasons.</p>
`
};
