// HVAC 208 - Module 8: Airflow for A/C Applications
module.exports = {
  number: 8,
  slug: "airflow-for-ac-applications",
  title: "Airflow for A/C Applications",
  estTime: "3–4 hours",
  objectives: [
    "State the 400 CFM-per-ton design rule of thumb and explain what it is — and is not.",
    "Compute required CFM for a given tonnage and diagnose the direction of an airflow error from measurements.",
    "Define total external static pressure and explain how duct resistance, filters, and coils consume the blower's pressure budget.",
    "Explain the performance consequences of low airflow: icing, capacity loss, poor dehumidification behavior, and compressor risk.",
    "Explain why airflow is verified before refrigerant charge is judged (NATE Core: achieving desired conditions).",
    "Identify common airflow restrictions and the order in which to correct them."
  ],
  sections: [
    {
      heading: "CFM per Ton: The Rule of Thumb That Runs the Trade",
      html: `<p>Air conditioning is a partnership between a refrigerant circuit and an airstream. The evaporator can only absorb as much heat as the air delivers to it, and the standard design target for moving that air is:</p><div class="formula">Design airflow ≈ 400 CFM per ton (rule of thumb) · Required CFM = tons × 400</div><p>So a 3-ton system wants about 1,200 CFM across its indoor coil, and a 5-ton about 2,000 CFM. Treat the number with respect and with limits: it is a <strong>rule of thumb for standard design conditions</strong>, not a law of physics. Manufacturers specify the airflow their equipment needs, and design targets shift with application — drier or more humid design goals justify somewhat lower or higher airflow per ton — but 400 CFM/ton is the reference point every technician uses to spot trouble: measure 900 CFM on a 3-ton and you already know a story needs explaining before any gauge comes out.</p><div class="callout"><strong>Key idea:</strong> This module opens the NATE Core thread of this course — <em>achieving desired conditions</em> and <em>taking temperature and humidity measurements</em>. Desired conditions are delivered by air: the right volume of air, at the right temperature, is the product the customer actually feels.</div><p>Everything in this module and the next two — static pressure, measurement methods, and capacity verification — exists to answer one question: is the airstream doing its half of the job?</p>`
    },
    {
      heading: "What Low Airflow Actually Does",
      html: `<p>Run too little air across an evaporator and the coil has more refrigeration capacity than the air can feed with heat. The coil temperature falls. Suction pressure and evaporating temperature drop with it; the temperature split across the coil (return minus supply) grows larger than normal because the smaller airstream is cooled more deeply; and if the coil surface falls below freezing while moisture is present, <strong>frost forms</strong>, which blocks airflow further, which lowers the temperature further — a spiral that can end with a solid block of ice and a compressor drinking liquid refrigerant.</p><p>The symptom list of low airflow reads like a charge problem — low suction pressure, weak cooling, icing — which is precisely the trap Module 12 drills. High airflow has its own faults: too much air raises the coil temperature, shortens contact time, and can leave the space clammy because moisture removal suffers, plus noise and drafts at the registers.</p><ul><li><strong>Low airflow:</strong> cold coil, low suction, wide air ΔT, icing risk, possible floodback damage.</li><li><strong>High airflow:</strong> warm coil, narrow ΔT, poor latent removal, noise.</li></ul><div class="callout"><strong>Key idea:</strong> Airflow faults and charge faults produce overlapping symptoms but opposite cures. Adding refrigerant to an airflow-starved system overcharges it; once airflow is restored, the system is now genuinely overcharged. Sequence is everything — which is why the next section exists.</div>`
    },
    {
      heading: "External Static Pressure: The Blower's Budget",
      html: `<p>A blower does not deliver a fixed CFM; it delivers whatever CFM results from pushing against the resistance of everything outside its cabinet. That resistance is the <strong>total external static pressure (TESP)</strong>: the pressure the duct system, filter, coil, and registers collectively impose, measured in inches of water column (in. w.c.) with a manometer. Every air handler and furnace is rated to deliver its airflow at up to a stated maximum TESP; beyond it, delivered CFM falls off the blower table.</p><p>Think of TESP as a budget spent item by item: the supply duct and fittings spend some, the return duct spends some, the filter spends some (more as it loads with dirt), and the wet evaporator coil spends some. The technician measures the total and, when it is excessive, measures the pieces to find the big spender — a method Module 9 turns into procedure.</p><div class="formula">TESP = supply-side static + return-side static (magnitudes added) — compare with the unit's rated maximum and its blower table</div><p><strong>Worked reasoning.</strong> A blower rated to deliver design CFM at 0.5 in. w.c. is found running against 0.9 in. w.c. No adjustment of refrigerant will fix what follows: the blower table says airflow is well down, the coil runs cold, and the customer reports weak cooling. The fix is in the pressure budget — a restrictive filter, crushed flex duct, closed registers, or undersized returns — not in the refrigerant circuit.</p>`
    },
    {
      heading: "Why Airflow Is Checked Before Charge — Every Time",
      html: `<p>Here is the discipline that separates diagnosis from guessing: <strong>superheat and subcooling are only meaningful at correct airflow.</strong> Both charge indicators are coil behaviors, and the coil's behavior is set jointly by refrigerant flow and airflow. Judge charge at 70% airflow and you will "correct" a healthy charge into an overcharge (or miss an undercharge hiding behind the airflow fault). The professional sequence is therefore fixed: (1) inspect and correct the air path — filter, coil, blower, ducts, registers; (2) measure and confirm airflow is in range; (3) only then evaluate charge by the manufacturer's method.</p><p>This ordering is not shop folklore; it is how the certification blueprints frame competence. NATE Core's <em>Achieving Desired Conditions</em> and <em>Taking Temperature and Humidity Measurements</em> domains assume the technician measures the air side as rigorously as the refrigerant side, and HVAC Excellence's Air Conditioning Employment Ready topics do the same. EPA Type II service discipline agrees from the other direction: refrigerant is added or recovered based on verified need, never as a first guess — unnecessary handling is both bad practice and bad stewardship of a regulated refrigerant.</p><div class="callout"><strong>Key idea:</strong> Repeat it as a rule of the trade: <em>Airflow first, charge second.</em> If you cannot state the system's measured CFM (or a defensible airflow measurement from Module 9), you are not yet entitled to an opinion about its charge.</div>`
    },
    {
      heading: "Finding and Fixing Restrictions — In Order",
      html: `<p>When airflow measures low, hunt restrictions from cheapest and most common to deepest. <strong>Filter:</strong> loaded, wrong size, or an ultra-restrictive "upgrade" the blower cannot pull through. <strong>Coil:</strong> a matted evaporator face (often from years of filter neglect) that must be cleaned. <strong>Blower:</strong> dirty wheel blades that move less air at the same speed, wrong speed tap or programmed setting, or a failing motor. <strong>Ducts:</strong> crushed flex runs, closed or blocked registers, undersized or sealed-off returns, disconnected runs dumping air into an attic. <strong>Settings:</strong> blower programmed for a different tonnage than installed — a commissioning error that survives for years because "it cools, sort of."</p><p><strong>Worked example.</strong> A 3-ton system measures 950 CFM (target ≈ 1,200) with high TESP. The return-side reading alone is most of the excess, and inspection finds a pleated high-efficiency filter choked with construction dust plus a return grille half-blocked by furniture. Filter replaced and grille cleared, TESP falls into the rated range and airflow recovers to about 1,150 CFM — close enough to target to proceed to charge evaluation, which now (and only now) is meaningful.</p><div class="callout"><strong>Key idea:</strong> Fix airflow with air-side tools: filters, cleaning, settings, duct repairs. Every airflow problem "solved" with refrigerant creates a second problem that arrives with the next season's weather.</div><p>Module 9 gives you the instruments; Module 10 turns airflow plus temperatures into verified delivered capacity.</p>`
    }
  ],
  keyTerms: [
    { term: "CFM", def: "Cubic feet per minute — the volume rate of airflow." },
    { term: "CFM per ton", def: "Design rule of thumb of about 400 CFM of indoor airflow per ton of cooling capacity." },
    { term: "Total external static pressure (TESP)", def: "Total resistance (supply + return magnitudes) the duct system and components impose on the blower, in inches of water column." },
    { term: "Static pressure", def: "Pressure exerted in all directions in a duct, measured against atmosphere with a manometer, in in. w.c." },
    { term: "Manometer", def: "Instrument measuring small pressure differences, used for static pressure readings." },
    { term: "Blower table", def: "Manufacturer chart of delivered CFM versus static pressure for each blower speed/setting." },
    { term: "Temperature split (air ΔT)", def: "Return-air minus supply-air dry-bulb temperature across the indoor unit in cooling." },
    { term: "Coil icing", def: "Frost accumulation on an evaporator whose surface falls below freezing, progressively blocking airflow." },
    { term: "Floodback", def: "Liquid refrigerant returning to the compressor, possible when an iced or starved coil cannot boil refrigerant fully." },
    { term: "Latent removal", def: "Moisture (humidity) removal at the coil; suffers when airflow is far from design in either direction." },
    { term: "Return side", def: "The duct path bringing air back to the unit, including grille, duct, and filter." },
    { term: "Supply side", def: "The duct path delivering conditioned air from the unit to the registers." },
    { term: "Air handler rating", def: "The maximum external static pressure at which the unit is rated to deliver its airflow." },
    { term: "Speed tap / blower setting", def: "Selectable blower speed (PSC taps or programmed ECM settings) that must match the installed tonnage and duct resistance." },
    { term: "Register / grille", def: "The terminal openings where supply air enters and return air leaves the occupied space." },
    { term: "Wet coil pressure drop", def: "The extra airflow resistance of an evaporator coil when wet with condensate, counted in the static budget." },
  ],
  video: {
    title: "Measuring Static Pressure on an Air Handler for Airflow CFM!",
    embedUrl: "https://www.youtube.com/embed/eFmDmk1Siqc",
    note: "An AC Service Tech field video measuring static pressure on an air handler and using the blower data to estimate CFM. Watch the probe placement for supply and return readings — exactly the TESP method this module builds and Module 9 practices.",
    more: [
      { title: "HVAC Delta T Explained!", url: "https://www.youtube.com/watch?v=9lDl5cfFSzs" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> Compute target design airflow for 2.5-ton, 4-ton, and 5-ton systems using the rule of thumb.</p>", solution: "<p><strong>Answer: 1,000 CFM; 1,600 CFM; 2,000 CFM.</strong> Step 1: Required CFM = tons × 400. Step 2: 2.5 × 400 = 1,000. Step 3: 4 × 400 = 1,600 and 5 × 400 = 2,000. These are design targets to verify against manufacturer requirements.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A 4-ton system measures 1,250 CFM. Express the shortfall in CFM and as a percentage of target.</p>", solution: "<p><strong>Answer: 350 CFM short, about 22% low.</strong> Step 1: Target = 4 × 400 = 1,600 CFM. Step 2: Shortfall = 1,600 − 1,250 = 350 CFM. Step 3: 350 ÷ 1,600 ≈ 0.22 — low enough to distort pressures, split, and charge readings; fix airflow first.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Supply static measures 0.45 in. w.c. and return static 0.35 in. w.c. (magnitudes). What is TESP, and what do you compare it with?</p>", solution: "<p><strong>Answer: TESP = 0.80 in. w.c.</strong> Step 1: Add magnitudes: 0.45 + 0.35 = 0.80. Step 2: Compare with the unit's rated maximum external static. Step 3: Then use the blower table at 0.80 to find what CFM the blower actually delivers at the selected speed.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> A system's suction pressure is low and the coil is icing. A coworker reaches for the refrigerant tank. Give the correct sequence and reason.</p>", solution: "<p><strong>Answer: airflow first.</strong> Step 1: Low airflow produces exactly these symptoms by overcooling the coil. Step 2: Inspect filter, coil, blower, ducts; measure airflow. Step 3: Only at verified airflow do superheat/subcooling become meaningful — adding refrigerant now would overcharge the system once airflow is fixed.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> Why does excessive airflow hurt humidity removal even though capacity (sensible) may look fine?</p>", solution: "<p><strong>Answer:</strong> Step 1: Higher airflow warms the coil surface and shortens air contact time. Step 2: Less moisture condenses per pass. Step 3: The thermostat satisfies on temperature while the space stays clammy — a desired-conditions failure that only air-side measurement reveals.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> List the airflow-restriction hunt in the order taught, cheapest first.</p>", solution: "<p><strong>Answer:</strong> Step 1: Filter (loaded/wrong/restrictive). Step 2: Evaporator coil face (matted). Step 3: Blower (dirty wheel, wrong setting, weak motor). Step 4: Ducts and registers (crushed, closed, disconnected, undersized returns). Step 5: Settings mismatch (blower programmed for another tonnage).</p>" }
  ],
  quiz: [
    { q: "The standard design airflow rule of thumb is:", choices: ["200 CFM per ton", "400 CFM per ton", "600 CFM per ton", "1,000 CFM per ton"], answer: 1, explanation: "Correct: (b). About 400 CFM/ton at standard design conditions. (a) 200 would starve the coil and risk icing. (c) 600 is well above design and harms latent removal. (d) 1,000 CFM/ton is not a design target for comfort cooling." },
    { q: "A 3.5-ton system should move approximately:", choices: ["1,050 CFM", "1,200 CFM", "1,400 CFM", "1,750 CFM"], answer: 2, explanation: "Correct: (c). 3.5 × 400 = 1,400 CFM. (a) 1,050 is 300 CFM/ton — low. (b) 1,200 is the 3-ton target. (d) 1,750 is 500 CFM/ton — high." },
    { q: "TESP is best described as:", choices: ["The pressure in the refrigerant suction line", "Supply plus return static pressure magnitudes the blower must overcome", "The duct velocity pressure alone", "The filter's pressure drop only"], answer: 1, explanation: "Correct: (b). Total external static is the whole external resistance seen by the blower. (a) Suction pressure is refrigerant-side, in psig. (c) Velocity pressure is one component of duct flow, not the total resistance. (d) The filter is one spender within the total budget." },
    { q: "Low evaporator airflow most directly causes:", choices: ["High suction pressure and warm coil", "Falling coil temperature, low suction pressure, and possible icing", "Immediate high head pressure trips", "Better humidity removal at all times"], answer: 1, explanation: "Correct: (b). Starved of heat, the coil overcools; frost can follow and worsen it. (a) That pattern fits high airflow or other faults. (c) Head pressure typically falls, not trips, with low indoor airflow in cooling. (d) Mild reductions can raise latent share briefly, but serious low airflow ices the coil and destroys performance." },
    { q: "Why must charge be evaluated only after airflow is verified?", choices: ["Because refrigerant is expensive", "Because superheat and subcooling are coil behaviors set jointly by refrigerant flow and airflow", "Because gauges cannot be connected before the filter is changed", "Because the EPA requires a written airflow report first"], answer: 1, explanation: "Correct: (b). At wrong airflow, charge indicators point the wrong way and invite over- or under-charging. (a) Cost is real but is not the technical reason. (c) Gauges connect anytime; the readings just mislead. (d) No such EPA paperwork rule creates this sequence — physics does." },
    { q: "With supply static 0.30 and return static 0.28 in. w.c., TESP is:", choices: ["0.02 in. w.c.", "0.58 in. w.c.", "0.30 in. w.c.", "1.16 in. w.c."], answer: 1, explanation: "Correct: (b). Add the magnitudes: 0.30 + 0.28 = 0.58. (a) Subtracting them is the classic error. (c) Uses only one side. (d) Doubles the correct total." },
    { q: "A blower found running against static pressure well above its rating will:", choices: ["Deliver its table CFM anyway", "Deliver reduced CFM per its blower table", "Speed up automatically to compensate (all types)", "Raise refrigerant head pressure directly"], answer: 1, explanation: "Correct: (b). Delivered airflow falls along the blower curve as resistance rises. (a) Tables exist precisely because delivery drops. (c) Some ECM constant-airflow motors do compensate — within limits — but PSC blowers, the baseline case, do not. (d) Static pressure is air-side; its refrigerant effect is indirect through coil temperature." },
    { q: "Which is the FIRST item to check when measured airflow is low?", choices: ["Refrigerant charge", "The filter", "The TXV bulb position", "The condenser fan"], answer: 1, explanation: "Correct: (b). The filter is the cheapest, most common restriction and starts the hunt. (a) Charge is evaluated only after airflow is right. (c) TXV faults are refrigerant-side and come later in sequence. (d) The condenser fan affects the outdoor coil, not indoor CFM." }
  ],
  studyGuide: `
<h3>Module 8 — Airflow for A/C Applications: Quick Reference</h3>
<div class="formula">Design airflow ≈ 400 CFM per ton (rule of thumb, verify with manufacturer data)</div>
<p><strong>Low airflow:</strong> coil overcools → low suction, wide air ΔT, icing spiral, floodback risk. <strong>High airflow:</strong> warm coil, narrow ΔT, poor latent removal, noise.</p>
<p><strong>TESP</strong> = supply static + return static (magnitudes, in. w.c.). Compare to the unit's rated maximum, then read delivered CFM from the blower table. Spenders: ducts, filter, wet coil, registers.</p>
<p><strong>Trade rule:</strong> airflow first, charge second — superheat/subcooling are meaningless at wrong airflow (NATE Core: achieving desired conditions; EPA Type II discipline: never add refrigerant on a guess).</p>
<p><strong>Restriction hunt order:</strong> filter → coil face → blower wheel/setting/motor → ducts & registers → tonnage/setting mismatch.</p>
<p><strong>Remember:</strong> 400 CFM/ton is a reference, not a law — manufacturer specs and application goals govern; big deviations in either direction are faults to explain.</p>
<p><strong>Numbers to carry:</strong> 3-ton ≈ 1,200 CFM · 4-ton ≈ 1,600 CFM · 5-ton ≈ 2,000 CFM. A 20% airflow shortfall is a fault to fix, not a rounding error to ignore.</p>
`
};
