// HVAC 208 - Module 9: Measuring Airflow
module.exports = {
  number: 9,
  slug: "measuring-airflow",
  title: "Measuring Airflow",
  estTime: "3–4 hours",
  objectives: [
    "Use a flow hood to measure register airflow and explain its strengths and limits.",
    "Compute CFM from duct area and average velocity measured with an anemometer traverse.",
    "Perform a duct traverse correctly: equal-area points, averaged readings, consistent technique.",
    "Use the temperature-split method as a screening estimate and state what it can and cannot prove.",
    "Combine static pressure and blower tables as an airflow estimate and cross-check methods against each other.",
    "Record airflow measurements in a form that supports capacity verification in Module 10."
  ],
  sections: [
    {
      heading: "Four Methods, One Quantity",
      html: `<p>Module 8 told you how much air a system <em>should</em> move. This module measures how much it <em>does</em> move. Four field methods dominate, and a good technician knows what each one actually measures, because they do not all measure the same thing. The <strong>flow hood</strong> captures air at a register and reads its CFM directly. An <strong>anemometer traverse</strong> measures air velocity at many points inside a duct and computes volume from velocity and area. The <strong>static-pressure/blower-table</strong> method infers airflow from what the blower must be doing against measured resistance. The <strong>temperature-split</strong> method infers airflow <em>adequacy</em> from air temperatures — a screen, not a measurement.</p><p>The governing relationship for every velocity-based method is the continuity equation:</p><div class="formula">CFM = Area (ft²) × Velocity (FPM)</div><p><strong>Worked example.</strong> A round duct 12 inches in diameter has area = π × (0.5 ft)² ≈ 0.785 ft². If the average velocity in it is 800 FPM, CFM = 0.785 × 800 ≈ 628 CFM. Every traverse problem in this module is that sentence with different numbers — area first, honest average velocity second, multiply last.</p><div class="callout"><strong>Key idea:</strong> Methods disagree in the field, and that is information. A hood total far below the blower-table estimate suggests duct leakage between the coil and the registers; a traverse far below the hood total suggests a bad traverse. Cross-checking is the craft.</div>`
    },
    {
      heading: "The Flow Hood: Direct at the Register",
      html: `<p>A <strong>flow hood</strong> (balometer) is a fabric hood with an air-straightening grid and a meter that integrates the air passing through it. You seal the hood over a supply register, and it reads that register's CFM; step around the building and sum the registers to get total delivered airflow. It is the fastest way to answer "what is each room actually getting?" — the balancing question — and it directly exposes dead registers, closed dampers, and disconnected runs (a register reading zero has a story to tell).</p><p>Limits to respect: the hood itself adds a little resistance, which can slightly change the flow it measures on weak systems; hoods must seal fully over the register or air escapes the measurement; and very low flows at large registers read less accurately. Hoods measure air <em>delivered at the grille</em> — which is the customer's truth — but not air <em>leaving the air handler</em>; the difference between the two totals is duct leakage, a finding in itself.</p><div class="callout"><strong>Key idea:</strong> Record per-register readings, not just the sum. The pattern — one room at half its neighbors, a whole branch low — points at the duct problem's location in a way a single total never can. (This is the measurement discipline NATE Core's temperature/humidity and desired-conditions domains assume.)</div><p>Return-side measurement with a hood is harder (returns pull air from a wide area), so totals usually come from summing supplies while returns are checked by traverse or static methods.</p>`
    },
    {
      heading: "Anemometers and the Duct Traverse",
      html: `<p>An <strong>anemometer</strong> measures air velocity: vane types spin a small impeller in the airstream; hot-wire types sense how fast air cools a heated element and excel at low velocities. To turn velocity into volume inside a duct, you <strong>traverse</strong> it: divide the duct cross-section into equal areas, take a velocity reading at the center of each, and average them. One reading at the duct's center is a lie of convenience — air moves fastest in the middle and slowest at the walls, so the center reading alone overstates the flow.</p><p><strong>Worked example — rectangular traverse.</strong> A duct measures 20 in × 12 in = 240 in² = 240 ÷ 144 = 1.667 ft². A proper traverse (say, 16 equal-area points) averages 900 FPM. CFM = 1.667 × 900 ≈ 1,500 CFM. On a 4-ton system (target ≈ 1,600 CFM), that is close to design; on a 5-ton (2,000), it is a 25% shortfall to investigate.</p><ul><li><strong>Technique that matters:</strong> probe perpendicular to flow, same depth pattern each point, readings settled before recording, traverse located in the straightest duct run available.</li><li><strong>Common errors:</strong> too few points, measuring in turbulent air right after an elbow, forgetting grille free-area when traversing at a register.</li></ul><div class="callout"><strong>Key idea:</strong> The traverse average is only as honest as its point pattern. Equal areas, patient readings, and area computed from actual inside dimensions — those three habits separate a measurement from a number you invented politely.</div>`
    },
    {
      heading: "Static-Pressure Inference and the Blower Table",
      html: `<p>When ducts offer no traverse location and registers are awkward, infer airflow from the blower itself. Measure <strong>TESP</strong> (Module 8), confirm the blower speed/setting, and read the manufacturer's <strong>blower table</strong>: at this static and this setting, the unit delivers a stated CFM. The method is only as good as its inputs — the table assumes a clean wheel, correct setting identification, and the manufacturer's test configuration (often including a wet coil and a standard filter, per the table's footnotes, which you must read).</p><p><strong>Worked reasoning.</strong> A unit's table shows 1,200 CFM at 0.5 in. w.c. and 1,050 CFM at 0.8 in. w.c. on the selected speed. Your TESP measures 0.8 — so infer ≈ 1,050 CFM, not the 1,200 the installer assumed from the 0.5 design estimate. The static method thereby converts a pressure measurement into an airflow finding and simultaneously tells you the system is restriction-limited: reduce TESP and the same blower delivers more air.</p><div class="callout"><strong>Key idea:</strong> Treat the static method as an estimate with named assumptions, and cross-check it when the stakes are high (capacity verification, charge decisions) with a hood or traverse. Agreement between two independent methods is what turns a reading into evidence.</div><p>Remember also what static readings give you beyond the total: supply and return components localize the restriction before you open anything (Module 8's budget, now with numbers).</p>`
    },
    {
      heading: "The Temperature-Split Screen — and Honest Records",
      html: `<p>The <strong>temperature-split method</strong> measures return and supply dry-bulb temperatures and interprets the difference. Under typical indoor conditions, a healthy cooling split is often around 16–22°F — but treat that band as a <em>screening reference, not a specification</em>: the split depends on indoor humidity (wet air splits less because energy goes into condensing moisture) and on the actual load, so a "correct" split proves neither correct CFM nor correct charge. Its real value is speed: a wildly abnormal split (say 28°F on a humid day, or 11°F) tells you in thirty seconds that airflow, charge, or load is off and deeper measurement is owed. Module 10 replaces the screen with arithmetic: measured CFM plus measured air enthalpies yields actual delivered capacity.</p><p>Close with the habit that makes all of this usable: <strong>record as you go</strong>. For each method note the instrument, the location, the conditions (system runtime, filter state, blower setting), and the raw readings — not just the computed CFM. A traverse average without its grid, or a hood total without per-register values, cannot be audited later by you, your supervisor, or the next technician.</p><div class="callout"><strong>Key idea:</strong> A measurement you cannot reconstruct is an opinion. The labs and Module 10's capacity work are graded on reconstructable numbers: stated givens, visible steps, computed result.</div>`
    }
  ],
  keyTerms: [
    { term: "Flow hood (balometer)", def: "Instrument that captures air at a register and reads its CFM directly; used per-register and summed for totals." },
    { term: "Anemometer", def: "Instrument measuring air velocity; vane and hot-wire are the common types." },
    { term: "Traverse", def: "Velocity measurement at equal-area points across a duct section, averaged to compute volume flow." },
    { term: "FPM", def: "Feet per minute — air velocity unit used in the CFM = area × velocity relation." },
    { term: "Free area", def: "The open area of a grille/register through which air actually passes, less than its face area." },
    { term: "Blower table", def: "Manufacturer data of CFM delivered versus external static pressure at each blower setting." },
    { term: "Temperature split", def: "Return minus supply dry-bulb temperature; a screening indicator, not a capacity or charge proof." },
    { term: "Equal-area method", def: "Dividing a duct cross-section into equal areas and sampling velocity at each area's center for a traverse." },
    { term: "Duct leakage", def: "Air lost between the air handler and the registers; revealed when unit airflow exceeds summed register airflow." },
    { term: "Hot-wire anemometer", def: "Velocity sensor using a heated element's cooling rate; accurate at low velocities." },
    { term: "Vane anemometer", def: "Velocity sensor using a small rotating impeller spun by the airstream." },
    { term: "Cross-checking", def: "Confirming a result with a second independent measurement method before acting on it." },
    { term: "Delivered airflow", def: "Air measured at the registers — what the occupied space actually receives." },
    { term: "Unit airflow", def: "Air moving through the air handler/coil, which may exceed delivered airflow by the leakage amount." },
    { term: "Grille factor (Ak)", def: "Manufacturer factor converting register face velocity readings to actual CFM for that grille." },
    { term: "Pitot tube", def: "Probe measuring velocity pressure in a duct, an alternative traverse instrument to an anemometer." },
  ],
  video: {
    title: "Airflow CFM Measure with a Hot Wire Anemometer",
    embedUrl: "https://www.youtube.com/embed/0wWYsAn6eGo",
    note: "An AC Service Tech demonstration of measuring airflow with a hot-wire anemometer. Watch the probe technique and how point readings become a CFM figure — the traverse discipline of Section 3 in action.",
    more: [
      { title: "HVAC Temp Rise Formula used to Measure Airflow", url: "https://www.youtube.com/watch?v=agAfV3Yqb7U" }
    ]
  },
  assignment: [
    { prompt: "<p><strong>Problem 1.</strong> A 10-inch round duct (area ≈ 0.545 ft²) has an average traverse velocity of 750 FPM. Compute the CFM.</p>", solution: "<p><strong>Answer: ≈ 409 CFM.</strong> Step 1: CFM = area × velocity. Step 2: 0.545 × 750 ≈ 409 CFM. Step 3: Sanity check: a 10-inch branch carrying ~400 CFM is a plausible single-branch figure.</p>" },
    { prompt: "<p><strong>Problem 2.</strong> A 16 in × 10 in duct is traversed; average velocity is 640 FPM. Compute CFM and compare with a 3-ton target.</p>", solution: "<p><strong>Answer: ≈ 711 CFM — far below target.</strong> Step 1: Area = 160 in² ÷ 144 = 1.111 ft². Step 2: CFM = 1.111 × 640 ≈ 711. Step 3: 3-ton target ≈ 1,200 CFM; this duct is either one of several paths or the system is badly under-aired — context decides, the arithmetic flags it.</p>" },
    { prompt: "<p><strong>Problem 3.</strong> Hood readings at six supplies: 210, 185, 240, 0, 195, 220 CFM. Total delivered? What does the zero demand?</p>", solution: "<p><strong>Answer: 1,050 CFM delivered; investigate the zero register.</strong> Step 1: Sum = 210+185+240+0+195+220 = 1,050 CFM. Step 2: A zero reading means a closed damper, crushed or disconnected run, or blocked grille. Step 3: Fix and re-measure that branch before judging the system total.</p>" },
    { prompt: "<p><strong>Problem 4.</strong> Blower-table inference says 1,400 CFM leaves the unit, but summed hood readings total 1,190 CFM. What is the difference and its likely meaning?</p>", solution: "<p><strong>Answer: 210 CFM unaccounted — probable duct leakage.</strong> Step 1: 1,400 − 1,190 = 210 CFM. Step 2: Air leaving the unit but not arriving at registers escapes through duct joints/leaks into unconditioned space. Step 3: Seal the duct path; the occupants are paying to cool an attic.</p>" },
    { prompt: "<p><strong>Problem 5.</strong> A tech takes one velocity reading at a duct's center, multiplies by area, and reports CFM. Identify the error and its direction.</p>", solution: "<p><strong>Answer: single-point sampling overstates flow.</strong> Step 1: Velocity is highest at the center and lowest at the walls. Step 2: A traverse averages equal-area points to capture the true mean. Step 3: The center-only figure overestimates CFM, potentially hiding an airflow fault.</p>" },
    { prompt: "<p><strong>Problem 6.</strong> On a humid afternoon a system shows a 14°F split. A coworker declares airflow 'proven low.' Evaluate the claim.</p>", solution: "<p><strong>Answer: not proven — the split is a screen, not a measurement.</strong> Step 1: High indoor humidity reduces dry-bulb split because coil energy goes into condensing moisture (latent work). Step 2: A 14°F split on a humid day may be normal for correct airflow. Step 3: Settle it with a hood, traverse, or static/blower-table measurement.</p>" }
  ],
  quiz: [
    { q: "The governing equation for velocity-based airflow measurement is:", choices: ["CFM = velocity ÷ area", "CFM = area × velocity", "CFM = area + velocity", "CFM = 1.08 × ΔT"], answer: 1, explanation: "Correct: (b). Volume flow = cross-sectional area times average velocity. (a) Dividing gives nonsense units and smaller ducts would 'flow more.' (c) Adding unlike units is meaningless. (d) 1.08 × CFM × ΔT is the sensible-heat formula, from Module 10." },
    { q: "A 20×10 in duct (1.389 ft²) averages 720 FPM. Its CFM is about:", choices: ["518", "1,000", "1,440", "720"], answer: 1, explanation: "Correct: (b). 1.389 × 720 ≈ 1,000 CFM. (a) 518 is area × 373 — no given supports it. (c) 1,440 doubles the product. (d) 720 is the velocity, not the volume." },
    { q: "A flow hood's distinctive strength is that it measures:", choices: ["Air velocity inside the main trunk", "CFM actually delivered at each register", "Static pressure in the return", "Refrigerant superheat"], answer: 1, explanation: "Correct: (b). Hoods capture register output directly, exposing per-room delivery. (a) Trunk velocity is anemometer/traverse work. (c) Static is manometer work. (d) Superheat is gauges and thermometers — refrigerant side." },
    { q: "A proper duct traverse requires:", choices: ["One reading at the center", "Readings at equal-area points, averaged", "Readings only at the walls", "The grille removed and discarded"], answer: 1, explanation: "Correct: (b). Equal-area sampling captures the velocity profile honestly. (a) Center-only overstates flow. (c) Wall-only understates it. (d) Grilles stay; free area is accounted for when traversing at a grille." },
    { q: "Blower-table inference of CFM depends on which two field inputs?", choices: ["Suction pressure and discharge pressure", "Measured TESP and confirmed blower setting", "Outdoor temperature and humidity", "Filter brand and duct color"], answer: 1, explanation: "Correct: (b). The table maps static and setting to delivered CFM. (a) Pressures are refrigerant-side. (c) Weather affects load, not the blower table lookup. (d) Neither identifies the blower's operating point (filter condition matters to static, which is already measured)." },
    { q: "Unit airflow 1,600 CFM but registers sum to 1,350 CFM. The best first conclusion is:", choices: ["The hood is broken", "About 250 CFM is likely lost to duct leakage", "Charge is low", "The traverse was done wrong"], answer: 1, explanation: "Correct: (b). Air that leaves the unit but never reaches a register escaped the duct path. (a) Assume instrument failure only after the physical explanation is checked. (c) Charge does not move air between unit and grille. (d) No traverse was involved in these two figures." },
    { q: "The temperature-split method's correct role is:", choices: ["Proving exact CFM", "Proving correct charge", "A fast screen that flags abnormal systems for real measurement", "Replacing the flow hood in balancing"], answer: 2, explanation: "Correct: (c). Split reacts to humidity and load as well as airflow, so it screens rather than proves. (a) CFM requires area × velocity, a hood, or blower data. (b) Charge requires superheat/subcooling at verified airflow. (d) Balancing needs per-register CFM, which split cannot give." },
    { q: "Why average multiple traverse points instead of trusting the center reading?", choices: ["Convention only", "Velocity varies across the duct — fastest at the center, slowest at the walls", "Anemometers are inaccurate", "To make the job take longer"], answer: 1, explanation: "Correct: (b). The velocity profile means the center reading overstates the mean; equal-area averaging corrects it. (a) The practice follows the physics of the profile. (c) Instruments are fine — sampling is the issue. (d) Time spent is the price of a defensible number, not the purpose." }
  ],
  studyGuide: `
<h3>Module 9 — Measuring Airflow: Quick Reference</h3>
<div class="formula">CFM = Area (ft²) × Velocity (FPM) · Rectangular area: (in × in) ÷ 144 = ft²</div>
<p><strong>Flow hood:</strong> direct CFM per register; sum for delivered total; per-register pattern locates duct faults. Watch sealing and weak-system effects.</p>
<p><strong>Traverse:</strong> anemometer at equal-area points, averaged; straight run, perpendicular probe, settled readings. Center-only readings overstate flow.</p>
<p><strong>Static/blower table:</strong> measured TESP + confirmed setting → inferred CFM; read table footnotes; cross-check for high-stakes decisions.</p>
<p><strong>Temperature split:</strong> screen only — humidity and load move it; it never proves CFM or charge.</p>
<p><strong>Cross-checks:</strong> unit CFM vs. summed registers → leakage. Two methods agreeing = evidence. Record instrument, location, conditions, and raw readings every time.</p>
<p><strong>Worked anchors:</strong> 20×12 in duct = 1.667 ft²; at 900 FPM ≈ 1,500 CFM. 12-in round ≈ 0.785 ft²; at 800 FPM ≈ 628 CFM.</p>
<p><strong>Method choice:</strong> balancing question → hood. Trunk total → traverse. No access → static + blower table. Quick sanity → split screen, then prove it with a real method.</p>
`
};
