// HVAC 132 — Scenario lab.
// Scenario labs run on the numeric engine: each row is a decision point; the student
// enters the number of the correct option, a step number, or a computed value.

module.exports = [
  {
    id: "combustion-analysis",
    title: "Combustion Analysis Interpretation",
    introHtml: "<p><strong>Job ticket #4471 — Annual maintenance + 'house feels stuffy.'</strong> Equipment: 8-year-old induced-draft natural gas furnace, 90,000 Btu/h input rating, Category I venting into a lined chimney. The customer mentions headaches on two evenings last month that 'were probably the flu.' You have your combustion analyzer (fuel set: natural gas), a manometer, and a meter clocking kit. The furnace has been running steadily for 12 minutes when you take your flue readings.</p><p><strong>Readings on arrival:</strong> Flue O₂ = 9.8% • CO (raw, as measured) = 100 ppm • Flue temperature = 355°F • Equipment room = 70°F • Draft steady • Manifold pressure = 3.5 in. w.c. • Meter clocking: 1 ft³ dial, 40 seconds per revolution.</p><p><strong>Watch it done:</strong> <a href=\"https://www.youtube.com/watch?v=3KiMTT_qGiU\" target=\"_blank\" rel=\"noopener\">Gas Furnace Combustion Analysis Training with Tyler Nelson!</a> — a full analyzer workflow on real equipment, from probe placement to interpreting the numbers together.</p>",
    taskHtml: "<p><strong>Step 0 — Safety first.</strong> Before any readings are interpreted: (1) Your personal CO monitor goes on and stays on — you breathe the equipment room's air for the whole call. (2) Take the ambient CO reading of the room and living space FIRST; if ambient CO is elevated, people and pets leave and the call becomes an emergency response per Module 1 — no diagnosis outranks that. Given this customer's headache report, the ambient check is not a formality. (3) Gas-leak discipline: any strong odor of gas means stop, no switch-flipping, evacuate, call the utility/911 from outside. (4) PPE: safety glasses when blowing out or brushing burner passages; gloves for hot vent piping — the flue connector at 355°F burns on contact. (5) Never leave a jumper on any safety, and seal any test hole you drill in the vent before you leave.</p><p><strong>Your job:</strong> work the decision points below in order. Enter the number the row asks for — an option number, a step number, or a computed value. All interpretation rules come from Module 6: CO air-free = CO × 20.9 ÷ (20.9 − O₂); net stack = flue temp − room temp; input = (3,600 × dial ft³ ÷ seconds) × 1,025 Btu/ft³.</p>",
    headers: ["Decision point", "Your call"],
    rows: [
      { label: "SAFETY FIRST. You walk in and your ambient CO meter reads a clearly elevated level in the living space, and the customer again mentions last month's headaches. What is the correct call? 1) Finish the combustion test quickly, then mention it 2) Get everyone out of the home, treat it as a CO emergency — utility/fire department per local protocol — and diagnose equipment only after people are safe 3) Open two windows and proceed with the maintenance visit 4) Turn the thermostat down and reschedule for next week", cells: [""], inputs: [
        { col: 1, key: "safety_first", expected: 2, hint: "Elevated ambient CO plus reported symptoms is an emergency, not a maintenance finding: people out first, responders notified, equipment diagnosis only after the space is safe (Module 1). Ventilating and continuing (3) leaves occupants in the hazard; finishing the test (1) or rescheduling (4) abandons people in a poisoned space." } ] },
      { label: "STEP ORDER. The five actions of a valid combustion test are listed in scrambled order. Enter this action's correct step number (1–5): 'Calibrate/zero the analyzer in fresh, clean air.' (The full sequence: A) select the correct fuel on the analyzer, B) zero the analyzer in fresh air, C) insert the probe in the flue before any dilution point, D) run the appliance to steady state, E) record and interpret readings.)", cells: [""], inputs: [
        { col: 1, key: "step_zero", expected: 2, hint: "Fuel selection comes first (step 1) because every computed value depends on it; zeroing in fresh air is step 2 — zeroing in flue-contaminated air would offset every reading that follows. Probe placement is 3, steady state is 4, interpretation is 5." } ] },
      { label: "STEP ORDER. Enter the correct step number (1–5) for: 'Insert the probe into the flue, ahead of any draft hood or dilution opening.' (Sequence: A) select fuel, B) zero in fresh air, C) insert probe before dilution, D) run to steady state, E) record and interpret.)", cells: [""], inputs: [
        { col: 1, key: "step_probe", expected: 3, hint: "Step 3. Sampling after a dilution point blends room air into the sample and grades the room instead of the burner — low everything, false health (Module 6)." } ] },
      { label: "STEP ORDER. Enter the correct step number (1–5) for: 'Run the appliance until temperatures and gas readings stabilize before trusting any number.' (Sequence: A) select fuel, B) zero in fresh air, C) insert probe before dilution, D) run to steady state, E) record and interpret.)", cells: [""], inputs: [
        { col: 1, key: "step_steady", expected: 4, hint: "Step 4 — steady state. Warm-up readings describe a cold, quenching exchanger, not the running appliance; only stabilized readings are evidence." } ] },
      { label: "COMPUTED VALUE. Using the arrival readings (flue 355°F, room 70°F), compute the NET STACK TEMPERATURE in °F and enter it.", cells: [""], inputs: [
        { col: 1, key: "net_stack", expected: 285, hint: "Net stack = flue temperature − ambient temperature = 355 − 70 = 285°F. Net stack drives the efficiency calculation; it is the heat the vent stream carries away above the temperature of the air the burner breathed." } ] },
      { label: "COMPUTED VALUE. The analyzer's raw CO is 100 ppm at O₂ = 10.9% on a re-test after burner cleaning (the job's second data set). Compute CO AIR-FREE in ppm and enter the whole number. Formula: CO × 20.9 ÷ (20.9 − O₂).", cells: [""], inputs: [
        { col: 1, key: "co_airfree_a", expected: 209, hint: "20.9 − 10.9 = 10.0; 20.9 ÷ 10.0 = 2.09; 100 × 2.09 = 209 ppm air-free. The raw 100 ppm was diluted by heavy excess air — the burner is producing CO at a 209 ppm air-free rate, which no adjustment-by-dilution can be allowed to hide." } ] },
      { label: "COMPUTED VALUE. A different furnace on your next call reads CO = 60 ppm at O₂ = 4.9%. Compute CO AIR-FREE in ppm (round to the nearest whole number) and enter it.", cells: [""], inputs: [
        { col: 1, key: "co_airfree_b", expected: 78, hint: "20.9 − 4.9 = 16.0; 20.9 ÷ 16.0 ≈ 1.31; 60 × 1.31 ≈ 78 ppm air-free. Compare with the previous row: a LOWER raw reading (60 vs 100) — the difference in judged severity comes entirely from how much excess air was diluting each sample." } ] },
      { label: "COMPUTED VALUE. Clock this furnace: 1 ft³ test dial, 40 seconds per revolution, only the furnace firing, gas heating value 1,025 Btu/ft³. Compute the actual INPUT in Btu/h and enter it.", cells: [""], inputs: [
        { col: 1, key: "clocking_input", expected: 92250, hint: "Flow = 3,600 × 1 ÷ 40 = 90 ft³/h. Input = 90 × 1,025 = 92,250 Btu/h — within a few percent of the 90,000 Btu/h rating plate, which is normal gas-heating-value variation, not a fault (Module 2)." } ] },
      { label: "INTERPRETATION. The arrival data set shows O₂ = 9.8% — noticeably above this manufacturer's target band — with CO air-free modest and net stack temperature on the low side. Manifold pressure is exactly 3.5 in. w.c. and clocking is on rate (92,250 vs 90,000 rated). What is the best interpretation? 1) The burner is over-fired 2) The mixture at the burner is fine, but extra air is entering the flue path downstream of the flame — dilution (inspect exchanger and vent joints, and verify probe placement) 3) The burner is starved of air 4) Nothing is wrong; high O₂ is always good", cells: [""], inputs: [
        { col: 1, key: "interp_dilution", expected: 2, hint: "On-rate clocking kills the over-fire theory (1); starved air (3) shows LOW O₂ and high CO — the opposite picture. With firing proven correct, high O₂ + cool stack means air joined the flue gas after the flame: dilution through a breach or leaking joint, or a sampling error. That is an inspection call, starting with the heat exchanger (Module 4/6 signature C/D)." } ] },
      { label: "INTERPRETATION. After cleaning the burners and intake, the re-test shows O₂ fallen into the manufacturer's band and CO air-free fallen with it, net stack temperature in family. What does this pair of movements prove? 1) The original problem was excess dilution air only 2) The original burner was air-starved/dirty: restoring clean air passages normalized BOTH the mixture (O₂) and combustion completion (CO) 3) The analyzer was miscalibrated before 4) The furnace now needs its manifold pressure raised", cells: [""], inputs: [
        { col: 1, key: "interp_cleaning", expected: 2, hint: "Dirt and blockage at the burners/intake distort the mixture and starve the flame's air where it matters; cleaning restored design conditions and both numbers normalized together — that is a root-cause repair verified by instruments. Manifold pressure (4) was already exactly on spec; changing it now would create the fault you just removed." } ] },
      { label: "DECISION. During a long verification run, you watch CO air-free climb steadily from low to several hundred ppm while O₂ also drifts upward, in step with the blower running and the exchanger heating up. What is the correct call? 1) Keep watching — it may settle 2) Finish the visit quickly and note it for next year 3) Shut the furnace down, check ambient CO at the registers, and inspect the heat exchanger — this is the breach-opening-with-heat signature 4) Open the air shutters to dilute the CO reading", cells: [""], inputs: [
        { col: 1, key: "decision_breach", expected: 3, hint: "Readings that move with heat and blower state are the exchanger's confession (Module 6, Problem 6): thermal expansion opens a crack, blower pressure dilutes the flue (O₂ up) while disturbed combustion drives CO up. A unit doing this does not stay in service. Diluting the reading (4) treats the gauge, not the poison." } ] },
      { label: "DECISION. A junior tech suggests 'fixing' a high-CO furnace by bending the air shutters open until the raw CO number looks acceptable. Your call as the senior tech: 1) Approve — lower CO is lower CO 2) Reject: dilution lowers the raw reading without reducing CO production (air-free exposes it); the repair is at the source — cleaning, input verification, and design air settings — proven by air-free CO 3) Approve if O₂ stays under the analyzer's maximum 4) Approve, but only on natural gas furnaces", cells: [""], inputs: [
        { col: 1, key: "decision_dilution_fix", expected: 2, hint: "CO is judged air-free precisely to defeat this maneuver (Module 6, Problem 4). Excess air beyond design also wastes efficiency and can lift flames. Fix causes — dirty burners, over-firing, blockage, quenching — then prove it with air-free numbers in the manufacturer's O₂ band." } ] },
      { label: "INTERPRETATION. Furnace A: O₂ well below band, CO air-free very high, visible soot at the burners. Furnace B: O₂ well above band, CO air-free low, input clocks low. Match Furnace A to its diagnosis: 1) Over-aired/diluted 2) Under-aired (fuel-rich): dirty/starved burners or over-firing — CO and soot are its signatures 3) Heat exchanger breach, proven 4) Normal for its age", cells: [""], inputs: [
        { col: 1, key: "interp_rich", expected: 2, hint: "Low O₂ means little leftover air — the flame consumed nearly everything and still couldn't finish: CO and soot are the receipts of incomplete combustion (Module 1's chain with gauges attached). Furnace B is the over-aired/under-fired mirror image. A breach (3) is suggested by readings that MOVE with heat/blower state, not by a static rich signature." } ] },
      { label: "DECISION. The final verification is complete: readings in band, CO air-free low and stable across a 15-minute run, ambient CO zero, draft steady. The customer's last request: 'Just leave that little test hole in the vent open — you'll need it next year.' Your call: 1) Leave it open as asked 2) Seal the test hole as required, and record all final readings on the ticket as next year's baseline 3) Leave it open but cover it with tape 4) Drill a second hole beside it for next time", cells: [""], inputs: [
        { col: 1, key: "decision_seal", expected: 2, hint: "An open test hole in a vent is a flue-gas leak path into the room (and a dilution error for any future test); seal it per standard practice. The real gift to next year's visit is the recorded baseline — readings trend better through paperwork than through holes (Module 6). Tape (3) is not a seal; a second hole (4) doubles the defect." } ] }
    ],
    passing: 70
  }
];
